#!/usr/bin/env bash
# Generate a deterministic schema-only snapshot from a freshly migrated DB.
# The snapshot is a GENERATED ARTIFACT — never hand-edited. Source of truth is
# db/migration/**. See end-state spec:
# docs/superpowers/specs/2026-06-18-postgresql-flyway-schema-governance-endstate.md (§3.4, P5)
#
# Usage:
#   scripts/db/generate-schema-snapshot.sh --edition oss
#   scripts/db/generate-schema-snapshot.sh --edition enterprise --enterprise-root <enterprise-repo-root>
#   scripts/db/generate-schema-snapshot.sh --edition oss --out /tmp/snap.sql   # custom output
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/db/flyway-common.sh
source "$SCRIPT_DIR/flyway-common.sh"

EDITION="oss"; ENTERPRISE_ROOT=""; OUT=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --edition) EDITION="${2:?}"; shift 2 ;;
    --enterprise-root) ENTERPRISE_ROOT="${2:?}"; shift 2 ;;
    --out) OUT="${2:?}"; shift 2 ;;
    -h|--help) sed -n '2,12p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "[snapshot] unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [[ -z "$OUT" ]]; then
  if [[ "$EDITION" == "enterprise" ]]; then
    OUT="$ENTERPRISE_ROOT/platform/src/main/resources/db/snapshots/schema-enterprise-current.sql"
  else
    OUT="$AURA_CORE_ROOT/platform/src/main/resources/db/snapshots/schema-current.sql"
  fi
fi

SNAP_DB="${SNAPSHOT_DB:-aura_schema_snapshot_$$}"
_psql_admin() { PGPASSWORD="$PG_PASSWORD" psql -h "$PG_HOST" -p "$PG_PORT" -U "$PG_USER" -d postgres "$@"; }
cleanup() { _psql_admin -c "DROP DATABASE IF EXISTS $SNAP_DB WITH (FORCE);" >/dev/null 2>&1 || true; }
trap cleanup EXIT

echo "[snapshot] building '$EDITION' snapshot from fresh DB $SNAP_DB" >&2
cleanup
_psql_admin -c "CREATE DATABASE $SNAP_DB;" >/dev/null
PG_DB="$SNAP_DB" run_flyway migrate "$EDITION" "$ENTERPRISE_ROOT" >&2

mkdir -p "$(dirname "$OUT")"
{
  echo "-- GENERATED by scripts/db/generate-schema-snapshot.sh — DO NOT EDIT BY HAND."
  echo "-- Source of truth is db/migration/**. Regenerate after migrations change."
  echo "-- edition=$EDITION"
  echo
  # Strip lines that vary per run / per pg_dump version so the snapshot is
  # byte-stable for drift checks: pg17 \restrict/\unrestrict session tokens
  # (randomized each run), pg17-only transaction_timeout, and the "Dumped ..."
  # version header comments.
  PGPASSWORD="$PG_PASSWORD" pg_dump -h "$PG_HOST" -p "$PG_PORT" -U "$PG_USER" \
    --schema-only --no-owner --no-privileges \
    --exclude-table=ab_flyway_schema_history "$SNAP_DB" \
    | grep -vE '^\\(un)?restrict |^SET transaction_timeout = |^-- Dumped (from database|by pg_dump) version '
} > "$OUT"
perl -0pi -e 's/\n+\z/\n/' "$OUT"
echo "[snapshot] wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)" >&2
