-- Migration: ab_jdbc_connector + ab_jdbc_connector_endpoint
-- Date: 2026-05-09
-- Plan: docs/plans/2026-05/2026-05-09-connector-sdk-mysql-impl-plan.md (Task 10)

CREATE TABLE IF NOT EXISTS ab_jdbc_connector (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id             BIGINT       NOT NULL,
    pid                   VARCHAR(32)  NOT NULL UNIQUE,
    name                  VARCHAR(128) NOT NULL,
    jdbc_url              VARCHAR(512) NOT NULL,
    username              VARCHAR(128) NOT NULL,
    password              VARCHAR(1024) NOT NULL,  -- encrypted-at-rest
    max_pool_size         INT          NOT NULL DEFAULT 5,
    connection_timeout_ms INT          NOT NULL DEFAULT 30000,
    enabled               BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by            BIGINT,
    updated_by            BIGINT
);
CREATE INDEX IF NOT EXISTS idx_ab_jdbc_connector_tenant ON ab_jdbc_connector(tenant_id);
COMMENT ON TABLE ab_jdbc_connector IS 'JDBC database connector configurations';
COMMENT ON COLUMN ab_jdbc_connector.password IS 'Encrypted via FieldEncryptionService; never returned by API';

CREATE TABLE IF NOT EXISTS ab_jdbc_connector_endpoint (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connector_pid VARCHAR(32)  NOT NULL,
    code          VARCHAR(64)  NOT NULL,
    name          VARCHAR(128),
    operation     VARCHAR(16)  NOT NULL,        -- 'query' | 'update'
    sql_template  TEXT         NOT NULL,
    UNIQUE (connector_pid, code)
);
CREATE INDEX IF NOT EXISTS idx_ab_jdbc_connector_endpoint_pid
    ON ab_jdbc_connector_endpoint(connector_pid);
COMMENT ON TABLE ab_jdbc_connector_endpoint IS 'JDBC connector endpoint definitions (parameterised SQL templates)';
COMMENT ON COLUMN ab_jdbc_connector_endpoint.operation IS 'query (SELECT) or update (INSERT/UPDATE/DELETE)';
