-- 2026-05-28: G5 — Automation node execution status table
-- Purpose: SmartEngine runs automations in MEMORY (CUSTOM) storage mode, so per-node
-- runtime state is never persisted by the engine itself. This table captures one row
-- per (automation_log, node) so the designer can overlay run history on the graph.
--
-- Lifecycle: AutomationActionServiceTaskDelegate inserts a 'running' row on entry and
-- updates it to 'completed' or 'failed' on exit. The delegate must propagate the
-- original exception (no swallow-and-ignore): the failure row is the observability
-- artefact, the exception is the control-flow signal SmartEngine needs.

CREATE TABLE IF NOT EXISTS ab_automation_node_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    automation_log_id BIGINT NOT NULL,           -- FK to ab_automation_log.id
    automation_id VARCHAR(64) NOT NULL,          -- denormalised Automation.pid (sized for ULID + safety margin)
    process_instance_id VARCHAR(128),            -- SmartEngine process instance id (best-effort)
    node_id VARCHAR(128) NOT NULL,               -- node id from the designer flow
    status VARCHAR(20) NOT NULL,                 -- pending|running|completed|failed|skipped
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_automation_node_exec_status CHECK (status IN (
        'pending', 'running', 'completed', 'failed', 'skipped'
    ))
);

CREATE INDEX IF NOT EXISTS idx_automation_node_exec_log
    ON ab_automation_node_execution(automation_log_id);
CREATE INDEX IF NOT EXISTS idx_automation_node_exec_tenant_automation
    ON ab_automation_node_execution(tenant_id, automation_id);
CREATE INDEX IF NOT EXISTS idx_automation_node_exec_pi
    ON ab_automation_node_execution(process_instance_id);

COMMENT ON TABLE ab_automation_node_execution IS
    'Per-node execution status for an automation run; powers the designer runtime overlay (G5).';
