-- EventPolicy transactional outbox (docs/2.md §9): a form/data-save transaction writes one PENDING
-- event row; after commit a processor runs the bound policy's run-and-execute. Decouples the save
-- from side effects (no notify/process failure rolls back the save; no slow external call blocks it).
-- Prefix ab_drt_ per DDR-2026-06-08.

CREATE TABLE IF NOT EXISTS ab_drt_outbox (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid           TEXT UNIQUE NOT NULL,
    tenant_id     BIGINT NOT NULL,
    event_id      TEXT NOT NULL,
    event_type    TEXT NOT NULL,
    target_type   TEXT,
    target_key    TEXT,
    context_json  JSONB NOT NULL DEFAULT '{}'::jsonb,
    status        TEXT NOT NULL DEFAULT 'PENDING',
    attempts      INT NOT NULL DEFAULT 0,
    last_error    TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at  TIMESTAMPTZ,

    CONSTRAINT uq_drt_outbox_tenant_event UNIQUE (tenant_id, event_id),
    CONSTRAINT chk_drt_outbox_status CHECK (status IN ('PENDING', 'PROCESSED', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_drt_outbox_pending
    ON ab_drt_outbox (tenant_id, status, created_at)
    WHERE status = 'PENDING';

COMMENT ON TABLE ab_drt_outbox IS 'EventPolicy transactional outbox; PENDING events processed after commit (docs/2.md §9)';
