-- 2026-06-08: Decision Runtime Foundation
-- Purpose: Persistence layer for the Decision Runtime (M1/M2 nucleus).
--
-- Three tables:
--   ab_drt_definition  – the logical decision catalogue entry per tenant
--   ab_drt_version     – versioned, immutable-once-published definition payload
--   ab_drt_log         – immutable evaluation audit trail
--
-- Naming: prefix ab_drt_ avoids collision with the existing ab_decision_definition /
-- ab_decision_record tables that belong to the meta-adjudication concept
-- (framework.meta...DecisionController @ /api/meta/decisions).

-- ─────────────────────────────────────────────────────────────────
-- ab_drt_definition
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ab_drt_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid             VARCHAR(26) UNIQUE NOT NULL,
    tenant_id       BIGINT NOT NULL,

    decision_code   VARCHAR(100) NOT NULL,
    decision_name   VARCHAR(200) NOT NULL,
    description     TEXT,

    -- optional scoping: MODEL / WORKFLOW / GLOBAL …
    scope_type      VARCHAR(50),
    scope_ref       VARCHAR(200),

    -- owning plugin / module for display grouping
    owner_module    VARCHAR(100),

    enabled         BOOLEAN NOT NULL DEFAULT TRUE,

    -- audit
    created_by      VARCHAR(26),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by      VARCHAR(26),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_drt_def_tenant_code UNIQUE (tenant_id, decision_code)
);

CREATE INDEX IF NOT EXISTS idx_drt_def_tenant
    ON ab_drt_definition (tenant_id);
CREATE INDEX IF NOT EXISTS idx_drt_def_code
    ON ab_drt_definition (tenant_id, decision_code);

COMMENT ON TABLE  ab_drt_definition IS 'Decision Runtime — logical decision catalogue entry per tenant';
COMMENT ON COLUMN ab_drt_definition.decision_code IS 'Unique machine-readable identifier within the tenant';
COMMENT ON COLUMN ab_drt_definition.scope_type    IS 'Scoping hint: MODEL | WORKFLOW | GLOBAL | COMMAND';
COMMENT ON COLUMN ab_drt_definition.owner_module  IS 'Plugin/module that owns this decision (grouping)';

-- ─────────────────────────────────────────────────────────────────
-- ab_drt_version
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ab_drt_version (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid                 VARCHAR(26) UNIQUE NOT NULL,
    tenant_id           BIGINT NOT NULL,

    decision_code       VARCHAR(100) NOT NULL,
    version             INTEGER NOT NULL,       -- monotonically incrementing per (tenant, code)
    version_tag         VARCHAR(100),           -- optional human label e.g. "v1.2-hotfix"

    -- lifecycle: DRAFT → VALIDATED → PUBLISHED → DEPRECATED → RETIRED
    status              VARCHAR(20) NOT NULL DEFAULT 'DRAFT',

    -- decision type and runtime adapter
    kind                VARCHAR(50) NOT NULL,   -- SIMPLE_CONDITION | DECISION_TABLE | …
    runtime_adapter     VARCHAR(50) NOT NULL,   -- AST_EVALUATOR | DMN | …

    -- content
    content_format      VARCHAR(20) NOT NULL DEFAULT 'JSON',
    content_json        JSONB,                  -- the serialised decision payload
    input_schema_json   JSONB,                  -- JSON Schema for caller input
    output_schema_json  JSONB,                  -- JSON Schema for result outputs
    context_schema_json JSONB,                  -- expected DecisionContext scopes
    field_refs_json     JSONB,                  -- field references extracted by validator
    function_refs_json  JSONB,                  -- function references extracted by validator
    content_hash        VARCHAR(64),            -- SHA-256 of content_json for change detection

    -- publish window
    effective_from      TIMESTAMPTZ,
    effective_to        TIMESTAMPTZ,

    -- publish provenance
    published_by        VARCHAR(26),
    published_at        TIMESTAMPTZ,

    -- row created
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_drt_ver_tenant_code_ver UNIQUE (tenant_id, decision_code, version),
    CONSTRAINT chk_drt_ver_status CHECK (status IN (
        'DRAFT', 'VALIDATED', 'PUBLISHED', 'DEPRECATED', 'RETIRED'
    )),
    CONSTRAINT chk_drt_ver_kind CHECK (kind IN (
        'SIMPLE_CONDITION', 'DECISION_TABLE', 'RULE_SET', 'EXPRESSION', 'COMPOSITE'
    ))
);

CREATE INDEX IF NOT EXISTS idx_drt_ver_tenant_code
    ON ab_drt_version (tenant_id, decision_code);
CREATE INDEX IF NOT EXISTS idx_drt_ver_published
    ON ab_drt_version (tenant_id, decision_code, status)
    WHERE status = 'PUBLISHED';

COMMENT ON TABLE  ab_drt_version IS 'Decision Runtime — versioned, immutable-once-published definition payload';
COMMENT ON COLUMN ab_drt_version.version      IS 'Monotonically incrementing version number per (tenant, decision_code)';
COMMENT ON COLUMN ab_drt_version.content_hash IS 'SHA-256 of content_json, used for change detection and idempotency';
COMMENT ON COLUMN ab_drt_version.field_refs_json    IS 'Field references extracted by DecisionRuntime.validate()';
COMMENT ON COLUMN ab_drt_version.function_refs_json IS 'Function references extracted by DecisionRuntime.validate()';

-- ─────────────────────────────────────────────────────────────────
-- ab_drt_log
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ab_drt_log (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid                 VARCHAR(26) UNIQUE NOT NULL,
    tenant_id           BIGINT NOT NULL,

    -- correlation
    trace_id            VARCHAR(64),            -- caller-supplied or generated UUID
    correlation_id      VARCHAR(64),            -- parent workflow / automation run id

    -- which decision was evaluated
    decision_code       VARCHAR(100) NOT NULL,
    decision_version    INTEGER NOT NULL,

    -- mirrored meta from the version row (denormalised for log independence)
    kind                VARCHAR(50),
    runtime_adapter     VARCHAR(50),

    -- caller context
    caller_type         VARCHAR(50),            -- AUTOMATION | BPM | API | TEST …
    caller_ref          VARCHAR(200),           -- pid of the calling entity

    -- payload fingerprints (sha-256; full payloads not stored to respect data minimisation)
    input_digest        VARCHAR(64),
    result_digest       VARCHAR(64),

    -- outcome
    matched             BOOLEAN NOT NULL DEFAULT FALSE,
    status              VARCHAR(20) NOT NULL,   -- MATCHED | NOT_MATCHED | ERROR | SKIPPED | UNKNOWN

    -- structured result detail
    matched_rules_json  JSONB,                  -- DecisionResult.matchedRules serialised

    -- performance
    duration_ms         BIGINT,

    -- error detail (only when status=ERROR)
    error_code          VARCHAR(100),
    error_message       TEXT,

    -- immutable once written
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT chk_drt_log_status CHECK (status IN (
        'MATCHED', 'NOT_MATCHED', 'ERROR', 'SKIPPED', 'UNKNOWN'
    ))
);

CREATE INDEX IF NOT EXISTS idx_drt_log_tenant_code
    ON ab_drt_log (tenant_id, decision_code, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_drt_log_trace
    ON ab_drt_log (trace_id)
    WHERE trace_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_drt_log_correlation
    ON ab_drt_log (correlation_id)
    WHERE correlation_id IS NOT NULL;

COMMENT ON TABLE  ab_drt_log IS 'Decision Runtime — immutable evaluation audit trail';
COMMENT ON COLUMN ab_drt_log.trace_id       IS 'Caller-supplied or auto-generated evaluation trace id';
COMMENT ON COLUMN ab_drt_log.input_digest   IS 'SHA-256 of serialised input context (data minimisation)';
COMMENT ON COLUMN ab_drt_log.result_digest  IS 'SHA-256 of serialised DecisionResult (data minimisation)';
