-- 2026-06-09: Decision Runtime impact acknowledgement audit
-- Purpose: persist explicit blast-radius acknowledgements before guarded changes.

CREATE TABLE IF NOT EXISTS ab_drt_impact_ack (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid                  VARCHAR(26) UNIQUE NOT NULL,
    tenant_id            BIGINT NOT NULL,
    action_type          VARCHAR(50) NOT NULL,
    target_type          VARCHAR(50) NOT NULL,
    target_code          VARCHAR(200),
    target_pid           VARCHAR(26),
    target_path          VARCHAR(500),
    impact_summary       TEXT,
    impact_snapshot_json JSONB,
    acknowledged_by      VARCHAR(26),
    acknowledged_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    note                 TEXT,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_drt_impact_ack_target
    ON ab_drt_impact_ack (tenant_id, target_type, target_code, target_pid);

CREATE INDEX IF NOT EXISTS idx_drt_impact_ack_field
    ON ab_drt_impact_ack (tenant_id, target_path)
    WHERE target_path IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_drt_impact_ack_action
    ON ab_drt_impact_ack (tenant_id, action_type, acknowledged_at DESC);

COMMENT ON TABLE ab_drt_impact_ack IS 'Decision Runtime - explicit blast-radius acknowledgement audit snapshots';
COMMENT ON COLUMN ab_drt_impact_ack.action_type IS 'PUBLISH | APPROVE | DEPRECATE | RETIRE | FIELD_DELETE | FIELD_TYPE_CHANGE';
