-- 2026-06-08: Event Policy Foundation
-- Purpose: Persistence layer for the EventPolicy module.
--
-- Two tables:
--   ab_drt_policy_definition  – logical catalogue entry (event_type / target)
--   ab_drt_policy_version     – versioned, immutable-once-published rules payload
--
-- Naming: prefix ab_drt_policy_ avoids collision with the existing ab_drt_* tables
-- (Decision Runtime) and any future ab_policy_* tables.
--
-- Enum values are copied verbatim from Java source:
--   VersionStatus    : com.auraboot.framework.decision.model.VersionStatus
--   PolicyPhase      : com.auraboot.framework.eventpolicy.model.PolicyPhase
--   MatchMode        : com.auraboot.framework.eventpolicy.model.MatchMode
--   ExecutionMode    : com.auraboot.framework.eventpolicy.model.ExecutionMode
--   FailureStrategy  : com.auraboot.framework.eventpolicy.model.FailureStrategy
--   ConflictStrategy : com.auraboot.framework.eventpolicy.model.ConflictStrategy
--   DedupStrategy    : com.auraboot.framework.eventpolicy.model.DedupStrategy

-- ─────────────────────────────────────────────────────────────────
-- ab_drt_policy_definition
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ab_drt_policy_definition (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid             VARCHAR(26) UNIQUE NOT NULL,
    tenant_id       BIGINT NOT NULL,

    policy_code     VARCHAR(100) NOT NULL,
    policy_name     VARCHAR(200) NOT NULL,

    -- what event triggers this policy and on what target
    event_type      VARCHAR(100) NOT NULL,
    target_type     VARCHAR(100),
    target_key      VARCHAR(200),

    enabled         BOOLEAN NOT NULL DEFAULT TRUE,

    -- audit
    created_by      VARCHAR(26),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by      VARCHAR(26),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_drt_policy_def_tenant_code UNIQUE (tenant_id, policy_code)
);

CREATE INDEX IF NOT EXISTS idx_drt_policy_def_tenant
    ON ab_drt_policy_definition (tenant_id);
CREATE INDEX IF NOT EXISTS idx_drt_policy_def_event_target
    ON ab_drt_policy_definition (tenant_id, event_type, target_type, target_key);

COMMENT ON TABLE  ab_drt_policy_definition IS 'Event Policy — logical policy catalogue entry per tenant';
COMMENT ON COLUMN ab_drt_policy_definition.policy_code  IS 'Unique machine-readable identifier within the tenant';
COMMENT ON COLUMN ab_drt_policy_definition.event_type   IS 'Event that triggers this policy, e.g. FORM_SUBMITTED';
COMMENT ON COLUMN ab_drt_policy_definition.target_type  IS 'Target entity type, e.g. FORM';
COMMENT ON COLUMN ab_drt_policy_definition.target_key   IS 'Target instance key, e.g. model code or form code';

-- ─────────────────────────────────────────────────────────────────
-- ab_drt_policy_version
-- ─────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS ab_drt_policy_version (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid                 VARCHAR(26) UNIQUE NOT NULL,
    tenant_id           BIGINT NOT NULL,

    policy_code         VARCHAR(100) NOT NULL,
    version             INTEGER NOT NULL,       -- monotonically incrementing per (tenant, code)

    -- lifecycle: DRAFT → VALIDATED → PUBLISHED → DEPRECATED → RETIRED
    -- values from com.auraboot.framework.decision.model.VersionStatus
    status              VARCHAR(20) NOT NULL DEFAULT 'DRAFT',

    -- execution configuration
    -- values from com.auraboot.framework.eventpolicy.model.PolicyPhase
    phase               VARCHAR(30) NOT NULL DEFAULT 'AFTER_COMMIT',
    -- values from com.auraboot.framework.eventpolicy.model.MatchMode
    match_mode          VARCHAR(30) NOT NULL DEFAULT 'COLLECT_ALL',
    -- values from com.auraboot.framework.eventpolicy.model.ExecutionMode
    execution_mode      VARCHAR(20) NOT NULL DEFAULT 'ORDERED',
    -- values from com.auraboot.framework.eventpolicy.model.FailureStrategy
    failure_strategy    VARCHAR(30) NOT NULL DEFAULT 'FAIL_FAST',
    -- values from com.auraboot.framework.eventpolicy.model.ConflictStrategy
    conflict_strategy   VARCHAR(30) NOT NULL DEFAULT 'REJECT_ON_CONFLICT',
    -- values from com.auraboot.framework.eventpolicy.model.DedupStrategy
    dedup_strategy      VARCHAR(40) NOT NULL DEFAULT 'BY_IDEMPOTENCY_KEY',

    -- the versioned rule set (serialised List<PolicyRule>)
    rules_json          JSONB,

    -- SHA-256 of rules_json
    content_hash        VARCHAR(64),

    -- publish provenance
    published_by        VARCHAR(26),
    published_at        TIMESTAMPTZ,

    -- row created
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_drt_policy_ver_tenant_code_ver UNIQUE (tenant_id, policy_code, version),

    -- status: com.auraboot.framework.decision.model.VersionStatus
    CONSTRAINT chk_drt_policy_ver_status CHECK (status IN (
        'DRAFT', 'VALIDATED', 'PUBLISHED', 'DEPRECATED', 'RETIRED'
    )),
    -- phase: com.auraboot.framework.eventpolicy.model.PolicyPhase
    CONSTRAINT chk_drt_policy_ver_phase CHECK (phase IN (
        'BEFORE_SUBMIT', 'AFTER_COMMIT', 'ASYNC_WORKER'
    )),
    -- match_mode: com.auraboot.framework.eventpolicy.model.MatchMode
    CONSTRAINT chk_drt_policy_ver_match_mode CHECK (match_mode IN (
        'FIRST_MATCH', 'COLLECT_ALL', 'UNIQUE', 'PRIORITY_FIRST'
    )),
    -- execution_mode: com.auraboot.framework.eventpolicy.model.ExecutionMode
    CONSTRAINT chk_drt_policy_ver_execution_mode CHECK (execution_mode IN (
        'ORDERED', 'UNORDERED'
    )),
    -- failure_strategy: com.auraboot.framework.eventpolicy.model.FailureStrategy
    CONSTRAINT chk_drt_policy_ver_failure_strategy CHECK (failure_strategy IN (
        'FAIL_FAST', 'CONTINUE_ON_ERROR', 'ALL_OR_NOTHING', 'RETRY_ASYNC', 'DEAD_LETTER'
    )),
    -- conflict_strategy: com.auraboot.framework.eventpolicy.model.ConflictStrategy
    CONSTRAINT chk_drt_policy_ver_conflict_strategy CHECK (conflict_strategy IN (
        'REJECT_ON_CONFLICT', 'PRIORITY_WINS', 'LAST_WRITE_WINS', 'MERGE_IF_COMPATIBLE'
    )),
    -- dedup_strategy: com.auraboot.framework.eventpolicy.model.DedupStrategy
    CONSTRAINT chk_drt_policy_ver_dedup_strategy CHECK (dedup_strategy IN (
        'NONE', 'BY_IDEMPOTENCY_KEY', 'BY_ACTION_TYPE_AND_TARGET'
    ))
);

CREATE INDEX IF NOT EXISTS idx_drt_policy_ver_tenant_code
    ON ab_drt_policy_version (tenant_id, policy_code);
CREATE INDEX IF NOT EXISTS idx_drt_policy_ver_published
    ON ab_drt_policy_version (tenant_id, policy_code, status)
    WHERE status = 'PUBLISHED';

COMMENT ON TABLE  ab_drt_policy_version IS 'Event Policy — versioned, immutable-once-published rules payload';
COMMENT ON COLUMN ab_drt_policy_version.version       IS 'Monotonically incrementing version number per (tenant, policy_code)';
COMMENT ON COLUMN ab_drt_policy_version.rules_json    IS 'Serialised List<PolicyRule> (each rule has ConditionNode + List<PolicyAction>)';
COMMENT ON COLUMN ab_drt_policy_version.content_hash  IS 'SHA-256 of rules_json, for change detection and idempotency';
