-- Decision Runtime rollout long-window metric buckets.

CREATE TABLE IF NOT EXISTS ab_drt_rollout_metric_bucket (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                  BIGINT NOT NULL,
    rollout_policy_pid         VARCHAR(26) NOT NULL,
    decision_code              VARCHAR(100) NOT NULL,
    rollout_arm                VARCHAR(20) NOT NULL,
    bucket_seconds             INTEGER NOT NULL,
    bucket_start               TIMESTAMPTZ NOT NULL,
    evaluations                BIGINT NOT NULL DEFAULT 0,
    matched                    BIGINT NOT NULL DEFAULT 0,
    errors                     BIGINT NOT NULL DEFAULT 0,
    p95_latency_ms             BIGINT,
    result_distribution_json   JSONB NOT NULL DEFAULT '{}'::jsonb,
    refreshed_at               TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                 TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_drt_rollout_metric_bucket_arm CHECK (rollout_arm IN ('BASELINE', 'CANDIDATE')),
    CONSTRAINT chk_drt_rollout_metric_bucket_seconds CHECK (bucket_seconds > 0),
    CONSTRAINT uk_drt_rollout_metric_bucket UNIQUE (
        tenant_id, rollout_policy_pid, bucket_seconds, bucket_start, rollout_arm
    )
);

CREATE INDEX IF NOT EXISTS idx_drt_rollout_metric_bucket_window
    ON ab_drt_rollout_metric_bucket (
        tenant_id, rollout_policy_pid, bucket_seconds, bucket_start DESC
    );

CREATE INDEX IF NOT EXISTS idx_drt_rollout_metric_bucket_retention
    ON ab_drt_rollout_metric_bucket (tenant_id, bucket_start);

COMMENT ON TABLE ab_drt_rollout_metric_bucket IS
    'Decision Runtime — pre-aggregated rollout metrics for long-window version comparisons';
