-- EventPolicy action execution log — restart-durable idempotency for the PolicyExecutor
-- (docs/2.md §8.2). A successful (tenant_id, idempotency_key) is never re-executed.
-- Prefix ab_drt_ per DDR-2026-06-08 (avoids the existing ab_decision_* adjudication tables).

CREATE TABLE IF NOT EXISTS ab_drt_policy_exec_log (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid             TEXT UNIQUE NOT NULL,
    tenant_id       BIGINT NOT NULL,
    idempotency_key TEXT NOT NULL,
    policy_code     TEXT,
    rule_code       TEXT,
    action_type     TEXT,
    status          TEXT NOT NULL,
    error_message   TEXT,
    executed_at     TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_drt_exec_tenant_key UNIQUE (tenant_id, idempotency_key),
    -- must match com.auraboot.framework.eventpolicy.executor.ActionExecutionStatus
    CONSTRAINT chk_drt_exec_status CHECK (status IN (
        'SUCCESS', 'FAILED', 'SKIPPED', 'NO_HANDLER', 'RETRY_PENDING', 'DEAD_LETTER', 'NOT_EXECUTED'
    ))
);

CREATE INDEX IF NOT EXISTS idx_drt_exec_tenant_key
    ON ab_drt_policy_exec_log (tenant_id, idempotency_key);
CREATE INDEX IF NOT EXISTS idx_drt_exec_policy
    ON ab_drt_policy_exec_log (tenant_id, policy_code, executed_at);

COMMENT ON TABLE ab_drt_policy_exec_log IS 'EventPolicy action execution log; unique (tenant, idempotency_key) gives restart-durable idempotency';
