-- Decision Runtime progressive rollout policies and evaluation metadata.

CREATE TABLE IF NOT EXISTS ab_drt_rollout_policy (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid                 VARCHAR(26) UNIQUE NOT NULL,
    tenant_id           BIGINT NOT NULL,
    decision_code       VARCHAR(100) NOT NULL,
    baseline_version    INTEGER NOT NULL,
    candidate_version   INTEGER NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    percentage          INTEGER NOT NULL DEFAULT 0,
    cohort_json         JSONB,
    segment_json        JSONB,
    routing_key_expr    VARCHAR(200),
    salt                VARCHAR(100),
    started_by          VARCHAR(26),
    started_at          TIMESTAMPTZ,
    ended_by            VARCHAR(26),
    ended_at            TIMESTAMPTZ,
    audit_json          JSONB,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_drt_rollout_status CHECK (status IN (
        'DRAFT', 'ACTIVE', 'PAUSED', 'PROMOTED', 'ROLLED_BACK'
    )),
    CONSTRAINT chk_drt_rollout_percentage CHECK (percentage >= 0 AND percentage <= 100),
    CONSTRAINT chk_drt_rollout_versions CHECK (baseline_version <> candidate_version)
);

CREATE INDEX IF NOT EXISTS idx_drt_rollout_decision
    ON ab_drt_rollout_policy (tenant_id, decision_code, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_drt_rollout_active
    ON ab_drt_rollout_policy (tenant_id, decision_code, status)
    WHERE status = 'ACTIVE';

ALTER TABLE ab_drt_log ADD COLUMN IF NOT EXISTS selected_version INTEGER;
ALTER TABLE ab_drt_log ADD COLUMN IF NOT EXISTS rollout_policy_pid VARCHAR(26);
ALTER TABLE ab_drt_log ADD COLUMN IF NOT EXISTS rollout_bucket INTEGER;
ALTER TABLE ab_drt_log ADD COLUMN IF NOT EXISTS rollout_arm VARCHAR(20);
ALTER TABLE ab_drt_log ADD COLUMN IF NOT EXISTS routing_key VARCHAR(200);
ALTER TABLE ab_drt_log ADD COLUMN IF NOT EXISTS rollout_result_key VARCHAR(200);

CREATE INDEX IF NOT EXISTS idx_drt_log_rollout
    ON ab_drt_log (tenant_id, rollout_policy_pid, created_at DESC)
    WHERE rollout_policy_pid IS NOT NULL;
