-- Permission Governance S1 foundation (existing-DB increment; schema.sql is authoritative for fresh resets).
-- Additive only — the live evaluator keeps using the legacy `conditions` column until Plan B swaps
-- PolicyExpressionEvaluator -> ConditionAstEvaluator. The enterprise PermissionCompiler is the ONLY writer
-- of condition_ast / data_scope_ast / source_ref / snapshot_id and of ab_permission_snapshot.

ALTER TABLE ab_role_permission ADD COLUMN IF NOT EXISTS condition_ast  JSONB;
ALTER TABLE ab_role_permission ADD COLUMN IF NOT EXISTS data_scope_ast JSONB;
ALTER TABLE ab_role_permission ADD COLUMN IF NOT EXISTS source_ref     TEXT;
ALTER TABLE ab_role_permission ADD COLUMN IF NOT EXISTS snapshot_id    BIGINT;

CREATE TABLE IF NOT EXISTS ab_permission_snapshot (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid         VARCHAR(32) UNIQUE NOT NULL,
    tenant_id   BIGINT NOT NULL,
    version     TEXT NOT NULL,
    scope       TEXT NOT NULL,              -- ROLE / PACKAGE / GLOBAL
    scope_ref   BIGINT,
    content     JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by  BIGINT
);
CREATE INDEX IF NOT EXISTS idx_perm_snapshot_tenant_scope ON ab_permission_snapshot (tenant_id, scope, scope_ref);
