-- 2026-06-09: Decision Runtime usage index
-- Purpose: persisted source -> target references for DecisionOps impact analysis.

CREATE TABLE IF NOT EXISTS ab_drt_usage_ref (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid             VARCHAR(26) UNIQUE NOT NULL,
    tenant_id       BIGINT NOT NULL,

    source_type     VARCHAR(50) NOT NULL,
    source_code     VARCHAR(200) NOT NULL,
    source_version  VARCHAR(50),
    source_pid      VARCHAR(26),

    target_type     VARCHAR(50) NOT NULL,
    target_code     VARCHAR(200),
    target_path     VARCHAR(500),

    binding         VARCHAR(50),
    metadata_json   JSONB,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_drt_usage_ref_target_decision
    ON ab_drt_usage_ref (tenant_id, target_type, target_code)
    WHERE target_type = 'DECISION';

CREATE INDEX IF NOT EXISTS idx_drt_usage_ref_target_field
    ON ab_drt_usage_ref (tenant_id, target_type, target_path)
    WHERE target_type = 'FIELD';

CREATE INDEX IF NOT EXISTS idx_drt_usage_ref_target_integration
    ON ab_drt_usage_ref (tenant_id, target_type, target_code)
    WHERE target_type IN ('CONNECTOR', 'WEBHOOK');

CREATE INDEX IF NOT EXISTS idx_drt_usage_ref_source
    ON ab_drt_usage_ref (tenant_id, source_type, source_code);

COMMENT ON TABLE ab_drt_usage_ref IS 'Decision Runtime - indexed source-to-target references for impact analysis';
COMMENT ON COLUMN ab_drt_usage_ref.source_type IS 'DECISION_VERSION | AUTOMATION | SLA_RULE | EVENT_POLICY | NAMED_QUERY | BPM';
COMMENT ON COLUMN ab_drt_usage_ref.target_type IS 'DECISION | FIELD | FUNCTION | CONNECTOR | WEBHOOK | POLICY';
