-- EventPolicy WRITE_AUDIT action trail (docs/2.md §7): a policy-author-configured audit action writes
-- a business audit entry when its rule matches. Distinct from ab_drt_policy_exec_log (system
-- execution telemetry / idempotency) — this is the user-configured business audit side effect.
-- Prefix ab_drt_ per DDR-2026-06-08.

CREATE TABLE IF NOT EXISTS ab_drt_action_audit (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid             TEXT UNIQUE NOT NULL,
    tenant_id       BIGINT NOT NULL,
    rule_code       TEXT,
    action_type     TEXT NOT NULL,
    target          TEXT,
    message         TEXT,
    payload_json    JSONB NOT NULL DEFAULT '{}'::jsonb,
    idempotency_key TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_drt_action_audit_tenant_time
    ON ab_drt_action_audit (tenant_id, created_at DESC);

COMMENT ON TABLE ab_drt_action_audit IS 'EventPolicy WRITE_AUDIT action trail (user-configured business audit, docs/2.md §7)';
