/**
 * Behavior Ingest Quarantine — Golden Spec
 *
 * Proves the Kafka-decoupled ingest contract from a public keyed endpoint:
 *   POST /api/collect/keyed → {accepted:1}
 *     valid event      → ab_behavior_event
 *     over-long event  → ab_behavior_quarantine(reason=constraint_violation), no event row
 *     malformed event  → ab_behavior_quarantine(reason=malformed_missing_event_id), no event row
 *
 * This spec intentionally does not depend on the SP3 public SDK branch; it verifies the
 * server-side user contract this Kafka-decouple slice owns.
 */

import { test, expect } from '@playwright/test';
import { execSync } from 'node:child_process';
import { PSQL_BASE, PG_ENV, BACKEND_URL } from '../../helpers/environments';

const KEYED_URL = `${BACKEND_URL}/api/collect/keyed`;

function sh(command: string): string {
  return execSync(command, { encoding: 'utf-8', timeout: 15_000 }).trim();
}

function psql(sql: string): string {
  return execSync(`${PSQL_BASE} -P pager=off -t -A -c "${sql.replace(/"/g, '\\"')}"`, {
    encoding: 'utf-8',
    env: { ...PG_ENV, PGPASSWORD: process.env.PGPASSWORD ?? 'auraboot' },
    timeout: 10_000,
  }).trim();
}

function sqlLit(s: string): string {
  return s.replace(/'/g, "''");
}

function keyedPost(siteKey: string, events: object[]): { status: number; body: string } {
  const bodyFile = `/tmp/behavior-keyed-${Date.now()}-${Math.random().toString(36).slice(2)}.json`;
  const status = sh(
    `curl --noproxy '*' -s -o '${bodyFile}' -w '%{http_code}' -X POST ${KEYED_URL} ` +
      `-H 'Content-Type: application/json' -H 'X-Site-Key: ${siteKey}' ` +
      `-d '${JSON.stringify({ events }).replace(/'/g, "'\\''")}'`,
  );
  const body = sh(`cat '${bodyFile}' && rm -f '${bodyFile}'`);
  return { status: parseInt(status, 10), body };
}

test.describe.serial('Behavior Ingest Quarantine — Golden', () => {
  test.setTimeout(120_000);

  let tenantId: string;
  let siteKey: string;

  test.beforeAll(() => {
    tenantId = '990367';
    siteKey = `abk_biq_${Date.now()}000000000000000000000`.slice(0, 48);
    psql(`
      CREATE TABLE IF NOT EXISTS mt_behavior_site_key (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        pid VARCHAR(32) NOT NULL,
        tenant_id BIGINT,
        site_key VARCHAR(64),
        name VARCHAR(200) NOT NULL,
        status VARCHAR(32) DEFAULT 'active',
        origin_allowlist JSONB,
        created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        created_by VARCHAR(255),
        updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
        updated_by VARCHAR(255)
      )
    `);
    psql(`ALTER TABLE mt_behavior_site_key ADD COLUMN IF NOT EXISTS created_by VARCHAR(255)`);
    psql(`ALTER TABLE mt_behavior_site_key ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP`);
    psql(`ALTER TABLE mt_behavior_site_key ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255)`);
    psql(`CREATE UNIQUE INDEX IF NOT EXISTS uk_mt_behavior_site_key_pid ON mt_behavior_site_key (pid)`);
    psql(`CREATE UNIQUE INDEX IF NOT EXISTS uk_mt_behavior_site_key_site_key ON mt_behavior_site_key (site_key)`);
    psql(`DELETE FROM mt_behavior_site_key WHERE site_key LIKE 'abk_biq_%'`);
    psql(`
      INSERT INTO mt_behavior_site_key (pid, tenant_id, site_key, name, status)
      VALUES ('biq-${Date.now()}', ${tenantId}, '${sqlLit(siteKey)}', 'Kafka Quarantine Golden', 'active')
    `);
    psql(`DELETE FROM ab_behavior_event WHERE tenant_id=${tenantId}`);
    psql(`DELETE FROM ab_behavior_quarantine WHERE tenant_id=${tenantId}`);
  });

  test('BIQ-01 valid keyed event lands in behavior store', async () => {
    const eventId = `biq-ok-${Date.now()}`.slice(0, 40);
    const anonId = `biq-anon-ok-${Date.now()}`.slice(0, 64);

    const resp = keyedPost(siteKey, [{
      eventId,
      eventName: 'page_view',
      anonId,
      occurredAt: new Date().toISOString(),
    }]);

    expect(resp.status, resp.body).toBe(200);
    expect(resp.body).toContain('"accepted":1');
    await expect
      .poll(() => psql(`SELECT count(*) FROM ab_behavior_event WHERE tenant_id=${tenantId} AND event_id='${sqlLit(eventId)}'`),
        { timeout: 15_000 })
      .toBe('1');
    expect(psql(`SELECT count(*) FROM ab_behavior_quarantine WHERE tenant_id=${tenantId} AND anon_id='${sqlLit(anonId)}'`))
      .toBe('0');
  });

  test('BIQ-02 over-long event is accepted, not stored, and quarantined with raw event id', async () => {
    const eventId = `biq-overlong-${'x'.repeat(80)}`;
    const anonId = `biq-anon-overlong-${Date.now()}`.slice(0, 64);

    const resp = keyedPost(siteKey, [{
      eventId,
      eventName: 'page_view',
      anonId,
      occurredAt: new Date().toISOString(),
    }]);

    expect(resp.status, resp.body).toBe(200);
    expect(resp.body).toContain('"accepted":1');
    await expect
      .poll(() => psql(`SELECT count(*) FROM ab_behavior_quarantine WHERE tenant_id=${tenantId} AND anon_id='${sqlLit(anonId)}'`),
        { timeout: 15_000 })
      .toBe('1');
    expect(psql(`SELECT count(*) FROM ab_behavior_event WHERE tenant_id=${tenantId} AND anon_id='${sqlLit(anonId)}'`))
      .toBe('0');
    expect(psql(`SELECT reason FROM ab_behavior_quarantine WHERE tenant_id=${tenantId} AND anon_id='${sqlLit(anonId)}'`))
      .toBe('constraint_violation');
    expect(psql(`SELECT event_id FROM ab_behavior_quarantine WHERE tenant_id=${tenantId} AND anon_id='${sqlLit(anonId)}'`))
      .toBe(eventId);
  });

  test('BIQ-03 missing event id is accepted, not stored, and quarantined as malformed', async () => {
    const anonId = `biq-anon-bad-${Date.now()}`.slice(0, 64);

    const resp = keyedPost(siteKey, [{
      eventName: 'page_view',
      anonId,
      occurredAt: new Date().toISOString(),
    }]);

    expect(resp.status, resp.body).toBe(200);
    expect(resp.body).toContain('"accepted":1');
    await expect
      .poll(() => psql(`SELECT count(*) FROM ab_behavior_quarantine WHERE tenant_id=${tenantId} AND anon_id='${sqlLit(anonId)}'`),
        { timeout: 15_000 })
      .toBe('1');
    expect(psql(`SELECT count(*) FROM ab_behavior_event WHERE tenant_id=${tenantId} AND anon_id='${sqlLit(anonId)}'`))
      .toBe('0');
    expect(psql(`SELECT reason FROM ab_behavior_quarantine WHERE tenant_id=${tenantId} AND anon_id='${sqlLit(anonId)}'`))
      .toBe('malformed_missing_event_id');
  });
});
