export interface BrandingConfig {
  mode: 'community' | 'commercial';
  productName: string;
  platformName: string;
  logoUrl: string;
  faviconUrl: string;
  favicon32Url: string;
  appleTouchIconUrl: string;
  manifestUrl: string;
  websiteUrl: string;
  docsUrl: string;
  supportUrl: string;
  sourceUrl: string;
  commercialContactUrl: string;
  licenseName: string;
  licenseUrl: string;
  copyrightHolder: string;
  aurabootCopyrightHolder: string;
  poweredByText: string;
  generatedByText: string;
  /**
   * Optional login-story copy (deployment-specific vertical, e.g. a school
   * product). When present the auth pages render this instead of the
   * platform-default feature tiles; every field is independently optional.
   */
  loginBadge?: string;
  loginHeadline?: string;
  loginHeadlineEm?: string;
  loginLead?: string;
  loginHeroUrl?: string;
  loginFeatures?: string[];
  /**
   * Pure-wechat school deployment: the school-side login page renders only the
   * WeChat entry (no email/password channels). Platform admins use the separate
   * admin login route. Branding-level flag — applies when commercial branding resolves.
   */
  loginWechatOnly?: boolean;
  /**
   * Optional product-specific copy and channel choice for the no-tenant
   * onboarding page. Keeping this in signed deployment branding lets a
   * vertical product say "school" while the platform default remains
   * organization/workspace neutral.
   */
  tenantOnboarding?: TenantOnboardingBranding;
}

export type TenantJoinChannel = 'invite_code' | 'wechat_mini';

export interface TenantOnboardingBranding {
  entityLabel: string;
  industryCode?: string;
  postCreateRedirect?: string;
  selectionTitle: string;
  selectionLead: string;
  createTitle: string;
  createDescription: string;
  createCta: string;
  joinTitle: string;
  joinDescription: string;
  joinCta: string;
  joinChannel: TenantJoinChannel;
  miniProgramName?: string;
  miniProgramQrUrl?: string;
  joinSteps?: string[];
}

type TenantOnboardingDocument = TenantOnboardingBranding;

export interface DeploymentBrandingDocument {
  schemaVersion: 1;
  orderReference: string;
  productName: string;
  platformName: string;
  logoUrl: string;
  faviconUrl: string;
  favicon32Url: string;
  appleTouchIconUrl: string;
  manifestUrl: string;
  websiteUrl: string;
  docsUrl: string;
  supportUrl: string;
  copyrightHolder: string;
  poweredByText: string;
  generatedByText: string;
  loginBadge?: string;
  loginHeadline?: string;
  loginHeadlineEm?: string;
  loginLead?: string;
  loginHeroUrl?: string;
  loginFeatures?: string[];
  /**
   * Pure-wechat school deployment: the school-side login page renders only the
   * WeChat entry (no email/password channels). Platform admins use the separate
   * admin login route. Branding-level flag — applies when commercial branding resolves.
   */
  loginWechatOnly?: boolean;
  tenantOnboarding?: TenantOnboardingDocument;
}

export interface BuildIdentity {
  version: string;
  revision: string;
}

/**
 * Community builds always resolve to the AuraBoot identity. Commercial
 * branding must be introduced through a licensed deployment-level resolver,
 * never through client-controlled preferences.
 */
export const COMMUNITY_BRANDING: Readonly<BrandingConfig> = Object.freeze({
  mode: 'community',
  productName: 'AuraBoot',
  platformName: 'AuraBoot Platform',
  logoUrl: '/android-chrome-192x192.png',
  faviconUrl: '/favicon.ico',
  favicon32Url: '/favicon-32x32.png',
  appleTouchIconUrl: '/apple-touch-icon.png',
  manifestUrl: '/manifest.json',
  websiteUrl: 'https://auraboot.com',
  docsUrl: 'https://auraboot.com/docs',
  supportUrl: 'https://auraboot.com/contact',
  sourceUrl: 'https://github.com/AuraBootTeam/auraboot',
  commercialContactUrl: 'https://auraboot.com/contact',
  licenseName: 'AuraBoot License Agreement 1.3',
  licenseUrl: 'https://github.com/AuraBootTeam/auraboot/blob/main/LICENSE.txt',
  copyrightHolder: 'The AuraBoot Project and its contributors',
  aurabootCopyrightHolder: 'The AuraBoot Project and its contributors',
  poweredByText: 'Powered by AuraBoot',
  generatedByText: 'Generated by AuraBoot Platform',
});

const DEPLOYMENT_KEYS = new Set<keyof DeploymentBrandingDocument>([
  'schemaVersion',
  'orderReference',
  'productName',
  'platformName',
  'logoUrl',
  'faviconUrl',
  'favicon32Url',
  'appleTouchIconUrl',
  'manifestUrl',
  'websiteUrl',
  'docsUrl',
  'supportUrl',
  'copyrightHolder',
  'poweredByText',
  'generatedByText',
  'loginBadge',
  'loginHeadline',
  'loginHeadlineEm',
  'loginLead',
  'loginHeroUrl',
  'loginFeatures',
  'loginWechatOnly',
  'tenantOnboarding',
]);

const TENANT_ONBOARDING_KEYS = new Set<keyof TenantOnboardingDocument>([
  'entityLabel',
  'industryCode',
  'postCreateRedirect',
  'selectionTitle',
  'selectionLead',
  'createTitle',
  'createDescription',
  'createCta',
  'joinTitle',
  'joinDescription',
  'joinCta',
  'joinChannel',
  'miniProgramName',
  'miniProgramQrUrl',
  'joinSteps',
]);

const FIELD_LIMITS: Partial<Record<keyof DeploymentBrandingDocument, number>> = {
  orderReference: 120,
  productName: 80,
  platformName: 120,
  copyrightHolder: 160,
  poweredByText: 160,
  generatedByText: 160,
  logoUrl: 2048,
  faviconUrl: 2048,
  favicon32Url: 2048,
  appleTouchIconUrl: 2048,
  manifestUrl: 2048,
  websiteUrl: 2048,
  docsUrl: 2048,
  supportUrl: 2048,
  loginBadge: 80,
  loginHeadline: 120,
  loginHeadlineEm: 120,
  loginLead: 240,
  loginHeroUrl: 2048,
};

function requiredText(value: unknown, field: keyof DeploymentBrandingDocument): string {
  if (typeof value !== 'string' || !value.trim()) {
    throw new Error(`Deployment branding field "${field}" must be a non-empty string.`);
  }
  const normalized = value.trim();
  const limit = FIELD_LIMITS[field];
  if (limit && normalized.length > limit) {
    throw new Error(`Deployment branding field "${field}" must be at most ${limit} characters.`);
  }
  return normalized;
}

function safeUrl(value: unknown, field: keyof DeploymentBrandingDocument): string {
  const url = requiredText(value, field);
  if (url.startsWith('/') && !url.startsWith('//')) return url;
  try {
    const parsed = new URL(url);
    if (parsed.protocol === 'https:' && parsed.hostname) return url;
  } catch {
    // Fall through to the stable configuration error below.
  }
  throw new Error(
    `Deployment branding field "${field}" must be a same-origin path or an HTTPS URL.`,
  );
}

function printableAsciiText(value: unknown, field: keyof DeploymentBrandingDocument): string {
  const text = requiredText(value, field);
  if (!/^[\x20-\x7E]+$/.test(text)) {
    throw new Error(
      `Deployment branding field "${field}" must use printable ASCII for PDF fallback compatibility.`,
    );
  }
  return text;
}

export function isCommercialEdition(edition: string | undefined): boolean {
  return ['standard', 'professional', 'enterprise'].includes(edition?.trim().toLowerCase() ?? '');
}

/**
 * A deployment that ships any part of the login story owns the whole
 * positioning narrative of the brand panel; the platform-level trust pillars
 * (model/command/delivery) would read as off-brand there and are hidden.
 */
export function hasDeploymentLoginStory(
  branding: Pick<
    BrandingConfig,
    | 'loginBadge'
    | 'loginHeadline'
    | 'loginLead'
    | 'loginHeroUrl'
    | 'loginFeatures'
    | 'loginWechatOnly'
  >,
): boolean {
  return Boolean(
    branding.loginBadge ||
    branding.loginHeadline ||
    branding.loginLead ||
    branding.loginHeroUrl ||
    branding.loginFeatures?.length ||
    branding.loginWechatOnly,
  );
}

export function resolveBrandDisplayName(
  branding: BrandingConfig,
  compliance: { enabled: boolean; siteDisplayName: string },
): string {
  if (branding.mode === 'commercial') return branding.productName;
  return compliance.enabled ? compliance.siteDisplayName : branding.productName;
}

export function resolveCommercialBranding(
  value: unknown,
  expectedOrderReference: string,
): BrandingConfig {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error('Deployment branding configuration must be a JSON object.');
  }
  const document = value as Record<string, unknown>;
  const unknownKeys = Object.keys(document).filter(
    (key) => !DEPLOYMENT_KEYS.has(key as keyof DeploymentBrandingDocument),
  );
  if (unknownKeys.length > 0) {
    throw new Error(`Deployment branding contains unsupported fields: ${unknownKeys.join(', ')}.`);
  }
  if (document.schemaVersion !== 1) {
    throw new Error('Deployment branding schemaVersion must be 1.');
  }

  const orderReference = requiredText(document.orderReference, 'orderReference');
  if (!expectedOrderReference.trim() || orderReference !== expectedOrderReference.trim()) {
    throw new Error('Deployment branding orderReference does not match the delivery order.');
  }

  return {
    mode: 'commercial',
    productName: requiredText(document.productName, 'productName'),
    platformName: requiredText(document.platformName, 'platformName'),
    logoUrl: safeUrl(document.logoUrl, 'logoUrl'),
    faviconUrl: safeUrl(document.faviconUrl, 'faviconUrl'),
    favicon32Url: safeUrl(document.favicon32Url, 'favicon32Url'),
    appleTouchIconUrl: safeUrl(document.appleTouchIconUrl, 'appleTouchIconUrl'),
    manifestUrl: safeUrl(document.manifestUrl, 'manifestUrl'),
    websiteUrl: safeUrl(document.websiteUrl, 'websiteUrl'),
    docsUrl: safeUrl(document.docsUrl, 'docsUrl'),
    supportUrl: safeUrl(document.supportUrl, 'supportUrl'),
    sourceUrl: COMMUNITY_BRANDING.sourceUrl,
    commercialContactUrl: COMMUNITY_BRANDING.commercialContactUrl,
    licenseName: COMMUNITY_BRANDING.licenseName,
    licenseUrl: COMMUNITY_BRANDING.licenseUrl,
    copyrightHolder: requiredText(document.copyrightHolder, 'copyrightHolder'),
    aurabootCopyrightHolder: COMMUNITY_BRANDING.aurabootCopyrightHolder,
    poweredByText: requiredText(document.poweredByText, 'poweredByText'),
    generatedByText: printableAsciiText(document.generatedByText, 'generatedByText'),
    loginBadge: optionalText(document.loginBadge, 'loginBadge'),
    loginHeadline: optionalText(document.loginHeadline, 'loginHeadline'),
    loginHeadlineEm: optionalText(document.loginHeadlineEm, 'loginHeadlineEm'),
    loginLead: optionalText(document.loginLead, 'loginLead'),
    loginHeroUrl: optionalText(document.loginHeroUrl, 'loginHeroUrl'),
    loginFeatures: optionalTextList(document.loginFeatures, 'loginFeatures'),
    loginWechatOnly:
      document.loginWechatOnly === undefined ? undefined : Boolean(document.loginWechatOnly),
    tenantOnboarding: resolveTenantOnboarding(document.tenantOnboarding),
  };
}

function onboardingText(
  value: unknown,
  field: keyof TenantOnboardingDocument,
  limit: number,
): string {
  if (typeof value !== 'string' || !value.trim()) {
    throw new Error(`Deployment branding tenantOnboarding.${field} must be a non-empty string.`);
  }
  const normalized = value.trim();
  if (normalized.length > limit) {
    throw new Error(
      `Deployment branding tenantOnboarding.${field} must be at most ${limit} characters.`,
    );
  }
  return normalized;
}

function resolveTenantOnboarding(value: unknown): TenantOnboardingBranding | undefined {
  if (value === undefined || value === null) return undefined;
  if (typeof value !== 'object' || Array.isArray(value)) {
    throw new Error('Deployment branding tenantOnboarding must be an object.');
  }

  const document = value as Record<string, unknown>;
  const unknownKeys = Object.keys(document).filter(
    (key) => !TENANT_ONBOARDING_KEYS.has(key as keyof TenantOnboardingDocument),
  );
  if (unknownKeys.length > 0) {
    throw new Error(
      `Deployment branding tenantOnboarding contains unsupported fields: ${unknownKeys.join(', ')}.`,
    );
  }

  const joinChannel = document.joinChannel;
  if (joinChannel !== 'invite_code' && joinChannel !== 'wechat_mini') {
    throw new Error(
      'Deployment branding tenantOnboarding.joinChannel must be invite_code or wechat_mini.',
    );
  }

  let joinSteps: string[] | undefined;
  if (document.joinSteps !== undefined) {
    if (
      !Array.isArray(document.joinSteps) ||
      document.joinSteps.length < 2 ||
      document.joinSteps.length > 4
    ) {
      throw new Error(
        'Deployment branding tenantOnboarding.joinSteps must be an array of 2-4 strings.',
      );
    }
    joinSteps = document.joinSteps.map((step) => onboardingText(step, 'joinSteps', 120));
  }
  if (joinChannel === 'wechat_mini' && !joinSteps) {
    throw new Error(
      'Deployment branding tenantOnboarding.joinSteps is required for the wechat_mini channel.',
    );
  }

  let miniProgramQrUrl: string | undefined;
  if (document.miniProgramQrUrl !== undefined) {
    miniProgramQrUrl = safeUrl(document.miniProgramQrUrl, 'tenantOnboarding');
  }

  let postCreateRedirect: string | undefined;
  if (document.postCreateRedirect !== undefined) {
    const candidate = onboardingText(document.postCreateRedirect, 'postCreateRedirect', 160);
    if (!/^\/(?!\/)[A-Za-z0-9._~!$&'()*+,;=:@%/?-]*$/.test(candidate)) {
      throw new Error('Deployment branding tenantOnboarding.postCreateRedirect must be a same-origin path.');
    }
    postCreateRedirect = candidate;
  }

  let industryCode: string | undefined;
  if (document.industryCode !== undefined) {
    const candidate = onboardingText(document.industryCode, 'industryCode', 40);
    if (!/^[a-z][a-z0-9_-]*$/.test(candidate)) {
      throw new Error('Deployment branding tenantOnboarding.industryCode must be a lowercase code.');
    }
    industryCode = candidate;
  }

  return {
    entityLabel: onboardingText(document.entityLabel, 'entityLabel', 24),
    industryCode,
    postCreateRedirect,
    selectionTitle: onboardingText(document.selectionTitle, 'selectionTitle', 80),
    selectionLead: onboardingText(document.selectionLead, 'selectionLead', 160),
    createTitle: onboardingText(document.createTitle, 'createTitle', 60),
    createDescription: onboardingText(document.createDescription, 'createDescription', 180),
    createCta: onboardingText(document.createCta, 'createCta', 40),
    joinTitle: onboardingText(document.joinTitle, 'joinTitle', 60),
    joinDescription: onboardingText(document.joinDescription, 'joinDescription', 180),
    joinCta: onboardingText(document.joinCta, 'joinCta', 40),
    joinChannel,
    miniProgramName:
      document.miniProgramName === undefined
        ? undefined
        : onboardingText(document.miniProgramName, 'miniProgramName', 40),
    miniProgramQrUrl,
    joinSteps,
  };
}

function optionalText(value: unknown, field: keyof DeploymentBrandingDocument): string | undefined {
  if (value === undefined || value === null || value === '') return undefined;
  return requiredText(value, field);
}

function optionalTextList(
  value: unknown,
  field: keyof DeploymentBrandingDocument,
): string[] | undefined {
  if (value === undefined || value === null) return undefined;
  if (!Array.isArray(value) || value.length === 0 || value.length > 4) {
    throw new Error(`Deployment branding field "${field}" must be an array of 1-4 strings.`);
  }
  return value.map((item) => requiredText(item, field));
}

export function resolveCommunityBranding(): BrandingConfig {
  return { ...COMMUNITY_BRANDING };
}

export function resolveBuildIdentity(env: Record<string, string | undefined>): BuildIdentity {
  return {
    version: env.AURABOOT_VERSION?.trim() || env.APP_VERSION?.trim() || 'development',
    revision: env.AURABOOT_GIT_SHA?.trim() || env.GIT_SHA?.trim() || 'local',
  };
}
