export interface BrandingConfig {
  productName: string;
  platformName: string;
  logoUrl: string;
  websiteUrl: string;
  docsUrl: string;
  sourceUrl: string;
  commercialContactUrl: string;
  licenseName: string;
  licenseUrl: string;
  copyrightHolder: string;
  poweredByText: string;
  generatedByText: string;
}

export interface BuildIdentity {
  version: string;
  revision: string;
}

/**
 * Community builds always resolve to the AuraBoot identity. Commercial
 * branding must be introduced through a licensed deployment-level resolver,
 * never through client-controlled preferences.
 */
export const COMMUNITY_BRANDING: Readonly<BrandingConfig> = Object.freeze({
  productName: 'AuraBoot',
  platformName: 'AuraBoot Platform',
  logoUrl: '/android-chrome-192x192.png',
  websiteUrl: 'https://auraboot.com',
  docsUrl: 'https://auraboot.com/docs',
  sourceUrl: 'https://github.com/AuraBootTeam/auraboot',
  commercialContactUrl: 'https://auraboot.com/contact',
  licenseName: 'AuraBoot License Agreement 1.3',
  licenseUrl: 'https://github.com/AuraBootTeam/auraboot/blob/main/LICENSE.txt',
  copyrightHolder: 'The AuraBoot Project and its contributors',
  poweredByText: 'Powered by AuraBoot',
  generatedByText: 'Generated by AuraBoot Platform',
});

export function resolveCommunityBranding(): BrandingConfig {
  return { ...COMMUNITY_BRANDING };
}

export function resolveBuildIdentity(env: Record<string, string | undefined>): BuildIdentity {
  return {
    version: env.AURABOOT_VERSION?.trim() || env.APP_VERSION?.trim() || 'development',
    revision: env.AURABOOT_GIT_SHA?.trim() || env.GIT_SHA?.trim() || 'local',
  };
}
