export interface BrandingConfig {
  mode: 'community' | 'commercial';
  productName: string;
  platformName: string;
  logoUrl: string;
  faviconUrl: string;
  favicon32Url: string;
  appleTouchIconUrl: string;
  manifestUrl: string;
  websiteUrl: string;
  docsUrl: string;
  supportUrl: string;
  sourceUrl: string;
  commercialContactUrl: string;
  licenseName: string;
  licenseUrl: string;
  copyrightHolder: string;
  aurabootCopyrightHolder: string;
  poweredByText: string;
  generatedByText: string;
}

export interface DeploymentBrandingDocument {
  schemaVersion: 1;
  orderReference: string;
  productName: string;
  platformName: string;
  logoUrl: string;
  faviconUrl: string;
  favicon32Url: string;
  appleTouchIconUrl: string;
  manifestUrl: string;
  websiteUrl: string;
  docsUrl: string;
  supportUrl: string;
  copyrightHolder: string;
  poweredByText: string;
  generatedByText: string;
}

export interface BuildIdentity {
  version: string;
  revision: string;
}

/**
 * Community builds always resolve to the AuraBoot identity. Commercial
 * branding must be introduced through a licensed deployment-level resolver,
 * never through client-controlled preferences.
 */
export const COMMUNITY_BRANDING: Readonly<BrandingConfig> = Object.freeze({
  mode: 'community',
  productName: 'AuraBoot',
  platformName: 'AuraBoot Platform',
  logoUrl: '/android-chrome-192x192.png',
  faviconUrl: '/favicon.ico',
  favicon32Url: '/favicon-32x32.png',
  appleTouchIconUrl: '/apple-touch-icon.png',
  manifestUrl: '/manifest.json',
  websiteUrl: 'https://auraboot.com',
  docsUrl: 'https://auraboot.com/docs',
  supportUrl: 'https://auraboot.com/contact',
  sourceUrl: 'https://github.com/AuraBootTeam/auraboot',
  commercialContactUrl: 'https://auraboot.com/contact',
  licenseName: 'AuraBoot License Agreement 1.3',
  licenseUrl: 'https://github.com/AuraBootTeam/auraboot/blob/main/LICENSE.txt',
  copyrightHolder: 'The AuraBoot Project and its contributors',
  aurabootCopyrightHolder: 'The AuraBoot Project and its contributors',
  poweredByText: 'Powered by AuraBoot',
  generatedByText: 'Generated by AuraBoot Platform',
});

const DEPLOYMENT_KEYS = new Set<keyof DeploymentBrandingDocument>([
  'schemaVersion',
  'orderReference',
  'productName',
  'platformName',
  'logoUrl',
  'faviconUrl',
  'favicon32Url',
  'appleTouchIconUrl',
  'manifestUrl',
  'websiteUrl',
  'docsUrl',
  'supportUrl',
  'copyrightHolder',
  'poweredByText',
  'generatedByText',
]);

const FIELD_LIMITS: Partial<Record<keyof DeploymentBrandingDocument, number>> = {
  orderReference: 120,
  productName: 80,
  platformName: 120,
  copyrightHolder: 160,
  poweredByText: 160,
  generatedByText: 160,
  logoUrl: 2048,
  faviconUrl: 2048,
  favicon32Url: 2048,
  appleTouchIconUrl: 2048,
  manifestUrl: 2048,
  websiteUrl: 2048,
  docsUrl: 2048,
  supportUrl: 2048,
};

function requiredText(value: unknown, field: keyof DeploymentBrandingDocument): string {
  if (typeof value !== 'string' || !value.trim()) {
    throw new Error(`Deployment branding field "${field}" must be a non-empty string.`);
  }
  const normalized = value.trim();
  const limit = FIELD_LIMITS[field];
  if (limit && normalized.length > limit) {
    throw new Error(`Deployment branding field "${field}" must be at most ${limit} characters.`);
  }
  return normalized;
}

function safeUrl(value: unknown, field: keyof DeploymentBrandingDocument): string {
  const url = requiredText(value, field);
  if (url.startsWith('/') && !url.startsWith('//')) return url;
  try {
    const parsed = new URL(url);
    if (parsed.protocol === 'https:' && parsed.hostname) return url;
  } catch {
    // Fall through to the stable configuration error below.
  }
  throw new Error(
    `Deployment branding field "${field}" must be a same-origin path or an HTTPS URL.`,
  );
}

function printableAsciiText(value: unknown, field: keyof DeploymentBrandingDocument): string {
  const text = requiredText(value, field);
  if (!/^[\x20-\x7E]+$/.test(text)) {
    throw new Error(
      `Deployment branding field "${field}" must use printable ASCII for PDF fallback compatibility.`,
    );
  }
  return text;
}

export function isCommercialEdition(edition: string | undefined): boolean {
  return ['standard', 'professional', 'enterprise'].includes(edition?.trim().toLowerCase() ?? '');
}

export function resolveBrandDisplayName(
  branding: BrandingConfig,
  compliance: { enabled: boolean; siteDisplayName: string },
): string {
  if (branding.mode === 'commercial') return branding.productName;
  return compliance.enabled ? compliance.siteDisplayName : branding.productName;
}

export function resolveCommercialBranding(
  value: unknown,
  expectedOrderReference: string,
): BrandingConfig {
  if (!value || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error('Deployment branding configuration must be a JSON object.');
  }
  const document = value as Record<string, unknown>;
  const unknownKeys = Object.keys(document).filter(
    (key) => !DEPLOYMENT_KEYS.has(key as keyof DeploymentBrandingDocument),
  );
  if (unknownKeys.length > 0) {
    throw new Error(`Deployment branding contains unsupported fields: ${unknownKeys.join(', ')}.`);
  }
  if (document.schemaVersion !== 1) {
    throw new Error('Deployment branding schemaVersion must be 1.');
  }

  const orderReference = requiredText(document.orderReference, 'orderReference');
  if (!expectedOrderReference.trim() || orderReference !== expectedOrderReference.trim()) {
    throw new Error('Deployment branding orderReference does not match the delivery order.');
  }

  return {
    mode: 'commercial',
    productName: requiredText(document.productName, 'productName'),
    platformName: requiredText(document.platformName, 'platformName'),
    logoUrl: safeUrl(document.logoUrl, 'logoUrl'),
    faviconUrl: safeUrl(document.faviconUrl, 'faviconUrl'),
    favicon32Url: safeUrl(document.favicon32Url, 'favicon32Url'),
    appleTouchIconUrl: safeUrl(document.appleTouchIconUrl, 'appleTouchIconUrl'),
    manifestUrl: safeUrl(document.manifestUrl, 'manifestUrl'),
    websiteUrl: safeUrl(document.websiteUrl, 'websiteUrl'),
    docsUrl: safeUrl(document.docsUrl, 'docsUrl'),
    supportUrl: safeUrl(document.supportUrl, 'supportUrl'),
    sourceUrl: COMMUNITY_BRANDING.sourceUrl,
    commercialContactUrl: COMMUNITY_BRANDING.commercialContactUrl,
    licenseName: COMMUNITY_BRANDING.licenseName,
    licenseUrl: COMMUNITY_BRANDING.licenseUrl,
    copyrightHolder: requiredText(document.copyrightHolder, 'copyrightHolder'),
    aurabootCopyrightHolder: COMMUNITY_BRANDING.aurabootCopyrightHolder,
    poweredByText: requiredText(document.poweredByText, 'poweredByText'),
    generatedByText: printableAsciiText(document.generatedByText, 'generatedByText'),
  };
}

export function resolveCommunityBranding(): BrandingConfig {
  return { ...COMMUNITY_BRANDING };
}

export function resolveBuildIdentity(env: Record<string, string | undefined>): BuildIdentity {
  return {
    version: env.AURABOOT_VERSION?.trim() || env.APP_VERSION?.trim() || 'development',
    revision: env.AURABOOT_GIT_SHA?.trim() || env.GIT_SHA?.trim() || 'local',
  };
}
