/**
 * BPM Process Definition API Tests
 *
 * Migrated from: tests/e2e/bpm/bpm-process-definition.spec.ts
 * Tests: D1-E02, D1-E04 ~ D1-E08
 *
 * E2E tests (D1-E01, D1-E03) remain in the e2e file.
 *
 * @since 4.0.0
 */

import { test, expect } from '@playwright/test';

function unwrap<T = any>(body: any): T {
  return (body?.data ?? body) as T;
}

function generateMinimalBpmn(processKey: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             targetNamespace="http://auraboot.com/bpm"
             id="definitions_${processKey}">
  <process id="${processKey}" name="E2E Test Process" isExecutable="true">
    <startEvent id="start"/>
    <userTask id="userTask1" name="Approve Task"/>
    <endEvent id="end"/>
    <sequenceFlow id="flow1" sourceRef="start" targetRef="userTask1"/>
    <sequenceFlow id="flow2" sourceRef="userTask1" targetRef="end"/>
  </process>
</definitions>`;
}

function generateProcessKey(): string {
  const ts = Date.now();
  const rand = Math.random().toString(36).slice(2, 7);
  return `e2e_proc_${ts}_${rand}`;
}

test.describe('BPM Process Definition API', () => {
  test.describe.configure({ mode: 'serial' });

  let processPid: string | null = null;
  let processKey: string;

  test.beforeAll(() => {
    processKey = generateProcessKey();
  });

  test('D1-E02: Create process definition via API', async ({ request }) => {
    const bpmnContent = generateMinimalBpmn(processKey);

    const response = await request.post(
      `/api/bpm/process-definitions`,
      {
        data: {
          processKey,
          processName: `E2E API Test Process ${processKey}`,
          description: 'Auto-generated by API test',
          category: 'e2e-test',
          bpmnContent,
        },
      }
    );

    if (response.status() === 500) {
      test.skip(true, 'BPM process-definitions API returned 500 (SmartEngine may not be initialized)');
      return;
    }

    expect(response.ok()).toBe(true);

    const data = unwrap(await response.json());
    expect(data).not.toBeNull();

    processPid = data.pid;
    expect(processPid).toBeTruthy();
    expect(data.processKey).toBe(processKey);
    expect(data.status).toBe('draft');
    expect(data.version).toBe(1);

    const verifyResponse = await request.get(
      `/api/bpm/process-definitions/${processPid}`
    );
    expect(verifyResponse.ok()).toBe(true);

    const verifyData = unwrap(await verifyResponse.json());
    expect(verifyData.processKey).toBe(processKey);
  });

  test('D1-E04: Save process definition', async ({ request }) => {
    test.skip(!processPid, 'Skipped: no process created in D1-E02');

    const updatedBpmn = generateMinimalBpmn(processKey);

    const response = await request.put(
      `/api/bpm/process-definitions/${processPid}`,
      {
        data: {
          processName: `E2E API Test Process Updated ${processKey}`,
          description: 'Updated by API test - save test',
          bpmnContent: updatedBpmn,
        },
      }
    );

    expect(response.ok()).toBe(true);

    const data = unwrap(await response.json());
    expect(data.processName).toContain('Updated');
    expect(data.status).toBe('draft');
  });

  test('D1-E05: Deploy process definition', async ({ request }) => {
    test.skip(!processPid, 'Skipped: no process created in D1-E02');

    const response = await request.post(
      `/api/bpm/process-definitions/${processPid}/deploy`
    );

    expect(response.ok()).toBe(true);

    const data = unwrap(await response.json());
    expect(data.status).toBe('deployed');
    expect(data.deployedAt).toBeTruthy();

    const verifyResponse = await request.get(
      `/api/bpm/process-definitions/${processPid}`
    );
    expect(verifyResponse.ok()).toBe(true);
    const verifyData = unwrap(await verifyResponse.json());
    expect(verifyData).toBeTruthy();
  });

  test('D1-E06: Version history', async ({ request }) => {
    test.skip(!processPid, 'Skipped: no process created in D1-E02');

    const newVersionResponse = await request.post(
      `/api/bpm/process-definitions/key/${processKey}/versions`,
      {
        data: {
          bpmnContent: generateMinimalBpmn(processKey),
        },
      }
    );

    if (newVersionResponse.ok()) {
      const newVersion = unwrap(await newVersionResponse.json());
      expect(newVersion.version).toBeGreaterThan(1);
    }

    const historyResponse = await request.get(
      `/api/bpm/process-definitions/key/${processKey}/versions`
    );
    expect(historyResponse.ok()).toBe(true);

    const versions = unwrap<any[]>(await historyResponse.json());
    expect(Array.isArray(versions)).toBe(true);
    expect(versions.length).toBeGreaterThanOrEqual(1);

    for (const v of versions) {
      expect(v.processKey).toBe(processKey);
    }
  });

  test('D1-E07: Suspend process definition', async ({ request }) => {
    test.skip(!processPid, 'Skipped: no process created in D1-E02');

    const checkResponse = await request.get(
      `/api/bpm/process-definitions/${processPid}`
    );
    const currentState = unwrap(await checkResponse.json());

    if (currentState.status !== 'deployed') {
      const redeployResponse = await request.post(
        `/api/bpm/process-definitions/${processPid}/deploy`
      );
      if (!redeployResponse.ok()) {
        test.skip(true, 'Cannot deploy process for suspend test');
      }
    }

    const response = await request.post(
      `/api/bpm/process-definitions/${processPid}/suspend`
    );

    expect(response.ok()).toBe(true);

    const data = unwrap(await response.json());
    expect(data.status).toBe('suspended');

    const verifyResponse = await request.get(
      `/api/bpm/process-definitions/${processPid}`
    );
    const verifyData = unwrap(await verifyResponse.json());
    expect(verifyData.status).toBe('suspended');
  });

  test('D1-E08: Resume process definition', async ({ request }) => {
    test.skip(!processPid, 'Skipped: no process created in D1-E02');

    const checkResponse = await request.get(
      `/api/bpm/process-definitions/${processPid}`
    );
    const currentState = unwrap(await checkResponse.json());

    if (currentState.status !== 'suspended') {
      test.skip(true, 'Process is not in suspended state');
    }

    const response = await request.post(
      `/api/bpm/process-definitions/${processPid}/resume`
    );

    expect(response.ok()).toBe(true);

    const data = unwrap(await response.json());
    expect(data.status).toBe('deployed');

    const verifyResponse = await request.get(
      `/api/bpm/process-definitions/${processPid}`
    );
    const verifyData = unwrap(await verifyResponse.json());
    expect(verifyData.status).toBe('deployed');
  });

  test.afterAll(async ({ request }) => {
    if (!processPid) return;

    try {
      await request.post(`/api/bpm/process-definitions/${processPid}/undeploy`);
    } catch { /* Ignore */ }

    try {
      await request.delete(`/api/bpm/process-definitions/${processPid}`);
    } catch (error) {
      console.warn('Failed to cleanup test process definition:', error);
    }
  });
});
