package com.auraboot.framework.plugin.extension;

import java.io.InputStream;

/**
 * Host-provided file byte bridge for plugin command handlers.
 *
 * <p>Plugins receive this accessor through
 * {@link CommandHandlerExtension.CommandContext#fileAccessor()}. It keeps
 * platform storage details inside the host while allowing plugins to read
 * uploaded files and persist generated files by platform file id.</p>
 */
public interface FileAccessor {

    /** Well-known key for FileAccessor in the command settings map. */
    String SETTINGS_KEY = "__fileAccessor";

    /**
     * Open a platform file by its public file id.
     *
     * @param fileId platform file pid/id returned by the upload API
     * @return readable file stream; caller must close it
     */
    InputStream open(String fileId);

    /**
     * Persist generated bytes as a platform file.
     *
     * @param originalName suggested download filename
     * @param contentType  MIME type
     * @param bytes        file content
     * @return saved platform file metadata
     */
    SavedFile save(String originalName, String contentType, byte[] bytes);

    /** Saved platform file metadata returned to plugin handlers. */
    record SavedFile(String fileId, String originalName, long size, String url) {
    }
}
