/**
 * Quarry Management E2E Test - Shared Setup & Helpers
 *
 * Provides quarry-specific utilities for quarry management test suites:
 * - Quarry menu navigation helpers
 * - Quarry-specific test data constants and generators
 *
 * Generic utilities (navigation, forms, dialogs, etc.) are in helpers/index.ts.
 * They are re-exported here for backward compatibility.
 *
 * NOTE: Authentication is handled via storageState (global-setup.ts).
 * Tests are automatically logged in.
 *
 * @since 4.0.0
 */

import { type Page } from '@playwright/test';

// Re-export all generic helpers for backward compatibility
export {
  uniqueId,
  todayStr,
  dateOffsetStr,
  navigateToDynamicPage,
  waitForDynamicPageLoad,
  waitForToast,
  acceptConfirmDialog,
  dismissConfirmDialog,
  fillField,
  selectOption,
  clickButton,
  clickSaveButton,
  confirmDialog,
  cancelDialog,
  getTableRowCount,
  getCellText,
  clickRowAction,
  findRowByText,
  executeCommandViaApi,
} from './helpers/index';

import { uniqueId, todayStr, executeCommandViaApi } from './helpers/index';
import { ErrorCodes } from '~/services/http-client/types';

// ---------------------------------------------------------------------------
// Quarry-specific Constants
// ---------------------------------------------------------------------------

/** Table names (model codes) used in /p/:tableName route.
 *  The route auto-appends '_list' to compute the pageKey for schema lookup. */
export const PAGE_KEYS = {
  DAILY_REPORT: 'qo_daily_report',
  DAILY_SUMMARY: 'qo_daily_summary',
  ANNUAL_PLAN: 'ap_annual_plan',
  ISSUE: 'dp_issue',
  RECTIFICATION: 'dp_rectification',
  INSPECTION_TASK: 'dp_inspection_task',
} as const;

/** Menu labels in the sidebar (Chinese) */
export const MENU_LABELS = {
  // Top-level
  QUARRY_OPERATION: '经营数据',
  ANNUAL_PLAN: '年度计划',
  DUAL_PREVENTION: '双重预防',

  // Sub-menus
  DATA_REPORT: '数据上报',
  DAILY_SUMMARY: '日生产/销售统计',
  PLAN_CREATION: '计划编制',
  ISSUE_MANAGEMENT: '隐患管理',
  RECTIFICATION: '整改管理',
  INSPECTION: '巡检管理',
} as const;

/** Status constants shared across modules */
export const STATUS = {
  draft: 'draft',
  submitted: 'submitted',
  approved: 'approved',
  rejected: 'rejected',
  pending: 'pending',
  RECTIFYING: 'rectifying',
  INITIATED: 'initiated',
  in_progress: 'in_progress',
  completed: 'completed',
  ACCEPTED: 'accepted',
} as const;

// ---------------------------------------------------------------------------
// Quarry-specific Test Data Generators
// ---------------------------------------------------------------------------

/**
 * Generate test data for a daily report.
 */
export function createDailyReportData(overrides?: Record<string, unknown>) {
  return {
    reportDate: todayStr(),
    projectName: `E2E Test Project ${uniqueId()}`,
    explosiveUsage: 120.5,
    remark: `Auto-generated by E2E test at ${new Date().toISOString()}`,
    ...overrides,
  };
}

/**
 * Generate test data for an annual plan.
 */
export function createAnnualPlanData(overrides?: Record<string, unknown>) {
  // Use random year (1000-9999) to avoid UNIQUE_COMPOSITE conflicts across test runs
  const randomYear = Math.floor(Math.random() * 9000) + 1000;
  return {
    planName: `${randomYear} Annual Plan ${uniqueId()}`,
    planYear: randomYear,
    remark: `Auto-generated by E2E test`,
    ...overrides,
  };
}

/**
 * Generate test data for an issue (dual-prevention).
 */
export function createIssueData(overrides?: Record<string, unknown>) {
  return {
    title: `E2E Issue ${uniqueId()}`,
    description: 'Auto-generated issue for E2E testing',
    location: 'Test Area A',
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Shared Test Project — created once per test run
// ---------------------------------------------------------------------------

let _testProjectId: string | null = null;

/**
 * Get or create a shared test project for quarry E2E tests.
 * The project is created once per worker and reused across tests.
 */
export async function getTestProjectId(page: Page): Promise<string> {
  if (_testProjectId) return _testProjectId;

  const result = await executeCommandViaApi(page, 'pm:create_project', {
    pm_project_name: `E2E Quarry Project ${uniqueId()}`,
    pm_project_code: `QE2E-${uniqueId()}`,
  });
  if (result.code !== ErrorCodes.SUCCESS) {
    throw new Error(`Failed to create test project: ${JSON.stringify(result)}`);
  }
  _testProjectId = result.recordId;
  return _testProjectId;
}

// ---------------------------------------------------------------------------
// Quarry-specific Navigation Helpers
// ---------------------------------------------------------------------------

/**
 * Navigate to a menu item by clicking through the sidebar menu hierarchy.
 *
 * @param page - Playwright page
 * @param menuPath - Array of menu labels to click, e.g. ['矿山运营', '数据上报']
 */
export async function navigateToMenu(page: Page, menuPath: string[]): Promise<void> {
  // Ensure we are on a page where the sidebar is visible
  await page.goto(`/`);
  await page.waitForLoadState('domcontentloaded');

  for (let i = 0; i < menuPath.length; i++) {
    const label = menuPath[i];
    const isLast = i === menuPath.length - 1;

    // For parent menus (directories), click to expand
    // For leaf menus, click to navigate
    const menuItem = page
      .locator(`nav >> text="${label}"`)
      .first()
      .or(page.getByText(label, { exact: false }).first());

    await menuItem.waitFor({ state: 'visible', timeout: 10000 });
    await menuItem.click();

    if (isLast) {
      // Wait for navigation to complete
      await page.waitForLoadState('domcontentloaded');
    } else {
      // Wait for submenu expansion animation
      await page.waitForLoadState('domcontentloaded');
    }
  }
}
