import { render, screen } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import AboutPage, { meta } from '../about';

const rootLoaderData = vi.hoisted(() => ({
  value: {
    edition: 'community',
    buildIdentity: { version: '1.2.3', revision: 'abc123' },
    branding: {
      mode: 'community',
      productName: 'AuraBoot',
      platformName: 'AuraBoot Platform',
      logoUrl: '/android-chrome-192x192.png',
      websiteUrl: 'https://auraboot.com',
      docsUrl: 'https://auraboot.com/docs',
      supportUrl: 'https://auraboot.com/contact',
      sourceUrl: 'https://github.com/AuraBootTeam/auraboot',
      commercialContactUrl: 'https://auraboot.com/contact',
      licenseName: 'AuraBoot License Agreement 1.3',
      licenseUrl: 'https://github.com/AuraBootTeam/auraboot/blob/main/LICENSE.txt',
      copyrightHolder: 'The AuraBoot Project and its contributors',
      aurabootCopyrightHolder: 'The AuraBoot Project and its contributors',
      poweredByText: 'Powered by AuraBoot',
      generatedByText: 'Generated by AuraBoot Platform',
    },
  } as any,
}));

vi.mock('~/root-data', () => ({
  useRootLoaderData: () => rootLoaderData.value,
}));

vi.mock('~/contexts/I18nContext', () => ({
  useI18n: () => ({
    locale: 'en-US',
    t: (_key: string, _params?: Record<string, unknown>, fallback?: string) => fallback,
  }),
}));

describe('AboutPage', () => {
  it('shows product, build, license, and official resource identity', () => {
    render(<AboutPage />);

    expect(screen.getByRole('heading', { name: 'About AuraBoot' })).toBeVisible();
    expect(screen.getByTestId('about-edition')).toHaveTextContent('Community');
    expect(screen.getByText('1.2.3')).toBeVisible();
    expect(screen.getByText('abc123')).toBeVisible();
    expect(screen.getByRole('link', { name: /AuraBoot License Agreement 1.3/ })).toHaveAttribute(
      'href',
      'https://github.com/AuraBootTeam/auraboot/blob/main/LICENSE.txt',
    );
    expect(screen.getByRole('link', { name: 'Commercial licensing and support' })).toHaveAttribute(
      'href',
      'https://auraboot.com/contact',
    );
  });

  it('uses the root deployment brand in About document metadata', () => {
    expect(
      meta({ matches: [{ id: 'root', data: rootLoaderData.value }] }),
    ).toEqual([{ title: 'About AuraBoot' }]);
    expect(
      meta({
        matches: [
          {
            id: 'root',
            data: {
              ...rootLoaderData.value,
              branding: { ...rootLoaderData.value.branding, productName: 'Northstar' },
            },
          },
        ],
      }),
    ).toEqual([{ title: 'About Northstar' }]);
  });

  it('shows customer identity without allowing legal notices to disappear', () => {
    rootLoaderData.value = {
      edition: 'standard',
      buildIdentity: { version: '2.0.0', revision: 'release-1' },
      branding: {
        ...rootLoaderData.value.branding,
        mode: 'commercial',
        productName: 'Northstar',
        platformName: 'Northstar Operations Platform',
        logoUrl: '/customer-brand/logo.png',
        websiteUrl: 'https://northstar.example.com',
        docsUrl: 'https://northstar.example.com/docs',
        supportUrl: 'https://northstar.example.com/support',
        copyrightHolder: 'Northstar Holdings Ltd.',
      },
    };

    render(<AboutPage />);

    expect(screen.getByRole('heading', { name: 'About Northstar' })).toBeVisible();
    expect(screen.getByTestId('about-edition')).toHaveTextContent('Standard');
    expect(screen.getByRole('link', { name: 'Customer support' })).toHaveAttribute(
      'href',
      'https://northstar.example.com/support',
    );
    expect(screen.getByTestId('about-owner-copyright')).toHaveTextContent(
      'Northstar Holdings Ltd.',
    );
    expect(screen.getByTestId('about-auraboot-notice')).toHaveTextContent(
      'AuraBoot License Agreement 1.3',
    );
  });
});
