import { render, screen } from '@testing-library/react';
import { describe, expect, it, vi } from 'vitest';
import AboutPage from '../about';

vi.mock('~/root', () => ({
  useRootLoaderData: () => ({
    edition: 'community',
    buildIdentity: { version: '1.2.3', revision: 'abc123' },
    branding: {
      productName: 'AuraBoot',
      platformName: 'AuraBoot Platform',
      logoUrl: '/android-chrome-192x192.png',
      websiteUrl: 'https://auraboot.com',
      docsUrl: 'https://auraboot.com/docs',
      sourceUrl: 'https://github.com/AuraBootTeam/auraboot',
      commercialContactUrl: 'https://auraboot.com/contact',
      licenseName: 'AuraBoot License Agreement 1.3',
      licenseUrl: 'https://github.com/AuraBootTeam/auraboot/blob/main/LICENSE.txt',
      copyrightHolder: 'The AuraBoot Project and its contributors',
      poweredByText: 'Powered by AuraBoot',
      generatedByText: 'Generated by AuraBoot Platform',
    },
  }),
}));

vi.mock('~/contexts/I18nContext', () => ({
  useI18n: () => ({
    locale: 'en-US',
    t: (_key: string, _params?: Record<string, unknown>, fallback?: string) => fallback,
  }),
}));

describe('AboutPage', () => {
  it('shows product, build, license, and official resource identity', () => {
    render(<AboutPage />);

    expect(screen.getByRole('heading', { name: 'About AuraBoot' })).toBeVisible();
    expect(screen.getByTestId('about-edition')).toHaveTextContent('Community');
    expect(screen.getByText('1.2.3')).toBeVisible();
    expect(screen.getByText('abc123')).toBeVisible();
    expect(screen.getByRole('link', { name: /AuraBoot License Agreement 1.3/ })).toHaveAttribute(
      'href',
      'https://github.com/AuraBootTeam/auraboot/blob/main/LICENSE.txt',
    );
    expect(screen.getByRole('link', { name: 'Commercial licensing and support' })).toHaveAttribute(
      'href',
      'https://auraboot.com/contact',
    );
  });
});
