package com.auraboot.framework.bpm;

import com.auraboot.framework.bpm.event.BpmEvent;
import com.auraboot.framework.event.AuraEvent;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.context.ApplicationEvent;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for BpmEvent after migration to extend AuraEvent.
 * Verifies inheritance chain, field mapping, and backward compatibility.
 */
@DisplayName("BpmEvent Migration Tests")
class BpmEventMigrationTest {

    @Nested
    @DisplayName("Inheritance and field mapping")
    class InheritanceTests {

        @Test
        @DisplayName("BpmEvent extends AuraEvent extends ApplicationEvent")
        void bpmEventExtendsAuraEventExtendsApplicationEvent() {
            BpmEvent event = new BpmEvent(1L, "process_started", "bpm",
                    "test-process", "inst-001", null, Map.of("key", "value"));

            assertInstanceOf(AuraEvent.class, event);
            assertInstanceOf(ApplicationEvent.class, event);
        }

        @Test
        @DisplayName("eventId is auto-generated ULID")
        void eventIdAutoGenerated() {
            BpmEvent event = new BpmEvent(1L, "task_created", "bpm",
                    "proc-1", "inst-1", "node-1", Map.of());

            assertNotNull(event.getEventId());
            assertEquals(26, event.getEventId().length(), "ULID should be 26 characters");
        }

        @Test
        @DisplayName("occurredAt is auto-set")
        void occurredAtAutoSet() {
            BpmEvent event = new BpmEvent(1L, "task_created", "bpm",
                    "proc-1", "inst-1", null, Map.of());

            assertNotNull(event.getOccurredAt());
        }

        @Test
        @DisplayName("tenantId stored as Long from AuraEvent")
        void tenantIdIsLong() {
            BpmEvent event = new BpmEvent(42L, "process_started", "bpm",
                    "proc-1", "inst-1", null, Map.of());

            assertEquals(42L, event.getTenantId());
        }

        @Test
        @DisplayName("null tenantId preserved")
        void nullTenantIdPreserved() {
            BpmEvent event = new BpmEvent(null, "process_started", "bpm",
                    "proc-1", "inst-1", null, Map.of());

            assertNull(event.getTenantId());
        }

        @Test
        @DisplayName("BPM-specific fields accessible via getters")
        void bpmSpecificFields() {
            BpmEvent event = new BpmEvent(1L, "task_created", "automation",
                    "leave-approval", "inst-123", "node-456", Map.of("taskId", "t1"));

            assertEquals("automation", event.getSourceType());
            assertEquals("leave-approval", event.getProcessKey());
            assertEquals("inst-123", event.getInstanceId());
            assertEquals("node-456", event.getNodeId());
        }

        @Test
        @DisplayName("sourceType defaults to BPM when null")
        void sourceTypeDefaultsBpm() {
            BpmEvent event = new BpmEvent(1L, "task_created", null,
                    "proc-1", "inst-1", null, Map.of());

            assertEquals("bpm", event.getSourceType());
        }

        @Test
        @DisplayName("payload is accessible from AuraEvent getter")
        void payloadAccessible() {
            Map<String, Object> payload = Map.of("startUserId", "123", "reason", "test");
            BpmEvent event = new BpmEvent(1L, "process_started", "bpm",
                    "proc-1", "inst-1", null, payload);

            assertEquals("123", event.getPayload().get("startUserId"));
            assertEquals("test", event.getPayload().get("reason"));
        }

        @Test
        @DisplayName("payload is immutable (copied by AuraEvent)")
        void payloadImmutable() {
            BpmEvent event = new BpmEvent(1L, "process_started", "bpm",
                    "proc-1", "inst-1", null, Map.of("key", "val"));

            assertThrows(UnsupportedOperationException.class,
                    () -> event.getPayload().put("newKey", "newVal"));
        }
    }

    @Nested
    @DisplayName("Event type format conversion")
    class EventTypeTests {

        @Test
        @DisplayName("getEventType returns prefixed lowercase format")
        void getEventTypeReturnsPrefixedFormat() {
            BpmEvent event = new BpmEvent(1L, "process_started", "bpm",
                    "proc-1", "inst-1", null, Map.of());

            assertEquals("bpm:process_started", event.getEventType());
        }

        @Test
        @DisplayName("getBpmEventType returns original uppercase format")
        void getBpmEventTypeReturnsOriginalFormat() {
            BpmEvent event = new BpmEvent(1L, "process_started", "bpm",
                    "proc-1", "inst-1", null, Map.of());

            assertEquals("process_started", event.getBpmEventType());
        }

        @Test
        @DisplayName("getBpmEventType handles all standard BPM event types")
        void getBpmEventTypeAllTypes() {
            String[] types = {"process_started", "process_ended", "task_created",
                    "task_completed", "sla_warning", "sla_escalated", "activity_completed"};

            for (String type : types) {
                BpmEvent event = new BpmEvent(1L, type, "bpm", null, null, null, Map.of());
                assertEquals(type, event.getBpmEventType(),
                        "getBpmEventType() should return " + type);
                assertEquals("bpm:" + type.toLowerCase(), event.getEventType(),
                        "getEventType() should return bpm:" + type.toLowerCase());
            }
        }

        @Test
        @DisplayName("modelCode maps to null (BPM events have processKey instead)")
        void modelCodeIsNull() {
            BpmEvent event = new BpmEvent(1L, "process_started", "bpm",
                    "proc-1", "inst-1", null, Map.of());

            assertNull(event.getModelCode());
        }

        @Test
        @DisplayName("recordId maps to instanceId")
        void recordIdMapsToInstanceId() {
            BpmEvent event = new BpmEvent(1L, "process_started", "bpm",
                    "proc-1", "inst-abc", null, Map.of());

            assertEquals("inst-abc", event.getRecordId());
            assertEquals("inst-abc", event.getInstanceId());
        }
    }

    @Nested
    @DisplayName("Static factory method")
    class FactoryMethodTests {

        @Test
        @DisplayName("BpmEvent.of() creates event identical to constructor")
        void ofCreatesEquivalentEvent() {
            BpmEvent event = BpmEvent.of(1L, "task_created", "bpm",
                    "proc-1", "inst-1", "node-1", Map.of("k", "v"));

            assertNotNull(event.getEventId());
            assertEquals("bpm:task_created", event.getEventType());
            assertEquals("task_created", event.getBpmEventType());
            assertEquals(1L, event.getTenantId());
            assertEquals("bpm", event.getSourceType());
            assertEquals("proc-1", event.getProcessKey());
            assertEquals("inst-1", event.getInstanceId());
            assertEquals("node-1", event.getNodeId());
            assertEquals("v", event.getPayload().get("k"));
        }
    }

    @Nested
    @DisplayName("Two events have unique IDs")
    class UniqueIdTests {

        @Test
        @DisplayName("Two BpmEvent instances have different eventIds")
        void uniqueEventIds() {
            BpmEvent e1 = new BpmEvent(1L, "task_created", "bpm",
                    "proc-1", "inst-1", null, Map.of());
            BpmEvent e2 = new BpmEvent(1L, "task_created", "bpm",
                    "proc-1", "inst-1", null, Map.of());

            assertNotEquals(e1.getEventId(), e2.getEventId());
        }
    }
}
