import { route } from '@react-router/dev/routes';

// Plugin-contributed static routes. Each core-* plugin exports a routes()
// function returning React Router 7 RouteConfigEntry[]. The same paths are
// registered with the kernel at runtime via PluginContext (in each plugin's
// index.ts) for menu / breadcrumb / permission gating.
//
// As of M3.6+M3.8, the following domains have migrated:
//   - BPM, Designers, Automation, Organization, Meta, AuraBot,
//     AI Colleagues, Personal, Settings, Platform, Admin, Ops
//
// Routes that remain hardcoded below are runtime-engine routes
// (/p/:pageKey, /dynamic/:tableName, /*) — these are kernel infrastructure
// rather than feature pages and stay here intentionally.

import { bpmRoutes } from '../../app/plugins/core-bpm/routes';
import { designerRoutes } from '../../app/plugins/core-designer/routes';
import { automationRoutes } from '../../app/plugins/core-automation/routes';
import { organizationRoutes } from '../../app/plugins/core-organization/routes';
import { metaRoutes } from '../../app/plugins/core-meta/routes';
import { aurabotRoutes } from '../../app/plugins/core-aurabot/routes';
import { aiColleaguesRoutes } from '../../app/plugins/core-ai-colleagues/routes';
import { personalRoutes } from '../../app/plugins/core-personal/routes';
import { settingsRoutes } from '../../app/plugins/core-settings/routes';
import { platformRoutes as platformPluginRoutes } from '../../app/plugins/core-platform/routes';
import { adminRoutes } from '../../app/plugins/core-admin/routes';
import { opsRoutes } from '../../app/plugins/core-ops/routes';
import { dashboardRoutes } from '../../app/plugins/core-dashboard/routes';

/**
 * Core routes — included in ALL editions (community, enterprise, website).
 * File paths are relative to the app/ directory.
 */
export function coreRoutes() {
  return [
    // Feature plugins (M3 migration).
    ...designerRoutes(),
    ...automationRoutes(),
    ...bpmRoutes(),
    ...organizationRoutes(),
    ...metaRoutes(),
    ...aurabotRoutes(),
    ...aiColleaguesRoutes(),
    ...personalRoutes(),
    ...settingsRoutes(),
    ...platformPluginRoutes(),
    ...adminRoutes(),
    ...opsRoutes(),
    ...dashboardRoutes(),

    // Legacy unified inbox route remains static during Task Center migration.
    // Old links still deep-link with ?task=... and should not fall through to
    // the menu-driven catch-all route.
    route('/inbox', './routes/inbox/index.tsx'),

    // Page routes — /p/:pageKey based (V2, underscores)
    route('/p/:pageKey', './routes/p.$pageKey.tsx'),
    route('/p/:pageKey/new', './routes/p.$pageKey.new.tsx'),
    route('/p/:pageKey/view/:recordId', './routes/p.$pageKey.view.tsx'),
    // Edit supports both /p/:pageKey/edit/:recordId (AGENTS.md convention) and
    // /p/:pageKey/:recordId/edit (legacy; still generated by many E2E tests and
    // helpers). Both routes resolve to the same component.
    route('/p/:pageKey/edit/:recordId', './routes/p.$pageKey.edit.tsx', { id: 'p-edit-new' }),
    route('/p/:pageKey/:recordId/edit', './routes/p.$pageKey.edit.tsx', { id: 'p-edit-legacy' }),

    // Legacy dynamic routes — redirect to /p/ prefix
    route('/dynamic/:tableName', './routes/dynamic.$tableName.tsx'),
    route('/dynamic/:tableName/new', './routes/dynamic.$tableName.new.tsx'),
    route('/dynamic/:tableName/view/:recordId', './routes/dynamic.$tableName.view.tsx'),
    route('/dynamic/:tableName/:recordId/edit', './routes/dynamic.$tableName.edit.tsx', { id: 'dynamic-edit-legacy' }),
    route('/dynamic/:tableName/edit/:recordId', './routes/dynamic.$tableName.edit.tsx', { id: 'dynamic-edit-new' }),

    // Wildcard route — handles plugin-defined custom paths
    route('/*', './routes/$.tsx'),
  ];
}
