package com.auraboot.framework.email.service;

import com.auraboot.framework.email.config.EmailTrackingConfig;
import com.auraboot.framework.email.mapper.EmailTrackingEventMapper;
import com.auraboot.framework.email.model.EmailConstants;
import com.auraboot.framework.email.model.EmailTrackingEvent;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Service for injecting open/click tracking into outbound HTML emails and recording
 * tracking events when recipients open or click links.
 *
 * <p>Tracking behaviour is controlled by {@link EmailTrackingConfig#isEnabled()}.
 * When disabled, {@link #injectTracking} returns the original HTML unchanged.
 *
 * @since 6.5.0
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class EmailTrackingService {

    /** Matches absolute http/https href attributes (captures the URL inside quotes). */
    private static final Pattern HREF_PATTERN =
            Pattern.compile("href=[\"'](https?://[^\"']+)[\"']", Pattern.CASE_INSENSITIVE);

    private final EmailTrackingConfig      trackingConfig;
    private final EmailTrackingEventMapper trackingEventMapper;

    // ──────────────────────────────────────────────────────────────────────────
    // Public API
    // ──────────────────────────────────────────────────────────────────────────

    /**
     * Generates a unique 32-character tracking token (UUID without dashes).
     *
     * @return 32-char hex string, unique per call
     */
    public String generateTrackingId() {
        return UUID.randomUUID().toString().replace("-", "");
    }

    /**
     * Injects a 1×1 tracking pixel and rewrites all absolute HTTP/HTTPS links in the
     * given HTML body.
     *
     * <p>If tracking is disabled ({@link EmailTrackingConfig#isEnabled()} == false),
     * the original {@code bodyHtml} is returned unchanged.
     *
     * <p>Link rewrite pattern: {@code <a href="https://example.com">} becomes
     * {@code <a href="{baseUrl}/api/email/tracking/{trackingId}/click?url=...">}.
     *
     * <p>Pixel injection: {@code <img src="{baseUrl}/api/email/tracking/{trackingId}/open.gif"
     * width="1" height="1" style="display:none">} is inserted immediately before the closing
     * {@code </body>} tag, or appended at the end if no {@code </body>} tag is found.
     *
     * @param bodyHtml   original HTML email body (may be {@code null} or blank)
     * @param trackingId the 32-char tracking token generated by {@link #generateTrackingId()}
     * @return modified HTML with tracking injected, or the original if tracking is disabled
     */
    public String injectTracking(String bodyHtml, String trackingId) {
        if (!trackingConfig.isEnabled()) {
            return bodyHtml;
        }
        if (bodyHtml == null || bodyHtml.isBlank()) {
            return bodyHtml;
        }

        String baseUrl = trackingConfig.getBaseUrl();

        // 1. Rewrite all absolute links
        String result = rewriteLinks(bodyHtml, baseUrl, trackingId);

        // 2. Inject tracking pixel
        result = injectPixel(result, baseUrl, trackingId);

        return result;
    }

    /**
     * Records a tracking event in {@code ab_email_tracking_event}.
     *
     * @param trackingId tracking token from the URL
     * @param eventType  {@link EmailConstants#TRACKING_OPEN} or {@link EmailConstants#TRACKING_CLICK}
     * @param linkUrl    original URL for click events; {@code null} for open events
     * @param ipAddress  client IP (may be {@code null})
     * @param userAgent  HTTP User-Agent (may be {@code null})
     * @param tenantId   tenant owning the message (may be {@code null} for anonymous events)
     * @param messageId  database ID of the outbound message (may be {@code null})
     */
    public void recordEvent(String trackingId, String eventType, String linkUrl,
                            String ipAddress, String userAgent,
                            Long tenantId, Long messageId) {
        EmailTrackingEvent event = new EmailTrackingEvent();
        event.setTenantId(tenantId);
        event.setMessageId(messageId);
        event.setTrackingId(trackingId);
        event.setEventType(eventType);
        event.setLinkUrl(linkUrl);
        event.setIpAddress(ipAddress);
        event.setUserAgent(userAgent);
        event.setEventAt(Instant.now());

        try {
            trackingEventMapper.insert(event);
            log.debug("Recorded tracking event: trackingId={}, type={}", trackingId, eventType);
        } catch (Exception e) {
            // Tracking failure must never interrupt the request
            log.warn("Failed to record tracking event trackingId={}: {}", trackingId, e.getMessage());
        }
    }

    /**
     * Returns open and click counts for the given message.
     *
     * @param messageId database ID of the message
     * @return map with keys {@code openCount} and {@code clickCount}
     */
    public Map<String, Integer> getStats(Long messageId) {
        int openCount  = trackingEventMapper.countByType(messageId, EmailConstants.TRACKING_OPEN);
        int clickCount = trackingEventMapper.countByType(messageId, EmailConstants.TRACKING_CLICK);
        return Map.of("openCount", openCount, "clickCount", clickCount);
    }

    // ──────────────────────────────────────────────────────────────────────────
    // Private helpers
    // ──────────────────────────────────────────────────────────────────────────

    private String rewriteLinks(String html, String baseUrl, String trackingId) {
        StringBuffer sb = new StringBuffer();
        Matcher matcher = HREF_PATTERN.matcher(html);
        while (matcher.find()) {
            String originalUrl = matcher.group(1);
            String encoded     = URLEncoder.encode(originalUrl, StandardCharsets.UTF_8);
            String redirectUrl = baseUrl + "/api/email/tracking/" + trackingId + "/click?url=" + encoded;
            // Preserve original quote character
            char quote = html.charAt(matcher.start() + 5); // 'href=' is 5 chars
            matcher.appendReplacement(sb, "href=" + quote + Matcher.quoteReplacement(redirectUrl) + quote);
        }
        matcher.appendTail(sb);
        return sb.toString();
    }

    private String injectPixel(String html, String baseUrl, String trackingId) {
        String pixel = "<img src=\"" + baseUrl + "/api/email/tracking/" + trackingId
                + "/open.gif\" width=\"1\" height=\"1\" style=\"display:none\" alt=\"\">";

        String lowerHtml = html.toLowerCase();
        int bodyCloseIndex = lowerHtml.lastIndexOf("</body>");
        if (bodyCloseIndex >= 0) {
            return html.substring(0, bodyCloseIndex) + pixel + html.substring(bodyCloseIndex);
        }
        // No </body> tag — append at end
        return html + pixel;
    }
}
