package com.auraboot.framework.meta.ddl;

import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.sql.Connection;

@Component
public class TableMetadataService {

    private final DataSource dataSource;
    private final DdlDialectProvider ddlDialectProvider;

    public TableMetadataService(DataSource dataSource, DdlDialectProvider ddlDialectProvider) {
        this.dataSource = dataSource;
        this.ddlDialectProvider = ddlDialectProvider;
    }

    public boolean tableExists(String tableName) {
        try (Connection connection = dataSource.getConnection()) {
            return ddlDialectProvider.getDialect().tableExists(connection, tableName);
        } catch (Exception e) {
            throw new IllegalStateException("Failed to check table existence: " + tableName, e);
        }
    }

    public boolean columnExists(String tableName, String columnName) {
        try (Connection connection = dataSource.getConnection()) {
            return ddlDialectProvider.getDialect().columnExists(connection, tableName, columnName);
        } catch (Exception e) {
            throw new IllegalStateException("Failed to check column existence: " + tableName + "." + columnName, e);
        }
    }

    public String getColumnTypeDefinition(String tableName, String columnName) {
        try (Connection connection = dataSource.getConnection()) {
            return ddlDialectProvider.getDialect().getColumnTypeDefinition(connection, tableName, columnName);
        } catch (Exception e) {
            throw new IllegalStateException("Failed to check column type: " + tableName + "." + columnName, e);
        }
    }

    public boolean isColumnNullable(String tableName, String columnName) {
        try (Connection connection = dataSource.getConnection()) {
            return ddlDialectProvider.getDialect().isColumnNullable(connection, tableName, columnName);
        } catch (Exception e) {
            throw new IllegalStateException("Failed to check column nullability: " + tableName + "." + columnName, e);
        }
    }

    public boolean indexExists(String tableName, String indexName) {
        try (Connection connection = dataSource.getConnection()) {
            return ddlDialectProvider.getDialect().indexExists(connection, tableName, indexName);
        } catch (Exception e) {
            throw new IllegalStateException("Failed to check index existence: " + tableName + "." + indexName, e);
        }
    }

    /** Only recognizes PostgreSQL's untruncated, generated single-column UNIQUE constraint. */
    public boolean hasGeneratedSingleColumnUniqueConstraint(String tableName, String columnName) {
        String constraintName = tableName + "_" + columnName + "_key";
        if (constraintName.getBytes(java.nio.charset.StandardCharsets.UTF_8).length > 63) return false;
        String sql = "SELECT 1 FROM pg_constraint c JOIN pg_attribute a "
                + "ON a.attrelid = c.conrelid AND c.conkey = ARRAY[a.attnum] "
                + "WHERE c.conrelid = to_regclass(?) AND c.contype = 'u' "
                + "AND c.conname = ? AND a.attname = ?";
        try (Connection connection = dataSource.getConnection();
             var statement = connection.prepareStatement(sql)) {
            statement.setString(1, tableName);
            statement.setString(2, constraintName);
            statement.setString(3, columnName);
            try (var result = statement.executeQuery()) {
                return result.next();
            }
        } catch (java.sql.SQLException e) {
            throw new IllegalStateException("Failed to inspect generated unique constraint", e);
        }
    }
    /** Recognizes only the exact two-column index generated by MultiTenantIndexManager. */
    public boolean hasGeneratedTenantUniqueIndex(String tableName, String columnName) {
        String indexName = "idx_" + tableName + "_" + columnName + "_tenant_unique";
        if (indexName.getBytes(java.nio.charset.StandardCharsets.UTF_8).length > 63) return false;
        String sql = "SELECT 1 FROM pg_index i JOIN pg_class x ON x.oid = i.indexrelid "
                + "JOIN pg_attribute t ON t.attrelid = i.indrelid AND t.attname = 'tenant_id' "
                + "JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attname = ? "
                + "WHERE i.indrelid = to_regclass(?) AND x.relname = ? "
                + "AND i.indisunique AND NOT i.indisprimary AND i.indisvalid "
                + "AND i.indnatts = 2 AND i.indnkeyatts = 2 "
                + "AND i.indkey[0] = t.attnum AND i.indkey[1] = a.attnum "
                + "AND i.indexprs IS NULL AND i.indpred IS NULL "
                + "AND NOT EXISTS (SELECT 1 FROM pg_constraint c WHERE c.conindid = i.indexrelid)";
        try (Connection connection = dataSource.getConnection();
             var statement = connection.prepareStatement(sql)) {
            statement.setString(1, columnName);
            statement.setString(2, tableName);
            statement.setString(3, indexName);
            try (var result = statement.executeQuery()) {
                return result.next();
            }
        } catch (java.sql.SQLException e) {
            throw new IllegalStateException("Failed to inspect generated tenant unique index", e);
        }
    }

}
