package com.auraboot.framework.branding;

/** Fixed product identity for AuraBoot Community runtime and generated outputs. */
public final class CommunityBranding {

    public static final String PRODUCT_NAME = "AuraBoot";
    public static final String PLATFORM_NAME = "AuraBoot Platform";
    public static final String POWERED_BY_TEXT = "Powered by " + PRODUCT_NAME;
    public static final String GENERATED_BY_TEXT = "Generated by " + PLATFORM_NAME;

    private CommunityBranding() {
    }
}
