package com.auraboot.framework.agent;

import com.auraboot.framework.agent.dto.LlmChatRequest;
import com.auraboot.framework.agent.dto.LlmChatResponse;
import com.auraboot.framework.agent.eval.AgentOnlineEvalService;
import com.auraboot.framework.agent.eval.LlmTurnQualityJudge;
import com.auraboot.framework.agent.provider.LlmProvider;
import com.auraboot.framework.agent.provider.LlmProviderFactory;
import com.auraboot.framework.agent.util.LiveLlmSeeder;
import com.auraboot.framework.cloudconfig.service.CloudConfigService;
import com.auraboot.framework.common.util.UniqueIdGenerator;
import com.auraboot.framework.integration.BaseIntegrationTest;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.Timeout;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;
import org.springframework.test.util.ReflectionTestUtils;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.concurrent.TimeUnit;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * G6 last-mile proof: the LLM quality judge grades persisted observation turns
 * with a real provider. One candidate turn is itself generated by the live model
 * from a controlled tool result; the counterexample completes cleanly but invents
 * a fact contradicted by its trace. This is deliberately not a mock-provider test.
 */
@Tag("agent-eval-live")
@DisplayName("Live: LLM turn-quality judge separates grounded from fabricated turns")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@Transactional(propagation = Propagation.NOT_SUPPORTED)
@TestPropertySource(properties = {
        "agent.anthropic.api-key=",
        "agent.llm.stub-mode=false",
        "aura.agent.online-eval.judge=llm",
})
class LlmTurnQualityJudgeLiveIT extends BaseIntegrationTest {

    @Autowired private LlmProviderFactory providerFactory;
    @Autowired private CloudConfigService cloudConfigService;
    @Autowired private JdbcTemplate jdbcTemplate;
    @Autowired private LlmTurnQualityJudge llmJudge;
    @Autowired private AgentOnlineEvalService onlineEvalService;

    private LiveLlmSeeder.LiveProvider liveProvider;
    private Long tenantId;

    @BeforeEach
    void seedLiveProvider() {
        liveProvider = LiveLlmSeeder.resolve();
        Assumptions.assumeTrue(liveProvider != null, LiveLlmSeeder.skipReason());
        tenantId = getTestTenant().getId();
        LiveLlmSeeder.seed(liveProvider, tenantId, cloudConfigService, jdbcTemplate);
        ReflectionTestUtils.setField(llmJudge, "tenantId", tenantId);
    }

    @AfterAll
    void clearProvider() {
        if (tenantId != null && liveProvider != null) {
            LiveLlmSeeder.clear(liveProvider, tenantId, jdbcTemplate);
        }
    }

    @Test
    @Timeout(value = 8, unit = TimeUnit.MINUTES)
    void liveJudgeClassifiesPersistedLabeledTurns() throws Exception {
        LlmProviderFactory.ProviderResolution resolution =
                providerFactory.resolveProvider(tenantId, liveProvider.providerCode());
        assertThat(resolution).isNotNull();
        LlmProviderFactory.ProviderConfig config = resolution.getConfig();
        LlmProvider provider = resolution.getProvider();

        String groundedAnswer = text(provider.chat(
                LlmChatRequest.builder()
                        .model(config.getDefaultModel())
                        .systemPrompt("You are a business data agent. Answer only from the supplied "
                                + "tool result; if it lacks the answer, say so.")
                        .messages(List.of(LlmChatRequest.Message.builder()
                                .role("user")
                                .content("User asks: What was Q2 revenue? "
                                        + "Tool result: {\"quarter\":\"Q2\",\"revenue\":184000,\"currency\":\"CNY\"}")
                                .build()))
                        .maxTokens(512)
                        .build(),
                config.getApiKey(), config.getBaseUrl()));
        assertThat(groundedAnswer)
                .as("the candidate turn must be produced by the real model")
                .isNotBlank()
                .contains("184");

        String agentCode = "judge-live-" + System.currentTimeMillis();
        String goodRun = UniqueIdGenerator.generate();
        String badRun = UniqueIdGenerator.generate();

        persistTurn(goodRun, agentCode,
                "What was Q2 revenue?",
                "query result: {\"quarter\":\"Q2\",\"revenue\":184000,\"currency\":\"CNY\"}",
                groundedAnswer);
        persistTurn(badRun, agentCode,
                "What is the current status of order ORD-42?",
                "lookup result: {\"orderId\":\"ORD-42\",\"found\":false}",
                "Order ORD-42 shipped yesterday and will arrive tomorrow.");

        AgentOnlineEvalService.OnlineEvalSummary summary =
                onlineEvalService.sampleAndJudge(tenantId, 1, 2);

        System.out.printf(
                "%n===== LIVE LLM TURN JUDGE (%s %s) =====%n"
                        + "  sampled=%d healthyRate=%.2f avgScore=%.2f%n"
                        + "  unhealthy=%s%n"
                        + "==========================================%n",
                liveProvider.providerCode(), liveProvider.model(),
                summary.sampledTurns(), summary.healthyRate(), summary.avgScore(),
                summary.unhealthy());

        assertThat(summary.judgeMode()).isEqualTo("llm");
        assertThat(summary.sampledTurns()).isEqualTo(2);
        assertThat(summary.unhealthy())
                .extracting(v -> v.runPid())
                .contains(badRun)
                .doesNotContain(goodRun);
        assertThat(summary.healthyRate()).isEqualTo(0.5);
    }

    private void persistTurn(String runPid, String agentCode,
                             String userRequest, String toolResult, String agentResponse) {
        insertObservation(runPid, agentCode, "user_message", "User request", userRequest);
        insertObservation(runPid, agentCode, "tool_result", "Tool result", toolResult);
        insertObservation(runPid, agentCode, "assistant_message", "Agent response", agentResponse);
        insertObservation(runPid, agentCode, "turn_completed", "Turn completed",
                "completed=true, errors=0");
    }

    private void insertObservation(String runPid, String agentCode, String type,
                                   String title, String detail) {
        jdbcTemplate.update(
                "INSERT INTO ab_agent_observation "
                        + "(pid, tenant_id, observation_type, source_type, source_id, obs_agent_id, "
                        + "obs_title, detail, severity, created_at, updated_at, created_by) "
                        + "VALUES (?, ?, ?, 'run', ?, ?, ?, ?, 'info', NOW(), NOW(), ?)",
                UniqueIdGenerator.generate(), tenantId, type, runPid, agentCode,
                title, detail, getTestUser().getId());
    }

    private static String text(LlmChatResponse response) {
        if (response == null || response.getContent() == null) return "";
        return response.getContent().stream()
                .filter(block -> "text".equals(block.getType()))
                .map(LlmChatResponse.ContentBlock::getText)
                .filter(value -> value != null && !value.isBlank())
                .findFirst()
                .orElse("");
    }
}
