-- Seed print templates (HTML → PDF)
-- Run after schema creation. Idempotent (uses ON CONFLICT).
-- Templates use table-based layout (CSS 2.1 for openhtmltopdf) and bracket notation for Map access.

-- Invoice template
INSERT INTO ab_report_template (
    pid, tenant_id, code, name, description, category,
    template_type, template_content, output_format,
    page_size, orientation, status, deleted_flag,
    created_at, updated_at
)
SELECT
    'print_tpl_invoice_01',
    t.id,
    'invoice',
    'Invoice',
    'Standard invoice template with line items, totals, and company branding',
    'print',
    'html',
    '<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8"/>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Helvetica, Arial, sans-serif; font-size: 12px; color: #333; padding: 40px; }
        .header-table { width: 100%; margin-bottom: 30px; }
        .header-table td { vertical-align: top; }
        .company-name { font-size: 20px; font-weight: bold; color: #1a1a1a; }
        .company-detail { font-size: 10px; color: #666; margin-top: 4px; }
        .doc-title { font-size: 24px; font-weight: bold; color: #2563eb; text-align: right; }
        .doc-number { font-size: 11px; color: #666; text-align: right; margin-top: 4px; }
        .info-table { width: 100%; margin-bottom: 20px; }
        .info-table td { vertical-align: top; width: 50%; }
        .info-label { font-size: 11px; color: #999; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 6px; }
        .data-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        .data-table thead th { background-color: #f8fafc; border-bottom: 2px solid #e2e8f0; padding: 8px 10px; text-align: left; font-size: 10px; text-transform: uppercase; letter-spacing: 0.5px; color: #64748b; }
        .data-table tbody td { padding: 8px 10px; border-bottom: 1px solid #f1f5f9; }
        .text-right { text-align: right; }
        .totals-table { width: 280px; margin-left: auto; margin-top: 16px; }
        .totals-table td { padding: 4px 10px; }
        .total-row td { font-weight: bold; font-size: 14px; border-top: 2px solid #333; }
        .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #999; text-align: center; }
    </style>
</head>
<body>
<table class="header-table"><tr>
    <td>
        <div class="company-name" th:text="${params[''companyName''] ?: ''AuraBoot Inc.''}">AuraBoot Inc.</div>
        <div class="company-detail" th:text="${params[''companyAddress''] ?: ''123 Tech Street, San Francisco, CA 94105''}">123 Tech Street</div>
        <div class="company-detail" th:text="${params[''companyContact''] ?: ''contact@auraboot.com''}">contact@auraboot.com</div>
    </td>
    <td style="text-align: right;">
        <div class="doc-title">INVOICE</div>
        <div class="doc-number">No. <span th:text="${record[''pid'']}">INV-001</span></div>
    </td>
</tr></table>

<table class="info-table"><tr>
    <td>
        <div class="info-label">Bill To</div>
        <p th:text="${record[''customer_name''] ?: record[''account_name''] ?: record[''org_dept_name''] ?: ''N/A''}">Customer</p>
    </td>
    <td style="text-align: right;">
        <div class="info-label">Details</div>
        <p>Date: <span th:text="${record[''created_at''] ?: ''N/A''}">2026-01-01</span></p>
        <p>Status: <span th:text="${record[''status''] ?: record[''org_dept_status''] ?: ''draft''}">draft</span></p>
    </td>
</tr></table>

<table class="data-table">
    <thead><tr><th style="width:5%;">#</th><th style="width:40%;">Description</th><th class="text-right" style="width:15%;">Qty</th><th class="text-right" style="width:20%;">Unit Price</th><th class="text-right" style="width:20%;">Amount</th></tr></thead>
    <tbody>
        <tr th:each="line, iter : ${lines}">
            <td th:text="${iter.index + 1}">1</td>
            <td th:text="${line[''description''] ?: line[''product_name''] ?: ''Item''}">Item</td>
            <td class="text-right" th:text="${line[''quantity''] ?: 1}">1</td>
            <td class="text-right" th:text="${line[''unit_price''] ?: ''0.00''}">0.00</td>
            <td class="text-right" th:text="${line[''amount''] ?: ''0.00''}">0.00</td>
        </tr>
        <tr th:if="${#lists.isEmpty(lines)}"><td colspan="5" style="text-align:center;color:#999;padding:20px;">No line items</td></tr>
    </tbody>
</table>

<table class="totals-table">
    <tr class="total-row"><td>Total:</td><td class="text-right" th:text="${record[''total_amount''] ?: ''0.00''}">0.00</td></tr>
</table>

<div class="footer">
    <p th:text="${params[''footerNote''] ?: ''Thank you for your business. Payment is due within 30 days.''}">Thank you.</p>
    <p style="margin-top: 4px;">Generated by AuraBoot Platform</p>
</div>
</body>
</html>',
    'pdf', 'A4', 'portrait', 'published', false,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM ab_tenant t LIMIT 1
ON CONFLICT (tenant_id, code) DO UPDATE SET
    template_type = EXCLUDED.template_type,
    template_content = EXCLUDED.template_content,
    status = EXCLUDED.status,
    updated_at = CURRENT_TIMESTAMP;

-- Quote template
INSERT INTO ab_report_template (
    pid, tenant_id, code, name, description, category,
    template_type, template_content, output_format,
    page_size, orientation, status, deleted_flag,
    created_at, updated_at
)
SELECT
    'print_tpl_quote_001',
    t.id,
    'quote',
    'Quotation',
    'Standard quotation template with line items and validity terms',
    'print',
    'html',
    '<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8"/>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Helvetica, Arial, sans-serif; font-size: 12px; color: #333; padding: 40px; }
        .header-table { width: 100%; margin-bottom: 30px; }
        .header-table td { vertical-align: top; }
        .company-name { font-size: 20px; font-weight: bold; }
        .doc-title { font-size: 24px; font-weight: bold; color: #059669; text-align: right; }
        .doc-number { font-size: 11px; color: #666; text-align: right; margin-top: 4px; }
        .info-table { width: 100%; margin-bottom: 20px; }
        .info-table td { vertical-align: top; width: 50%; }
        .info-label { font-size: 11px; color: #999; text-transform: uppercase; margin-bottom: 6px; }
        .data-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        .data-table thead th { background-color: #f0fdf4; border-bottom: 2px solid #bbf7d0; padding: 8px 10px; text-align: left; font-size: 10px; text-transform: uppercase; color: #166534; }
        .data-table tbody td { padding: 8px 10px; border-bottom: 1px solid #f1f5f9; }
        .text-right { text-align: right; }
        .totals-table { width: 280px; margin-left: auto; margin-top: 16px; }
        .totals-table td { padding: 4px 10px; }
        .total-row td { font-weight: bold; font-size: 14px; border-top: 2px solid #333; }
        .validity { margin-top: 30px; padding: 16px; background-color: #f0fdf4; }
        .validity-title { font-size: 12px; color: #166534; margin-bottom: 8px; font-weight: bold; }
        .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #999; text-align: center; }
    </style>
</head>
<body>
<table class="header-table"><tr>
    <td><div class="company-name" th:text="${params[''companyName''] ?: ''AuraBoot Inc.''}">AuraBoot Inc.</div></td>
    <td style="text-align: right;"><div class="doc-title">QUOTATION</div><div class="doc-number">No. <span th:text="${record[''pid'']}">QT-001</span></div></td>
</tr></table>
<table class="info-table"><tr>
    <td><div class="info-label">Prepared For</div><p th:text="${record[''customer_name''] ?: record[''account_name''] ?: record[''org_dept_name''] ?: ''N/A''}">Customer</p></td>
    <td style="text-align: right;"><div class="info-label">Quote Details</div><p>Date: <span th:text="${record[''created_at''] ?: ''N/A''}">2026-01-01</span></p><p>Status: <span th:text="${record[''status''] ?: record[''org_dept_status''] ?: ''draft''}">draft</span></p></td>
</tr></table>
<table class="data-table">
    <thead><tr><th>#</th><th>Item</th><th class="text-right">Qty</th><th class="text-right">Price</th><th class="text-right">Amount</th></tr></thead>
    <tbody>
        <tr th:each="line, iter : ${lines}"><td th:text="${iter.index + 1}">1</td><td th:text="${line[''description''] ?: ''Item''}">Item</td><td class="text-right" th:text="${line[''quantity''] ?: 1}">1</td><td class="text-right" th:text="${line[''unit_price''] ?: ''0.00''}">0.00</td><td class="text-right" th:text="${line[''amount''] ?: ''0.00''}">0.00</td></tr>
        <tr th:if="${#lists.isEmpty(lines)}"><td colspan="5" style="text-align:center;color:#999;padding:20px;">No line items</td></tr>
    </tbody>
</table>
<table class="totals-table"><tr class="total-row"><td>Total:</td><td class="text-right" th:text="${record[''total_amount''] ?: ''0.00''}">0.00</td></tr></table>
<div class="validity"><div class="validity-title">Terms &amp; Conditions</div><p th:text="${record[''terms''] ?: params[''terms''] ?: ''This quotation is valid for 30 days from the date of issue.''}">Terms.</p></div>
<div class="footer"><p>Generated by AuraBoot Platform</p></div>
</body>
</html>',
    'pdf', 'A4', 'portrait', 'published', false,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM ab_tenant t LIMIT 1
ON CONFLICT (tenant_id, code) DO UPDATE SET
    template_type = EXCLUDED.template_type,
    template_content = EXCLUDED.template_content,
    status = EXCLUDED.status,
    updated_at = CURRENT_TIMESTAMP;

-- Delivery note template
INSERT INTO ab_report_template (
    pid, tenant_id, code, name, description, category,
    template_type, template_content, output_format,
    page_size, orientation, status, deleted_flag,
    created_at, updated_at
)
SELECT
    'print_tpl_delivery_01',
    t.id,
    'delivery_note',
    'Delivery Note',
    'Delivery/shipping note template with item list and recipient info',
    'print',
    'html',
    '<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="UTF-8"/>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: Helvetica, Arial, sans-serif; font-size: 12px; color: #333; padding: 40px; }
        .header-table { width: 100%; margin-bottom: 30px; }
        .header-table td { vertical-align: top; }
        .company-name { font-size: 20px; font-weight: bold; }
        .doc-title { font-size: 24px; font-weight: bold; color: #d97706; text-align: right; }
        .doc-number { font-size: 11px; color: #666; text-align: right; margin-top: 4px; }
        .info-table { width: 100%; margin-bottom: 20px; }
        .info-table td { vertical-align: top; width: 50%; }
        .info-label { font-size: 11px; color: #999; text-transform: uppercase; margin-bottom: 6px; }
        .data-table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        .data-table thead th { background-color: #fffbeb; border-bottom: 2px solid #fde68a; padding: 8px 10px; text-align: left; font-size: 10px; text-transform: uppercase; color: #92400e; }
        .data-table tbody td { padding: 8px 10px; border-bottom: 1px solid #f1f5f9; }
        .text-right { text-align: right; }
        .sig-table { width: 100%; margin-top: 60px; }
        .sig-block { border-top: 1px solid #333; padding-top: 8px; font-size: 11px; width: 45%; }
        .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 10px; color: #999; text-align: center; }
    </style>
</head>
<body>
<table class="header-table"><tr>
    <td><div class="company-name" th:text="${params[''companyName''] ?: ''AuraBoot Inc.''}">AuraBoot Inc.</div></td>
    <td style="text-align: right;"><div class="doc-title">DELIVERY NOTE</div><div class="doc-number">No. <span th:text="${record[''pid'']}">DN-001</span></div></td>
</tr></table>
<table class="info-table"><tr>
    <td><div class="info-label">Ship To</div><p th:text="${record[''customer_name''] ?: record[''account_name''] ?: record[''org_dept_name''] ?: ''N/A''}">Customer</p><p th:text="${record[''shipping_address''] ?: record[''address''] ?: ''''}"></p></td>
    <td style="text-align: right;"><div class="info-label">Shipping Details</div><p>Date: <span th:text="${record[''created_at''] ?: ''N/A''}">2026-01-01</span></p><p>Status: <span th:text="${record[''status''] ?: record[''org_dept_status''] ?: ''pending''}">pending</span></p></td>
</tr></table>
<table class="data-table">
    <thead><tr><th>#</th><th>Item</th><th class="text-right">Qty</th><th>Unit</th><th>Notes</th></tr></thead>
    <tbody>
        <tr th:each="line, iter : ${lines}"><td th:text="${iter.index + 1}">1</td><td th:text="${line[''description''] ?: line[''product_name''] ?: ''Item''}">Item</td><td class="text-right" th:text="${line[''quantity''] ?: 1}">1</td><td th:text="${line[''unit''] ?: ''pcs''}">pcs</td><td th:text="${line[''notes''] ?: ''''}"></td></tr>
        <tr th:if="${#lists.isEmpty(lines)}"><td colspan="5" style="text-align:center;color:#999;padding:20px;">No items</td></tr>
    </tbody>
</table>
<table class="sig-table"><tr><td class="sig-block">Dispatched by: _______________</td><td style="width:10%;"></td><td class="sig-block">Received by: _______________</td></tr></table>
<div class="footer"><p>Generated by AuraBoot Platform</p></div>
</body>
</html>',
    'pdf', 'A4', 'portrait', 'published', false,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM ab_tenant t LIMIT 1
ON CONFLICT (tenant_id, code) DO UPDATE SET
    template_type = EXCLUDED.template_type,
    template_content = EXCLUDED.template_content,
    status = EXCLUDED.status,
    updated_at = CURRENT_TIMESTAMP;
