package com.auraboot.framework.aurabot.service;

import com.auraboot.framework.agent.dto.AgentToolDefinition;
import com.auraboot.framework.common.util.LogSanitizer;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.TimeUnit;

/**
 * Store for pending tool confirmations in AuraBot chat sessions.
 *
 * <p>Uses Redis for persistence (survives server restarts). Falls back to
 * in-memory ConcurrentHashMap if Redis is unavailable.
 *
 * <p>Phase B.6 (2026-04-27) key migration: pending entries are now keyed by
 * the suspended turn's {@code turnId} (per-turn PID generated by
 * {@code TurnContext}) rather than the legacy sessionId — per design v3.3
 * §3.10 step 4. Reasons:
 * <ul>
 *     <li>A session can suspend multiple turns sequentially; sessionId+toolId
 *         conflicts when the same toolId reappears across turns.</li>
 *     <li>{@code resumeTurn(pendingTurnId)} is now the canonical resume entry —
 *         the SSE {@code confirm_required} event already carries turnId so the
 *         frontend echoes it back in {@code POST /execute}.</li>
 *     <li>{@link PendingTool} carries the full identity tuple
 *         (tenantId / userId / humanMemberId / conversationId / agentCode) so
 *         the resume path can rebuild a {@link com.auraboot.framework.conversation.TurnContext}
 *         and validate that the user requesting resume actually owns the
 *         suspended turn.</li>
 * </ul>
 *
 * <p>Key pattern: {@code aurabot:pending:{turnId}:{toolId}} with 10-minute TTL.
 */
@Slf4j
@Component
public class ChatSessionStore {

    private static final String PENDING_KEY_PREFIX = "aurabot:pending:";
    private static final String MESSAGES_KEY_PREFIX = "aurabot:messages:";
    private static final long PENDING_TTL_MINUTES = 10;
    private static final long MESSAGES_TTL_MINUTES = 60;

    // Fallback in-memory store (used only when Redis is unavailable)
    private static final long IN_MEMORY_TTL_MILLIS = PENDING_TTL_MINUTES * 60 * 1000L;
    private final ConcurrentHashMap<String, PendingTool> inMemoryFallback = new ConcurrentHashMap<>();
    private final ConcurrentHashMap<String, StoredMessages> inMemoryMessagesFallback = new ConcurrentHashMap<>();

    private final ObjectMapper objectMapper;
    private final StringRedisTemplate redisTemplate;
    private final boolean redisAvailable;

    @Autowired
    public ChatSessionStore(ObjectMapper objectMapper,
                            @Autowired(required = false) StringRedisTemplate redisTemplate) {
        this.objectMapper = objectMapper;
        this.redisTemplate = redisTemplate;
        this.redisAvailable = redisTemplate != null;
        if (!redisAvailable) {
            log.warn("Redis not available - ChatSessionStore falling back to in-memory storage");
        }
    }

    /**
     * Phase B.6: store a pending tool keyed solely by the suspended turn's
     * {@code turnId}. The chat-impl tool loop breaks out of the inner for-loop
     * the moment a write tool is queued for confirmation, so at any given time
     * there is at most one pending entry per turn — the toolId is part of the
     * stored {@link PendingTool} payload, not the key.
     */
    public void storePending(String turnId, PendingTool pendingTool) {
        if (redisAvailable) {
            try {
                String key = pendingKey(turnId);
                String json = objectMapper.writeValueAsString(pendingTool);
                redisTemplate.opsForValue().set(key, json, PENDING_TTL_MINUTES, TimeUnit.MINUTES);
                log.debug("Stored pending tool [{}] for turn [{}] in Redis (TTL={}min)",
                        LogSanitizer.safe(pendingTool.getToolId()), LogSanitizer.safe(turnId), PENDING_TTL_MINUTES);
                return;
            } catch (JsonProcessingException e) {
                log.error("Failed to serialize PendingTool to JSON, falling back to in-memory", e);
            } catch (Exception e) {
                log.error("Redis write failed for pending tool [{}], falling back to in-memory",
                        LogSanitizer.safe(pendingTool.getToolId()), e);
            }
        }
        // Fallback: in-memory keyed by turnId
        inMemoryFallback.put(turnId, pendingTool);
        log.debug("Stored pending tool [{}] for turn [{}] in memory",
                LogSanitizer.safe(pendingTool.getToolId()), LogSanitizer.safe(turnId));
    }

    /**
     * Phase B.6: retrieve AND remove the pending tool entry for the given turn.
     * Returns {@code null} when no pending entry exists or the TTL has elapsed.
     * Designed for {@code ConversationTurnService.resumeTurn} which only knows
     * the {@code pendingTurnId}.
     */
    public PendingTool consumePending(String turnId) {
        if (redisAvailable) {
            try {
                String key = pendingKey(turnId);
                String json = redisTemplate.opsForValue().getAndDelete(key);
                if (json == null) {
                    log.debug("No pending tool for turn [{}] (not found or expired)", LogSanitizer.safe(turnId));
                    return null;
                }
                PendingTool tool = objectMapper.readValue(json, PendingTool.class);
                log.debug("Consumed pending tool [{}] for turn [{}] via Redis",
                        LogSanitizer.safe(tool.getToolId()), LogSanitizer.safe(turnId));
                return tool;
            } catch (JsonProcessingException e) {
                log.error("Failed to deserialize PendingTool from Redis", e);
                return null;
            } catch (Exception e) {
                log.error("Redis read failed for turn [{}], trying in-memory fallback", LogSanitizer.safe(turnId), e);
            }
        }
        // Fallback: in-memory with manual TTL check
        PendingTool tool = inMemoryFallback.remove(turnId);
        if (tool == null) {
            return null;
        }
        if (Instant.now().toEpochMilli() - tool.getCreatedAt() > IN_MEMORY_TTL_MILLIS) {
            log.debug("Pending tool for turn [{}] has expired (in-memory)", LogSanitizer.safe(turnId));
            return null;
        }
        log.debug("Consumed pending tool [{}] for turn [{}] via in-memory fallback",
                LogSanitizer.safe(tool.getToolId()), LogSanitizer.safe(turnId));
        return tool;
    }

    /**
     * Phase B.6: pending key uses turnId only (one pending per turn at a time —
     * the chat-impl tool loop breaks the moment one tool is queued for confirm).
     */
    private String pendingKey(String turnId) {
        return PENDING_KEY_PREFIX + turnId;
    }

    /**
     * Store structured LLM messages for the chat session.
     * This preserves assistant tool_use and user tool_result blocks across HTTP turns.
     * Independent from pending-tool storage — uses the {@code aurabot:messages:}
     * key prefix and a longer TTL so message history is retrievable across the
     * tool-loop continuation cycle introduced on main.
     */
    public void storeConversationMessages(String sessionId, List<Map<String, Object>> messages) {
        if (sessionId == null || sessionId.isBlank() || messages == null) {
            return;
        }
        if (redisAvailable) {
            try {
                String json = objectMapper.writeValueAsString(messages);
                redisTemplate.opsForValue().set(messagesKey(sessionId), json, MESSAGES_TTL_MINUTES, TimeUnit.MINUTES);
                log.debug("Stored {} conversation messages for session [{}] in Redis (TTL={}min)",
                        messages.size(), LogSanitizer.safe(sessionId), MESSAGES_TTL_MINUTES);
                return;
            } catch (JsonProcessingException e) {
                log.error("Failed to serialize conversation messages, falling back to in-memory", e);
            } catch (Exception e) {
                log.error("Redis write failed for conversation messages [{}], falling back to in-memory",
                        LogSanitizer.safe(sessionId), e);
            }
        }
        inMemoryMessagesFallback.put(sessionId, new StoredMessages(messages));
        log.debug("Stored {} conversation messages for session [{}] in memory",
                messages.size(), LogSanitizer.safe(sessionId));
    }

    /**
     * Load structured LLM messages for a chat session.
     */
    public List<Map<String, Object>> loadConversationMessages(String sessionId) {
        if (sessionId == null || sessionId.isBlank()) {
            return List.of();
        }
        if (redisAvailable) {
            try {
                String json = redisTemplate.opsForValue().get(messagesKey(sessionId));
                if (json == null || json.isBlank()) {
                    return List.of();
                }
                return objectMapper.readValue(json, new com.fasterxml.jackson.core.type.TypeReference<>() {});
            } catch (JsonProcessingException e) {
                log.error("Failed to deserialize conversation messages from Redis", e);
                return List.of();
            } catch (Exception e) {
                log.error("Redis read failed for conversation messages [{}], trying in-memory fallback",
                        LogSanitizer.safe(sessionId), e);
            }
        }
        StoredMessages stored = inMemoryMessagesFallback.get(sessionId);
        if (stored == null) {
            return List.of();
        }
        if (Instant.now().toEpochMilli() - stored.createdAt() > MESSAGES_TTL_MINUTES * 60 * 1000L) {
            inMemoryMessagesFallback.remove(sessionId);
            return List.of();
        }
        return stored.messages();
    }

    private String messagesKey(String sessionId) {
        return MESSAGES_KEY_PREFIX + sessionId;
    }

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class PendingTool {

        // --- Phase B.6: turn identity captured at suspend time so the resume
        //     entry (turnService.resumeTurn) can rebuild the TurnContext and
        //     verify the requesting user owns the suspended turn. ---
        private String turnId;
        private Long tenantId;
        private Long userId;
        private Long humanMemberId;
        private Long conversationId;
        private String agentCode;
        private String sessionId;            // legacy: kept for trace continuity, NOT used as key
        // GAP-295 resume path: channel session pid captured at suspend so
        // resumeTurn can re-attach the same ab_agent_channel_session_state row
        // (rather than leaving TurnContext.channelSessionId null on resume).
        private String channelSessionPid;

        // --- Tool call info ---
        private String toolId;
        private String toolName;
        private Map<String, Object> input;
        private String description;
        private String modelCode;
        private String toolSpanId;  // for trace: span ID of the pending tool
        // Phase B.6 + main: agentCode lives in the identity tuple above.
        // The fields below were added on main for tool-loop continuation.
        private String runPid;
        private String taskPid;
        private List<AgentToolDefinition> agentToolDefinitions;

        // --- Conversation context needed to resume LLM after confirmation ---
        private List<Map<String, Object>> messages;
        private String providerCode;
        private String apiKey;
        private String baseUrl;
        private String model;
        private String systemPrompt;
        private Integer maxTokens;
        private int currentLoop;

        // --- Metadata ---
        @Builder.Default
        private long createdAt = Instant.now().toEpochMilli();

        // Provider-specific resume payload. AuraBot Skill SPI stores
        // _aurabot_skill / previewToken / preview / riskLevel so resume can
        // call ToolLoopService confirm instead of re-running preview dispatch.
        // Jackson serializes the map into JSON for Redis round-tripping; nested
        // values must be JSON-friendly. May be null when the suspended tool has
        // no extension contract.
        private Map<String, Object> extension;
    }

    private record StoredMessages(List<Map<String, Object>> messages, long createdAt) {
        StoredMessages(List<Map<String, Object>> messages) {
            this(messages, Instant.now().toEpochMilli());
        }
    }
}
