package com.auraboot.framework.aurabot.service;

import com.auraboot.framework.agent.runtime.ChatMessageTapeStore;
import com.auraboot.framework.agent.runtime.PendingToolStore;
import com.auraboot.framework.agent.runtime.PendingToolExecutionClaim;
import com.auraboot.framework.agent.runtime.PendingToolExecutionLedger;
import com.auraboot.framework.agent.runtime.PendingToolExecutionRecord;
import com.auraboot.framework.agent.runtime.PendingToolSnapshot;
import com.auraboot.framework.common.util.LogSanitizer;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.redis.core.script.DefaultRedisScript;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.util.Collections;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.TimeUnit;

/**
 * Store for pending tool confirmations in AuraBot chat sessions.
 *
 * <p>Uses Redis for persistence (survives server restarts). Uses an in-memory
 * store only when no RedisTemplate bean is configured; Redis operation failures
 * fail closed instead of silently moving pending confirmations to local state.
 *
 * <p>Phase B.6 (2026-04-27) key migration: pending entries are now keyed by
 * the suspended turn's {@code turnId} (per-turn PID generated by
 * {@code TurnContext}) rather than the legacy sessionId — per design v3.3
 * §3.10 step 4. Reasons:
 * <ul>
 *     <li>A session can suspend multiple turns sequentially; sessionId+toolId
 *         conflicts when the same toolId reappears across turns.</li>
 *     <li>{@code resumeTurn(pendingTurnId)} is now the canonical resume entry —
 *         the SSE {@code confirm_required} event already carries turnId so the
 *         frontend echoes it back in {@code POST /execute}.</li>
 *     <li>{@link PendingToolSnapshot} carries the full identity tuple
 *         (tenantId / userId / humanMemberId / conversationId / agentCode) so
 *         the resume path can rebuild a {@link com.auraboot.framework.conversation.TurnContext}
 *         and validate that the user requesting resume actually owns the
 *         suspended turn.</li>
 * </ul>
 *
 * <p>Key pattern: {@code aurabot:pending:{turnId}}. New pending snapshots carry
 * their own expiration timestamp; legacy snapshots fall back to a 10-minute TTL.
 */
@Slf4j
@Component
public class ChatSessionStore implements PendingToolStore, ChatMessageTapeStore {

    private static final String PENDING_KEY_PREFIX = "aurabot:pending:";
    private static final String EXECUTION_KEY_PREFIX = "aurabot:pending-execution:";
    private static final String MESSAGES_KEY_PREFIX = "aurabot:messages:";
    private static final long PENDING_TTL_MINUTES = 10;
    private static final long EXECUTION_TTL_MINUTES = 60;
    private static final long MESSAGES_TTL_MINUTES = 60;
    private static final DefaultRedisScript<String> CONSUME_PENDING_FOR_OWNER_SCRIPT =
            new DefaultRedisScript<>("""
                    local value = redis.call('GET', KEYS[1])
                    if not value then
                      return nil
                    end
                    local function field_matches(raw, field, expected)
                      if expected == '' then
                        return true
                      end
                      local quoted = string.match(raw, '"' .. field .. '"%s*:%s*"([^"]*)"')
                      if quoted ~= nil then
                        return quoted == expected
                      end
                      local number = string.match(raw, '"' .. field .. '"%s*:%s*(-?%d+)')
                      if number ~= nil then
                        return number == expected
                      end
                      return false
                    end
                    local tenant = ARGV[1]
                    local user = ARGV[2]
                    if not field_matches(value, 'tenantId', tenant) then
                      return nil
                    end
                    if not field_matches(value, 'userId', user) then
                      return nil
                    end
                    redis.call('DEL', KEYS[1])
                    return value
                    """, String.class);

    // Local-mode in-memory store (used only when no RedisTemplate bean is configured)
    private static final long IN_MEMORY_TTL_MILLIS = PENDING_TTL_MINUTES * 60 * 1000L;
    private final ConcurrentHashMap<String, PendingToolSnapshot> inMemoryFallback = new ConcurrentHashMap<>();
    private final ConcurrentHashMap<String, PendingToolExecutionRecord> inMemoryExecutionRecords = new ConcurrentHashMap<>();
    private final ConcurrentHashMap<String, StoredMessages> inMemoryMessagesFallback = new ConcurrentHashMap<>();

    private final ObjectMapper objectMapper;
    private final StringRedisTemplate redisTemplate;
    private final PendingToolExecutionLedger executionLedger;
    private final boolean redisAvailable;

    @Autowired
    public ChatSessionStore(ObjectMapper objectMapper,
                            @Autowired(required = false) StringRedisTemplate redisTemplate,
                            @Autowired(required = false) PendingToolExecutionLedger executionLedger) {
        this.objectMapper = objectMapper;
        this.redisTemplate = redisTemplate;
        this.executionLedger = executionLedger;
        this.redisAvailable = redisTemplate != null;
        if (!redisAvailable) {
            log.warn("RedisTemplate not configured - ChatSessionStore using in-memory local storage");
        }
    }

    ChatSessionStore(ObjectMapper objectMapper, StringRedisTemplate redisTemplate) {
        this(objectMapper, redisTemplate, null);
    }

    /**
     * Phase B.6: store a pending tool keyed solely by the suspended turn's
     * {@code turnId}. The chat-impl tool loop breaks out of the inner for-loop
     * the moment a write tool is queued for confirmation, so at any given time
     * there is at most one pending entry per turn — the toolId is part of the
     * stored {@link PendingToolSnapshot} payload, not the key.
     */
    @Override
    public void storePending(String turnId, PendingToolSnapshot pendingTool) {
        if (redisAvailable) {
            try {
                String key = pendingKey(turnId);
                String json = objectMapper.writeValueAsString(pendingTool);
                PendingTtl ttl = resolvePendingTtl(pendingTool);
                redisTemplate.opsForValue().set(key, json, ttl.value(), ttl.unit());
                log.debug("Stored pending tool [{}] for turn [{}] in Redis (TTL={} {})",
                        LogSanitizer.safe(pendingTool.getToolId()), LogSanitizer.safe(turnId),
                        ttl.value(), ttl.unit());
                return;
            } catch (JsonProcessingException e) {
                throw pendingStoreUnavailable("serialize pending tool", e);
            } catch (Exception e) {
                throw pendingStoreUnavailable("write pending tool to Redis", e);
            }
        }
        // Local mode: in-memory keyed by turnId
        if (isExpired(pendingTool)) {
            log.debug("Skipping already expired pending tool for turn [{}]", LogSanitizer.safe(turnId));
            return;
        }
        inMemoryFallback.put(turnId, pendingTool);
        log.debug("Stored pending tool [{}] for turn [{}] in memory",
                LogSanitizer.safe(pendingTool.getToolId()), LogSanitizer.safe(turnId));
    }

    /**
     * Consume a pending confirmation only when the stored owner identity matches
     * the caller. A mismatch leaves the pending payload intact so a bad resume
     * attempt cannot destroy another user's confirmation token.
     */
    @Override
    public PendingToolSnapshot consumePendingForOwner(String turnId, Long tenantId, Long userId) {
        if (redisAvailable) {
            try {
                String key = pendingKey(turnId);
                String json = redisTemplate.execute(
                        CONSUME_PENDING_FOR_OWNER_SCRIPT,
                        Collections.singletonList(key),
                        tenantId != null ? String.valueOf(tenantId) : "",
                        userId != null ? String.valueOf(userId) : "");
                if (json == null) {
                    log.debug("No owned pending tool for turn [{}] (not found, expired, or owner mismatch)",
                            LogSanitizer.safe(turnId));
                    return null;
                }
                PendingToolSnapshot tool = objectMapper.readValue(json, PendingToolSnapshot.class);
                if (isExpired(tool)) {
                    log.debug("Pending tool for turn [{}] has expired after Redis consume",
                            LogSanitizer.safe(turnId));
                    return null;
                }
                log.debug("Consumed owned pending tool [{}] for turn [{}] via Redis",
                        LogSanitizer.safe(tool.getToolId()), LogSanitizer.safe(turnId));
                return tool;
            } catch (JsonProcessingException e) {
                throw pendingStoreUnavailable("deserialize pending tool from Redis", e);
            } catch (Exception e) {
                throw pendingStoreUnavailable("read owned pending tool from Redis", e);
            }
        }

        PendingToolSnapshot tool = inMemoryFallback.get(turnId);
        if (tool == null) {
            return null;
        }
        if (isExpired(tool)) {
            inMemoryFallback.remove(turnId, tool);
            log.debug("Pending tool for turn [{}] has expired (in-memory)", LogSanitizer.safe(turnId));
            return null;
        }
        if (!ownerMatches(tool, tenantId, userId)) {
            log.warn("Pending tool owner mismatch for turn [{}]; refusing to consume", LogSanitizer.safe(turnId));
            return null;
        }
        return inMemoryFallback.remove(turnId, tool) ? tool : null;
    }

    @Override
    public PendingToolExecutionClaim claimExecution(PendingToolSnapshot pendingTool) {
        if (executionLedger != null) {
            return executionLedger.claim(pendingTool);
        }
        String executionKey = PendingToolStore.executionKey(pendingTool);
        PendingToolExecutionRecord running = PendingToolExecutionRecord.running(executionKey);
        if (redisAvailable) {
            try {
                String key = executionKey(executionKey);
                String json = objectMapper.writeValueAsString(running);
                Boolean claimed = redisTemplate.opsForValue()
                        .setIfAbsent(key, json, EXECUTION_TTL_MINUTES, TimeUnit.MINUTES);
                if (Boolean.TRUE.equals(claimed)) {
                    return PendingToolExecutionClaim.acquired(executionKey);
                }
                String existing = redisTemplate.opsForValue().get(key);
                if (existing == null || existing.isBlank()) {
                    return PendingToolExecutionClaim.acquired(executionKey);
                }
                return PendingToolExecutionClaim.replay(
                        objectMapper.readValue(existing, PendingToolExecutionRecord.class));
            } catch (JsonProcessingException e) {
                // CATCH: non-transactional Redis boundary; fail closed when execution record serialization is unsafe.
                throw pendingStoreUnavailable("serialize pending tool execution record", e);
            } catch (Exception e) {
                // CATCH: non-transactional Redis boundary; fail closed instead of risking duplicate side effects.
                throw pendingStoreUnavailable("claim pending tool execution record in Redis", e);
            }
        }

        PendingToolExecutionRecord existing = inMemoryExecutionRecords.putIfAbsent(executionKey, running);
        if (existing == null) {
            return PendingToolExecutionClaim.acquired(executionKey);
        }
        return PendingToolExecutionClaim.replay(existing);
    }

    @Override
    public void completeExecution(String executionKey, Map<String, Object> result) {
        storeExecutionRecord(PendingToolExecutionRecord.succeeded(executionKey, result));
    }

    @Override
    public void completeExecution(PendingToolSnapshot pendingTool, String executionKey, Map<String, Object> result) {
        if (executionLedger != null) {
            executionLedger.complete(pendingTool, executionKey, result);
            return;
        }
        completeExecution(executionKey, result);
    }

    @Override
    public void failExecution(String executionKey, Map<String, Object> result, String errorMessage) {
        storeExecutionRecord(PendingToolExecutionRecord.failed(executionKey, result, errorMessage));
    }

    @Override
    public void failExecution(PendingToolSnapshot pendingTool,
                              String executionKey,
                              Map<String, Object> result,
                              String errorMessage) {
        if (executionLedger != null) {
            executionLedger.fail(pendingTool, executionKey, result, errorMessage);
            return;
        }
        failExecution(executionKey, result, errorMessage);
    }

    /**
     * Phase B.6: pending key uses turnId only (one pending per turn at a time —
     * the chat-impl tool loop breaks the moment one tool is queued for confirm).
     */
    private String pendingKey(String turnId) {
        return PENDING_KEY_PREFIX + turnId;
    }

    private String executionKey(String executionKey) {
        return EXECUTION_KEY_PREFIX + executionKey;
    }

    private void storeExecutionRecord(PendingToolExecutionRecord record) {
        if (record == null || record.executionKey() == null || record.executionKey().isBlank()) {
            return;
        }
        if (redisAvailable) {
            try {
                redisTemplate.opsForValue().set(
                        executionKey(record.executionKey()),
                        objectMapper.writeValueAsString(record),
                        EXECUTION_TTL_MINUTES,
                        TimeUnit.MINUTES);
                return;
            } catch (JsonProcessingException e) {
                // CATCH: non-transactional Redis boundary; fail closed when execution record serialization is unsafe.
                throw pendingStoreUnavailable("serialize pending tool execution record", e);
            } catch (Exception e) {
                // CATCH: non-transactional Redis boundary; fail closed so callers do not overclaim exactly-once persistence.
                throw pendingStoreUnavailable("write pending tool execution record to Redis", e);
            }
        }
        inMemoryExecutionRecords.put(record.executionKey(), record);
    }

    private PendingTtl resolvePendingTtl(PendingToolSnapshot pendingTool) {
        if (pendingTool != null && pendingTool.getExpiresAt() != null) {
            long ttlMillis = pendingTool.getExpiresAt() - Instant.now().toEpochMilli();
            return new PendingTtl(Math.max(1L, ttlMillis), TimeUnit.MILLISECONDS);
        }
        return new PendingTtl(PENDING_TTL_MINUTES, TimeUnit.MINUTES);
    }

    private static boolean isExpired(PendingToolSnapshot tool) {
        if (tool == null) {
            return true;
        }
        long now = Instant.now().toEpochMilli();
        if (tool.getExpiresAt() != null) {
            return tool.getExpiresAt() <= now;
        }
        return now - tool.getCreatedAt() > IN_MEMORY_TTL_MILLIS;
    }

    private record PendingTtl(long value, TimeUnit unit) {
    }

    private static boolean ownerMatches(PendingToolSnapshot tool, Long tenantId, Long userId) {
        if (tenantId != null && !tenantId.equals(tool.getTenantId())) {
            return false;
        }
        return userId == null || userId.equals(tool.getUserId());
    }

    /**
     * Store structured LLM messages for the chat session.
     * This preserves assistant tool_use and user tool_result blocks across HTTP turns.
     * Independent from pending-tool storage — uses the {@code aurabot:messages:}
     * key prefix and a longer TTL so message history is retrievable across the
     * tool-loop continuation cycle introduced on main.
     */
    @Override
    public void storeConversationMessages(String sessionId, List<Map<String, Object>> messages) {
        if (sessionId == null || sessionId.isBlank() || messages == null) {
            return;
        }
        if (redisAvailable) {
            try {
                String json = objectMapper.writeValueAsString(messages);
                redisTemplate.opsForValue().set(messagesKey(sessionId), json, MESSAGES_TTL_MINUTES, TimeUnit.MINUTES);
                log.debug("Stored {} conversation messages for session [{}] in Redis (TTL={}min)",
                        messages.size(), LogSanitizer.safe(sessionId), MESSAGES_TTL_MINUTES);
                return;
            } catch (JsonProcessingException e) {
                throw messageTapeUnavailable("serialize conversation messages", e);
            } catch (Exception e) {
                throw messageTapeUnavailable("write conversation messages to Redis", e);
            }
        }
        inMemoryMessagesFallback.put(sessionId, new StoredMessages(messages));
        log.debug("Stored {} conversation messages for session [{}] in memory",
                messages.size(), LogSanitizer.safe(sessionId));
    }

    /**
     * Load structured LLM messages for a chat session.
     */
    @Override
    public List<Map<String, Object>> loadConversationMessages(String sessionId) {
        if (sessionId == null || sessionId.isBlank()) {
            return List.of();
        }
        if (redisAvailable) {
            try {
                String json = redisTemplate.opsForValue().get(messagesKey(sessionId));
                if (json == null || json.isBlank()) {
                    return List.of();
                }
                return objectMapper.readValue(json, new com.fasterxml.jackson.core.type.TypeReference<>() {});
            } catch (JsonProcessingException e) {
                throw messageTapeUnavailable("deserialize conversation messages from Redis", e);
            } catch (Exception e) {
                throw messageTapeUnavailable("read conversation messages from Redis", e);
            }
        }
        StoredMessages stored = inMemoryMessagesFallback.get(sessionId);
        if (stored == null) {
            return List.of();
        }
        if (Instant.now().toEpochMilli() - stored.createdAt() > MESSAGES_TTL_MINUTES * 60 * 1000L) {
            inMemoryMessagesFallback.remove(sessionId);
            return List.of();
        }
        return stored.messages();
    }

    private String messagesKey(String sessionId) {
        return MESSAGES_KEY_PREFIX + sessionId;
    }

    private IllegalStateException pendingStoreUnavailable(String operation, Exception cause) {
        log.error("Pending tool storage unavailable during {}", operation, cause);
        return new IllegalStateException("Pending tool storage unavailable: " + operation, cause);
    }

    private IllegalStateException messageTapeUnavailable(String operation, Exception cause) {
        log.error("Chat message tape storage unavailable during {}", operation, cause);
        return new IllegalStateException("Chat message tape storage unavailable: " + operation, cause);
    }

    private record StoredMessages(List<Map<String, Object>> messages, long createdAt) {
        StoredMessages(List<Map<String, Object>> messages) {
            this(messages, Instant.now().toEpochMilli());
        }
    }
}
