import { appendFile, copyFile, mkdtemp, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import {
  clearDeploymentBrandingCacheForTests,
  resolveDeploymentBranding,
} from '../branding.server';

const tempDirectories: string[] = [];
const licenseFixtureRoot = resolve(
  process.cwd(),
  '../platform/src/test/resources/branding/commercial-license',
);

function signedEnvironment(configPath: string) {
  return {
    EDITION: 'standard',
    AURABOOT_BRANDING_CONFIG_PATH: configPath,
    AURABOOT_WHITE_LABEL_ORDER_REFERENCE: 'SO-2026-001',
    AURABOOT_COMMERCIAL_LICENSE_ENFORCEMENT: 'offline-signature',
    AURABOOT_COMMERCIAL_LICENSE_PATH: join(licenseFixtureRoot, 'license.json'),
    AURABOOT_COMMERCIAL_LICENSE_SIGNATURE_PATH: join(licenseFixtureRoot, 'license.sig'),
    AURABOOT_COMMERCIAL_LICENSE_PUBLIC_KEY_PATH: join(licenseFixtureRoot, 'public.pem'),
    AURABOOT_COMMERCIAL_LICENSE_KEY_ID: 'test-commercial-2026-01',
    AURABOOT_COMMERCIAL_LICENSE_CUSTOMER: 'northstar',
    AURABOOT_VERSION: '1.0.0',
  };
}

async function writeBranding(overrides: Record<string, unknown> = {}): Promise<string> {
  const directory = await mkdtemp(join(tmpdir(), 'auraboot-branding-'));
  tempDirectories.push(directory);
  const configPath = join(directory, 'branding.json');
  await writeFile(
    configPath,
    JSON.stringify({
      schemaVersion: 1,
      orderReference: 'SO-2026-001',
      productName: 'Northstar',
      platformName: 'Northstar Operations Platform',
      logoUrl: '/customer-brand/logo.png',
      faviconUrl: '/customer-brand/favicon.ico',
      favicon32Url: '/customer-brand/favicon-32x32.png',
      appleTouchIconUrl: '/customer-brand/apple-touch-icon.png',
      manifestUrl: '/customer-brand/manifest.webmanifest',
      websiteUrl: 'https://northstar.example.com',
      docsUrl: 'https://northstar.example.com/docs',
      supportUrl: 'https://northstar.example.com/support',
      copyrightHolder: 'Northstar Holdings Ltd.',
      poweredByText: 'Powered by Northstar',
      generatedByText: 'Generated by Northstar Operations Platform',
      ...overrides,
    }),
  );
  return configPath;
}

afterEach(async () => {
  clearDeploymentBrandingCacheForTests();
  await Promise.all(
    tempDirectories.splice(0).map((directory) => rm(directory, { recursive: true })),
  );
});

describe('deployment branding server resolver', () => {
  it('loads an order-bound config for Standard', async () => {
    const configPath = await writeBranding();

    await expect(
      resolveDeploymentBranding({
        EDITION: 'standard',
        AURABOOT_BRANDING_CONFIG_PATH: configPath,
        AURABOOT_WHITE_LABEL_ORDER_REFERENCE: 'SO-2026-001',
      }),
    ).resolves.toMatchObject({ mode: 'commercial', productName: 'Northstar' });
  });

  it('ignores injected branding in Community edition', async () => {
    const configPath = await writeBranding();

    await expect(
      resolveDeploymentBranding({
        EDITION: 'community',
        AURABOOT_BRANDING_CONFIG_PATH: configPath,
        AURABOOT_WHITE_LABEL_ORDER_REFERENCE: 'SO-2026-001',
        AURABOOT_COMMERCIAL_LICENSE_ENFORCEMENT: 'offline-signature',
      }),
    ).resolves.toMatchObject({ mode: 'community', productName: 'AuraBoot' });
  });

  it('accepts the shared RS256 License fixture for Standard branding', async () => {
    const configPath = await writeBranding();

    await expect(resolveDeploymentBranding(signedEnvironment(configPath))).resolves.toMatchObject({
      mode: 'commercial',
      productName: 'Northstar',
    });
  });

  it('fails closed for signed License tampering and deployment mismatches', async () => {
    const configPath = await writeBranding();
    const directory = await mkdtemp(join(tmpdir(), 'auraboot-license-tampered-'));
    tempDirectories.push(directory);
    const tamperedLicense = join(directory, 'license.json');
    await copyFile(join(licenseFixtureRoot, 'license.json'), tamperedLicense);
    await appendFile(tamperedLicense, ' ');

    await expect(
      resolveDeploymentBranding({
        ...signedEnvironment(configPath),
        AURABOOT_COMMERCIAL_LICENSE_PATH: tamperedLicense,
      }),
    ).rejects.toThrow(/SHA-256 digest does not match/);
    await expect(
      resolveDeploymentBranding({
        ...signedEnvironment(configPath),
        AURABOOT_COMMERCIAL_LICENSE_CUSTOMER: 'other-customer',
      }),
    ).rejects.toThrow(/customer does not match/);
    await expect(
      resolveDeploymentBranding({
        ...signedEnvironment(configPath),
        AURABOOT_VERSION: '2.0.0',
      }),
    ).rejects.toThrow(/platformVersion does not match/);
  });

  it('rejects a valid signed License that excludes white-label rights', async () => {
    const configPath = await writeBranding();

    await expect(
      resolveDeploymentBranding({
        ...signedEnvironment(configPath),
        AURABOOT_COMMERCIAL_LICENSE_PATH: join(licenseFixtureRoot, 'license-no-white-label.json'),
        AURABOOT_COMMERCIAL_LICENSE_SIGNATURE_PATH: join(
          licenseFixtureRoot,
          'license-no-white-label.sig',
        ),
      }),
    ).rejects.toThrow(/does not grant required feature: white_label/);
  });

  it('rejects a License supplied through a symbolic link', async () => {
    const configPath = await writeBranding();
    const directory = await mkdtemp(join(tmpdir(), 'auraboot-license-symlink-'));
    tempDirectories.push(directory);
    const linkedLicense = join(directory, 'license.json');
    await symlink(join(licenseFixtureRoot, 'license.json'), linkedLicense);

    await expect(
      resolveDeploymentBranding({
        ...signedEnvironment(configPath),
        AURABOOT_COMMERCIAL_LICENSE_PATH: linkedLicense,
      }),
    ).rejects.toThrow(/Unable to read Commercial License/);
  });

  it('rejects unsupported commercial License enforcement modes', async () => {
    const configPath = await writeBranding();

    await expect(
      resolveDeploymentBranding({
        EDITION: 'standard',
        AURABOOT_BRANDING_CONFIG_PATH: configPath,
        AURABOOT_WHITE_LABEL_ORDER_REFERENCE: 'SO-2026-001',
        AURABOOT_COMMERCIAL_LICENSE_ENFORCEMENT: 'remote-server',
      }),
    ).rejects.toThrow(/Unsupported commercial License enforcement mode/);
  });

  it('fails closed when the order evidence is missing or mismatched', async () => {
    const configPath = await writeBranding();

    await expect(
      resolveDeploymentBranding({ EDITION: 'standard', AURABOOT_BRANDING_CONFIG_PATH: configPath }),
    ).rejects.toThrow(/ORDER_REFERENCE is required/);
    await expect(
      resolveDeploymentBranding({
        EDITION: 'standard',
        AURABOOT_BRANDING_CONFIG_PATH: configPath,
        AURABOOT_WHITE_LABEL_ORDER_REFERENCE: 'SO-OTHER',
      }),
    ).rejects.toThrow(/orderReference does not match/);
  });
});
