import { describe, expect, it } from 'vitest';
import {
  COMMUNITY_BRANDING,
  hasDeploymentLoginStory,
  isCommercialEdition,
  resolveBuildIdentity,
  resolveBrandDisplayName,
  resolveCommercialBranding,
  resolveCommunityBranding,
} from '../branding';

const commercialDocument = {
  schemaVersion: 1,
  orderReference: 'SO-2026-001',
  productName: 'Northstar',
  platformName: 'Northstar Operations Platform',
  logoUrl: '/customer-brand/logo.png',
  faviconUrl: '/customer-brand/favicon.ico',
  favicon32Url: '/customer-brand/favicon-32x32.png',
  appleTouchIconUrl: '/customer-brand/apple-touch-icon.png',
  manifestUrl: '/customer-brand/manifest.webmanifest',
  websiteUrl: 'https://northstar.example.com',
  docsUrl: 'https://northstar.example.com/docs',
  supportUrl: 'https://northstar.example.com/support',
  copyrightHolder: 'Northstar Holdings Ltd.',
  poweredByText: 'Powered by Northstar',
  generatedByText: 'Generated by Northstar Operations Platform',
} as const;

describe('community branding contract', () => {
  it('keeps the AuraBoot identity as the immutable community default', () => {
    const branding = resolveCommunityBranding();

    expect(branding).toEqual(COMMUNITY_BRANDING);
    expect(branding.productName).toBe('AuraBoot');
    expect(branding.mode).toBe('community');
    expect(branding.poweredByText).toBe('Powered by AuraBoot');
    expect(branding.generatedByText).toBe('Generated by AuraBoot Platform');
    expect(branding).not.toBe(COMMUNITY_BRANDING);
  });

  it('resolves an order-bound commercial identity while preserving AuraBoot legal fields', () => {
    const branding = resolveCommercialBranding(commercialDocument, 'SO-2026-001');

    expect(branding).toMatchObject({
      mode: 'commercial',
      productName: 'Northstar',
      manifestUrl: '/customer-brand/manifest.webmanifest',
      copyrightHolder: 'Northstar Holdings Ltd.',
      licenseName: COMMUNITY_BRANDING.licenseName,
      licenseUrl: COMMUNITY_BRANDING.licenseUrl,
      sourceUrl: COMMUNITY_BRANDING.sourceUrl,
      aurabootCopyrightHolder: COMMUNITY_BRANDING.aurabootCopyrightHolder,
    });
  });

  it('rejects a mismatched order, unsafe URL, or unsupported field', () => {
    expect(() => resolveCommercialBranding(commercialDocument, 'SO-OTHER')).toThrow(
      /orderReference does not match/,
    );
    expect(() =>
      resolveCommercialBranding(
        { ...commercialDocument, logoUrl: 'javascript:alert(1)' },
        'SO-2026-001',
      ),
    ).toThrow(/same-origin path or an HTTPS URL/);
    expect(() =>
      resolveCommercialBranding({ ...commercialDocument, hideLegalNotices: true }, 'SO-2026-001'),
    ).toThrow(/unsupported fields: hideLegalNotices/);
    expect(() =>
      resolveCommercialBranding(
        { ...commercialDocument, generatedByText: '由 Northstar 生成' },
        'SO-2026-001',
      ),
    ).toThrow(/printable ASCII/);
  });

  it('recognizes only explicit commercial editions', () => {
    expect(isCommercialEdition('standard')).toBe(true);
    expect(isCommercialEdition('Professional')).toBe(true);
    expect(isCommercialEdition('enterprise')).toBe(true);
    expect(isCommercialEdition('community')).toBe(false);
    expect(isCommercialEdition('oss')).toBe(false);
  });

  it('resolves the optional deployment login story fields', () => {
    const branding = resolveCommercialBranding(
      {
        ...commercialDocument,
        loginBadge: 'SMALL STEPS. WONDERFUL GROWTH.',
        loginHeadline: '今天的小小进步，',
        loginHeadlineEm: '长成明天的大树。',
        loginLead: '随手送出鼓励，让孩子拥有自己的成长伙伴。',
        loginHeroUrl: '/customer-brand/login-hero.png',
        loginFeatures: ['微信一键登录，无需短信验证码', '导入名单，一分钟建好班级'],
        loginWechatOnly: true,
      },
      'SO-2026-001',
    );

    expect(branding.loginHeadline).toBe('今天的小小进步，');
    expect(branding.loginFeatures).toHaveLength(2);
    expect(branding.loginWechatOnly).toBe(true);
  });

  it('resolves a deployment-owned school onboarding flow', () => {
    const branding = resolveCommercialBranding(
      {
        ...commercialDocument,
        tenantOnboarding: {
          entityLabel: '学校',
          industryCode: 'education',
          postCreateRedirect: '/xy/setup',
          selectionTitle: '选择你的开始方式',
          selectionLead: '创建学校，或使用学校教师码加入已有学校',
          createTitle: '创建学校',
          createDescription: '适合学校管理员，创建后自动获得学校管理权限。',
          createCta: '开始创建',
          joinTitle: '使用学校教师码加入学校',
          joinDescription: '适合班主任和任课老师，请前往微信小程序完成入校。',
          joinCta: '查看小程序入校步骤',
          joinChannel: 'wechat_mini',
          miniProgramName: '蜂耘',
          joinSteps: ['打开微信小程序并登录', '输入学校教师码加入学校', '绑定已有班级或创建新班级'],
        },
      },
      'SO-2026-001',
    );

    expect(branding.tenantOnboarding).toMatchObject({
      entityLabel: '学校',
      industryCode: 'education',
      postCreateRedirect: '/xy/setup',
      joinChannel: 'wechat_mini',
      miniProgramName: '蜂耘',
    });
    expect(branding.tenantOnboarding?.joinSteps).toHaveLength(3);
  });

  it('rejects incomplete or unsafe school onboarding documents', () => {
    const baseOnboarding = {
      entityLabel: '学校',
      selectionTitle: '选择你的开始方式',
      selectionLead: '选择一条路径继续',
      createTitle: '创建学校',
      createDescription: '学校管理员自助创建学校',
      createCta: '开始创建',
      joinTitle: '加入学校',
      joinDescription: '老师通过微信小程序加入学校',
      joinCta: '查看步骤',
      joinChannel: 'wechat_mini',
      joinSteps: ['打开微信小程序', '输入学校教师码'],
    } as const;

    expect(() =>
      resolveCommercialBranding(
        {
          ...commercialDocument,
          tenantOnboarding: { ...baseOnboarding, joinSteps: undefined },
        },
        'SO-2026-001',
      ),
    ).toThrow(/joinSteps is required/);

    expect(() =>
      resolveCommercialBranding(
        {
          ...commercialDocument,
          tenantOnboarding: { ...baseOnboarding, postCreateRedirect: 'https://evil.example' },
        },
        'SO-2026-001',
      ),
    ).toThrow(/same-origin path/);
    expect(() =>
      resolveCommercialBranding(
        {
          ...commercialDocument,
          tenantOnboarding: { ...baseOnboarding, hiddenAdminBypass: true },
        },
        'SO-2026-001',
      ),
    ).toThrow(/unsupported fields: hiddenAdminBypass/);
    expect(() =>
      resolveCommercialBranding(
        {
          ...commercialDocument,
          tenantOnboarding: {
            ...baseOnboarding,
            miniProgramQrUrl: 'javascript:alert(1)',
          },
        },
        'SO-2026-001',
      ),
    ).toThrow(/same-origin path or an HTTPS URL/);
  });

  it('treats any login story field as the deployment owning the brand panel', () => {
    const empty = {};
    expect(hasDeploymentLoginStory(empty)).toBe(false);

    for (const field of [
      'loginBadge',
      'loginHeadline',
      'loginLead',
      'loginHeroUrl',
      'loginWechatOnly',
    ] as const) {
      expect(hasDeploymentLoginStory({ [field]: 'x' })).toBe(true);
    }
    expect(hasDeploymentLoginStory({ loginFeatures: [] })).toBe(false);
    expect(hasDeploymentLoginStory({ loginFeatures: ['微信一键登录'] })).toBe(true);
  });

  it('keeps commercial identity ahead of the Community ICP display fallback', () => {
    const commercial = resolveCommercialBranding(commercialDocument, 'SO-2026-001');
    const compliance = { enabled: true, siteDisplayName: 'AuraBoot Filed Site' };

    expect(resolveBrandDisplayName(commercial, compliance)).toBe('Northstar');
    expect(resolveBrandDisplayName(COMMUNITY_BRANDING, compliance)).toBe('AuraBoot Filed Site');
  });

  it('resolves deployment build identity without accepting branding overrides', () => {
    expect(
      resolveBuildIdentity({
        AURABOOT_VERSION: ' 1.2.3 ',
        AURABOOT_GIT_SHA: ' abc123 ',
        AURABOOT_PRODUCT_NAME: 'Customer Brand',
      }),
    ).toEqual({ version: '1.2.3', revision: 'abc123' });
  });

  it('uses explicit development fallbacks when build metadata is absent', () => {
    expect(resolveBuildIdentity({})).toEqual({ version: 'development', revision: 'local' });
  });
});
