import { describe, expect, it } from 'vitest';
import {
  COMMUNITY_BRANDING,
  isCommercialEdition,
  resolveBuildIdentity,
  resolveBrandDisplayName,
  resolveCommercialBranding,
  resolveCommunityBranding,
} from '../branding';

const commercialDocument = {
  schemaVersion: 1,
  orderReference: 'SO-2026-001',
  productName: 'Northstar',
  platformName: 'Northstar Operations Platform',
  logoUrl: '/customer-brand/logo.png',
  faviconUrl: '/customer-brand/favicon.ico',
  favicon32Url: '/customer-brand/favicon-32x32.png',
  appleTouchIconUrl: '/customer-brand/apple-touch-icon.png',
  manifestUrl: '/customer-brand/manifest.webmanifest',
  websiteUrl: 'https://northstar.example.com',
  docsUrl: 'https://northstar.example.com/docs',
  supportUrl: 'https://northstar.example.com/support',
  copyrightHolder: 'Northstar Holdings Ltd.',
  poweredByText: 'Powered by Northstar',
  generatedByText: 'Generated by Northstar Operations Platform',
} as const;

describe('community branding contract', () => {
  it('keeps the AuraBoot identity as the immutable community default', () => {
    const branding = resolveCommunityBranding();

    expect(branding).toEqual(COMMUNITY_BRANDING);
    expect(branding.productName).toBe('AuraBoot');
    expect(branding.mode).toBe('community');
    expect(branding.poweredByText).toBe('Powered by AuraBoot');
    expect(branding.generatedByText).toBe('Generated by AuraBoot Platform');
    expect(branding).not.toBe(COMMUNITY_BRANDING);
  });

  it('resolves an order-bound commercial identity while preserving AuraBoot legal fields', () => {
    const branding = resolveCommercialBranding(commercialDocument, 'SO-2026-001');

    expect(branding).toMatchObject({
      mode: 'commercial',
      productName: 'Northstar',
      manifestUrl: '/customer-brand/manifest.webmanifest',
      copyrightHolder: 'Northstar Holdings Ltd.',
      licenseName: COMMUNITY_BRANDING.licenseName,
      licenseUrl: COMMUNITY_BRANDING.licenseUrl,
      sourceUrl: COMMUNITY_BRANDING.sourceUrl,
      aurabootCopyrightHolder: COMMUNITY_BRANDING.aurabootCopyrightHolder,
    });
  });

  it('rejects a mismatched order, unsafe URL, or unsupported field', () => {
    expect(() => resolveCommercialBranding(commercialDocument, 'SO-OTHER')).toThrow(
      /orderReference does not match/,
    );
    expect(() =>
      resolveCommercialBranding(
        { ...commercialDocument, logoUrl: 'javascript:alert(1)' },
        'SO-2026-001',
      ),
    ).toThrow(/same-origin path or an HTTPS URL/);
    expect(() =>
      resolveCommercialBranding({ ...commercialDocument, hideLegalNotices: true }, 'SO-2026-001'),
    ).toThrow(/unsupported fields: hideLegalNotices/);
    expect(() =>
      resolveCommercialBranding(
        { ...commercialDocument, generatedByText: '由 Northstar 生成' },
        'SO-2026-001',
      ),
    ).toThrow(/printable ASCII/);
  });

  it('recognizes only explicit commercial editions', () => {
    expect(isCommercialEdition('standard')).toBe(true);
    expect(isCommercialEdition('Professional')).toBe(true);
    expect(isCommercialEdition('enterprise')).toBe(true);
    expect(isCommercialEdition('community')).toBe(false);
    expect(isCommercialEdition('oss')).toBe(false);
  });

  it('keeps commercial identity ahead of the Community ICP display fallback', () => {
    const commercial = resolveCommercialBranding(commercialDocument, 'SO-2026-001');
    const compliance = { enabled: true, siteDisplayName: 'AuraBoot Filed Site' };

    expect(resolveBrandDisplayName(commercial, compliance)).toBe('Northstar');
    expect(resolveBrandDisplayName(COMMUNITY_BRANDING, compliance)).toBe('AuraBoot Filed Site');
  });

  it('resolves deployment build identity without accepting branding overrides', () => {
    expect(
      resolveBuildIdentity({
        AURABOOT_VERSION: ' 1.2.3 ',
        AURABOOT_GIT_SHA: ' abc123 ',
        AURABOOT_PRODUCT_NAME: 'Customer Brand',
      }),
    ).toEqual({ version: '1.2.3', revision: 'abc123' });
  });

  it('uses explicit development fallbacks when build metadata is absent', () => {
    expect(resolveBuildIdentity({})).toEqual({ version: 'development', revision: 'local' });
  });
});
