import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import {
  clearDeploymentBrandingCacheForTests,
  resolveDeploymentBranding,
} from '../branding.server';

const tempDirectories: string[] = [];

async function writeBranding(overrides: Record<string, unknown> = {}): Promise<string> {
  const directory = await mkdtemp(join(tmpdir(), 'auraboot-branding-'));
  tempDirectories.push(directory);
  const configPath = join(directory, 'branding.json');
  await writeFile(
    configPath,
    JSON.stringify({
      schemaVersion: 1,
      orderReference: 'SO-2026-001',
      productName: 'Northstar',
      platformName: 'Northstar Operations Platform',
      logoUrl: '/customer-brand/logo.png',
      faviconUrl: '/customer-brand/favicon.ico',
      favicon32Url: '/customer-brand/favicon-32x32.png',
      appleTouchIconUrl: '/customer-brand/apple-touch-icon.png',
      manifestUrl: '/customer-brand/manifest.webmanifest',
      websiteUrl: 'https://northstar.example.com',
      docsUrl: 'https://northstar.example.com/docs',
      supportUrl: 'https://northstar.example.com/support',
      copyrightHolder: 'Northstar Holdings Ltd.',
      poweredByText: 'Powered by Northstar',
      generatedByText: 'Generated by Northstar Operations Platform',
      ...overrides,
    }),
  );
  return configPath;
}

afterEach(async () => {
  clearDeploymentBrandingCacheForTests();
  await Promise.all(
    tempDirectories.splice(0).map((directory) => rm(directory, { recursive: true })),
  );
});

describe('deployment branding server resolver', () => {
  it('loads an order-bound config for Standard', async () => {
    const configPath = await writeBranding();

    await expect(
      resolveDeploymentBranding({
        EDITION: 'standard',
        AURABOOT_BRANDING_CONFIG_PATH: configPath,
        AURABOOT_WHITE_LABEL_ORDER_REFERENCE: 'SO-2026-001',
      }),
    ).resolves.toMatchObject({ mode: 'commercial', productName: 'Northstar' });
  });

  it('ignores injected branding in Community edition', async () => {
    const configPath = await writeBranding();

    await expect(
      resolveDeploymentBranding({
        EDITION: 'community',
        AURABOOT_BRANDING_CONFIG_PATH: configPath,
        AURABOOT_WHITE_LABEL_ORDER_REFERENCE: 'SO-2026-001',
      }),
    ).resolves.toMatchObject({ mode: 'community', productName: 'AuraBoot' });
  });

  it('fails closed when the order evidence is missing or mismatched', async () => {
    const configPath = await writeBranding();

    await expect(
      resolveDeploymentBranding({ EDITION: 'standard', AURABOOT_BRANDING_CONFIG_PATH: configPath }),
    ).rejects.toThrow(/ORDER_REFERENCE is required/);
    await expect(
      resolveDeploymentBranding({
        EDITION: 'standard',
        AURABOOT_BRANDING_CONFIG_PATH: configPath,
        AURABOOT_WHITE_LABEL_ORDER_REFERENCE: 'SO-OTHER',
      }),
    ).rejects.toThrow(/orderReference does not match/);
  });
});
