import { describe, expect, it } from 'vitest';
import { COMMUNITY_BRANDING, resolveBuildIdentity, resolveCommunityBranding } from '../branding';

describe('community branding contract', () => {
  it('keeps the AuraBoot identity as the immutable community default', () => {
    const branding = resolveCommunityBranding();

    expect(branding).toEqual(COMMUNITY_BRANDING);
    expect(branding.productName).toBe('AuraBoot');
    expect(branding.poweredByText).toBe('Powered by AuraBoot');
    expect(branding.generatedByText).toBe('Generated by AuraBoot Platform');
    expect(branding).not.toBe(COMMUNITY_BRANDING);
  });

  it('resolves deployment build identity without accepting branding overrides', () => {
    expect(
      resolveBuildIdentity({
        AURABOOT_VERSION: ' 1.2.3 ',
        AURABOOT_GIT_SHA: ' abc123 ',
        AURABOOT_PRODUCT_NAME: 'Customer Brand',
      }),
    ).toEqual({ version: '1.2.3', revision: 'abc123' });
  });

  it('uses explicit development fallbacks when build metadata is absent', () => {
    expect(resolveBuildIdentity({})).toEqual({ version: 'development', revision: 'local' });
  });
});
