package com.auraboot.framework.plugin.extension;

import java.io.InputStream;

/**
 * Host-provided file byte bridge for plugin command handlers.
 *
 * <p>Plugins receive this accessor through
 * {@link CommandHandlerExtension.CommandContext#fileAccessor()}. It keeps
 * platform storage details inside the host while allowing plugins to read
 * uploaded files and persist generated files by platform file id.</p>
 */
public interface FileAccessor {

    /** Well-known key for FileAccessor in the command settings map. */
    String SETTINGS_KEY = "__fileAccessor";

    /**
     * Open a platform file by its public file id.
     *
     * @param fileId platform file pid/id returned by the upload API
     * @return readable file stream; caller must close it
     */
    InputStream open(String fileId);

    /**
     * Describe a tenant-visible file by its stable public pid.
     *
     * <p>The default keeps older host implementations binary-compatible while
     * allowing security-sensitive handlers to fail closed when metadata is not
     * available. Implementations must not accept storage keys or internal
     * numeric ids through this method.</p>
     *
     * @param fileId stable public file pid returned by the upload API
     * @return tenant-scoped metadata, or {@code null} when the host does not
     *         implement the metadata capability
     */
    default FileMetadata describe(String fileId) {
        return null;
    }

    /**
     * Whether a tenant-visible public file pid is linked to a business object
     * field through the platform file-relation registry.
     *
     * <p>The conservative default is {@code false}; callers must never infer a
     * relationship merely because {@link #open(String)} succeeds.</p>
     */
    default boolean isLinkedTo(String fileId, String entityType, String entityId, String fieldName) {
        return false;
    }

    /**
     * Apply a monotonic retention lock to released/auditable file bytes.
     *
     * <p>The conservative default keeps older hosts binary compatible while making
     * security-sensitive release handlers fail closed when retention is unavailable.</p>
     */
    default boolean retain(String fileId) {
        return false;
    }

    /**
     * Persist generated bytes as a platform file.
     *
     * @param originalName suggested download filename
     * @param contentType  MIME type
     * @param bytes        file content
     * @return saved platform file metadata
     */
    SavedFile save(String originalName, String contentType, byte[] bytes);

    /** Saved platform file metadata returned to plugin handlers. */
    record SavedFile(String fileId, String originalName, long size, String url) {
    }

    /** Tenant-scoped, storage-opaque metadata for an existing platform file. */
    record FileMetadata(
            String fileId,
            String originalName,
            long size,
            String contentType,
            String ownerUserId,
            String status
    ) {
    }
}
