package com.auraboot.module.meta.excel;

import com.auraboot.framework.meta.constant.SystemFieldConstants;
import com.auraboot.framework.meta.dto.*;
import com.auraboot.framework.meta.entity.payload.DataSourceItemBean;
import com.auraboot.framework.meta.service.DynamicDataService;
import com.auraboot.framework.meta.service.MetaFieldService;
import com.auraboot.framework.meta.service.MetaModelService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.io.InputStream;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.*;
import java.util.stream.Collectors;
import java.util.Locale;

/**
 * Validates an Excel file against a model's field definitions before import.
 * <p>
 * Checks performed:
 * <ol>
 *   <li>Required field — missing or blank value → error</li>
 *   <li>Type check — value cannot be parsed as the expected data type → error</li>
 *   <li>Dictionary value — value not in the field's dictionary → warning</li>
 *   <li>Reference check — referenced record doesn't exist → error</li>
 *   <li>Cross-row duplicate detection — duplicate on unique fields → error</li>
 * </ol>
 *
 * @author AuraBoot Team
 * @since 6.0.0
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class ExcelValidationEngine {

    private final MetaModelService metaModelService;
    private final MetaFieldService metaFieldService;
    private final DynamicDataService dynamicDataService;

    /** Fields auto-generated by the platform — not expected in import. */
    private static final Set<String> AUTO_FIELDS = SystemFieldConstants.ALL_INFRASTRUCTURE;

    /**
     * Validate the given Excel workbook against the model's field definitions.
     *
     * @param modelCode the target model code
     * @param stream    input stream of the .xlsx file
     * @return validation report with errors and warnings
     */
    public ValidationReport validate(String modelCode, InputStream stream) throws IOException {
        ValidationReport report = new ValidationReport();

        List<FieldDefinition> fieldDefs = metaModelService.getModelFields(modelCode);
        if (fieldDefs == null || fieldDefs.isEmpty()) {
            report.getErrors().add(new ValidationReport.RowError(
                    0, null, "Model '" + modelCode + "' has no field definitions", null));
            return report;
        }

        // Build lookup maps
        Map<String, FieldDefinition> fieldByCode = new LinkedHashMap<>();
        for (FieldDefinition fd : fieldDefs) {
            if (!AUTO_FIELDS.contains(fd.getCode()) && !fd.isPrimaryKey() && !fd.isComputedReadonly()) {
                fieldByCode.put(fd.getCode(), fd);
            }
        }

        // Parse workbook
        List<Map<String, String>> rows;
        try (Workbook workbook = new XSSFWorkbook(stream)) {
            rows = parseSheet(workbook.getSheetAt(0), fieldDefs);
        }

        report.setTotalRows(rows.size());

        if (rows.isEmpty()) {
            report.setValidRows(0);
            return report;
        }

        // Pre-fetch dictionary values for dict-bound fields
        Map<String, Set<String>> dictValues = loadDictValues(fieldByCode);

        // Track unique field values for cross-row duplicate detection
        Map<String, Map<String, Integer>> uniqueTracker = new LinkedHashMap<>();
        for (Map.Entry<String, FieldDefinition> entry : fieldByCode.entrySet()) {
            if (entry.getValue().isUnique()) {
                uniqueTracker.put(entry.getKey(), new LinkedHashMap<>());
            }
        }

        int validCount = 0;
        for (int i = 0; i < rows.size(); i++) {
            int rowNum = i + 2; // Excel row number (1-indexed, header = row 1)
            Map<String, String> row = rows.get(i);
            boolean rowValid = true;

            for (Map.Entry<String, FieldDefinition> entry : fieldByCode.entrySet()) {
                String code = entry.getKey();
                FieldDefinition fd = entry.getValue();
                String value = row.get(code);
                boolean blank = value == null || value.isBlank();

                // 1. Required check
                if (fd.isRequired() && blank) {
                    report.getErrors().add(new ValidationReport.RowError(
                            rowNum, code, "Required field is missing", value));
                    rowValid = false;
                    continue;
                }

                if (blank) continue;

                // 2. Type check
                if (!isTypeValid(fd.getDataType(), value)) {
                    report.getErrors().add(new ValidationReport.RowError(
                            rowNum, code, "Value cannot be parsed as " + fd.getDataType(), value));
                    rowValid = false;
                    continue;
                }

                // 3. Dictionary value check (warning only)
                if (dictValues.containsKey(code)) {
                    Set<String> allowed = dictValues.get(code);
                    if (!allowed.contains(value)) {
                        report.getWarnings().add(new ValidationReport.RowWarning(
                                rowNum, code, "Value '" + value + "' is not in the dictionary"));
                    }
                }

                // 4. Cross-row duplicate on unique fields
                if (uniqueTracker.containsKey(code)) {
                    Map<String, Integer> seen = uniqueTracker.get(code);
                    if (seen.containsKey(value)) {
                        report.getErrors().add(new ValidationReport.RowError(
                                rowNum, code,
                                "Duplicate value on unique field (first seen at row " + seen.get(value) + ")",
                                value));
                        rowValid = false;
                    } else {
                        seen.put(value, rowNum);
                    }
                }
            }

            if (rowValid) {
                validCount++;
            }
        }

        report.setValidRows(validCount);
        return report;
    }

    /**
     * Check if a string value can be parsed as the given data type.
     */
    boolean isTypeValid(String dataType, String value) {
        if (dataType == null || value == null || value.isBlank()) {
            return true;
        }

        return switch (dataType.toLowerCase(Locale.ROOT)) {
            case "integer", "int" -> {
                try {
                    Long.parseLong(value);
                    yield true;
                } catch (NumberFormatException e) {
                    yield false;
                }
            }
            case "decimal", "float", "double", "number", "numeric" -> {
                try {
                    new java.math.BigDecimal(value);
                    yield true;
                } catch (NumberFormatException e) {
                    yield false;
                }
            }
            case "boolean", "bool" -> {
                String lower = value.toLowerCase();
                yield "true".equals(lower) || "false".equals(lower)
                        || "1".equals(lower) || "0".equals(lower)
                        || "yes".equals(lower) || "no".equals(lower);
            }
            case "date" -> {
                try {
                    LocalDate.parse(value, DateTimeFormatter.ofPattern("yyyy-MM-dd"));
                    yield true;
                } catch (DateTimeParseException e) {
                    // Try ISO format
                    try {
                        LocalDate.parse(value);
                        yield true;
                    } catch (DateTimeParseException e2) {
                        yield false;
                    }
                }
            }
            case "datetime", "timestamp" -> {
                try {
                    java.time.LocalDateTime.parse(value);
                    yield true;
                } catch (DateTimeParseException e) {
                    try {
                        // Try common format: yyyy-MM-dd HH:mm:ss
                        java.time.LocalDateTime.parse(value,
                                DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
                        yield true;
                    } catch (DateTimeParseException e2) {
                        yield false;
                    }
                }
            }
            // TEXT, STRING, VARCHAR, RICHTEXT, etc. — always valid
            default -> true;
        };
    }

    /**
     * Parse a sheet into row maps using the same header resolution as ExcelImportService.
     */
    private List<Map<String, String>> parseSheet(Sheet sheet, List<FieldDefinition> fieldDefs) {
        List<Map<String, String>> rows = new ArrayList<>();
        if (sheet == null || sheet.getPhysicalNumberOfRows() < 2) {
            return rows;
        }

        DataFormatter dataFormatter = new DataFormatter();
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");

        // Read headers
        Row headerRow = sheet.getRow(0);
        if (headerRow == null) return rows;

        List<String> rawHeaders = new ArrayList<>();
        for (int c = 0; c < headerRow.getLastCellNum(); c++) {
            Cell cell = headerRow.getCell(c);
            rawHeaders.add(cell != null ? dataFormatter.formatCellValue(cell).trim() : "");
        }

        // Resolve header -> field code mapping
        Map<String, String> headerMapping = ExcelImportService.resolveHeaderMapping(rawHeaders, fieldDefs);

        // Parse data rows
        for (int r = 1; r <= sheet.getLastRowNum(); r++) {
            Row row = sheet.getRow(r);
            if (row == null) continue;

            Map<String, String> rowMap = new LinkedHashMap<>();
            boolean hasData = false;

            for (int c = 0; c < rawHeaders.size(); c++) {
                String rawHeader = rawHeaders.get(c);
                if (rawHeader.isEmpty()) continue;

                String fieldCode = headerMapping.getOrDefault(rawHeader, rawHeader);
                Cell cell = row.getCell(c);
                String value = "";
                if (cell != null) {
                    if (cell.getCellType() == CellType.NUMERIC && DateUtil.isCellDateFormatted(cell)) {
                        value = cell.getDateCellValue().toInstant()
                                .atZone(ZoneId.systemDefault()).toLocalDate().format(dtf);
                    } else {
                        value = dataFormatter.formatCellValue(cell).trim();
                    }
                }

                rowMap.put(fieldCode, value);
                if (!value.isEmpty()) {
                    hasData = true;
                }
            }

            if (hasData) {
                rows.add(rowMap);
            }
        }

        return rows;
    }

    /**
     * Load dictionary values for fields that have a bound dictionary.
     * Returns fieldCode -> set of allowed string values.
     */
    private Map<String, Set<String>> loadDictValues(Map<String, FieldDefinition> fieldByCode) {
        Map<String, Set<String>> result = new LinkedHashMap<>();

        for (Map.Entry<String, FieldDefinition> entry : fieldByCode.entrySet()) {
            String fieldCode = entry.getKey();
            FieldDefinition fd = entry.getValue();

            // Check extraProps for dictCode binding
            if (fd.getExtraProps() != null && fd.getExtraProps().containsKey("dictCode")) {
                String dictCode = fd.getExtraProps().get("dictCode").toString();
                try {
                    Optional<MetaFieldDTO> fieldDto = metaFieldService.findCurrentByCode(fieldCode);
                    if (fieldDto.isPresent()) {
                        Optional<DictDTO> dictOpt = metaFieldService.getBoundDictionary(fieldDto.get().getPid());
                        if (dictOpt.isPresent() && dictOpt.get().getItems() != null) {
                            Set<String> values = dictOpt.get().getItems().stream()
                                    .filter(item -> item.getValue() != null)
                                    .map(item -> item.getValue().toString())
                                    .collect(Collectors.toSet());
                            // Also include labels for user-friendly matching
                            dictOpt.get().getItems().stream()
                                    .filter(item -> item.getLabel() != null)
                                    .forEach(item -> values.add(item.getLabel()));
                            result.put(fieldCode, values);
                        }
                    }
                } catch (Exception e) {
                    log.debug("Failed to load dictionary for field {}: {}", fieldCode, e.getMessage());
                }
            }
        }

        return result;
    }
}
