/**
 * Smart组件配置定义
 * 包含所有Smart组件的详细配置信息
 */

import type { ComponentConfig } from '~/framework/meta/registry/components/ComponentConfig';
import { COMPONENT_RUNTIME_MANIFEST } from '~/framework/meta/registry/components/ComponentRuntimeManifest';

// 共享属性配置
export const SHARED_PROPERTIES = {
  // 标准宽度属性配置（12列网格系统）
  WIDTH_PROPERTY: {
    key: 'width',
    label: '宽度(Grid列数)',
    type: 'number' as const,
    group: 'basic' as const,
    min: 1,
    max: 12,
    description: '占用的网格列数，12列时自动占满整行',
  },

  // 标准高度属性配置
  HEIGHT_PROPERTY: {
    key: 'height',
    label: '高度',
    type: 'string' as const,
    group: 'basic' as const,
    description: '高度值，如: auto, 100px, 50vh',
  },

  // 基础布局属性组
  BASIC_LAYOUT_PROPERTIES: [
    {
      key: 'width',
      label: '宽度(Grid列数)',
      type: 'number' as const,
      group: 'basic' as const,
      min: 1,
      max: 12,
      description: '占用的网格列数，12列时自动占满整行',
    },
    {
      key: 'height',
      label: '高度',
      type: 'string' as const,
      group: 'basic' as const,
      description: '高度值，如: auto, 100px, 50vh',
    },
  ],

  // 外观属性组
  APPEARANCE_PROPERTIES: {
    BACKGROUND_COLOR: {
      key: 'backgroundColor',
      label: '背景色',
      type: 'color' as const,
      group: 'appearance' as const,
    },
    BORDER_RADIUS: {
      key: 'borderRadius',
      label: '圆角',
      type: 'number' as const,
      group: 'appearance' as const,
      min: 0,
      max: 50,
      description: '圆角大小(px)',
    },
    BORDER: {
      key: 'border',
      label: '边框',
      type: 'string' as const,
      group: 'appearance' as const,
      description: '边框样式，如: 1px solid #ccc',
    },
    BOX_SHADOW: {
      key: 'boxShadow',
      label: '阴影',
      type: 'string' as const,
      group: 'appearance' as const,
      description: '阴影效果，如: 0 2px 4px rgba(0,0,0,0.1)',
    },
  },

  // 间距属性组
  SPACING_PROPERTIES: {
    PADDING: {
      key: 'padding',
      label: '内边距',
      type: 'number' as const,
      group: 'spacing' as const,
      min: 0,
      max: 100,
      description: '内边距大小(px)',
    },
    MARGIN: {
      key: 'margin',
      label: '外边距',
      type: 'number' as const,
      group: 'spacing' as const,
      min: 0,
      max: 100,
      description: '外边距大小(px)',
    },
  },
};

export const FORM_COMPONENT_CONFIGS: ComponentConfig[] = [
  {
    type: 'input',
    name: '输入框',
    category: 'form',
    icon: '📝',
    description: '单行文本输入框，支持多种验证规则',
    defaultProps: {
      label: '输入框',
      placeholder: '请输入内容',
      required: false,
      size: 'medium',
      variant: 'default',
      disabled: false,
      maxLength: 255,
    },
    propertySchema: [
      { key: 'label', label: '标签', type: 'string', required: true, group: 'basic' },
      { key: 'name', label: '字段名', type: 'string', required: true, group: 'basic' },
      { key: 'placeholder', label: '占位符', type: 'string', group: 'basic' },
      { key: 'defaultValue', label: '默认值', type: 'string', group: 'basic' },
      { key: 'required', label: '必填', type: 'boolean', group: 'validation' },
      { key: 'disabled', label: '禁用', type: 'boolean', group: 'behavior' },
      { key: 'maxLength', label: '最大长度', type: 'number', group: 'validation', min: 1 },
      { key: 'minLength', label: '最小长度', type: 'number', group: 'validation', min: 0 },
      { key: 'pattern', label: '正则验证', type: 'string', group: 'validation' },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        options: [
          { label: '小', value: 'small' },
          { label: '中', value: 'medium' },
          { label: '大', value: 'large' },
        ],
        group: 'appearance',
      },
      {
        key: 'variant',
        label: '样式',
        type: 'select',
        options: [
          { label: '默认', value: 'default' },
          { label: '边框', value: 'outline' },
          { label: '填充', value: 'filled' },
        ],
        group: 'appearance',
      },
    ],
    tags: ['input', 'text', 'form', 'basic'],
  },
  {
    type: 'textarea',
    name: '多行文本',
    category: 'form',
    icon: '📄',
    description: '多行文本输入框，适用于长文本输入',
    defaultProps: {
      label: '多行文本',
      placeholder: '请输入内容',
      required: false,
      rows: 4,
      maxLength: 1000,
      resize: 'vertical',
    },
    propertySchema: [
      { key: 'label', label: '标签', type: 'string', required: true, group: 'basic' },
      { key: 'name', label: '字段名', type: 'string', required: true, group: 'basic' },
      { key: 'placeholder', label: '占位符', type: 'string', group: 'basic' },
      { key: 'defaultValue', label: '默认值', type: 'string', group: 'basic' },
      { key: 'required', label: '必填', type: 'boolean', group: 'validation' },
      { key: 'disabled', label: '禁用', type: 'boolean', group: 'behavior' },
      { key: 'rows', label: '行数', type: 'number', group: 'appearance', min: 2, max: 20 },
      { key: 'maxLength', label: '最大长度', type: 'number', group: 'validation', min: 1 },
      {
        key: 'resize',
        label: '调整大小',
        type: 'select',
        options: [
          { label: '垂直', value: 'vertical' },
          { label: '水平', value: 'horizontal' },
          { label: '双向', value: 'both' },
          { label: '禁用', value: 'none' },
        ],
        group: 'behavior',
      },
    ],
    tags: ['textarea', 'text', 'multiline', 'form'],
  },
  {
    type: 'select',
    name: '下拉选择',
    category: 'form',
    icon: '📋',
    description: '下拉选择框，支持单选和多选',
    defaultProps: {
      label: '下拉选择',
      placeholder: '请选择',
      required: false,
      multiple: false,
      clearable: true,
      searchable: false,
      options: [],
    },
    propertySchema: [
      { key: 'label', label: '标签', type: 'string', required: true, group: 'basic' },
      { key: 'name', label: '字段名', type: 'string', required: true, group: 'basic' },
      { key: 'placeholder', label: '占位符', type: 'string', group: 'basic' },
      { key: 'required', label: '必填', type: 'boolean', group: 'validation' },
      { key: 'disabled', label: '禁用', type: 'boolean', group: 'behavior' },
      { key: 'multiple', label: '多选', type: 'boolean', group: 'behavior' },
      { key: 'clearable', label: '可清空', type: 'boolean', group: 'behavior' },
      { key: 'searchable', label: '可搜索', type: 'boolean', group: 'behavior' },
      {
        key: 'options',
        label: '选项',
        type: 'array',
        group: 'basic',
        description: '格式: [{"label": "显示文本", "value": "值"}]',
      },
    ],
    tags: ['select', 'dropdown', 'options', 'form'],
  },
  {
    type: 'checkbox',
    name: '复选框',
    category: 'form',
    icon: '☑️',
    description: '复选框，支持单个或多个选项',
    defaultProps: {
      label: '复选框',
      required: false,
      disabled: false,
      checked: false,
      indeterminate: false,
    },
    propertySchema: [
      { key: 'label', label: '标签', type: 'string', required: true, group: 'basic' },
      { key: 'name', label: '字段名', type: 'string', required: true, group: 'basic' },
      { key: 'required', label: '必填', type: 'boolean', group: 'validation' },
      { key: 'disabled', label: '禁用', type: 'boolean', group: 'behavior' },
      { key: 'checked', label: '默认选中', type: 'boolean', group: 'basic' },
      { key: 'indeterminate', label: '半选状态', type: 'boolean', group: 'appearance' },
    ],
    tags: ['checkbox', 'check', 'boolean', 'form'],
  },
  {
    type: 'radio',
    name: '单选框',
    category: 'form',
    icon: '🔘',
    description: '单选框组，用于单选场景',
    defaultProps: {
      label: '单选框',
      required: false,
      disabled: false,
      options: [],
      direction: 'horizontal',
    },
    propertySchema: [
      { key: 'label', label: '标签', type: 'string', required: true, group: 'basic' },
      { key: 'name', label: '字段名', type: 'string', required: true, group: 'basic' },
      { key: 'required', label: '必填', type: 'boolean', group: 'validation' },
      { key: 'disabled', label: '禁用', type: 'boolean', group: 'behavior' },
      {
        key: 'direction',
        label: '排列方向',
        type: 'select',
        options: [
          { label: '水平', value: 'horizontal' },
          { label: '垂直', value: 'vertical' },
        ],
        group: 'appearance',
      },
      {
        key: 'options',
        label: '选项',
        type: 'array',
        group: 'basic',
        description: '格式: [{"label": "显示文本", "value": "值"}]',
      },
    ],
    tags: ['radio', 'single', 'options', 'form'],
  },
  {
    type: 'datepicker',
    name: '日期选择',
    category: 'form',
    icon: '📅',
    description: '日期选择器，支持多种日期格式',
    defaultProps: {
      label: '日期选择',
      placeholder: '请选择日期',
      required: false,
      format: 'YYYY-MM-DD',
      showTime: false,
      clearable: true,
    },
    propertySchema: [
      { key: 'label', label: '标签', type: 'string', required: true, group: 'basic' },
      { key: 'name', label: '字段名', type: 'string', required: true, group: 'basic' },
      { key: 'placeholder', label: '占位符', type: 'string', group: 'basic' },
      { key: 'required', label: '必填', type: 'boolean', group: 'validation' },
      { key: 'disabled', label: '禁用', type: 'boolean', group: 'behavior' },
      { key: 'showTime', label: '显示时间', type: 'boolean', group: 'behavior' },
      { key: 'clearable', label: '可清空', type: 'boolean', group: 'behavior' },
      {
        key: 'format',
        label: '日期格式',
        type: 'select',
        options: [
          { label: 'YYYY-MM-DD', value: 'YYYY-MM-DD' },
          { label: 'YYYY/MM/DD', value: 'YYYY/MM/DD' },
          { label: 'DD/MM/YYYY', value: 'DD/MM/YYYY' },
          { label: 'MM/DD/YYYY', value: 'MM/DD/YYYY' },
        ],
        group: 'appearance',
      },
    ],
    tags: ['date', 'picker', 'calendar', 'form'],
  },
  // 新增 FormRef 组件配置
  {
    type: 'formref',
    name: '表单引用',
    category: 'form',
    icon: '🔗',
    description: '引用独立的表单，支持嵌入、模态框等多种显示模式',
    defaultProps: {
      formRefId: '',
      mode: 'embedded',
      title: '',
      showTitle: true,
      showBorder: true,
      padding: 16,
      placeholder: '请选择表单',
    },
    propertySchema: [
      {
        key: 'formRefId',
        label: '表单ID',
        type: 'formref-select',
        required: true,
        group: 'basic',
        description: '选择要引用的表单',
      },
      {
        key: 'mode',
        label: '显示模式',
        type: 'select',
        options: [
          { label: '嵌入', value: 'embedded' },
          { label: '模态框', value: 'modal' },
          { label: '抽屉', value: 'drawer' },
          { label: '页面', value: 'page' },
        ],
        group: 'basic',
      },
      { key: 'title', label: '标题', type: 'string', group: 'basic' },
      { key: 'showTitle', label: '显示标题', type: 'boolean', group: 'appearance' },
      { key: 'showBorder', label: '显示边框', type: 'boolean', group: 'appearance' },
      { key: 'padding', label: '内边距', type: 'number', group: 'appearance', min: 0, max: 50 },
      {
        key: 'width',
        label: '宽度',
        type: 'string',
        group: 'appearance',
        description: '仅在模态框/抽屉模式下生效',
      },
      SHARED_PROPERTIES.HEIGHT_PROPERTY,
      {
        key: 'closable',
        label: '可关闭',
        type: 'boolean',
        group: 'behavior',
        description: '仅在模态框/抽屉模式下生效',
      },
      {
        key: 'maskClosable',
        label: '点击遮罩关闭',
        type: 'boolean',
        group: 'behavior',
        description: '仅在模态框/抽屉模式下生效',
      },
    ],
    tags: ['formref', 'reference', 'embed', 'modal'],
  },
  // T9.1: 时间选择器
  {
    type: 'timepicker',
    name: '时间选择',
    category: 'form',
    icon: '⏰',
    description: '时间选择器，支持小时、分钟、秒选择',
    defaultProps: {
      label: '时间选择',
      placeholder: '请选择时间',
      required: false,
      disabled: false,
      format: 'HH:mm',
      showSecond: false,
      use12Hours: false,
      clearable: true,
      hourStep: 1,
      minuteStep: 1,
      secondStep: 1,
    },
    propertySchema: [
      { key: 'label', label: '标签', type: 'string', required: true, group: 'basic' },
      { key: 'name', label: '字段名', type: 'string', required: true, group: 'basic' },
      { key: 'placeholder', label: '占位符', type: 'string', group: 'basic' },
      {
        key: 'defaultValue',
        label: '默认值',
        type: 'string',
        group: 'basic',
        description: '格式: HH:mm 或 HH:mm:ss',
      },
      { key: 'required', label: '必填', type: 'boolean', group: 'validation' },
      { key: 'disabled', label: '禁用', type: 'boolean', group: 'behavior' },
      { key: 'clearable', label: '可清空', type: 'boolean', group: 'behavior' },
      {
        key: 'format',
        label: '时间格式',
        type: 'select',
        options: [
          { label: 'HH:mm', value: 'HH:mm' },
          { label: 'HH:mm:ss', value: 'HH:mm:ss' },
          { label: 'hh:mm A', value: 'hh:mm A' },
          { label: 'hh:mm:ss A', value: 'hh:mm:ss A' },
        ],
        group: 'appearance',
      },
      { key: 'showSecond', label: '显示秒', type: 'boolean', group: 'appearance' },
      { key: 'use12Hours', label: '12小时制', type: 'boolean', group: 'appearance' },
      { key: 'hourStep', label: '小时步长', type: 'number', group: 'behavior', min: 1, max: 12 },
      { key: 'minuteStep', label: '分钟步长', type: 'number', group: 'behavior', min: 1, max: 30 },
      { key: 'secondStep', label: '秒步长', type: 'number', group: 'behavior', min: 1, max: 30 },
    ],
    tags: ['time', 'picker', 'clock', 'form'],
  },
  // T9.1: 开关组件
  {
    type: 'switch',
    name: '开关',
    category: 'form',
    icon: '🔘',
    description: '开关选择器，用于两种状态之间切换',
    defaultProps: {
      label: '开关',
      required: false,
      disabled: false,
      checked: false,
      size: 'default',
      checkedText: '',
      uncheckedText: '',
      loading: false,
    },
    propertySchema: [
      { key: 'label', label: '标签', type: 'string', required: true, group: 'basic' },
      { key: 'name', label: '字段名', type: 'string', required: true, group: 'basic' },
      { key: 'checked', label: '默认选中', type: 'boolean', group: 'basic' },
      { key: 'required', label: '必填', type: 'boolean', group: 'validation' },
      { key: 'disabled', label: '禁用', type: 'boolean', group: 'behavior' },
      { key: 'loading', label: '加载中', type: 'boolean', group: 'behavior' },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        options: [
          { label: '小', value: 'small' },
          { label: '默认', value: 'default' },
          { label: '大', value: 'large' },
        ],
        group: 'appearance',
      },
      {
        key: 'checkedText',
        label: '选中文本',
        type: 'string',
        group: 'appearance',
        description: '开关打开时显示的文本',
      },
      {
        key: 'uncheckedText',
        label: '未选中文本',
        type: 'string',
        group: 'appearance',
        description: '开关关闭时显示的文本',
      },
      {
        key: 'checkedValue',
        label: '选中值',
        type: 'string',
        group: 'basic',
        description: '选中状态的值，默认为 true',
      },
      {
        key: 'uncheckedValue',
        label: '未选中值',
        type: 'string',
        group: 'basic',
        description: '未选中状态的值，默认为 false',
      },
    ],
    tags: ['switch', 'toggle', 'boolean', 'form'],
  },
  // T9.1: 数字输入框
  {
    type: 'numberinput',
    name: '数字输入',
    category: 'form',
    icon: '🔢',
    description: '数字输入框，支持精度、范围、步进控制',
    defaultProps: {
      label: '数字输入',
      placeholder: '请输入数字',
      required: false,
      disabled: false,
      min: undefined,
      max: undefined,
      step: 1,
      precision: 0,
      showButtons: true,
      size: 'medium',
    },
    propertySchema: [
      { key: 'label', label: '标签', type: 'string', required: true, group: 'basic' },
      { key: 'name', label: '字段名', type: 'string', required: true, group: 'basic' },
      { key: 'placeholder', label: '占位符', type: 'string', group: 'basic' },
      { key: 'defaultValue', label: '默认值', type: 'number', group: 'basic' },
      { key: 'required', label: '必填', type: 'boolean', group: 'validation' },
      { key: 'disabled', label: '禁用', type: 'boolean', group: 'behavior' },
      { key: 'min', label: '最小值', type: 'number', group: 'validation' },
      { key: 'max', label: '最大值', type: 'number', group: 'validation' },
      { key: 'step', label: '步长', type: 'number', group: 'behavior', min: 0.001 },
      { key: 'precision', label: '小数位数', type: 'number', group: 'behavior', min: 0, max: 10 },
      { key: 'showButtons', label: '显示加减按钮', type: 'boolean', group: 'appearance' },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        options: [
          { label: '小', value: 'small' },
          { label: '中', value: 'medium' },
          { label: '大', value: 'large' },
        ],
        group: 'appearance',
      },
      {
        key: 'prefix',
        label: '前缀',
        type: 'string',
        group: 'appearance',
        description: '输入框前缀文本',
      },
      {
        key: 'suffix',
        label: '后缀',
        type: 'string',
        group: 'appearance',
        description: '输入框后缀文本，如单位',
      },
    ],
    tags: ['number', 'input', 'numeric', 'form'],
  },
  // T9.1: 文件上传
  {
    type: 'upload',
    name: '文件上传',
    category: 'form',
    icon: '📤',
    description: '文件上传组件，支持拖拽、多文件、图片预览',
    defaultProps: {
      label: '文件上传',
      required: false,
      disabled: false,
      multiple: false,
      maxCount: 1,
      maxSize: 10,
      accept: '',
      listType: 'text',
      draggable: false,
      showUploadList: true,
      action: '/api/upload',
    },
    propertySchema: [
      { key: 'label', label: '标签', type: 'string', required: true, group: 'basic' },
      { key: 'name', label: '字段名', type: 'string', required: true, group: 'basic' },
      { key: 'required', label: '必填', type: 'boolean', group: 'validation' },
      { key: 'disabled', label: '禁用', type: 'boolean', group: 'behavior' },
      {
        key: 'action',
        label: '上传地址',
        type: 'string',
        group: 'basic',
        description: '文件上传的服务端地址',
      },
      { key: 'multiple', label: '多文件', type: 'boolean', group: 'behavior' },
      {
        key: 'maxCount',
        label: '最大文件数',
        type: 'number',
        group: 'validation',
        min: 1,
        max: 100,
      },
      {
        key: 'maxSize',
        label: '最大文件大小(MB)',
        type: 'number',
        group: 'validation',
        min: 0.1,
        max: 1000,
      },
      {
        key: 'accept',
        label: '接受的文件类型',
        type: 'string',
        group: 'validation',
        description: '如: .jpg,.png,.pdf 或 image/*',
      },
      {
        key: 'listType',
        label: '列表类型',
        type: 'select',
        options: [
          { label: '文本', value: 'text' },
          { label: '图片', value: 'picture' },
          { label: '卡片', value: 'picture-card' },
        ],
        group: 'appearance',
      },
      { key: 'draggable', label: '支持拖拽', type: 'boolean', group: 'behavior' },
      { key: 'showUploadList', label: '显示文件列表', type: 'boolean', group: 'appearance' },
      {
        key: 'buttonText',
        label: '按钮文字',
        type: 'string',
        group: 'appearance',
        description: '上传按钮的文字',
      },
      {
        key: 'hint',
        label: '提示文字',
        type: 'string',
        group: 'appearance',
        description: '上传区域的提示文字',
      },
    ],
    tags: ['upload', 'file', 'attachment', 'form'],
  },
];

export const DISPLAY_COMPONENT_CONFIGS: ComponentConfig[] = [
  {
    type: 'display',
    name: '文本显示',
    category: 'display',
    icon: '📖',
    description: '用于显示文本内容',
    defaultProps: {
      text: '显示文本',
      size: 'medium',
      color: 'default',
      weight: 'normal',
      align: 'left',
    },
    propertySchema: [
      { key: 'text', label: '显示文本', type: 'string', required: true, group: 'basic' },
      {
        key: 'size',
        label: '字体大小',
        type: 'select',
        options: [
          { label: '小', value: 'small' },
          { label: '中', value: 'medium' },
          { label: '大', value: 'large' },
          { label: '特大', value: 'xlarge' },
        ],
        group: 'appearance',
      },
      {
        key: 'weight',
        label: '字体粗细',
        type: 'select',
        options: [
          { label: '正常', value: 'normal' },
          { label: '粗体', value: 'bold' },
          { label: '细体', value: 'light' },
        ],
        group: 'appearance',
      },
      {
        key: 'align',
        label: '对齐方式',
        type: 'select',
        options: [
          { label: '左对齐', value: 'left' },
          { label: '居中', value: 'center' },
          { label: '右对齐', value: 'right' },
        ],
        group: 'appearance',
      },
      { key: 'color', label: '文字颜色', type: 'color', group: 'appearance' },
    ],
    tags: ['text', 'display', 'content'],
  },
  {
    type: 'image',
    name: '图片',
    category: 'display',
    icon: '🖼️',
    description: '图片展示组件',
    defaultProps: {
      src: '',
      alt: '图片',
      width: 'auto',
      height: 'auto',
      fit: 'cover',
      lazy: true,
    },
    propertySchema: [
      { key: 'src', label: '图片地址', type: 'string', required: true, group: 'basic' },
      { key: 'alt', label: '替代文本', type: 'string', group: 'basic' },
      SHARED_PROPERTIES.WIDTH_PROPERTY,
      SHARED_PROPERTIES.HEIGHT_PROPERTY,
      {
        key: 'fit',
        label: '适应方式',
        type: 'select',
        options: [
          { label: '覆盖', value: 'cover' },
          { label: '包含', value: 'contain' },
          { label: '填充', value: 'fill' },
          { label: '缩放', value: 'scale-down' },
        ],
        group: 'appearance',
      },
      { key: 'lazy', label: '懒加载', type: 'boolean', group: 'behavior' },
    ],
    tags: ['image', 'picture', 'media', 'display'],
  },
  {
    type: 'table',
    name: '表格',
    category: 'display',
    icon: '📊',
    description: '数据表格展示组件',
    defaultProps: {
      columns: [],
      data: [],
      pagination: true,
      pageSize: 10,
      bordered: true,
      striped: false,
    },
    propertySchema: [
      { key: 'columns', label: '列配置', type: 'array', group: 'basic', description: '表格列配置' },
      { key: 'data', label: '数据源', type: 'array', group: 'basic', description: '表格数据' },
      { key: 'pagination', label: '分页', type: 'boolean', group: 'behavior' },
      { key: 'pageSize', label: '每页条数', type: 'number', group: 'behavior', min: 1, max: 100 },
      { key: 'bordered', label: '显示边框', type: 'boolean', group: 'appearance' },
      { key: 'striped', label: '斑马纹', type: 'boolean', group: 'appearance' },
    ],
    tags: ['table', 'data', 'grid', 'display'],
  },
];

export const INTERACTION_COMPONENT_CONFIGS: ComponentConfig[] = [
  {
    type: 'button',
    name: '按钮',
    category: 'interaction',
    icon: '🔘',
    description: '交互按钮组件',
    defaultProps: {
      text: '按钮',
      type: 'primary',
      size: 'medium',
      disabled: false,
      loading: false,
      block: false,
    },
    propertySchema: [
      { key: 'text', label: '按钮文字', type: 'string', required: true, group: 'basic' },
      {
        key: 'type',
        label: '按钮类型',
        type: 'select',
        options: [
          { label: '主要', value: 'primary' },
          { label: '次要', value: 'secondary' },
          { label: '成功', value: 'success' },
          { label: '警告', value: 'warning' },
          { label: '危险', value: 'danger' },
          { label: '链接', value: 'link' },
        ],
        group: 'appearance',
      },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        options: [
          { label: '小', value: 'small' },
          { label: '中', value: 'medium' },
          { label: '大', value: 'large' },
        ],
        group: 'appearance',
      },
      { key: 'disabled', label: '禁用', type: 'boolean', group: 'behavior' },
      { key: 'loading', label: '加载中', type: 'boolean', group: 'behavior' },
      { key: 'block', label: '块级按钮', type: 'boolean', group: 'appearance' },
    ],
    tags: ['button', 'click', 'action', 'interaction'],
  },
];

export const LAYOUT_COMPONENT_CONFIGS: ComponentConfig[] = [
  {
    type: 'div',
    name: 'Div容器',
    category: 'layout',
    icon: '📦',
    description: '通用div容器，支持属性面板编辑和自动grid占用',
    defaultProps: {
      width: 12,
      height: 'auto',
      padding: 16,
      margin: 0,
      backgroundColor: 'transparent',
      borderRadius: 0,
      border: 'none',
      boxShadow: 'none',
      display: 'block',
      position: 'static',
      zIndex: 'auto',
      overflow: 'visible',
    },
    propertySchema: [
      // 基础属性
      SHARED_PROPERTIES.WIDTH_PROPERTY,
      SHARED_PROPERTIES.HEIGHT_PROPERTY,

      // 外观属性
      SHARED_PROPERTIES.APPEARANCE_PROPERTIES.BACKGROUND_COLOR,
      SHARED_PROPERTIES.APPEARANCE_PROPERTIES.BORDER_RADIUS,
      SHARED_PROPERTIES.APPEARANCE_PROPERTIES.BORDER,
      SHARED_PROPERTIES.APPEARANCE_PROPERTIES.BOX_SHADOW,

      // 间距属性
      SHARED_PROPERTIES.SPACING_PROPERTIES.PADDING,
      SHARED_PROPERTIES.SPACING_PROPERTIES.MARGIN,

      // 布局属性
      {
        key: 'display',
        label: '显示方式',
        type: 'select',
        options: [
          { label: '块级', value: 'block' },
          { label: '内联块', value: 'inline-block' },
          { label: '弹性盒', value: 'flex' },
          { label: '网格', value: 'grid' },
          { label: '隐藏', value: 'none' },
        ],
        group: 'layout',
      },
      {
        key: 'position',
        label: '定位方式',
        type: 'select',
        options: [
          { label: '静态', value: 'static' },
          { label: '相对', value: 'relative' },
          { label: '绝对', value: 'absolute' },
          { label: '固定', value: 'fixed' },
          { label: '粘性', value: 'sticky' },
        ],
        group: 'layout',
      },
      {
        key: 'zIndex',
        label: '层级',
        type: 'string',
        group: 'layout',
        description: '元素层级，如: auto, 1, 10',
      },
      {
        key: 'overflow',
        label: '溢出处理',
        type: 'select',
        options: [
          { label: '可见', value: 'visible' },
          { label: '隐藏', value: 'hidden' },
          { label: '滚动', value: 'scroll' },
          { label: '自动', value: 'auto' },
        ],
        group: 'layout',
      },
    ],
    tags: ['div', 'container', 'layout', 'basic', 'grid'],
  },
  {
    type: 'form',
    name: '表单容器',
    category: 'layout',
    icon: '📋',
    description: '表单布局容器',
    defaultProps: {
      title: '表单',
      layout: 'vertical',
      labelWidth: 'auto',
      size: 'medium',
      bordered: false,
    },
    propertySchema: [
      { key: 'title', label: '表单标题', type: 'string', group: 'basic' },
      {
        key: 'layout',
        label: '布局方式',
        type: 'select',
        options: [
          { label: '垂直', value: 'vertical' },
          { label: '水平', value: 'horizontal' },
          { label: '内联', value: 'inline' },
        ],
        group: 'appearance',
      },
      { key: 'labelWidth', label: '标签宽度', type: 'string', group: 'appearance' },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        options: [
          { label: '小', value: 'small' },
          { label: '中', value: 'medium' },
          { label: '大', value: 'large' },
        ],
        group: 'appearance',
      },
      { key: 'bordered', label: '显示边框', type: 'boolean', group: 'appearance' },
    ],
    tags: ['form', 'container', 'layout'],
  },
  {
    type: 'navigation',
    name: '导航组件',
    category: 'layout',
    icon: '🧭',
    description: '水平导航栏组件，支持组件选择和数据源配置',
    defaultProps: {
      theme: 'light',
      items: [
        { key: 'home', label: '首页', href: '/' },
        { key: 'about', label: '关于', href: '/about' },
      ],
      selectedKey: 'home',
      collapsed: false,
      width: 12,
      height: 'auto',
      targetComponent: '',
      dataSource: '',
    },
    propertySchema: [
      {
        key: 'theme',
        label: '主题',
        type: 'select',
        options: [
          { label: '浅色', value: 'light' },
          { label: '深色', value: 'dark' },
        ],
        group: 'appearance',
      },
      {
        key: 'items',
        label: '导航项',
        type: 'array',
        group: 'basic',
        description: '格式: [{"key": "唯一标识", "label": "显示文本", "href": "链接地址"}]',
      },
      { key: 'selectedKey', label: '选中项', type: 'string', group: 'behavior' },
      { key: 'collapsed', label: '折叠状态', type: 'boolean', group: 'behavior' },
      SHARED_PROPERTIES.WIDTH_PROPERTY,
      SHARED_PROPERTIES.HEIGHT_PROPERTY,
      {
        key: 'targetComponent',
        label: '目标组件',
        type: 'component-select',
        group: 'behavior',
        description: '选择要关联的组件',
      },
      {
        key: 'dataSource',
        label: '数据源',
        type: 'datasource-select',
        group: 'basic',
        description: '选择数据源',
      },
    ],
    tags: ['navigation', 'menu', 'nav', 'layout'],
  },
  {
    type: 'container',
    name: '容器组件',
    category: 'layout',
    icon: '📦',
    description: '通用布局容器，支持内边距、边框等样式配置',
    defaultProps: {
      padding: 16,
      margin: 0,
      backgroundColor: 'transparent',
      borderRadius: 0,
      bordered: false,
      shadow: 'none',
      width: '100%',
      height: 'auto',
      minHeight: 'auto',
    },
    propertySchema: [
      { key: 'padding', label: '内边距', type: 'number', group: 'appearance', min: 0, max: 100 },
      { key: 'margin', label: '外边距', type: 'number', group: 'appearance', min: 0, max: 100 },
      { key: 'backgroundColor', label: '背景色', type: 'color', group: 'appearance' },
      { key: 'borderRadius', label: '圆角', type: 'number', group: 'appearance', min: 0, max: 50 },
      { key: 'bordered', label: '显示边框', type: 'boolean', group: 'appearance' },
      {
        key: 'shadow',
        label: '阴影',
        type: 'select',
        options: [
          { label: '无', value: 'none' },
          { label: '小', value: 'small' },
          { label: '中', value: 'medium' },
          { label: '大', value: 'large' },
        ],
        group: 'appearance',
      },
      SHARED_PROPERTIES.WIDTH_PROPERTY,
      SHARED_PROPERTIES.HEIGHT_PROPERTY,
      { key: 'minHeight', label: '最小高度', type: 'string', group: 'appearance' },
    ],
    tags: ['container', 'wrapper', 'box', 'layout'],
  },
  {
    type: 'grid',
    name: '网格布局',
    category: 'layout',
    icon: '⚏',
    description: '网格布局容器，支持响应式网格系统',
    defaultProps: {
      columns: 12,
      gutter: 16,
      justify: 'start',
      align: 'top',
      wrap: true,
      responsive: true,
    },
    propertySchema: [
      { key: 'columns', label: '列数', type: 'number', group: 'basic', min: 1, max: 24 },
      { key: 'gutter', label: '间距', type: 'number', group: 'appearance', min: 0, max: 48 },
      {
        key: 'justify',
        label: '水平对齐',
        type: 'select',
        options: [
          { label: '左对齐', value: 'start' },
          { label: '居中', value: 'center' },
          { label: '右对齐', value: 'end' },
          { label: '两端对齐', value: 'space-between' },
          { label: '环绕对齐', value: 'space-around' },
        ],
        group: 'appearance',
      },
      {
        key: 'align',
        label: '垂直对齐',
        type: 'select',
        options: [
          { label: '顶部', value: 'top' },
          { label: '居中', value: 'middle' },
          { label: '底部', value: 'bottom' },
        ],
        group: 'appearance',
      },
      { key: 'wrap', label: '自动换行', type: 'boolean', group: 'behavior' },
      { key: 'responsive', label: '响应式', type: 'boolean', group: 'behavior' },
    ],
    tags: ['grid', 'layout', 'responsive', 'columns'],
  },
  {
    type: 'flex',
    name: '弹性布局',
    category: 'layout',
    icon: '🔄',
    description: '弹性布局容器，基于 Flexbox 实现灵活布局',
    defaultProps: {
      direction: 'row',
      justify: 'flex-start',
      align: 'stretch',
      wrap: 'nowrap',
      gap: 8,
      flex: '1',
    },
    propertySchema: [
      {
        key: 'direction',
        label: '排列方向',
        type: 'select',
        options: [
          { label: '水平', value: 'row' },
          { label: '垂直', value: 'column' },
          { label: '水平反向', value: 'row-reverse' },
          { label: '垂直反向', value: 'column-reverse' },
        ],
        group: 'basic',
      },
      {
        key: 'justify',
        label: '主轴对齐',
        type: 'select',
        options: [
          { label: '起始', value: 'flex-start' },
          { label: '居中', value: 'center' },
          { label: '末尾', value: 'flex-end' },
          { label: '两端对齐', value: 'space-between' },
          { label: '环绕对齐', value: 'space-around' },
          { label: '均匀分布', value: 'space-evenly' },
        ],
        group: 'appearance',
      },
      {
        key: 'align',
        label: '交叉轴对齐',
        type: 'select',
        options: [
          { label: '拉伸', value: 'stretch' },
          { label: '起始', value: 'flex-start' },
          { label: '居中', value: 'center' },
          { label: '末尾', value: 'flex-end' },
          { label: '基线', value: 'baseline' },
        ],
        group: 'appearance',
      },
      {
        key: 'wrap',
        label: '换行方式',
        type: 'select',
        options: [
          { label: '不换行', value: 'nowrap' },
          { label: '换行', value: 'wrap' },
          { label: '反向换行', value: 'wrap-reverse' },
        ],
        group: 'behavior',
      },
      { key: 'gap', label: '间距', type: 'number', group: 'appearance', min: 0, max: 48 },
      { key: 'flex', label: '弹性系数', type: 'string', group: 'behavior' },
    ],
    tags: ['flex', 'flexbox', 'layout', 'responsive'],
  },
  {
    type: 'columns',
    name: '分栏布局',
    category: 'layout',
    icon: '📰',
    description: '多列布局组件，支持等宽或自定义宽度分栏',
    defaultProps: {
      count: 2,
      gutter: 16,
      split: false,
      responsive: true,
      breakpoints: {
        xs: 1,
        sm: 1,
        md: 2,
        lg: 2,
        xl: 2,
      },
    },
    propertySchema: [
      { key: 'count', label: '列数', type: 'number', group: 'basic', min: 1, max: 6 },
      { key: 'gutter', label: '列间距', type: 'number', group: 'appearance', min: 0, max: 48 },
      { key: 'split', label: '显示分割线', type: 'boolean', group: 'appearance' },
      { key: 'responsive', label: '响应式', type: 'boolean', group: 'behavior' },
      {
        key: 'breakpoints',
        label: '断点配置',
        type: 'object',
        group: 'behavior',
        description: '不同屏幕尺寸下的列数配置',
      },
    ],
    tags: ['columns', 'layout', 'responsive', 'multi-column'],
  },
  {
    type: 'card',
    name: '卡片容器',
    category: 'layout',
    icon: '🃏',
    description: '卡片式容器，包含标题、内容区域和操作区域',
    defaultProps: {
      title: '卡片标题',
      showHeader: true,
      showFooter: false,
      bordered: true,
      hoverable: false,
      loading: false,
      size: 'default',
      headerStyle: {},
      bodyStyle: { padding: 24 },
      footerStyle: {},
    },
    propertySchema: [
      { key: 'title', label: '卡片标题', type: 'string', group: 'basic' },
      { key: 'showHeader', label: '显示头部', type: 'boolean', group: 'appearance' },
      { key: 'showFooter', label: '显示底部', type: 'boolean', group: 'appearance' },
      { key: 'bordered', label: '显示边框', type: 'boolean', group: 'appearance' },
      { key: 'hoverable', label: '悬停效果', type: 'boolean', group: 'behavior' },
      { key: 'loading', label: '加载状态', type: 'boolean', group: 'behavior' },
      {
        key: 'size',
        label: '尺寸',
        type: 'select',
        options: [
          { label: '小', value: 'small' },
          { label: '默认', value: 'default' },
          { label: '大', value: 'large' },
        ],
        group: 'appearance',
      },
      {
        key: 'bodyStyle',
        label: '内容样式',
        type: 'object',
        group: 'appearance',
        description: 'CSS 样式对象',
      },
    ],
    tags: ['card', 'container', 'panel', 'layout'],
  },
];

export const DATETIME_COMPONENT_CONFIGS: ComponentConfig[] = [
  {
    type: 'date',
    name: '日期显示',
    category: 'datetime',
    icon: '📅',
    description: '日期显示组件',
    defaultProps: {
      value: '',
      format: 'YYYY-MM-DD',
      relative: false,
    },
    propertySchema: [
      { key: 'value', label: '日期值', type: 'date', group: 'basic' },
      {
        key: 'format',
        label: '显示格式',
        type: 'select',
        options: [
          { label: 'YYYY-MM-DD', value: 'YYYY-MM-DD' },
          { label: 'YYYY/MM/DD', value: 'YYYY/MM/DD' },
          { label: 'DD/MM/YYYY', value: 'DD/MM/YYYY' },
          { label: 'MM/DD/YYYY', value: 'MM/DD/YYYY' },
        ],
        group: 'appearance',
      },
      { key: 'relative', label: '相对时间', type: 'boolean', group: 'behavior' },
    ],
    tags: ['date', 'time', 'display'],
  },
  {
    type: 'datetime',
    name: '日期时间显示',
    category: 'datetime',
    icon: '🕐',
    description: '日期时间显示组件',
    defaultProps: {
      value: '',
      format: 'YYYY-MM-DD HH:mm:ss',
      showSeconds: true,
      relative: false,
    },
    propertySchema: [
      { key: 'value', label: '日期时间值', type: 'string', group: 'basic' },
      { key: 'format', label: '显示格式', type: 'string', group: 'appearance' },
      { key: 'showSeconds', label: '显示秒', type: 'boolean', group: 'behavior' },
      { key: 'relative', label: '相对时间', type: 'boolean', group: 'behavior' },
    ],
    tags: ['datetime', 'time', 'display'],
  },
];

export const CHART_COMPONENT_CONFIGS: ComponentConfig[] = [
  // SmartChart 组件配置
  {
    type: 'smart-number-card',
    name: '数字卡片',
    category: 'chart',
    icon: '🔢',
    description: 'KPI 指标数字展示',
    defaultProps: {
      title: '指标',
      format: 'number',
      precision: 0,
    },
    propertySchema: [
      { key: 'title', label: '标题', type: 'string', group: 'basic' },
      { key: 'icon', label: '图标', type: 'icon', group: 'basic' },
      {
        key: 'format',
        label: '格式',
        type: 'select',
        options: [
          { label: '数字', value: 'number' },
          { label: '货币', value: 'currency' },
          { label: '百分比', value: 'percent' },
        ],
        group: 'basic',
      },
      { key: 'precision', label: '小数位数', type: 'number', group: 'basic' },
      {
        key: 'dataSource.type',
        label: '数据源类型',
        type: 'select',
        options: [
          { label: '聚合查询', value: 'aggregate' },
          { label: 'NamedQuery', value: 'namedQuery' },
        ],
        group: 'advanced',
      },
      { key: 'dataSource.modelCode', label: '数据模型', type: 'string', group: 'advanced' },
      { key: 'dataSource.metrics', label: '指标配置', type: 'object', group: 'advanced' },
    ],
    tags: ['chart', 'kpi', 'number', '数字卡片'],
  },
  {
    type: 'smart-bar-chart',
    name: '柱状图',
    category: 'chart',
    icon: '📊',
    description: '柱状图/条形图，适合对比分析',
    defaultProps: {
      horizontal: false,
      stacked: false,
      showLabel: false,
    },
    propertySchema: [
      { key: 'title', label: '标题', type: 'string', group: 'basic' },
      { key: 'horizontal', label: '水平显示', type: 'boolean', group: 'appearance' },
      { key: 'stacked', label: '堆叠', type: 'boolean', group: 'appearance' },
      {
        key: 'dataSource.type',
        label: '数据源类型',
        type: 'select',
        options: [
          { label: '聚合查询', value: 'aggregate' },
          { label: 'NamedQuery', value: 'namedQuery' },
        ],
        group: 'advanced',
      },
      { key: 'dataSource.modelCode', label: '数据模型', type: 'string', group: 'advanced' },
      { key: 'dataSource.dimensions', label: '维度字段', type: 'array', group: 'advanced' },
      { key: 'dataSource.metrics', label: '指标配置', type: 'object', group: 'advanced' },
      { key: 'drillDown.enabled', label: '启用钻取', type: 'boolean', group: 'behavior' },
      { key: 'linkage.enabled', label: '启用联动', type: 'boolean', group: 'behavior' },
      { key: 'linkage.groupId', label: '联动组', type: 'string', group: 'behavior' },
    ],
    tags: ['chart', 'bar', 'column', '柱状图', '对比'],
  },
  {
    type: 'smart-line-chart',
    name: '折线图',
    category: 'chart',
    icon: '📈',
    description: '折线图/面积图，适合趋势分析',
    defaultProps: {
      smooth: false,
      area: false,
    },
    propertySchema: [
      { key: 'title', label: '标题', type: 'string', group: 'basic' },
      { key: 'smooth', label: '平滑曲线', type: 'boolean', group: 'appearance' },
      { key: 'area', label: '面积图', type: 'boolean', group: 'appearance' },
      {
        key: 'dataSource.type',
        label: '数据源类型',
        type: 'select',
        options: [
          { label: '聚合查询', value: 'aggregate' },
          { label: 'NamedQuery', value: 'namedQuery' },
        ],
        group: 'advanced',
      },
      { key: 'dataSource.modelCode', label: '数据模型', type: 'string', group: 'advanced' },
      { key: 'dataSource.dimensions', label: '维度字段', type: 'array', group: 'advanced' },
      { key: 'dataSource.metrics', label: '指标配置', type: 'object', group: 'advanced' },
      { key: 'drillDown.enabled', label: '启用钻取', type: 'boolean', group: 'behavior' },
      { key: 'linkage.enabled', label: '启用联动', type: 'boolean', group: 'behavior' },
      { key: 'linkage.groupId', label: '联动组', type: 'string', group: 'behavior' },
    ],
    tags: ['chart', 'line', 'trend', '折线图', '趋势'],
  },
  {
    type: 'smart-pie-chart',
    name: '饼图',
    category: 'chart',
    icon: '🥧',
    description: '饼图/环形图，适合占比分析',
    defaultProps: {
      donut: false,
      showLabel: true,
    },
    propertySchema: [
      { key: 'title', label: '标题', type: 'string', group: 'basic' },
      { key: 'donut', label: '环形图', type: 'boolean', group: 'appearance' },
      { key: 'showLabel', label: '显示标签', type: 'boolean', group: 'appearance' },
      {
        key: 'dataSource.type',
        label: '数据源类型',
        type: 'select',
        options: [
          { label: '聚合查询', value: 'aggregate' },
          { label: 'NamedQuery', value: 'namedQuery' },
        ],
        group: 'advanced',
      },
      { key: 'dataSource.modelCode', label: '数据模型', type: 'string', group: 'advanced' },
      { key: 'dataSource.dimensions', label: '维度字段', type: 'array', group: 'advanced' },
      { key: 'dataSource.metrics', label: '指标配置', type: 'object', group: 'advanced' },
      { key: 'drillDown.enabled', label: '启用钻取', type: 'boolean', group: 'behavior' },
      { key: 'linkage.enabled', label: '启用联动', type: 'boolean', group: 'behavior' },
      { key: 'linkage.groupId', label: '联动组', type: 'string', group: 'behavior' },
    ],
    tags: ['chart', 'pie', 'donut', '饼图', '占比'],
  },
  {
    type: 'smart-kanban',
    name: '看板',
    category: 'chart',
    icon: '📋',
    description: '看板视图，支持拖拽卡片',
    defaultProps: {
      draggable: false,
      showCount: true,
      showAggregations: true,
    },
    propertySchema: [
      { key: 'title', label: '标题', type: 'string', group: 'basic' },
      { key: 'draggable', label: '允许拖拽', type: 'boolean', group: 'basic' },
      { key: 'showCount', label: '显示数量', type: 'boolean', group: 'basic' },
      { key: 'showAggregations', label: '显示统计', type: 'boolean', group: 'basic' },
      {
        key: 'dataSource.type',
        label: '数据源类型',
        type: 'select',
        options: [{ label: '聚合查询', value: 'aggregate' }],
        group: 'dataSource',
      },
      { key: 'dataSource.modelCode', label: '数据模型', type: 'model-select', group: 'dataSource' },
      {
        key: 'dataSource.groupByField',
        label: '分组字段',
        type: 'field-select',
        group: 'dataSource',
      },
      {
        key: 'dataSource.titleField',
        label: '标题字段',
        type: 'field-select',
        group: 'dataSource',
      },
      {
        key: 'dataSource.descriptionField',
        label: '描述字段',
        type: 'field-select',
        group: 'dataSource',
      },
    ],
    tags: ['chart', 'kanban', 'board', '看板', '拖拽'],
  },
  // 基础图表组件配置
  {
    type: 'bar-chart',
    name: '柱状图',
    category: 'chart',
    icon: '📊',
    description: '柱状图，用于展示分类数据的对比',
    defaultProps: {
      title: '柱状图',
      width: '100%',
      height: 400,
      data: [],
      xField: 'category',
      yField: 'value',
      color: '#1890ff',
      showLegend: true,
      showGrid: true,
      showTooltip: true,
    },
    propertySchema: [
      { key: 'title', label: '图表标题', type: 'string', group: 'basic' },
      SHARED_PROPERTIES.WIDTH_PROPERTY,
      SHARED_PROPERTIES.HEIGHT_PROPERTY,
      {
        key: 'data',
        label: '数据源',
        type: 'array',
        group: 'basic',
        description: '图表数据，格式: [{"category": "分类", "value": 数值}]',
      },
      { key: 'xField', label: 'X轴字段', type: 'string', group: 'basic' },
      { key: 'yField', label: 'Y轴字段', type: 'string', group: 'basic' },
      { key: 'color', label: '颜色', type: 'color', group: 'appearance' },
      { key: 'showLegend', label: '显示图例', type: 'boolean', group: 'appearance' },
      { key: 'showGrid', label: '显示网格', type: 'boolean', group: 'appearance' },
      { key: 'showTooltip', label: '显示提示', type: 'boolean', group: 'behavior' },
    ],
    tags: ['chart', 'bar', 'column', 'data', 'visualization'],
  },
  {
    type: 'line-chart',
    name: '折线图',
    category: 'chart',
    icon: '📈',
    description: '折线图，用于展示数据的趋势变化',
    defaultProps: {
      title: '折线图',
      width: '100%',
      height: 400,
      data: [],
      xField: 'date',
      yField: 'value',
      color: '#52c41a',
      smooth: true,
      showPoints: true,
      showLegend: true,
      showGrid: true,
      showTooltip: true,
    },
    propertySchema: [
      { key: 'title', label: '图表标题', type: 'string', group: 'basic' },
      SHARED_PROPERTIES.WIDTH_PROPERTY,
      SHARED_PROPERTIES.HEIGHT_PROPERTY,
      {
        key: 'data',
        label: '数据源',
        type: 'array',
        group: 'basic',
        description: '图表数据，格式: [{"date": "日期", "value": 数值}]',
      },
      { key: 'xField', label: 'X轴字段', type: 'string', group: 'basic' },
      { key: 'yField', label: 'Y轴字段', type: 'string', group: 'basic' },
      { key: 'color', label: '颜色', type: 'color', group: 'appearance' },
      { key: 'smooth', label: '平滑曲线', type: 'boolean', group: 'appearance' },
      { key: 'showPoints', label: '显示数据点', type: 'boolean', group: 'appearance' },
      { key: 'showLegend', label: '显示图例', type: 'boolean', group: 'appearance' },
      { key: 'showGrid', label: '显示网格', type: 'boolean', group: 'appearance' },
      { key: 'showTooltip', label: '显示提示', type: 'boolean', group: 'behavior' },
    ],
    tags: ['chart', 'line', 'trend', 'data', 'visualization'],
  },
  {
    type: 'pie-chart',
    name: '饼图',
    category: 'chart',
    icon: '🥧',
    description: '饼图，用于展示数据的占比关系',
    defaultProps: {
      title: '饼图',
      width: '100%',
      height: 400,
      data: [],
      angleField: 'value',
      colorField: 'category',
      radius: 0.8,
      innerRadius: 0,
      showLegend: true,
      showLabels: true,
      showTooltip: true,
    },
    propertySchema: [
      { key: 'title', label: '图表标题', type: 'string', group: 'basic' },
      SHARED_PROPERTIES.WIDTH_PROPERTY,
      SHARED_PROPERTIES.HEIGHT_PROPERTY,
      {
        key: 'data',
        label: '数据源',
        type: 'array',
        group: 'basic',
        description: '图表数据，格式: [{"category": "分类", "value": 数值}]',
      },
      { key: 'angleField', label: '角度字段', type: 'string', group: 'basic' },
      { key: 'colorField', label: '颜色字段', type: 'string', group: 'basic' },
      {
        key: 'radius',
        label: '外半径',
        type: 'number',
        group: 'appearance',
        min: 0.1,
        max: 1,
        defaultValue: 0.8,
      },
      {
        key: 'innerRadius',
        label: '内半径',
        type: 'number',
        group: 'appearance',
        min: 0,
        max: 0.9,
        defaultValue: 0,
      },
      { key: 'showLegend', label: '显示图例', type: 'boolean', group: 'appearance' },
      { key: 'showLabels', label: '显示标签', type: 'boolean', group: 'appearance' },
      { key: 'showTooltip', label: '显示提示', type: 'boolean', group: 'behavior' },
    ],
    tags: ['chart', 'pie', 'donut', 'proportion', 'data', 'visualization'],
  },
  {
    type: 'area-chart',
    name: '面积图',
    category: 'chart',
    icon: '🏔️',
    description: '面积图，用于展示数据的累积变化',
    defaultProps: {
      title: '面积图',
      width: '100%',
      height: 400,
      data: [],
      xField: 'date',
      yField: 'value',
      color: '#722ed1',
      smooth: true,
      fillOpacity: 0.6,
      showLegend: true,
      showGrid: true,
      showTooltip: true,
    },
    propertySchema: [
      { key: 'title', label: '图表标题', type: 'string', group: 'basic' },
      SHARED_PROPERTIES.WIDTH_PROPERTY,
      SHARED_PROPERTIES.HEIGHT_PROPERTY,
      {
        key: 'data',
        label: '数据源',
        type: 'array',
        group: 'basic',
        description: '图表数据，格式: [{"date": "日期", "value": 数值}]',
      },
      { key: 'xField', label: 'X轴字段', type: 'string', group: 'basic' },
      { key: 'yField', label: 'Y轴字段', type: 'string', group: 'basic' },
      { key: 'color', label: '颜色', type: 'color', group: 'appearance' },
      { key: 'smooth', label: '平滑曲线', type: 'boolean', group: 'appearance' },
      {
        key: 'fillOpacity',
        label: '填充透明度',
        type: 'number',
        group: 'appearance',
        min: 0,
        max: 1,
        defaultValue: 0.6,
      },
      { key: 'showLegend', label: '显示图例', type: 'boolean', group: 'appearance' },
      { key: 'showGrid', label: '显示网格', type: 'boolean', group: 'appearance' },
      { key: 'showTooltip', label: '显示提示', type: 'boolean', group: 'behavior' },
    ],
    tags: ['chart', 'area', 'filled', 'trend', 'data', 'visualization'],
  },
];

// 合并所有组件配置
export const ALL_COMPONENT_CONFIGS: ComponentConfig[] = [
  ...FORM_COMPONENT_CONFIGS,
  ...DISPLAY_COMPONENT_CONFIGS,
  ...INTERACTION_COMPONENT_CONFIGS,
  ...LAYOUT_COMPONENT_CONFIGS,
  ...DATETIME_COMPONENT_CONFIGS,
  ...CHART_COMPONENT_CONFIGS,
];

const RUNTIME_AWARE_CONFIG_GROUPS = [
  FORM_COMPONENT_CONFIGS,
  DISPLAY_COMPONENT_CONFIGS,
  INTERACTION_COMPONENT_CONFIGS,
  LAYOUT_COMPONENT_CONFIGS,
  DATETIME_COMPONENT_CONFIGS,
  CHART_COMPONENT_CONFIGS,
];

RUNTIME_AWARE_CONFIG_GROUPS.forEach((group) => {
  group.forEach((config) => {
    const runtime = COMPONENT_RUNTIME_MANIFEST[config.type];
    if (runtime) {
      config.runtime = runtime;
    }
  });
});
