/**
 * Smart组件配置定义
 * 包含所有Smart组件的详细配置信息
 */

import { componentText } from './componentText';
import type { ComponentConfig } from '~/framework/meta/registry/components/ComponentConfig';
import { COMPONENT_RUNTIME_MANIFEST } from '~/framework/meta/registry/components/ComponentRuntimeManifest';

// 共享属性配置
export const SHARED_PROPERTIES = {
  // 标准宽度属性配置（12列网格系统）
  WIDTH_PROPERTY: {
    key: 'width',
    label: componentText('metadata.widthGridColumns'),
    type: 'number' as const,
    group: 'basic' as const,
    min: 1,
    max: 12,
    description: componentText('metadata.numberOfOccupiedGridColumns12FillsTheEntireRow'),
  },

  // 标准高度属性配置
  HEIGHT_PROPERTY: {
    key: 'height',
    label: componentText('metadata.height'),
    type: 'string' as const,
    group: 'basic' as const,
    description: componentText('metadata.heightValueSuchAsAuto100pxOr50vh'),
  },

  // 基础布局属性组
  BASIC_LAYOUT_PROPERTIES: [
    {
      key: 'width',
      label: componentText('metadata.widthGridColumns'),
      type: 'number' as const,
      group: 'basic' as const,
      min: 1,
      max: 12,
      description: componentText('metadata.numberOfOccupiedGridColumns12FillsTheEntireRow'),
    },
    {
      key: 'height',
      label: componentText('metadata.height'),
      type: 'string' as const,
      group: 'basic' as const,
      description: componentText('metadata.heightValueSuchAsAuto100pxOr50vh'),
    },
  ],

  // 外观属性组
  APPEARANCE_PROPERTIES: {
    BACKGROUND_COLOR: {
      key: 'backgroundColor',
      label: componentText('metadata.backgroundColor'),
      type: 'color' as const,
      group: 'appearance' as const,
    },
    BORDER_RADIUS: {
      key: 'borderRadius',
      label: componentText('metadata.borderRadius'),
      type: 'number' as const,
      group: 'appearance' as const,
      min: 0,
      max: 50,
      description: componentText('metadata.borderRadiusInPixels'),
    },
    BORDER: {
      key: 'border',
      label: componentText('metadata.border'),
      type: 'string' as const,
      group: 'appearance' as const,
      description: componentText('metadata.borderStyleSuchAs1pxSolidCcc'),
    },
    BOX_SHADOW: {
      key: 'boxShadow',
      label: componentText('metadata.shadow'),
      type: 'string' as const,
      group: 'appearance' as const,
      description: componentText('metadata.shadowEffectSuchAs02px4pxRgba00001'),
    },
  },

  // 间距属性组
  SPACING_PROPERTIES: {
    PADDING: {
      key: 'padding',
      label: componentText('metadata.padding'),
      type: 'number' as const,
      group: 'spacing' as const,
      min: 0,
      max: 100,
      description: componentText('metadata.paddingInPixels'),
    },
    MARGIN: {
      key: 'margin',
      label: componentText('metadata.margin'),
      type: 'number' as const,
      group: 'spacing' as const,
      min: 0,
      max: 100,
      description: componentText('metadata.marginInPixels'),
    },
  },
};

export const FORM_COMPONENT_CONFIGS: ComponentConfig[] = [
  {
    type: 'input',
    name: componentText('metadata.input'),
    category: 'form',
    icon: '📝',
    description: componentText('metadata.singleLineTextInputWithValidationRules'),
    defaultProps: {
      label: '输入框',
      placeholder: '请输入内容',
      required: false,
      size: 'medium',
      variant: 'default',
      disabled: false,
      maxLength: 255,
    },
    propertySchema: [
      { key: 'label', label: componentText('metadata.label'), type: 'string', required: true, group: 'basic' },
      { key: 'name', label: componentText('metadata.fieldName'), type: 'string', required: true, group: 'basic' },
      { key: 'placeholder', label: componentText('metadata.placeholder'), type: 'string', group: 'basic' },
      { key: 'defaultValue', label: componentText('metadata.defaultValue'), type: 'string', group: 'basic' },
      { key: 'required', label: componentText('metadata.required'), type: 'boolean', group: 'validation' },
      { key: 'disabled', label: componentText('metadata.disabled'), type: 'boolean', group: 'behavior' },
      { key: 'maxLength', label: componentText('metadata.maximumLength'), type: 'number', group: 'validation', min: 1 },
      { key: 'minLength', label: componentText('metadata.minimumLength'), type: 'number', group: 'validation', min: 0 },
      { key: 'pattern', label: componentText('metadata.regularExpressionValidation'), type: 'string', group: 'validation' },
      {
        key: 'size',
        label: componentText('metadata.size'),
        type: 'select',
        options: [
          { label: componentText('metadata.small'), value: 'small' },
          { label: componentText('metadata.medium'), value: 'medium' },
          { label: componentText('metadata.large'), value: 'large' },
        ],
        group: 'appearance',
      },
      {
        key: 'variant',
        label: componentText('metadata.style'),
        type: 'select',
        options: [
          { label: componentText('metadata.default'), value: 'default' },
          { label: componentText('metadata.border'), value: 'outline' },
          { label: componentText('metadata.filled'), value: 'filled' },
        ],
        group: 'appearance',
      },
    ],
    tags: ['input', 'text', 'form', 'basic'],
  },
  {
    type: 'textarea',
    name: componentText('metadata.textarea'),
    category: 'form',
    icon: '📄',
    description: componentText('metadata.multiLineTextInputForLongerContent'),
    defaultProps: {
      label: '多行文本',
      placeholder: '请输入内容',
      required: false,
      rows: 4,
      maxLength: 1000,
      resize: 'vertical',
    },
    propertySchema: [
      { key: 'label', label: componentText('metadata.label'), type: 'string', required: true, group: 'basic' },
      { key: 'name', label: componentText('metadata.fieldName'), type: 'string', required: true, group: 'basic' },
      { key: 'placeholder', label: componentText('metadata.placeholder'), type: 'string', group: 'basic' },
      { key: 'defaultValue', label: componentText('metadata.defaultValue'), type: 'string', group: 'basic' },
      { key: 'required', label: componentText('metadata.required'), type: 'boolean', group: 'validation' },
      { key: 'disabled', label: componentText('metadata.disabled'), type: 'boolean', group: 'behavior' },
      { key: 'rows', label: componentText('metadata.rows'), type: 'number', group: 'appearance', min: 2, max: 20 },
      { key: 'maxLength', label: componentText('metadata.maximumLength'), type: 'number', group: 'validation', min: 1 },
      {
        key: 'resize',
        label: componentText('metadata.resize'),
        type: 'select',
        options: [
          { label: componentText('metadata.vertical'), value: 'vertical' },
          { label: componentText('metadata.horizontal'), value: 'horizontal' },
          { label: componentText('metadata.bothDirections'), value: 'both' },
          { label: componentText('metadata.disabled'), value: 'none' },
        ],
        group: 'behavior',
      },
    ],
    tags: ['textarea', 'text', 'multiline', 'form'],
  },
  {
    type: 'json-editor',
    name: componentText('metadata.jsonEditor'),
    category: 'form',
    icon: '{}',
    description: componentText('metadata.jsonOrSchemaEditorWithObjectArrayValidationAndFormatting'),
    defaultProps: {
      label: 'JSON',
      placeholder: '{"key":"value"}',
      required: false,
      rows: 8,
      formatOnBlur: false,
      mode: 'json',
    },
    propertySchema: [
      { key: 'label', label: componentText('metadata.label'), type: 'string', required: true, group: 'basic' },
      { key: 'name', label: componentText('metadata.fieldName'), type: 'string', required: true, group: 'basic' },
      { key: 'placeholder', label: componentText('metadata.placeholder'), type: 'string', group: 'basic' },
      { key: 'required', label: componentText('metadata.required'), type: 'boolean', group: 'validation' },
      { key: 'disabled', label: componentText('metadata.disabled'), type: 'boolean', group: 'behavior' },
      { key: 'rows', label: componentText('metadata.rows'), type: 'number', group: 'appearance', min: 4, max: 30 },
      { key: 'formatOnBlur', label: componentText('metadata.formatOnBlur'), type: 'boolean', group: 'behavior' },
      {
        key: 'mode',
        label: componentText('metadata.mode'),
        type: 'select',
        options: [
          { label: 'JSON', value: 'json' },
          { label: 'Schema', value: 'schema' },
        ],
        group: 'basic',
      },
    ],
    tags: ['json', 'schema', 'editor', 'form'],
  },
  {
    type: 'select',
    name: componentText('metadata.select'),
    category: 'form',
    icon: '📋',
    description: componentText('metadata.dropdownWithSingleAndMultipleSelection'),
    defaultProps: {
      label: '下拉选择',
      placeholder: '请选择',
      required: false,
      multiple: false,
      clearable: true,
      searchable: false,
      options: [],
    },
    propertySchema: [
      { key: 'label', label: componentText('metadata.label'), type: 'string', required: true, group: 'basic' },
      { key: 'name', label: componentText('metadata.fieldName'), type: 'string', required: true, group: 'basic' },
      { key: 'placeholder', label: componentText('metadata.placeholder'), type: 'string', group: 'basic' },
      { key: 'required', label: componentText('metadata.required'), type: 'boolean', group: 'validation' },
      { key: 'disabled', label: componentText('metadata.disabled'), type: 'boolean', group: 'behavior' },
      { key: 'multiple', label: componentText('metadata.multipleSelection'), type: 'boolean', group: 'behavior' },
      { key: 'clearable', label: componentText('metadata.clearable'), type: 'boolean', group: 'behavior' },
      { key: 'searchable', label: componentText('metadata.searchable'), type: 'boolean', group: 'behavior' },
      {
        key: 'options',
        label: componentText('metadata.options'),
        type: 'array',
        group: 'basic',
        description: componentText('metadata.formatLabelDisplayTextValueValue'),
      },
    ],
    tags: ['select', 'dropdown', 'options', 'form'],
  },
  {
    type: 'checkbox',
    name: componentText('metadata.checkbox'),
    category: 'form',
    icon: '☑️',
    description: componentText('metadata.checkboxWithSingleOrMultipleOptions'),
    defaultProps: {
      label: '复选框',
      required: false,
      disabled: false,
      checked: false,
      indeterminate: false,
    },
    propertySchema: [
      { key: 'label', label: componentText('metadata.label'), type: 'string', required: true, group: 'basic' },
      { key: 'name', label: componentText('metadata.fieldName'), type: 'string', required: true, group: 'basic' },
      { key: 'required', label: componentText('metadata.required'), type: 'boolean', group: 'validation' },
      { key: 'disabled', label: componentText('metadata.disabled'), type: 'boolean', group: 'behavior' },
      { key: 'checked', label: componentText('metadata.checkedByDefault'), type: 'boolean', group: 'basic' },
      { key: 'indeterminate', label: componentText('metadata.indeterminate'), type: 'boolean', group: 'appearance' },
    ],
    tags: ['checkbox', 'check', 'boolean', 'form'],
  },
  {
    type: 'radio',
    name: componentText('metadata.radio'),
    category: 'form',
    icon: '🔘',
    description: componentText('metadata.radioGroupForSingleSelection'),
    defaultProps: {
      label: '单选框',
      required: false,
      disabled: false,
      options: [],
      direction: 'horizontal',
    },
    propertySchema: [
      { key: 'label', label: componentText('metadata.label'), type: 'string', required: true, group: 'basic' },
      { key: 'name', label: componentText('metadata.fieldName'), type: 'string', required: true, group: 'basic' },
      { key: 'required', label: componentText('metadata.required'), type: 'boolean', group: 'validation' },
      { key: 'disabled', label: componentText('metadata.disabled'), type: 'boolean', group: 'behavior' },
      {
        key: 'direction',
        label: componentText('metadata.direction'),
        type: 'select',
        options: [
          { label: componentText('metadata.horizontal'), value: 'horizontal' },
          { label: componentText('metadata.vertical'), value: 'vertical' },
        ],
        group: 'appearance',
      },
      {
        key: 'options',
        label: componentText('metadata.options'),
        type: 'array',
        group: 'basic',
        description: componentText('metadata.formatLabelDisplayTextValueValue'),
      },
    ],
    tags: ['radio', 'single', 'options', 'form'],
  },
  {
    type: 'datepicker',
    name: componentText('metadata.datePicker'),
    category: 'form',
    icon: '📅',
    description: componentText('metadata.datePickerWithMultipleDateFormats'),
    defaultProps: {
      label: '日期选择',
      placeholder: '请选择日期',
      required: false,
      format: 'YYYY-MM-DD',
      showTime: false,
      clearable: true,
    },
    propertySchema: [
      { key: 'label', label: componentText('metadata.label'), type: 'string', required: true, group: 'basic' },
      { key: 'name', label: componentText('metadata.fieldName'), type: 'string', required: true, group: 'basic' },
      { key: 'placeholder', label: componentText('metadata.placeholder'), type: 'string', group: 'basic' },
      { key: 'required', label: componentText('metadata.required'), type: 'boolean', group: 'validation' },
      { key: 'disabled', label: componentText('metadata.disabled'), type: 'boolean', group: 'behavior' },
      { key: 'showTime', label: componentText('metadata.showTime'), type: 'boolean', group: 'behavior' },
      { key: 'clearable', label: componentText('metadata.clearable'), type: 'boolean', group: 'behavior' },
      {
        key: 'format',
        label: componentText('metadata.dateFormat'),
        type: 'select',
        options: [
          { label: 'YYYY-MM-DD', value: 'YYYY-MM-DD' },
          { label: 'YYYY/MM/DD', value: 'YYYY/MM/DD' },
          { label: 'DD/MM/YYYY', value: 'DD/MM/YYYY' },
          { label: 'MM/DD/YYYY', value: 'MM/DD/YYYY' },
        ],
        group: 'appearance',
      },
    ],
    tags: ['date', 'picker', 'calendar', 'form'],
  },
  // 新增 FormRef 组件配置
  {
    type: 'formref',
    name: componentText('metadata.formReference'),
    category: 'form',
    icon: '🔗',
    description: componentText('metadata.referenceAStandaloneFormInEmbeddedModalOrOtherDisplayModes'),
    defaultProps: {
      formRefId: '',
      mode: 'embedded',
      title: '',
      showTitle: true,
      showBorder: true,
      padding: 16,
      placeholder: '请选择表单',
    },
    propertySchema: [
      {
        key: 'formRefId',
        label: componentText('metadata.formID'),
        type: 'formref-select',
        required: true,
        group: 'basic',
        description: componentText('metadata.selectTheFormToReference'),
      },
      {
        key: 'mode',
        label: componentText('metadata.displayMode'),
        type: 'select',
        options: [
          { label: componentText('metadata.embedded'), value: 'embedded' },
          { label: componentText('metadata.modal'), value: 'modal' },
          { label: componentText('metadata.drawer'), value: 'drawer' },
          { label: componentText('metadata.page'), value: 'page' },
        ],
        group: 'basic',
      },
      { key: 'title', label: componentText('metadata.title'), type: 'string', group: 'basic' },
      { key: 'showTitle', label: componentText('metadata.showTitle'), type: 'boolean', group: 'appearance' },
      { key: 'showBorder', label: componentText('metadata.showBorder'), type: 'boolean', group: 'appearance' },
      { key: 'padding', label: componentText('metadata.padding'), type: 'number', group: 'appearance', min: 0, max: 50 },
      {
        key: 'width',
        label: componentText('metadata.width'),
        type: 'string',
        group: 'appearance',
        description: componentText('metadata.appliesOnlyToModalAndDrawerModes'),
      },
      SHARED_PROPERTIES.HEIGHT_PROPERTY,
      {
        key: 'closable',
        label: componentText('metadata.closable'),
        type: 'boolean',
        group: 'behavior',
        description: componentText('metadata.appliesOnlyToModalAndDrawerModes'),
      },
      {
        key: 'maskClosable',
        label: componentText('metadata.closeOnBackdropClick'),
        type: 'boolean',
        group: 'behavior',
        description: componentText('metadata.appliesOnlyToModalAndDrawerModes'),
      },
    ],
    tags: ['formref', 'reference', 'embed', 'modal'],
  },
  // T9.1: 时间选择器
  {
    type: 'timepicker',
    name: componentText('metadata.timePicker'),
    category: 'form',
    icon: '⏰',
    description: componentText('metadata.timePickerWithHoursMinutesAndSeconds'),
    defaultProps: {
      label: '时间选择',
      placeholder: '请选择时间',
      required: false,
      disabled: false,
      format: 'HH:mm',
      showSecond: false,
      use12Hours: false,
      clearable: true,
      hourStep: 1,
      minuteStep: 1,
      secondStep: 1,
    },
    propertySchema: [
      { key: 'label', label: componentText('metadata.label'), type: 'string', required: true, group: 'basic' },
      { key: 'name', label: componentText('metadata.fieldName'), type: 'string', required: true, group: 'basic' },
      { key: 'placeholder', label: componentText('metadata.placeholder'), type: 'string', group: 'basic' },
      {
        key: 'defaultValue',
        label: componentText('metadata.defaultValue'),
        type: 'string',
        group: 'basic',
        description: componentText('metadata.formatHHMmOrHHMmSs'),
      },
      { key: 'required', label: componentText('metadata.required'), type: 'boolean', group: 'validation' },
      { key: 'disabled', label: componentText('metadata.disabled'), type: 'boolean', group: 'behavior' },
      { key: 'clearable', label: componentText('metadata.clearable'), type: 'boolean', group: 'behavior' },
      {
        key: 'format',
        label: componentText('metadata.timeFormat'),
        type: 'select',
        options: [
          { label: 'HH:mm', value: 'HH:mm' },
          { label: 'HH:mm:ss', value: 'HH:mm:ss' },
          { label: 'hh:mm A', value: 'hh:mm A' },
          { label: 'hh:mm:ss A', value: 'hh:mm:ss A' },
        ],
        group: 'appearance',
      },
      { key: 'showSecond', label: componentText('metadata.showSeconds'), type: 'boolean', group: 'appearance' },
      { key: 'use12Hours', label: componentText('metadata.12HourClock'), type: 'boolean', group: 'appearance' },
      { key: 'hourStep', label: componentText('metadata.hourStep'), type: 'number', group: 'behavior', min: 1, max: 12 },
      { key: 'minuteStep', label: componentText('metadata.minuteStep'), type: 'number', group: 'behavior', min: 1, max: 30 },
      { key: 'secondStep', label: componentText('metadata.secondStep'), type: 'number', group: 'behavior', min: 1, max: 30 },
    ],
    tags: ['time', 'picker', 'clock', 'form'],
  },
  // T9.1: 开关组件
  {
    type: 'switch',
    name: componentText('metadata.switch'),
    category: 'form',
    icon: '🔘',
    description: componentText('metadata.switchBetweenTwoStates'),
    defaultProps: {
      label: '开关',
      required: false,
      disabled: false,
      checked: false,
      size: 'default',
      checkedText: '',
      uncheckedText: '',
      loading: false,
    },
    propertySchema: [
      { key: 'label', label: componentText('metadata.label'), type: 'string', required: true, group: 'basic' },
      { key: 'name', label: componentText('metadata.fieldName'), type: 'string', required: true, group: 'basic' },
      { key: 'checked', label: componentText('metadata.checkedByDefault'), type: 'boolean', group: 'basic' },
      { key: 'required', label: componentText('metadata.required'), type: 'boolean', group: 'validation' },
      { key: 'disabled', label: componentText('metadata.disabled'), type: 'boolean', group: 'behavior' },
      { key: 'loading', label: componentText('metadata.loading'), type: 'boolean', group: 'behavior' },
      {
        key: 'size',
        label: componentText('metadata.size'),
        type: 'select',
        options: [
          { label: componentText('metadata.small'), value: 'small' },
          { label: componentText('metadata.default'), value: 'default' },
          { label: componentText('metadata.large'), value: 'large' },
        ],
        group: 'appearance',
      },
      {
        key: 'checkedText',
        label: componentText('metadata.checkedText'),
        type: 'string',
        group: 'appearance',
        description: componentText('metadata.textDisplayedWhenTheSwitchIsOn'),
      },
      {
        key: 'uncheckedText',
        label: componentText('metadata.uncheckedText'),
        type: 'string',
        group: 'appearance',
        description: componentText('metadata.textDisplayedWhenTheSwitchIsOff'),
      },
      {
        key: 'checkedValue',
        label: componentText('metadata.checkedValue'),
        type: 'string',
        group: 'basic',
        description: componentText('metadata.valueWhenCheckedDefaultsToTrue'),
      },
      {
        key: 'uncheckedValue',
        label: componentText('metadata.uncheckedValue'),
        type: 'string',
        group: 'basic',
        description: componentText('metadata.valueWhenUncheckedDefaultsToFalse'),
      },
    ],
    tags: ['switch', 'toggle', 'boolean', 'form'],
  },
  // T9.1: 数字输入框
  {
    type: 'numberinput',
    name: componentText('metadata.numberInput'),
    category: 'form',
    icon: '🔢',
    description: componentText('metadata.numericInputWithPrecisionRangeAndStepControls'),
    defaultProps: {
      label: '数字输入',
      placeholder: '请输入数字',
      required: false,
      disabled: false,
      min: undefined,
      max: undefined,
      step: 1,
      precision: 0,
      showButtons: true,
      size: 'medium',
    },
    propertySchema: [
      { key: 'label', label: componentText('metadata.label'), type: 'string', required: true, group: 'basic' },
      { key: 'name', label: componentText('metadata.fieldName'), type: 'string', required: true, group: 'basic' },
      { key: 'placeholder', label: componentText('metadata.placeholder'), type: 'string', group: 'basic' },
      { key: 'defaultValue', label: componentText('metadata.defaultValue'), type: 'number', group: 'basic' },
      { key: 'required', label: componentText('metadata.required'), type: 'boolean', group: 'validation' },
      { key: 'disabled', label: componentText('metadata.disabled'), type: 'boolean', group: 'behavior' },
      { key: 'min', label: componentText('metadata.minimum'), type: 'number', group: 'validation' },
      { key: 'max', label: componentText('metadata.maximum'), type: 'number', group: 'validation' },
      { key: 'step', label: componentText('metadata.step'), type: 'number', group: 'behavior', min: 0.001 },
      { key: 'precision', label: componentText('metadata.decimalPlaces'), type: 'number', group: 'behavior', min: 0, max: 10 },
      { key: 'showButtons', label: componentText('metadata.showIncrementDecrementButtons'), type: 'boolean', group: 'appearance' },
      {
        key: 'size',
        label: componentText('metadata.size'),
        type: 'select',
        options: [
          { label: componentText('metadata.small'), value: 'small' },
          { label: componentText('metadata.medium'), value: 'medium' },
          { label: componentText('metadata.large'), value: 'large' },
        ],
        group: 'appearance',
      },
      {
        key: 'prefix',
        label: componentText('metadata.prefix'),
        type: 'string',
        group: 'appearance',
        description: componentText('metadata.textBeforeTheInput'),
      },
      {
        key: 'suffix',
        label: componentText('metadata.suffix'),
        type: 'string',
        group: 'appearance',
        description: componentText('metadata.textAfterTheInputSuchAsAUnit'),
      },
    ],
    tags: ['number', 'input', 'numeric', 'form'],
  },
  // T9.1: 文件上传
  {
    type: 'upload',
    name: componentText('metadata.fileUpload'),
    category: 'form',
    icon: '📤',
    description: componentText('metadata.fileUploadWithDragAndDropMultipleFilesAndImagePreviews'),
    defaultProps: {
      label: '文件上传',
      required: false,
      disabled: false,
      multiple: false,
      maxCount: 1,
      maxSize: 10,
      accept: '',
      listType: 'text',
      draggable: false,
      showUploadList: true,
      action: '/api/upload',
    },
    propertySchema: [
      { key: 'label', label: componentText('metadata.label'), type: 'string', required: true, group: 'basic' },
      { key: 'name', label: componentText('metadata.fieldName'), type: 'string', required: true, group: 'basic' },
      { key: 'required', label: componentText('metadata.required'), type: 'boolean', group: 'validation' },
      { key: 'disabled', label: componentText('metadata.disabled'), type: 'boolean', group: 'behavior' },
      {
        key: 'action',
        label: componentText('metadata.uploadURL'),
        type: 'string',
        group: 'basic',
        description: componentText('metadata.serverURLForFileUploads'),
      },
      { key: 'multiple', label: componentText('metadata.multipleFiles'), type: 'boolean', group: 'behavior' },
      {
        key: 'maxCount',
        label: componentText('metadata.maximumFileCount'),
        type: 'number',
        group: 'validation',
        min: 1,
        max: 100,
      },
      {
        key: 'maxSize',
        label: componentText('metadata.maximumFileSizeMB'),
        type: 'number',
        group: 'validation',
        min: 0.1,
        max: 1000,
      },
      {
        key: 'accept',
        label: componentText('metadata.acceptedFileTypes'),
        type: 'string',
        group: 'validation',
        description: componentText('metadata.forExampleJpgPngPdfOrImage'),
      },
      {
        key: 'listType',
        label: componentText('metadata.listType'),
        type: 'select',
        options: [
          { label: componentText('metadata.text'), value: 'text' },
          { label: componentText('metadata.image'), value: 'picture' },
          { label: componentText('metadata.card'), value: 'picture-card' },
        ],
        group: 'appearance',
      },
      { key: 'draggable', label: componentText('metadata.enableDragAndDrop'), type: 'boolean', group: 'behavior' },
      { key: 'showUploadList', label: componentText('metadata.showFileList'), type: 'boolean', group: 'appearance' },
      {
        key: 'buttonText',
        label: componentText('metadata.buttonText'),
        type: 'string',
        group: 'appearance',
        description: componentText('metadata.textOnTheUploadButton'),
      },
      {
        key: 'hint',
        label: componentText('metadata.hintText'),
        type: 'string',
        group: 'appearance',
        description: componentText('metadata.hintDisplayedInTheUploadArea'),
      },
    ],
    tags: ['upload', 'file', 'attachment', 'form'],
  },
];

export const DISPLAY_COMPONENT_CONFIGS: ComponentConfig[] = [
  {
    type: 'display',
    name: componentText('metadata.textDisplay'),
    category: 'display',
    icon: '📖',
    description: componentText('metadata.displayTextContent'),
    defaultProps: {
      text: '显示文本',
      size: 'medium',
      color: 'default',
      weight: 'normal',
      align: 'left',
    },
    propertySchema: [
      { key: 'text', label: componentText('metadata.displayText'), type: 'string', required: true, group: 'basic' },
      {
        key: 'size',
        label: componentText('metadata.fontSize'),
        type: 'select',
        options: [
          { label: componentText('metadata.small'), value: 'small' },
          { label: componentText('metadata.medium'), value: 'medium' },
          { label: componentText('metadata.large'), value: 'large' },
          { label: componentText('metadata.extraLarge'), value: 'xlarge' },
        ],
        group: 'appearance',
      },
      {
        key: 'weight',
        label: componentText('metadata.fontWeight'),
        type: 'select',
        options: [
          { label: componentText('metadata.normal'), value: 'normal' },
          { label: componentText('metadata.bold'), value: 'bold' },
          { label: componentText('metadata.light'), value: 'light' },
        ],
        group: 'appearance',
      },
      {
        key: 'align',
        label: componentText('metadata.alignment'),
        type: 'select',
        options: [
          { label: componentText('metadata.alignLeft'), value: 'left' },
          { label: componentText('metadata.center'), value: 'center' },
          { label: componentText('metadata.alignRight'), value: 'right' },
        ],
        group: 'appearance',
      },
      { key: 'color', label: componentText('metadata.textColor'), type: 'color', group: 'appearance' },
    ],
    tags: ['text', 'display', 'content'],
  },
  {
    type: 'image',
    name: componentText('metadata.image'),
    category: 'display',
    icon: '🖼️',
    description: componentText('metadata.imageDisplayComponent'),
    defaultProps: {
      src: '',
      alt: '图片',
      width: 'auto',
      height: 'auto',
      fit: 'cover',
      lazy: true,
    },
    propertySchema: [
      { key: 'src', label: componentText('metadata.imageURL'), type: 'string', required: true, group: 'basic' },
      { key: 'alt', label: componentText('metadata.alternativeText'), type: 'string', group: 'basic' },
      SHARED_PROPERTIES.WIDTH_PROPERTY,
      SHARED_PROPERTIES.HEIGHT_PROPERTY,
      {
        key: 'fit',
        label: componentText('metadata.fit'),
        type: 'select',
        options: [
          { label: componentText('metadata.cover'), value: 'cover' },
          { label: componentText('metadata.contain'), value: 'contain' },
          { label: componentText('metadata.filled'), value: 'fill' },
          { label: componentText('metadata.scaleDown'), value: 'scale-down' },
        ],
        group: 'appearance',
      },
      { key: 'lazy', label: componentText('metadata.lazyLoading'), type: 'boolean', group: 'behavior' },
    ],
    tags: ['image', 'picture', 'media', 'display'],
  },
  {
    type: 'table',
    name: componentText('metadata.table'),
    category: 'display',
    icon: '📊',
    description: componentText('metadata.dataTableDisplayComponent'),
    defaultProps: {
      columns: [],
      data: [],
      pagination: true,
      pageSize: 10,
      bordered: true,
      striped: false,
    },
    propertySchema: [
      { key: 'columns', label: componentText('metadata.columnConfiguration'), type: 'array', group: 'basic', description: componentText('metadata.tableColumnConfiguration') },
      { key: 'data', label: componentText('metadata.dataSource'), type: 'array', group: 'basic', description: componentText('metadata.tableData') },
      { key: 'pagination', label: componentText('metadata.pagination'), type: 'boolean', group: 'behavior' },
      { key: 'pageSize', label: componentText('metadata.pageSize'), type: 'number', group: 'behavior', min: 1, max: 100 },
      { key: 'bordered', label: componentText('metadata.showBorder'), type: 'boolean', group: 'appearance' },
      { key: 'striped', label: componentText('metadata.stripedRows'), type: 'boolean', group: 'appearance' },
    ],
    tags: ['table', 'data', 'grid', 'display'],
  },
  {
    type: 'decisionrolloutmonitor',
    name: 'Decision Rollout Monitor',
    category: 'display',
    icon: 'split',
    description: 'DecisionOps rollout policy monitor and promote/rollback control for DSL pages.',
    defaultProps: {
      initialDecisionCode: 'complaint_sla_deadline',
    },
    propertySchema: [
      {
        key: 'initialDecisionCode',
        label: 'Initial decision code',
        type: 'string',
        group: 'basic',
        description: 'Decision code loaded when the rollout monitor custom block mounts.',
      },
    ],
    tags: ['decisionops', 'rollout', 'governance', 'custom-block'],
  },
  {
    type: 'decisionfieldimpact',
    name: 'Decision Field Impact',
    category: 'display',
    icon: 'git-branch',
    description: 'DecisionOps field impact graph and schema-change preflight for DSL pages.',
    defaultProps: {
      initialFieldRef: 'record.data.priority',
      initialCurrentDataType: 'string',
    },
    propertySchema: [
      {
        key: 'initialFieldRef',
        label: 'Initial field ref',
        type: 'string',
        group: 'basic',
        description: 'Field reference loaded when the field-impact custom block mounts.',
      },
      {
        key: 'initialCurrentDataType',
        label: 'Initial current data type',
        type: 'string',
        group: 'basic',
        description: 'Current field data type used by preflight requests.',
      },
    ],
    tags: ['decisionops', 'impact', 'field', 'governance', 'custom-block'],
  },
  {
    type: 'decisionintegrationimpact',
    name: 'Decision Integration Impact',
    category: 'display',
    icon: 'network',
    description: 'DecisionOps connector/webhook impact graph for DSL detail pages.',
    defaultProps: {
      targetType: 'CONNECTOR',
    },
    propertySchema: [
      {
        key: 'targetType',
        label: 'Target type',
        type: 'select',
        options: [
          { label: 'Connector', value: 'CONNECTOR' },
          { label: 'Webhook', value: 'WEBHOOK' },
        ],
        group: 'basic',
        description: 'Integration target family.',
      },
      {
        key: 'targetCode',
        label: 'Target code',
        type: 'string',
        group: 'basic',
        description:
          'Optional explicit target code. Detail pages can omit this and use route recordPid.',
      },
    ],
    tags: ['decisionops', 'impact', 'integration', 'connector', 'webhook', 'custom-block'],
  },
  {
    type: 'decisionrulebinding',
    name: 'Decision Rule Binding',
    category: 'display',
    icon: 'git-branch',
    description: 'Rule-center condition and decision binding editor for DSL-hosted consumers.',
    defaultProps: {
      mode: 'combined',
      initialDecisionCode: 'approval_routing',
      initialVersionPolicy: 'LATEST_PUBLISHED',
    },
    propertySchema: [
      {
        key: 'mode',
        label: 'Mode',
        type: 'select',
        options: [
          { label: 'Condition + decision', value: 'combined' },
          { label: 'Condition only', value: 'condition' },
          { label: 'Decision only', value: 'decision' },
        ],
        group: 'basic',
        description: 'Editor sections rendered by the block.',
      },
      {
        key: 'initialDecisionCode',
        label: 'Initial decision code',
        type: 'string',
        group: 'basic',
        description: 'Decision code selected when the block mounts.',
      },
      {
        key: 'initialVersionPolicy',
        label: 'Initial version policy',
        type: 'select',
        options: [
          { label: 'Latest published', value: 'LATEST_PUBLISHED' },
          { label: 'Fixed version', value: 'FIXED_VERSION' },
          { label: 'Version tag', value: 'VERSION_TAG' },
          { label: 'Rollout', value: 'ROLLOUT' },
        ],
        group: 'basic',
        description: 'Version policy selected when the block mounts.',
      },
      {
        key: 'valueField',
        label: 'Value field',
        type: 'string',
        group: 'advanced',
        description: 'DSL form field path that stores the full RuleConsumerBinding JSON.',
      },
      {
        key: 'consumerType',
        label: 'Consumer type',
        type: 'select',
        options: [
          { label: 'Automation', value: 'AUTOMATION' },
          { label: 'BPM', value: 'BPM' },
          { label: 'SLA', value: 'SLA' },
          { label: 'Permission', value: 'PERMISSION' },
          { label: 'Event Policy', value: 'EVENT_POLICY' },
        ],
        group: 'advanced',
        description: 'Rule-center consumer family used for impact and trace metadata.',
      },
      {
        key: 'consumerCode',
        label: 'Consumer code',
        type: 'string',
        group: 'advanced',
        description: 'Automation code, process code, SLA code, permission code, or policy code.',
      },
      {
        key: 'consumerNodeId',
        label: 'Consumer node id',
        type: 'string',
        group: 'advanced',
        description: 'Optional node/action/rule id for designer or nested consumer surfaces.',
      },
      {
        key: 'showImpactPreview',
        label: 'Show impact preview',
        type: 'boolean',
        group: 'behavior',
        description: 'Render the decision impact preview section.',
      },
      {
        key: 'showTestRunner',
        label: 'Show test runner',
        type: 'boolean',
        group: 'behavior',
        description: 'Render the published decision test-runner section.',
      },
      {
        key: 'initialContextJson',
        label: 'Initial context JSON',
        type: 'object',
        group: 'advanced',
        description: 'Optional mock context used to initialize the test runner.',
      },
      {
        key: 'fields',
        label: 'Context fields',
        type: 'array',
        group: 'advanced',
        description:
          'Optional field options for condition and input mapping. Format: [{scope,path,label,dataType}].',
      },
      {
        key: 'decisions',
        label: 'Decision options',
        type: 'array',
        group: 'advanced',
        description: 'Optional decision options. Format: [{code,name}].',
      },
    ],
    tags: ['decisionops', 'rule-center', 'condition', 'decision-binding', 'custom-block'],
  },
  {
    type: 'decisionactionplan',
    name: 'Decision Action Plan',
    category: 'display',
    icon: 'workflow',
    description: 'Rule-center action catalog orchestration block for SLA, Automation, BPM and EventPolicy side effects.',
    defaultProps: {
      valueField: 'action_policy',
      title: 'Action plan',
      triggerLabel: 'Rule matched',
      defaultTrigger: 'RULE_MATCHED',
    },
    propertySchema: [
      {
        key: 'valueField',
        label: 'Value field',
        type: 'string',
        group: 'basic',
        description: 'DSL form field that stores the action policy JSON.',
      },
      {
        key: 'title',
        label: 'Title',
        type: 'string',
        group: 'basic',
        description: 'Section title rendered above the action chain.',
      },
      {
        key: 'triggerLabel',
        label: 'Trigger label',
        type: 'string',
        group: 'basic',
        description: 'Human-readable trigger label, for example SLA timeout.',
      },
      {
        key: 'defaultTrigger',
        label: 'Default trigger',
        type: 'string',
        group: 'advanced',
        description: 'Machine trigger code written when the policy is created.',
      },
      {
        key: 'consumerType',
        label: 'Consumer type',
        type: 'select',
        options: [
          { label: 'SLA', value: 'SLA' },
          { label: 'Automation', value: 'AUTOMATION' },
          { label: 'BPM', value: 'BPM' },
          { label: 'Event Policy', value: 'EVENT_POLICY' },
        ],
        group: 'advanced',
        description: 'Consumer family used to read action-catalog availability.',
      },
      {
        key: 'logsUrl',
        label: 'Logs URL',
        type: 'string',
        group: 'advanced',
        description: 'Optional execution-log link template.',
      },
      {
        key: 'readOnly',
        label: 'Read only',
        type: 'boolean',
        group: 'behavior',
        description: 'Render the action policy as a read-only summary.',
      },
    ],
    tags: ['decisionops', 'rule-center', 'action-catalog', 'side-effect', 'custom-block'],
  },
];

export const INTERACTION_COMPONENT_CONFIGS: ComponentConfig[] = [
  {
    type: 'button',
    name: componentText('metadata.button'),
    category: 'interaction',
    icon: '🔘',
    description: componentText('metadata.interactiveButtonComponent'),
    defaultProps: {
      text: '按钮',
      type: 'primary',
      size: 'medium',
      disabled: false,
      loading: false,
      block: false,
    },
    propertySchema: [
      { key: 'text', label: componentText('metadata.buttonText'), type: 'string', required: true, group: 'basic' },
      {
        key: 'type',
        label: componentText('metadata.buttonType'),
        type: 'select',
        options: [
          { label: componentText('metadata.primary'), value: 'primary' },
          { label: componentText('metadata.secondary'), value: 'secondary' },
          { label: componentText('metadata.success'), value: 'success' },
          { label: componentText('metadata.warning'), value: 'warning' },
          { label: componentText('metadata.danger'), value: 'danger' },
          { label: componentText('metadata.link'), value: 'link' },
        ],
        group: 'appearance',
      },
      {
        key: 'size',
        label: componentText('metadata.size'),
        type: 'select',
        options: [
          { label: componentText('metadata.small'), value: 'small' },
          { label: componentText('metadata.medium'), value: 'medium' },
          { label: componentText('metadata.large'), value: 'large' },
        ],
        group: 'appearance',
      },
      { key: 'disabled', label: componentText('metadata.disabled'), type: 'boolean', group: 'behavior' },
      { key: 'loading', label: componentText('metadata.loading'), type: 'boolean', group: 'behavior' },
      { key: 'block', label: componentText('metadata.blockButton'), type: 'boolean', group: 'appearance' },
    ],
    tags: ['button', 'click', 'action', 'interaction'],
  },
];

export const LAYOUT_COMPONENT_CONFIGS: ComponentConfig[] = [
  {
    type: 'div',
    name: componentText('metadata.divContainer'),
    category: 'layout',
    icon: '📦',
    description: componentText('metadata.generalDivContainerWithEditablePropertiesAndAutomaticGridOccupancy'),
    defaultProps: {
      width: 12,
      height: 'auto',
      padding: 16,
      margin: 0,
      backgroundColor: 'transparent',
      borderRadius: 0,
      border: 'none',
      boxShadow: 'none',
      display: 'block',
      position: 'static',
      zIndex: 'auto',
      overflow: 'visible',
    },
    propertySchema: [
      // 基础属性
      SHARED_PROPERTIES.WIDTH_PROPERTY,
      SHARED_PROPERTIES.HEIGHT_PROPERTY,

      // 外观属性
      SHARED_PROPERTIES.APPEARANCE_PROPERTIES.BACKGROUND_COLOR,
      SHARED_PROPERTIES.APPEARANCE_PROPERTIES.BORDER_RADIUS,
      SHARED_PROPERTIES.APPEARANCE_PROPERTIES.BORDER,
      SHARED_PROPERTIES.APPEARANCE_PROPERTIES.BOX_SHADOW,

      // 间距属性
      SHARED_PROPERTIES.SPACING_PROPERTIES.PADDING,
      SHARED_PROPERTIES.SPACING_PROPERTIES.MARGIN,

      // 布局属性
      {
        key: 'display',
        label: componentText('metadata.display'),
        type: 'select',
        options: [
          { label: componentText('metadata.block'), value: 'block' },
          { label: componentText('metadata.inlineBlock'), value: 'inline-block' },
          { label: componentText('metadata.flex'), value: 'flex' },
          { label: componentText('metadata.grid'), value: 'grid' },
          { label: componentText('metadata.hidden'), value: 'none' },
        ],
        group: 'layout',
      },
      {
        key: 'position',
        label: componentText('metadata.position'),
        type: 'select',
        options: [
          { label: componentText('metadata.static'), value: 'static' },
          { label: componentText('metadata.relative'), value: 'relative' },
          { label: componentText('metadata.absolute'), value: 'absolute' },
          { label: componentText('metadata.fixed'), value: 'fixed' },
          { label: componentText('metadata.sticky'), value: 'sticky' },
        ],
        group: 'layout',
      },
      {
        key: 'zIndex',
        label: componentText('metadata.zIndex'),
        type: 'string',
        group: 'layout',
        description: componentText('metadata.stackingOrderSuchAsAuto1Or10'),
      },
      {
        key: 'overflow',
        label: componentText('metadata.overflow'),
        type: 'select',
        options: [
          { label: componentText('metadata.visible'), value: 'visible' },
          { label: componentText('metadata.hidden'), value: 'hidden' },
          { label: componentText('metadata.scroll'), value: 'scroll' },
          { label: componentText('metadata.auto'), value: 'auto' },
        ],
        group: 'layout',
      },
    ],
    tags: ['div', 'container', 'layout', 'basic', 'grid'],
  },
  {
    type: 'form',
    name: componentText('metadata.formContainer'),
    category: 'layout',
    icon: '📋',
    description: componentText('metadata.formLayoutContainer'),
    defaultProps: {
      title: '表单',
      layout: 'vertical',
      labelWidth: 'auto',
      size: 'medium',
      bordered: false,
    },
    propertySchema: [
      { key: 'title', label: componentText('metadata.formTitle'), type: 'string', group: 'basic' },
      {
        key: 'layout',
        label: componentText('metadata.layout'),
        type: 'select',
        options: [
          { label: componentText('metadata.vertical'), value: 'vertical' },
          { label: componentText('metadata.horizontal'), value: 'horizontal' },
          { label: componentText('metadata.inline'), value: 'inline' },
        ],
        group: 'appearance',
      },
      { key: 'labelWidth', label: componentText('metadata.labelWidth'), type: 'string', group: 'appearance' },
      {
        key: 'size',
        label: componentText('metadata.size'),
        type: 'select',
        options: [
          { label: componentText('metadata.small'), value: 'small' },
          { label: componentText('metadata.medium'), value: 'medium' },
          { label: componentText('metadata.large'), value: 'large' },
        ],
        group: 'appearance',
      },
      { key: 'bordered', label: componentText('metadata.showBorder'), type: 'boolean', group: 'appearance' },
    ],
    tags: ['form', 'container', 'layout'],
  },
  {
    type: 'navigation',
    name: componentText('metadata.navigation'),
    category: 'layout',
    icon: '🧭',
    description: componentText('metadata.horizontalNavigationWithComponentSelectionAndDataSourceConfiguration'),
    defaultProps: {
      theme: 'light',
      items: [
        { key: 'home', label: '首页', href: '/' },
        { key: 'about', label: '关于', href: '/about' },
      ],
      selectedKey: 'home',
      collapsed: false,
      width: 12,
      height: 'auto',
      targetComponent: '',
      dataSource: '',
    },
    propertySchema: [
      {
        key: 'theme',
        label: componentText('metadata.theme'),
        type: 'select',
        options: [
          { label: componentText('metadata.light198'), value: 'light' },
          { label: componentText('metadata.dark'), value: 'dark' },
        ],
        group: 'appearance',
      },
      {
        key: 'items',
        label: componentText('metadata.navigationItems'),
        type: 'array',
        group: 'basic',
        description: componentText('metadata.formatKeyUniqueKeyLabelDisplayTextHrefLinkURL'),
      },
      { key: 'selectedKey', label: componentText('metadata.selectedItem'), type: 'string', group: 'behavior' },
      { key: 'collapsed', label: componentText('metadata.collapsed'), type: 'boolean', group: 'behavior' },
      SHARED_PROPERTIES.WIDTH_PROPERTY,
      SHARED_PROPERTIES.HEIGHT_PROPERTY,
      {
        key: 'targetComponent',
        label: componentText('metadata.targetComponent'),
        type: 'component-select',
        group: 'behavior',
        description: componentText('metadata.selectTheComponentToAssociate'),
      },
      {
        key: 'dataSource',
        label: componentText('metadata.dataSource'),
        type: 'datasource-select',
        group: 'basic',
        description: componentText('metadata.selectADataSource'),
      },
    ],
    tags: ['navigation', 'menu', 'nav', 'layout'],
  },
  {
    type: 'container',
    name: componentText('metadata.container'),
    category: 'layout',
    icon: '📦',
    description: componentText('metadata.generalLayoutContainerWithPaddingBordersAndOtherStyles'),
    defaultProps: {
      padding: 16,
      margin: 0,
      backgroundColor: 'transparent',
      borderRadius: 0,
      bordered: false,
      shadow: 'none',
      width: '100%',
      height: 'auto',
      minHeight: 'auto',
    },
    propertySchema: [
      { key: 'padding', label: componentText('metadata.padding'), type: 'number', group: 'appearance', min: 0, max: 100 },
      { key: 'margin', label: componentText('metadata.margin'), type: 'number', group: 'appearance', min: 0, max: 100 },
      { key: 'backgroundColor', label: componentText('metadata.backgroundColor'), type: 'color', group: 'appearance' },
      { key: 'borderRadius', label: componentText('metadata.borderRadius'), type: 'number', group: 'appearance', min: 0, max: 50 },
      { key: 'bordered', label: componentText('metadata.showBorder'), type: 'boolean', group: 'appearance' },
      {
        key: 'shadow',
        label: componentText('metadata.shadow'),
        type: 'select',
        options: [
          { label: componentText('metadata.none'), value: 'none' },
          { label: componentText('metadata.small'), value: 'small' },
          { label: componentText('metadata.medium'), value: 'medium' },
          { label: componentText('metadata.large'), value: 'large' },
        ],
        group: 'appearance',
      },
      SHARED_PROPERTIES.WIDTH_PROPERTY,
      SHARED_PROPERTIES.HEIGHT_PROPERTY,
      { key: 'minHeight', label: componentText('metadata.minimumHeight'), type: 'string', group: 'appearance' },
    ],
    tags: ['container', 'wrapper', 'box', 'layout'],
  },
  {
    type: 'grid',
    name: componentText('metadata.gridLayout'),
    category: 'layout',
    icon: '⚏',
    description: componentText('metadata.gridLayoutContainerWithResponsiveColumns'),
    defaultProps: {
      columns: 12,
      gutter: 16,
      justify: 'start',
      align: 'top',
      wrap: true,
      responsive: true,
    },
    propertySchema: [
      { key: 'columns', label: componentText('metadata.columns'), type: 'number', group: 'basic', min: 1, max: 24 },
      { key: 'gutter', label: componentText('metadata.gap'), type: 'number', group: 'appearance', min: 0, max: 48 },
      {
        key: 'justify',
        label: componentText('metadata.horizontalAlignment'),
        type: 'select',
        options: [
          { label: componentText('metadata.alignLeft'), value: 'start' },
          { label: componentText('metadata.center'), value: 'center' },
          { label: componentText('metadata.alignRight'), value: 'end' },
          { label: componentText('metadata.spaceBetween'), value: 'space-between' },
          { label: componentText('metadata.spaceAround'), value: 'space-around' },
        ],
        group: 'appearance',
      },
      {
        key: 'align',
        label: componentText('metadata.verticalAlignment'),
        type: 'select',
        options: [
          { label: componentText('metadata.top'), value: 'top' },
          { label: componentText('metadata.center'), value: 'middle' },
          { label: componentText('metadata.bottom'), value: 'bottom' },
        ],
        group: 'appearance',
      },
      { key: 'wrap', label: componentText('metadata.wrapAutomatically'), type: 'boolean', group: 'behavior' },
      { key: 'responsive', label: componentText('metadata.responsive'), type: 'boolean', group: 'behavior' },
    ],
    tags: ['grid', 'layout', 'responsive', 'columns'],
  },
  {
    type: 'flex',
    name: componentText('metadata.flexLayout'),
    category: 'layout',
    icon: '🔄',
    description: componentText('metadata.flexibleLayoutContainerBasedOnFlexbox'),
    defaultProps: {
      direction: 'row',
      justify: 'flex-start',
      align: 'stretch',
      wrap: 'nowrap',
      gap: 8,
      flex: '1',
    },
    propertySchema: [
      {
        key: 'direction',
        label: componentText('metadata.direction'),
        type: 'select',
        options: [
          { label: componentText('metadata.horizontal'), value: 'row' },
          { label: componentText('metadata.vertical'), value: 'column' },
          { label: componentText('metadata.rowReverse'), value: 'row-reverse' },
          { label: componentText('metadata.columnReverse'), value: 'column-reverse' },
        ],
        group: 'basic',
      },
      {
        key: 'justify',
        label: componentText('metadata.mainAxisAlignment'),
        type: 'select',
        options: [
          { label: componentText('metadata.start'), value: 'flex-start' },
          { label: componentText('metadata.center'), value: 'center' },
          { label: componentText('metadata.end'), value: 'flex-end' },
          { label: componentText('metadata.spaceBetween'), value: 'space-between' },
          { label: componentText('metadata.spaceAround'), value: 'space-around' },
          { label: componentText('metadata.spaceEvenly'), value: 'space-evenly' },
        ],
        group: 'appearance',
      },
      {
        key: 'align',
        label: componentText('metadata.crossAxisAlignment'),
        type: 'select',
        options: [
          { label: componentText('metadata.stretch'), value: 'stretch' },
          { label: componentText('metadata.start'), value: 'flex-start' },
          { label: componentText('metadata.center'), value: 'center' },
          { label: componentText('metadata.end'), value: 'flex-end' },
          { label: componentText('metadata.baseline'), value: 'baseline' },
        ],
        group: 'appearance',
      },
      {
        key: 'wrap',
        label: componentText('metadata.wrapMode'),
        type: 'select',
        options: [
          { label: componentText('metadata.noWrap'), value: 'nowrap' },
          { label: componentText('metadata.wrap'), value: 'wrap' },
          { label: componentText('metadata.wrapReverse'), value: 'wrap-reverse' },
        ],
        group: 'behavior',
      },
      { key: 'gap', label: componentText('metadata.gap'), type: 'number', group: 'appearance', min: 0, max: 48 },
      { key: 'flex', label: componentText('metadata.flexFactor'), type: 'string', group: 'behavior' },
    ],
    tags: ['flex', 'flexbox', 'layout', 'responsive'],
  },
  {
    type: 'columns',
    name: componentText('metadata.columnLayout'),
    category: 'layout',
    icon: '📰',
    description: componentText('metadata.multiColumnLayoutWithEqualOrCustomWidths'),
    defaultProps: {
      count: 2,
      gutter: 16,
      split: false,
      responsive: true,
      breakpoints: {
        xs: 1,
        sm: 1,
        md: 2,
        lg: 2,
        xl: 2,
      },
    },
    propertySchema: [
      { key: 'count', label: componentText('metadata.columns'), type: 'number', group: 'basic', min: 1, max: 6 },
      { key: 'gutter', label: componentText('metadata.columnGap'), type: 'number', group: 'appearance', min: 0, max: 48 },
      { key: 'split', label: componentText('metadata.showDividers'), type: 'boolean', group: 'appearance' },
      { key: 'responsive', label: componentText('metadata.responsive'), type: 'boolean', group: 'behavior' },
      {
        key: 'breakpoints',
        label: componentText('metadata.breakpointConfiguration'),
        type: 'object',
        group: 'behavior',
        description: componentText('metadata.columnCountsForDifferentScreenSizes'),
      },
    ],
    tags: ['columns', 'layout', 'responsive', 'multi-column'],
  },
  {
    type: 'card',
    name: componentText('metadata.cardContainer'),
    category: 'layout',
    icon: '🃏',
    description: componentText('metadata.cardContainerWithHeaderContentAndActionAreas'),
    defaultProps: {
      title: '卡片标题',
      showHeader: true,
      showFooter: false,
      bordered: true,
      hoverable: false,
      loading: false,
      size: 'default',
      headerStyle: {},
      bodyStyle: { padding: 24 },
      footerStyle: {},
    },
    propertySchema: [
      { key: 'title', label: componentText('metadata.cardTitle'), type: 'string', group: 'basic' },
      { key: 'showHeader', label: componentText('metadata.showHeader'), type: 'boolean', group: 'appearance' },
      { key: 'showFooter', label: componentText('metadata.showFooter'), type: 'boolean', group: 'appearance' },
      { key: 'bordered', label: componentText('metadata.showBorder'), type: 'boolean', group: 'appearance' },
      { key: 'hoverable', label: componentText('metadata.hoverEffect'), type: 'boolean', group: 'behavior' },
      { key: 'loading', label: componentText('metadata.loadingState'), type: 'boolean', group: 'behavior' },
      {
        key: 'size',
        label: componentText('metadata.size'),
        type: 'select',
        options: [
          { label: componentText('metadata.small'), value: 'small' },
          { label: componentText('metadata.default'), value: 'default' },
          { label: componentText('metadata.large'), value: 'large' },
        ],
        group: 'appearance',
      },
      {
        key: 'bodyStyle',
        label: componentText('metadata.contentStyle'),
        type: 'object',
        group: 'appearance',
        description: componentText('metadata.cssStyleObject'),
      },
    ],
    tags: ['card', 'container', 'panel', 'layout'],
  },
];

export const DATETIME_COMPONENT_CONFIGS: ComponentConfig[] = [
  {
    type: 'date',
    name: componentText('metadata.dateDisplay'),
    category: 'datetime',
    icon: '📅',
    description: componentText('metadata.dateDisplayComponent'),
    defaultProps: {
      value: '',
      format: 'YYYY-MM-DD',
      relative: false,
    },
    propertySchema: [
      { key: 'value', label: componentText('metadata.dateValue'), type: 'date', group: 'basic' },
      {
        key: 'format',
        label: componentText('metadata.displayFormat'),
        type: 'select',
        options: [
          { label: 'YYYY-MM-DD', value: 'YYYY-MM-DD' },
          { label: 'YYYY/MM/DD', value: 'YYYY/MM/DD' },
          { label: 'DD/MM/YYYY', value: 'DD/MM/YYYY' },
          { label: 'MM/DD/YYYY', value: 'MM/DD/YYYY' },
        ],
        group: 'appearance',
      },
      { key: 'relative', label: componentText('metadata.relativeTime'), type: 'boolean', group: 'behavior' },
    ],
    tags: ['date', 'time', 'display'],
  },
  {
    type: 'datetime',
    name: componentText('metadata.datetimeDisplay'),
    category: 'datetime',
    icon: '🕐',
    description: componentText('metadata.datetimeDisplayComponent'),
    defaultProps: {
      value: '',
      format: 'YYYY-MM-DD HH:mm:ss',
      showSeconds: true,
      relative: false,
    },
    propertySchema: [
      { key: 'value', label: componentText('metadata.datetimeValue'), type: 'string', group: 'basic' },
      { key: 'format', label: componentText('metadata.displayFormat'), type: 'string', group: 'appearance' },
      { key: 'showSeconds', label: componentText('metadata.showSeconds'), type: 'boolean', group: 'behavior' },
      { key: 'relative', label: componentText('metadata.relativeTime'), type: 'boolean', group: 'behavior' },
    ],
    tags: ['datetime', 'time', 'display'],
  },
];

export const CHART_COMPONENT_CONFIGS: ComponentConfig[] = [
  // SmartChart 组件配置
  {
    type: 'smart-number-card',
    name: componentText('metadata.numberCard'),
    category: 'chart',
    icon: '🔢',
    description: componentText('metadata.kpiMetricDisplay'),
    defaultProps: {
      title: '指标',
      format: 'number',
      precision: 0,
    },
    propertySchema: [
      { key: 'title', label: componentText('metadata.title'), type: 'string', group: 'basic' },
      { key: 'icon', label: componentText('metadata.icon'), type: 'icon', group: 'basic' },
      {
        key: 'format',
        label: componentText('metadata.format'),
        type: 'select',
        options: [
          { label: componentText('metadata.number'), value: 'number' },
          { label: componentText('metadata.currency'), value: 'currency' },
          { label: componentText('metadata.percentage'), value: 'percent' },
        ],
        group: 'basic',
      },
      { key: 'precision', label: componentText('metadata.decimalPlaces'), type: 'number', group: 'basic' },
      {
        key: 'dataSource.type',
        label: componentText('metadata.dataSourceType'),
        type: 'select',
        options: [
          { label: componentText('metadata.aggregateQuery'), value: 'aggregate' },
          { label: 'NamedQuery', value: 'namedQuery' },
        ],
        group: 'advanced',
      },
      { key: 'dataSource.modelCode', label: componentText('metadata.dataModel'), type: 'string', group: 'advanced' },
      { key: 'dataSource.metrics', label: componentText('metadata.metricConfiguration'), type: 'object', group: 'advanced' },
    ],
    tags: ['chart', 'kpi', 'number', '数字卡片'],
  },
  {
    type: 'smart-bar-chart',
    name: componentText('metadata.barChart'),
    category: 'chart',
    icon: '📊',
    description: componentText('metadata.barChartForComparisons'),
    defaultProps: {
      horizontal: false,
      stacked: false,
      showLabel: false,
    },
    propertySchema: [
      { key: 'title', label: componentText('metadata.title'), type: 'string', group: 'basic' },
      { key: 'horizontal', label: componentText('metadata.horizontal275'), type: 'boolean', group: 'appearance' },
      { key: 'stacked', label: componentText('metadata.stacking'), type: 'boolean', group: 'appearance' },
      {
        key: 'dataSource.type',
        label: componentText('metadata.dataSourceType'),
        type: 'select',
        options: [
          { label: componentText('metadata.aggregateQuery'), value: 'aggregate' },
          { label: 'NamedQuery', value: 'namedQuery' },
        ],
        group: 'advanced',
      },
      { key: 'dataSource.modelCode', label: componentText('metadata.dataModel'), type: 'string', group: 'advanced' },
      { key: 'dataSource.dimensions', label: componentText('metadata.dimensionField'), type: 'array', group: 'advanced' },
      { key: 'dataSource.metrics', label: componentText('metadata.metricConfiguration'), type: 'object', group: 'advanced' },
      { key: 'drillDown.enabled', label: componentText('metadata.enableDrilldown'), type: 'boolean', group: 'behavior' },
      { key: 'linkage.enabled', label: componentText('metadata.enableLinkage'), type: 'boolean', group: 'behavior' },
      { key: 'linkage.groupId', label: componentText('metadata.linkageGroup'), type: 'string', group: 'behavior' },
    ],
    tags: ['chart', 'bar', 'column', '柱状图', '对比'],
  },
  {
    type: 'smart-line-chart',
    name: componentText('metadata.lineChart'),
    category: 'chart',
    icon: '📈',
    description: componentText('metadata.lineOrAreaChartForTrends'),
    defaultProps: {
      smooth: false,
      area: false,
    },
    propertySchema: [
      { key: 'title', label: componentText('metadata.title'), type: 'string', group: 'basic' },
      { key: 'smooth', label: componentText('metadata.smoothCurve'), type: 'boolean', group: 'appearance' },
      { key: 'area', label: componentText('metadata.areaChart'), type: 'boolean', group: 'appearance' },
      {
        key: 'dataSource.type',
        label: componentText('metadata.dataSourceType'),
        type: 'select',
        options: [
          { label: componentText('metadata.aggregateQuery'), value: 'aggregate' },
          { label: 'NamedQuery', value: 'namedQuery' },
        ],
        group: 'advanced',
      },
      { key: 'dataSource.modelCode', label: componentText('metadata.dataModel'), type: 'string', group: 'advanced' },
      { key: 'dataSource.dimensions', label: componentText('metadata.dimensionField'), type: 'array', group: 'advanced' },
      { key: 'dataSource.metrics', label: componentText('metadata.metricConfiguration'), type: 'object', group: 'advanced' },
      { key: 'drillDown.enabled', label: componentText('metadata.enableDrilldown'), type: 'boolean', group: 'behavior' },
      { key: 'linkage.enabled', label: componentText('metadata.enableLinkage'), type: 'boolean', group: 'behavior' },
      { key: 'linkage.groupId', label: componentText('metadata.linkageGroup'), type: 'string', group: 'behavior' },
    ],
    tags: ['chart', 'line', 'trend', '折线图', '趋势'],
  },
  {
    type: 'smart-pie-chart',
    name: componentText('metadata.pieChart'),
    category: 'chart',
    icon: '🥧',
    description: componentText('metadata.pieOrDonutChartForProportions'),
    defaultProps: {
      donut: false,
      showLabel: true,
    },
    propertySchema: [
      { key: 'title', label: componentText('metadata.title'), type: 'string', group: 'basic' },
      { key: 'donut', label: componentText('metadata.doughnut'), type: 'boolean', group: 'appearance' },
      { key: 'showLabel', label: componentText('metadata.showLabels'), type: 'boolean', group: 'appearance' },
      {
        key: 'dataSource.type',
        label: componentText('metadata.dataSourceType'),
        type: 'select',
        options: [
          { label: componentText('metadata.aggregateQuery'), value: 'aggregate' },
          { label: 'NamedQuery', value: 'namedQuery' },
        ],
        group: 'advanced',
      },
      { key: 'dataSource.modelCode', label: componentText('metadata.dataModel'), type: 'string', group: 'advanced' },
      { key: 'dataSource.dimensions', label: componentText('metadata.dimensionField'), type: 'array', group: 'advanced' },
      { key: 'dataSource.metrics', label: componentText('metadata.metricConfiguration'), type: 'object', group: 'advanced' },
      { key: 'drillDown.enabled', label: componentText('metadata.enableDrilldown'), type: 'boolean', group: 'behavior' },
      { key: 'linkage.enabled', label: componentText('metadata.enableLinkage'), type: 'boolean', group: 'behavior' },
      { key: 'linkage.groupId', label: componentText('metadata.linkageGroup'), type: 'string', group: 'behavior' },
    ],
    tags: ['chart', 'pie', 'donut', '饼图', '占比'],
  },
  {
    type: 'smart-kanban',
    name: componentText('metadata.kanban'),
    category: 'chart',
    icon: '📋',
    description: componentText('metadata.kanbanViewWithDraggableCards'),
    defaultProps: {
      draggable: false,
      showCount: true,
      showAggregations: true,
    },
    propertySchema: [
      { key: 'title', label: componentText('metadata.title'), type: 'string', group: 'basic' },
      { key: 'draggable', label: componentText('metadata.allowDragging'), type: 'boolean', group: 'basic' },
      { key: 'showCount', label: componentText('metadata.showCount'), type: 'boolean', group: 'basic' },
      { key: 'showAggregations', label: componentText('metadata.showStatistics'), type: 'boolean', group: 'basic' },
      {
        key: 'dataSource.type',
        label: componentText('metadata.dataSourceType'),
        type: 'select',
        options: [{ label: componentText('metadata.aggregateQuery'), value: 'aggregate' }],
        group: 'dataSource',
      },
      { key: 'dataSource.modelCode', label: componentText('metadata.dataModel'), type: 'model-select', group: 'dataSource' },
      {
        key: 'dataSource.groupByField',
        label: componentText('metadata.groupField'),
        type: 'field-select',
        group: 'dataSource',
      },
      {
        key: 'dataSource.titleField',
        label: componentText('metadata.titleField'),
        type: 'field-select',
        group: 'dataSource',
      },
      {
        key: 'dataSource.descriptionField',
        label: componentText('metadata.descriptionField'),
        type: 'field-select',
        group: 'dataSource',
      },
    ],
    tags: ['chart', 'kanban', 'board', '看板', '拖拽'],
  },
  // 基础图表组件配置
  {
    type: 'bar-chart',
    name: componentText('metadata.barChart'),
    category: 'chart',
    icon: '📊',
    description: componentText('metadata.barChartComparingCategories'),
    defaultProps: {
      title: '柱状图',
      width: '100%',
      height: 400,
      data: [],
      xField: 'category',
      yField: 'value',
      color: '#1890ff',
      showLegend: true,
      showGrid: true,
      showTooltip: true,
    },
    propertySchema: [
      { key: 'title', label: componentText('metadata.chartTitle'), type: 'string', group: 'basic' },
      SHARED_PROPERTIES.WIDTH_PROPERTY,
      SHARED_PROPERTIES.HEIGHT_PROPERTY,
      {
        key: 'data',
        label: componentText('metadata.dataSource'),
        type: 'array',
        group: 'basic',
        description: componentText('metadata.chartDataCategoryCategoryValue10'),
      },
      { key: 'xField', label: componentText('metadata.xAxisField'), type: 'string', group: 'basic' },
      { key: 'yField', label: componentText('metadata.yAxisField'), type: 'string', group: 'basic' },
      { key: 'color', label: componentText('metadata.color'), type: 'color', group: 'appearance' },
      { key: 'showLegend', label: componentText('metadata.showLegend'), type: 'boolean', group: 'appearance' },
      { key: 'showGrid', label: componentText('metadata.showGrid'), type: 'boolean', group: 'appearance' },
      { key: 'showTooltip', label: componentText('metadata.showTooltip'), type: 'boolean', group: 'behavior' },
    ],
    tags: ['chart', 'bar', 'column', 'data', 'visualization'],
  },
  {
    type: 'line-chart',
    name: componentText('metadata.lineChart'),
    category: 'chart',
    icon: '📈',
    description: componentText('metadata.lineChartShowingDataTrends'),
    defaultProps: {
      title: '折线图',
      width: '100%',
      height: 400,
      data: [],
      xField: 'date',
      yField: 'value',
      color: '#52c41a',
      smooth: true,
      showPoints: true,
      showLegend: true,
      showGrid: true,
      showTooltip: true,
    },
    propertySchema: [
      { key: 'title', label: componentText('metadata.chartTitle'), type: 'string', group: 'basic' },
      SHARED_PROPERTIES.WIDTH_PROPERTY,
      SHARED_PROPERTIES.HEIGHT_PROPERTY,
      {
        key: 'data',
        label: componentText('metadata.dataSource'),
        type: 'array',
        group: 'basic',
        description: componentText('metadata.chartDataDateDateValue10'),
      },
      { key: 'xField', label: componentText('metadata.xAxisField'), type: 'string', group: 'basic' },
      { key: 'yField', label: componentText('metadata.yAxisField'), type: 'string', group: 'basic' },
      { key: 'color', label: componentText('metadata.color'), type: 'color', group: 'appearance' },
      { key: 'smooth', label: componentText('metadata.smoothCurve'), type: 'boolean', group: 'appearance' },
      { key: 'showPoints', label: componentText('metadata.showDataPoints'), type: 'boolean', group: 'appearance' },
      { key: 'showLegend', label: componentText('metadata.showLegend'), type: 'boolean', group: 'appearance' },
      { key: 'showGrid', label: componentText('metadata.showGrid'), type: 'boolean', group: 'appearance' },
      { key: 'showTooltip', label: componentText('metadata.showTooltip'), type: 'boolean', group: 'behavior' },
    ],
    tags: ['chart', 'line', 'trend', 'data', 'visualization'],
  },
  {
    type: 'pie-chart',
    name: componentText('metadata.pieChart'),
    category: 'chart',
    icon: '🥧',
    description: componentText('metadata.pieChartShowingProportions'),
    defaultProps: {
      title: '饼图',
      width: '100%',
      height: 400,
      data: [],
      angleField: 'value',
      colorField: 'category',
      radius: 0.8,
      innerRadius: 0,
      showLegend: true,
      showLabels: true,
      showTooltip: true,
    },
    propertySchema: [
      { key: 'title', label: componentText('metadata.chartTitle'), type: 'string', group: 'basic' },
      SHARED_PROPERTIES.WIDTH_PROPERTY,
      SHARED_PROPERTIES.HEIGHT_PROPERTY,
      {
        key: 'data',
        label: componentText('metadata.dataSource'),
        type: 'array',
        group: 'basic',
        description: componentText('metadata.chartDataCategoryCategoryValue10'),
      },
      { key: 'angleField', label: componentText('metadata.angleField'), type: 'string', group: 'basic' },
      { key: 'colorField', label: componentText('metadata.colorField'), type: 'string', group: 'basic' },
      {
        key: 'radius',
        label: componentText('metadata.outerRadius'),
        type: 'number',
        group: 'appearance',
        min: 0.1,
        max: 1,
        defaultValue: 0.8,
      },
      {
        key: 'innerRadius',
        label: componentText('metadata.innerRadius'),
        type: 'number',
        group: 'appearance',
        min: 0,
        max: 0.9,
        defaultValue: 0,
      },
      { key: 'showLegend', label: componentText('metadata.showLegend'), type: 'boolean', group: 'appearance' },
      { key: 'showLabels', label: componentText('metadata.showLabels'), type: 'boolean', group: 'appearance' },
      { key: 'showTooltip', label: componentText('metadata.showTooltip'), type: 'boolean', group: 'behavior' },
    ],
    tags: ['chart', 'pie', 'donut', 'proportion', 'data', 'visualization'],
  },
  {
    type: 'area-chart',
    name: componentText('metadata.areaChart'),
    category: 'chart',
    icon: '🏔️',
    description: componentText('metadata.areaChartShowingCumulativeChanges'),
    defaultProps: {
      title: '面积图',
      width: '100%',
      height: 400,
      data: [],
      xField: 'date',
      yField: 'value',
      color: '#722ed1',
      smooth: true,
      fillOpacity: 0.6,
      showLegend: true,
      showGrid: true,
      showTooltip: true,
    },
    propertySchema: [
      { key: 'title', label: componentText('metadata.chartTitle'), type: 'string', group: 'basic' },
      SHARED_PROPERTIES.WIDTH_PROPERTY,
      SHARED_PROPERTIES.HEIGHT_PROPERTY,
      {
        key: 'data',
        label: componentText('metadata.dataSource'),
        type: 'array',
        group: 'basic',
        description: componentText('metadata.chartDataDateDateValue10'),
      },
      { key: 'xField', label: componentText('metadata.xAxisField'), type: 'string', group: 'basic' },
      { key: 'yField', label: componentText('metadata.yAxisField'), type: 'string', group: 'basic' },
      { key: 'color', label: componentText('metadata.color'), type: 'color', group: 'appearance' },
      { key: 'smooth', label: componentText('metadata.smoothCurve'), type: 'boolean', group: 'appearance' },
      {
        key: 'fillOpacity',
        label: componentText('metadata.fillOpacity'),
        type: 'number',
        group: 'appearance',
        min: 0,
        max: 1,
        defaultValue: 0.6,
      },
      { key: 'showLegend', label: componentText('metadata.showLegend'), type: 'boolean', group: 'appearance' },
      { key: 'showGrid', label: componentText('metadata.showGrid'), type: 'boolean', group: 'appearance' },
      { key: 'showTooltip', label: componentText('metadata.showTooltip'), type: 'boolean', group: 'behavior' },
    ],
    tags: ['chart', 'area', 'filled', 'trend', 'data', 'visualization'],
  },
];

// 合并所有组件配置
export const ALL_COMPONENT_CONFIGS: ComponentConfig[] = [
  ...FORM_COMPONENT_CONFIGS,
  ...DISPLAY_COMPONENT_CONFIGS,
  ...INTERACTION_COMPONENT_CONFIGS,
  ...LAYOUT_COMPONENT_CONFIGS,
  ...DATETIME_COMPONENT_CONFIGS,
  ...CHART_COMPONENT_CONFIGS,
];

const RUNTIME_AWARE_CONFIG_GROUPS = [
  FORM_COMPONENT_CONFIGS,
  DISPLAY_COMPONENT_CONFIGS,
  INTERACTION_COMPONENT_CONFIGS,
  LAYOUT_COMPONENT_CONFIGS,
  DATETIME_COMPONENT_CONFIGS,
  CHART_COMPONENT_CONFIGS,
];

RUNTIME_AWARE_CONFIG_GROUPS.forEach((group) => {
  group.forEach((config) => {
    const runtime = COMPONENT_RUNTIME_MANIFEST[config.type];
    if (runtime) {
      config.runtime = runtime;
    }
  });
});
