package com.auraboot.framework.crm;

import com.auraboot.framework.application.tenant.MetaContext;
import com.auraboot.framework.crm.service.LeadDeduplicationService;
import com.auraboot.framework.crm.service.LeadDeduplicationService.DeduplicationResult;
import com.auraboot.framework.integration.BaseIntegrationTest;
import com.auraboot.framework.meta.mapper.DynamicDataMapper;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Integration tests for LeadDeduplicationService — exact (email/phone) and fuzzy (company+name) matching.
 * <p>
 * Uses NOT_SUPPORTED propagation so seed data persists across ordered tests.
 *
 * @since 5.3.0
 */
@Slf4j
@DisplayName("Lead Deduplication Integration Tests (DD-01~DD-06)")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@Transactional(propagation = Propagation.NOT_SUPPORTED)
class LeadDeduplicationIntegrationTest extends BaseIntegrationTest {

    @Autowired
    private LeadDeduplicationService deduplicationService;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private DynamicDataMapper dynamicDataMapper;

    private final String runId = "dd-" + System.currentTimeMillis();
    private final String seedEmail = runId + "@acme-test.com";
    private final String seedPhone = "+86" + System.currentTimeMillis() % 10000000000L;
    private final String seedCompany = "Acme Corporation " + runId;
    private final String seedName = "John Smith";
    private Long seedLeadId;
    private Long tenantId;

    // ==================== Setup ====================

    private void ensureTableAndSeedData() {
        if (seedLeadId != null) return;

        tenantId = getTestTenant().getId();

        // Ensure table exists
        if (dynamicDataMapper.checkTableExistsWithoutTenant("mt_crm_lead") == 0) {
            jdbcTemplate.execute("""
                CREATE TABLE mt_crm_lead (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    pid VARCHAR(32) NOT NULL UNIQUE,
                    tenant_id BIGINT,
                    crm_lead_code VARCHAR(50) NOT NULL,
                    crm_lead_company VARCHAR(200) NOT NULL,
                    crm_lead_contact_name VARCHAR(100) NOT NULL,
                    crm_lead_contact_phone VARCHAR(50),
                    crm_lead_contact_email VARCHAR(200),
                    crm_lead_source VARCHAR(50),
                    crm_lead_requirement TEXT,
                    crm_lead_status VARCHAR(50),
                    created_at TIMESTAMPTZ DEFAULT NOW(),
                    updated_at TIMESTAMPTZ DEFAULT NOW(),
                    created_by BIGINT,
                    updated_by BIGINT
                )
            """);
            log.info("Created test table mt_crm_lead");
        }

        // Ensure pg_trgm extension
        try {
            jdbcTemplate.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm");
        } catch (Exception e) {
            log.warn("pg_trgm extension creation skipped: {}", e.getMessage());
        }

        // Insert seed lead record
        seedLeadId = System.currentTimeMillis();
        jdbcTemplate.update(
                "INSERT INTO mt_crm_lead " +
                "(id, pid, tenant_id, crm_lead_code, crm_lead_company, crm_lead_contact_name, " +
                "crm_lead_contact_phone, crm_lead_contact_email, crm_lead_source, crm_lead_requirement, " +
                "crm_lead_status, created_at, updated_at, created_by, updated_by) " +
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW(), 0, 0)",
                seedLeadId, "lead-" + seedLeadId, tenantId,
                "LD-" + runId,
                seedCompany,
                seedName,
                seedPhone,
                seedEmail,
                "manual",
                "Needs CRM solution",
                "new"
        );

        log.info("Seed lead created: id={}, tenant={}", seedLeadId, tenantId);
    }

    // ==================== DD-01: No Match ====================

    @Test
    @Order(1)
    @DisplayName("DD-01: unique data returns NONE — no duplicate found")
    void dedup01_noMatch_returnsNone() {
        ensureTableAndSeedData();

        Map<String, Object> data = Map.of(
                "crm_lead_contact_email", "unique-" + runId + "@example.com",
                "crm_lead_contact_phone", "+11111111111",
                "crm_lead_company", "Totally Unique Corp " + runId,
                "crm_lead_contact_name", "Nobody Here"
        );

        DeduplicationResult result = deduplicationService.checkDuplicate(data, tenantId);

        assertThat(result.type()).isEqualTo("none");
        assertThat(result.existingLeadId()).isNull();
        assertThat(result.matchScore()).isEqualByComparingTo(BigDecimal.ZERO);
        assertThat(result.matchFields()).isEmpty();

        log.info("DD-01 passed: unique data returns NONE");
    }

    // ==================== DD-02: Exact Email Match ====================

    @Test
    @Order(2)
    @DisplayName("DD-02: same email (case-insensitive) returns EXACT with existing leadId")
    void dedup02_exactEmailMatch_returnsExact() {
        ensureTableAndSeedData();

        Map<String, Object> data = Map.of(
                "crm_lead_contact_email", seedEmail.toUpperCase(),  // different case
                "crm_lead_company", "Different Company"
        );

        DeduplicationResult result = deduplicationService.checkDuplicate(data, tenantId);

        assertThat(result.type()).isEqualTo("exact");
        assertThat(result.existingLeadId()).isEqualTo(seedLeadId);
        assertThat(result.matchScore()).isEqualByComparingTo(new BigDecimal("100"));
        assertThat(result.matchFields()).containsEntry("email", new BigDecimal("100"));

        log.info("DD-02 passed: exact email match returns EXACT, leadId={}", result.existingLeadId());
    }

    // ==================== DD-03: Exact Phone Match ====================

    @Test
    @Order(3)
    @DisplayName("DD-03: same phone returns EXACT with existing leadId")
    void dedup03_exactPhoneMatch_returnsExact() {
        ensureTableAndSeedData();

        Map<String, Object> data = Map.of(
                "crm_lead_contact_phone", seedPhone,
                "crm_lead_contact_email", "other-" + runId + "@other.com",
                "crm_lead_company", "Other Company " + runId
        );

        DeduplicationResult result = deduplicationService.checkDuplicate(data, tenantId);

        assertThat(result.type()).isEqualTo("exact");
        assertThat(result.existingLeadId()).isEqualTo(seedLeadId);
        assertThat(result.matchScore()).isEqualByComparingTo(new BigDecimal("100"));
        assertThat(result.matchFields()).containsEntry("phone", new BigDecimal("100"));

        log.info("DD-03 passed: exact phone match returns EXACT, leadId={}", result.existingLeadId());
    }

    // ==================== DD-04: Fuzzy Company Match ====================

    @Test
    @Order(4)
    @DisplayName("DD-04: similar company name returns FUZZY with score >= 70")
    void dedup04_fuzzyCompanyMatch_returnsFuzzy() {
        ensureTableAndSeedData();

        // Use a company name similar to seedCompany, plus matching name and phone last-4
        // seedCompany = "Acme Corporation <runId>" — we use "Acme Corp <runId>" (high similarity)
        String last4 = seedPhone.substring(seedPhone.length() - 4);
        Map<String, Object> data = Map.of(
                "crm_lead_contact_email", "fuzzy-" + runId + "@other.com",  // unique email — no exact match
                "crm_lead_contact_phone", "+1111111" + last4,  // last 4 digits match
                "crm_lead_company", "Acme Corp " + runId,      // similar to seedCompany
                "crm_lead_contact_name", seedName              // same name
        );

        DeduplicationResult result = deduplicationService.checkDuplicate(data, tenantId);

        assertThat(result.type()).isEqualTo("fuzzy");
        assertThat(result.existingLeadId()).isEqualTo(seedLeadId);
        assertThat(result.matchScore()).isGreaterThanOrEqualTo(new BigDecimal("70"));
        assertThat(result.matchFields()).containsKey("company");
        assertThat(result.matchFields()).containsKey("name");

        log.info("DD-04 passed: fuzzy match returns FUZZY, score={}, fields={}",
                result.matchScore(), result.matchFields());
    }

    // ==================== DD-05: Low Similarity ====================

    @Test
    @Order(5)
    @DisplayName("DD-05: very different company returns NONE even with some similarity")
    void dedup05_lowSimilarity_returnsNone() {
        ensureTableAndSeedData();

        Map<String, Object> data = Map.of(
                "crm_lead_contact_email", "low-sim-" + runId + "@example.com",
                "crm_lead_contact_phone", "+99999999999",
                "crm_lead_company", "Zebra Technologies International",
                "crm_lead_contact_name", "Maria Garcia"
        );

        DeduplicationResult result = deduplicationService.checkDuplicate(data, tenantId);

        assertThat(result.type()).isEqualTo("none");
        assertThat(result.existingLeadId()).isNull();

        log.info("DD-05 passed: low similarity returns NONE");
    }

    // ==================== DD-06: Exact Merge Updates Lead ====================

    @Test
    @Order(6)
    @DisplayName("DD-06: EXACT merge updates existing lead fields and appends requirement")
    void dedup06_exactMerge_updatesLead() {
        ensureTableAndSeedData();

        // Insert a second lead to merge into
        Long mergeTargetId = System.currentTimeMillis() + 1;
        jdbcTemplate.update(
                "INSERT INTO mt_crm_lead " +
                "(id, pid, tenant_id, crm_lead_code, crm_lead_company, crm_lead_contact_name, " +
                "crm_lead_contact_phone, crm_lead_contact_email, crm_lead_requirement, " +
                "crm_lead_status, created_at, updated_at, created_by, updated_by) " +
                "VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, NOW(), NOW(), 0, 0)",
                mergeTargetId, "lead-" + mergeTargetId, tenantId,
                "LD-MERGE-" + runId,
                "MergeCorp",
                "Original Name",
                "+8618000005678",
                "merge-target-" + runId + "@corp.com",
                "Original requirement",
                "new"
        );

        // Simulate merge: update with new fields via JdbcTemplate (same logic as IngestionPipelineService)
        String newRequirement = "Additional need from inbound";
        Map<String, Object> inboundData = new LinkedHashMap<>();
        inboundData.put("crm_lead_company", "MergeCorp Updated");
        inboundData.put("crm_lead_contact_name", "Updated Name");
        inboundData.put("crm_lead_requirement", newRequirement);

        // Build SET clause — same pattern as IngestionPipelineService.mergeIntoExistingLead()
        jdbcTemplate.update(
                "UPDATE mt_crm_lead SET " +
                "crm_lead_company = ?, crm_lead_contact_name = ?, " +
                "crm_lead_requirement = CASE WHEN crm_lead_requirement IS NULL OR crm_lead_requirement = '' " +
                "THEN ? ELSE crm_lead_requirement || E'\\n---\\n' || ? END, " +
                "updated_at = NOW() " +
                "WHERE id = ? AND tenant_id = ?",
                "MergeCorp Updated", "Updated Name",
                newRequirement, newRequirement,
                mergeTargetId, tenantId
        );

        // Verify the merge result
        List<Map<String, Object>> rows = jdbcTemplate.queryForList(
                "SELECT crm_lead_company, crm_lead_contact_name, crm_lead_requirement " +
                "FROM mt_crm_lead WHERE id = ? AND tenant_id = ?",
                mergeTargetId, tenantId
        );

        assertThat(rows).hasSize(1);
        Map<String, Object> merged = rows.get(0);
        assertThat(merged.get("crm_lead_company")).isEqualTo("MergeCorp Updated");
        assertThat(merged.get("crm_lead_contact_name")).isEqualTo("Updated Name");

        String requirement = (String) merged.get("crm_lead_requirement");
        assertThat(requirement).contains("Original requirement");
        assertThat(requirement).contains("Additional need from inbound");
        assertThat(requirement).contains("---");  // separator between old and new

        log.info("DD-06 passed: exact merge updated lead fields and appended requirement");
    }
}
