package com.auraboot.framework.crm;

import com.auraboot.framework.application.tenant.MetaContext;
import com.auraboot.framework.common.util.UniqueIdGenerator;
import com.auraboot.framework.crm.adapter.InboundMessage;
import com.auraboot.framework.crm.dto.InboundChannelCreateRequest;
import com.auraboot.framework.crm.entity.InboundChannel;
import com.auraboot.framework.crm.entity.InboundMessageEntity;
import com.auraboot.framework.crm.entity.LeadMergeQueue;
import com.auraboot.framework.crm.mapper.InboundMessageMapper;
import com.auraboot.framework.crm.mapper.LeadMergeQueueMapper;
import com.auraboot.framework.crm.service.InboundChannelService;
import com.auraboot.framework.crm.service.IngestionPipelineService;
import com.auraboot.framework.crm.service.MergeQueueService;
import com.auraboot.framework.integration.BaseIntegrationTest;
import com.auraboot.framework.meta.mapper.DynamicDataMapper;
import com.baomidou.mybatisplus.core.conditions.query.LambdaQueryWrapper;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Propagation;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Integration tests for MergeQueueService.
 * Uses NOT_SUPPORTED propagation so data persists between ordered tests.
 *
 * @since 5.3.0
 */
@Slf4j
@DisplayName("Merge Queue Service Integration Tests (MQ-01~MQ-05)")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
@Transactional(propagation = Propagation.NOT_SUPPORTED)
class MergeQueueServiceIntegrationTest extends BaseIntegrationTest {

    @Autowired
    private MergeQueueService mergeQueueService;

    @Autowired
    private InboundChannelService inboundChannelService;

    @Autowired
    private IngestionPipelineService pipelineService;

    @Autowired
    private InboundMessageMapper inboundMessageMapper;

    @Autowired
    private LeadMergeQueueMapper mergeQueueMapper;

    @Autowired
    private DynamicDataMapper dynamicDataMapper;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    private final String runId = "mq-" + System.currentTimeMillis();
    private String channelPid;

    // Cross-test shared IDs
    private Long queueEntryId;
    private Long inboundMessageId;
    private Long candidateLeadId;

    // IDs for action tests (separate entries per action test)
    private Long mergeQueueId;
    private Long rejectQueueId;
    private Long createNewQueueId;

    // ===== Setup helpers =====

    private void ensureTablesExist() {
        if (dynamicDataMapper.checkTableExistsWithoutTenant("mt_crm_lead") == 0) {
            jdbcTemplate.execute("""
                CREATE TABLE mt_crm_lead (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    pid VARCHAR(32) NOT NULL UNIQUE,
                    tenant_id BIGINT,
                    crm_lead_code VARCHAR(50) NOT NULL,
                    crm_lead_company VARCHAR(200) NOT NULL,
                    crm_lead_contact_name VARCHAR(100) NOT NULL,
                    crm_lead_contact_phone VARCHAR(50),
                    crm_lead_contact_email VARCHAR(200),
                    crm_lead_source VARCHAR(50),
                    crm_lead_requirement TEXT,
                    crm_lead_status VARCHAR(50),
                    created_at TIMESTAMPTZ DEFAULT NOW(),
                    updated_at TIMESTAMPTZ DEFAULT NOW(),
                    created_by BIGINT,
                    updated_by BIGINT
                )
            """);
        }
        if (dynamicDataMapper.checkTableExistsWithoutTenant("mt_crm_activity") == 0) {
            jdbcTemplate.execute("""
                CREATE TABLE mt_crm_activity (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tenant_id BIGINT,
                    crm_act_type VARCHAR(50),
                    crm_act_subject VARCHAR(200),
                    crm_act_content TEXT,
                    crm_act_date TIMESTAMPTZ,
                    crm_act_source VARCHAR(50),
                    created_at TIMESTAMPTZ DEFAULT NOW(),
                    updated_at TIMESTAMPTZ DEFAULT NOW(),
                    created_by BIGINT,
                    updated_by BIGINT
                )
            """);
        }
    }

    private void ensureChannelCreated() {
        if (channelPid != null) return;
        ensureTablesExist();
        InboundChannelCreateRequest req = new InboundChannelCreateRequest();
        req.setName(runId + "-mq-test-channel");
        req.setChannelType("generic_webhook");
        req.setConfig(Map.of("url", "https://test.example.com"));
        req.setFieldMapping(Map.of(
                "email", "crm_lead_contact_email",
                "phone", "crm_lead_contact_phone",
                "company", "crm_lead_company",
                "name", "crm_lead_contact_name"
        ));
        InboundChannel channel = inboundChannelService.create(req);
        channelPid = channel.getPid();
        log.info("Test channel created: pid={}", channelPid);
    }

    /**
     * Re-establishes MetaContext after pipelineService.process() clears it.
     */
    private void restoreContext() {
        MetaContext.setContext(
                getTestTenant().getId(),
                getTestUser().getId(),
                getTestUser().getPid(),
                getTestUser().getUserName()
        );
    }

    /**
     * Inserts a seed lead directly into the database and returns its ID.
     */
    private Long seedLead(String company, String email, String phone) {
        Long tenantId = getTestTenant().getId();
        String pid = "lead-" + UniqueIdGenerator.generate();
        jdbcTemplate.update(
                "INSERT INTO mt_crm_lead " +
                "(pid, tenant_id, crm_lead_company, crm_lead_contact_name, crm_lead_contact_email, crm_lead_contact_phone, " +
                " crm_lead_code, crm_lead_status, crm_lead_source, created_at, updated_at, created_by, updated_by) " +
                "VALUES (?, ?, ?, ?, ?, ?, ?, 'new', 'inbound', NOW(), NOW(), 0, 0)",
                pid, tenantId, company, company + " Contact", email, phone, "ld-seed-" + UniqueIdGenerator.generate());
        List<Map<String, Object>> rows = jdbcTemplate.queryForList(
                "SELECT id FROM mt_crm_lead WHERE tenant_id = ? AND crm_lead_contact_email = ? ORDER BY id DESC LIMIT 1",
                tenantId, email);
        return ((Number) rows.get(0).get("id")).longValue();
    }

    /**
     * Creates an InboundMessageEntity stub for use in merge queue tests.
     */
    private InboundMessageEntity seedInboundMessage(String normalizedDataJson) {
        ensureChannelCreated();
        InboundMessageEntity entity = new InboundMessageEntity();
        entity.setTenantId(getTestTenant().getId());
        entity.setChannelPid(channelPid);
        entity.setExternalId(runId + "-ext-" + System.currentTimeMillis());
        entity.setRawPayload("{}");
        entity.setNormalizedData(normalizedDataJson);
        entity.setStatus("created");
        entity.setCreatedAt(Instant.now());
        inboundMessageMapper.insert(entity);
        return entity;
    }

    // ==================== MQ-01: Create Entry ====================

    @Test
    @Order(1)
    @DisplayName("MQ-01: create() persists entry with status=PENDING")
    void mq01_createEntry() {
        ensureChannelCreated();

        Long tenantId = getTestTenant().getId();
        candidateLeadId = seedLead("MqCandidateCorp-" + runId,
                runId + "-candidate@mq01.test",
                "+1-mq01-" + runId);

        InboundMessageEntity msgEntity = seedInboundMessage(
                "{\"crm_lead_company\":\"MqCandidateCorp-" + runId + "\"}");
        inboundMessageId = msgEntity.getId();

        Map<String, BigDecimal> matchFields = Map.of(
                "company", new BigDecimal("85.0"),
                "name", new BigDecimal("70.0"));

        LeadMergeQueue entry = mergeQueueService.create(
                inboundMessageId, candidateLeadId, new BigDecimal("80.0"), matchFields);

        assertThat(entry).isNotNull();
        assertThat(entry.getId()).isNotNull();
        assertThat(entry.getTenantId()).isEqualTo(tenantId);
        assertThat(entry.getInboundMessageId()).isEqualTo(inboundMessageId);
        assertThat(entry.getCandidateLeadId()).isEqualTo(candidateLeadId);
        assertThat(entry.getMatchScore()).isEqualByComparingTo(new BigDecimal("80.0"));
        assertThat(entry.getStatus()).isEqualTo("pending");
        assertThat(entry.getMatchFields()).contains("company");

        queueEntryId = entry.getId();
        log.info("MQ-01 passed: entry created id={}, status=PENDING", queueEntryId);
    }

    // ==================== MQ-02: List Pending ====================

    @Test
    @Order(2)
    @DisplayName("MQ-02: listPending() returns PENDING entries ordered newest first")
    void mq02_listPending() {
        ensureChannelCreated();
        assertThat(queueEntryId).as("queueEntryId must be set by MQ-01").isNotNull();

        Long tenantId = getTestTenant().getId();

        // Create a second entry
        Long candidateId2 = seedLead("MqCandidateCorp2-" + runId,
                runId + "-candidate2@mq02.test",
                "+1-mq02b-" + runId);
        InboundMessageEntity msg2 = seedInboundMessage("{}");
        LeadMergeQueue entry2 = mergeQueueService.create(
                msg2.getId(), candidateId2, new BigDecimal("75.0"), Map.of("company", new BigDecimal("75.0")));

        // Query PENDING entries directly via mapper (listPending not yet a service method)
        List<LeadMergeQueue> pending = mergeQueueMapper.selectList(
                new LambdaQueryWrapper<LeadMergeQueue>()
                        .eq(LeadMergeQueue::getTenantId, tenantId)
                        .eq(LeadMergeQueue::getStatus, "pending")
                        .orderByDesc(LeadMergeQueue::getCreatedAt));

        assertThat(pending).isNotNull();
        assertThat(pending).isNotEmpty();
        // Both entries created in this run should be present
        List<Long> ids = pending.stream().map(LeadMergeQueue::getId).toList();
        assertThat(ids).contains(queueEntryId, entry2.getId());
        // All returned entries must be PENDING
        pending.forEach(e -> assertThat(e.getStatus()).isEqualTo("pending"));
        // Ordered newest first
        if (pending.size() >= 2) {
            assertThat(pending.get(0).getCreatedAt()).isAfterOrEqualTo(pending.get(1).getCreatedAt());
        }

        log.info("MQ-02 passed: listPending returned {} entries, all PENDING", pending.size());
    }

    // ==================== MQ-03: Merge Action ====================

    @Test
    @Order(3)
    @DisplayName("MQ-03: merge() sets status=MERGED and updates candidate lead fields")
    void mq03_mergeAction() {
        ensureChannelCreated();

        Long tenantId = getTestTenant().getId();
        Long userId = getTestUser().getId();

        // Create a candidate lead with partial data
        Long mergeCandidateId = seedLead("MergeCorp-" + runId,
                runId + "-merge-candidate@mq03.test",
                "+1-mq03-" + runId);

        // Create inbound message with additional contact name
        String normalizedJson = "{\"crm_lead_company\":\"MergeCorp-" + runId + "\"," +
                "\"crm_lead_contact_name\":\"Merged Contact " + runId + "\"," +
                "\"crm_lead_contact_email\":\"" + runId + "-merge-candidate@mq03.test\"}";
        InboundMessageEntity msgEntity = seedInboundMessage(normalizedJson);
        // Set lead_id on the message entity (simulate pipeline having created an inbound lead)
        msgEntity.setLeadId(mergeCandidateId);
        inboundMessageMapper.updateById(msgEntity);

        LeadMergeQueue mergeEntry = mergeQueueService.create(
                msgEntity.getId(), mergeCandidateId, new BigDecimal("82.0"),
                Map.of("company", new BigDecimal("82.0")));
        mergeQueueId = mergeEntry.getId();

        // Execute merge
        mergeQueueService.merge(mergeQueueId, userId);
        restoreContext();

        // Verify queue status = MERGED
        LeadMergeQueue updated = mergeQueueMapper.selectById(mergeQueueId);
        assertThat(updated.getStatus()).isEqualTo("merged");
        assertThat(updated.getReviewedBy()).isEqualTo(userId);
        assertThat(updated.getReviewedAt()).isNotNull();

        // Verify candidate lead was updated with inbound contact name
        List<Map<String, Object>> leads = jdbcTemplate.queryForList(
                "SELECT crm_lead_contact_name FROM mt_crm_lead WHERE id = ? AND tenant_id = ?",
                mergeCandidateId, tenantId);
        assertThat(leads).isNotEmpty();
        assertThat(leads.get(0).get("crm_lead_contact_name"))
                .isEqualTo("Merged Contact " + runId);

        // Verify inbound message status = MERGED
        InboundMessageEntity refreshed = inboundMessageMapper.selectById(msgEntity.getId());
        assertThat(refreshed.getStatus()).isEqualTo("merged");
        assertThat(refreshed.getLeadId()).isEqualTo(mergeCandidateId);

        log.info("MQ-03 passed: merge action completed, status=MERGED, candidateLeadId={}", mergeCandidateId);
    }

    // ==================== MQ-04: Reject Action ====================

    @Test
    @Order(4)
    @DisplayName("MQ-04: reject() sets status=REJECTED with reviewer info")
    void mq04_rejectAction() {
        ensureChannelCreated();

        Long userId = getTestUser().getId();

        Long rejectCandidateId = seedLead("RejectCorp-" + runId,
                runId + "-reject@mq04.test",
                "+1-mq04-" + runId);
        InboundMessageEntity msgEntity = seedInboundMessage("{}");

        LeadMergeQueue rejectEntry = mergeQueueService.create(
                msgEntity.getId(), rejectCandidateId, new BigDecimal("71.0"),
                Map.of("company", new BigDecimal("71.0")));
        rejectQueueId = rejectEntry.getId();

        mergeQueueService.reject(rejectQueueId, userId);
        restoreContext();

        LeadMergeQueue updated = mergeQueueMapper.selectById(rejectQueueId);
        assertThat(updated.getStatus()).isEqualTo("rejected");
        assertThat(updated.getReviewedBy()).isEqualTo(userId);
        assertThat(updated.getReviewedAt()).isNotNull();

        // Attempt second action on already-reviewed entry should fail
        assertThatThrownBy(() -> mergeQueueService.reject(rejectQueueId, userId))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("not PENDING");

        log.info("MQ-04 passed: reject action completed, status=REJECTED, id={}", rejectQueueId);
    }

    // ==================== MQ-05: Create New Action ====================

    @Test
    @Order(5)
    @DisplayName("MQ-05: createNew() promotes inbound lead from PENDING_REVIEW to NEW, sets CREATED_NEW")
    void mq05_createNewAction() {
        ensureChannelCreated();

        Long tenantId = getTestTenant().getId();
        Long userId = getTestUser().getId();

        Long existingLeadId = seedLead("ExistingCorp-" + runId,
                runId + "-existing@mq05.test",
                "+1-mq05-" + runId);

        // Create an inbound lead with PENDING_REVIEW status (simulates fuzzy pipeline output)
        Long inboundLeadId = seedLead("InboundCorp-" + runId,
                runId + "-inbound@mq05.test",
                "+1-mq05-inbound-" + runId);
        jdbcTemplate.update(
                "UPDATE mt_crm_lead SET crm_lead_status = 'pending_review' WHERE id = ?",
                inboundLeadId);

        // Create inbound message entity pointing to the inbound lead
        InboundMessageEntity msgEntity = seedInboundMessage("{\"crm_lead_company\":\"InboundCorp-" + runId + "\"}");
        msgEntity.setLeadId(inboundLeadId);
        inboundMessageMapper.updateById(msgEntity);

        LeadMergeQueue createNewEntry = mergeQueueService.create(
                msgEntity.getId(), existingLeadId, new BigDecimal("73.0"),
                Map.of("company", new BigDecimal("73.0")));
        createNewQueueId = createNewEntry.getId();

        mergeQueueService.createNew(createNewQueueId, userId);
        restoreContext();

        // Verify queue status = CREATED_NEW
        LeadMergeQueue updated = mergeQueueMapper.selectById(createNewQueueId);
        assertThat(updated.getStatus()).isEqualTo("created_new");
        assertThat(updated.getReviewedBy()).isEqualTo(userId);
        assertThat(updated.getReviewedAt()).isNotNull();

        // Verify inbound lead status promoted to NEW
        List<Map<String, Object>> leads = jdbcTemplate.queryForList(
                "SELECT crm_lead_status FROM mt_crm_lead WHERE id = ? AND tenant_id = ?",
                inboundLeadId, tenantId);
        assertThat(leads).isNotEmpty();
        assertThat(leads.get(0).get("crm_lead_status")).isEqualTo("new");

        log.info("MQ-05 passed: createNew completed, inbound lead {} promoted to NEW, queueId={}",
                inboundLeadId, createNewQueueId);
    }
}
