package com.auraboot.framework.integration;

import com.auraboot.framework.application.TestApplication;
import com.auraboot.framework.meta.entity.OutboxEvent;
import com.auraboot.framework.meta.mapper.OutboxEventMapper;
import com.auraboot.framework.meta.service.impl.OutboxWorkerImpl;
import com.auraboot.framework.plugin.extension.integration.IntegrationEventEnvelope;
import com.auraboot.framework.plugin.extension.integration.ReliableEventConsumerExtension;
import com.auraboot.framework.plugin.extension.integration.ReliableIntegrationAccessor;
import io.micrometer.core.instrument.MeterRegistry;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.actuate.health.Status;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.atomic.AtomicBoolean;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

@SpringBootTest(classes = TestApplication.class)
@ActiveProfiles("integration-test")
@Import(ReliableIntegrationRuntimeIT.PilotConfiguration.class)
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@DisplayName("AMOS-T01 reliable integration runtime — real PostgreSQL pilot")
class ReliableIntegrationRuntimeIT {

    private static final long TENANT_ID = 992_010_001L;
    private static final String EVENT_TYPE =
            "procurement.purchase-order.receipt-requested.v1";

    @Autowired private JdbcTemplate jdbc;
    @Autowired private PlatformTransactionManager transactionManager;
    @Autowired private ReliableIntegrationAccessor accessor;
    @Autowired private OutboxEventMapper outboxMapper;
    @Autowired private OutboxWorkerImpl worker;
    @Autowired private ReliableIntegrationStateService stateService;
    @Autowired private ReliableIntegrationOperatorService operatorService;
    @Autowired private ReliableIntegrationHealth health;
    @Autowired private MeterRegistry meterRegistry;
    @Autowired private PilotInventoryConsumer pilotConsumer;

    @BeforeAll
    void prepareFixtureTables() {
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS amos_t01_procurement_source_fixture (
                    event_id TEXT PRIMARY KEY,
                    tenant_id BIGINT NOT NULL,
                    purchase_order_pid TEXT NOT NULL,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """);
        jdbc.execute("""
                CREATE TABLE IF NOT EXISTS amos_t01_inventory_projection_fixture (
                    apply_order BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    event_id TEXT NOT NULL UNIQUE,
                    tenant_id BIGINT NOT NULL,
                    ordering_key TEXT NOT NULL,
                    event_sequence BIGINT NOT NULL,
                    receipt_request_pid TEXT NOT NULL,
                    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
                """);
        cleanupRows();
    }

    @AfterAll
    void cleanup() {
        cleanupRows();
    }

    private void cleanupRows() {
        jdbc.update("DELETE FROM ab_integration_dead_letter_replay WHERE tenant_id = ?", TENANT_ID);
        jdbc.update("DELETE FROM ab_integration_dead_letter WHERE tenant_id = ?", TENANT_ID);
        jdbc.update("DELETE FROM ab_integration_receipt WHERE tenant_id = ?", TENANT_ID);
        jdbc.update("DELETE FROM ab_outbox WHERE tenant_id = ?", TENANT_ID);
        jdbc.update("DELETE FROM amos_t01_inventory_projection_fixture WHERE tenant_id = ?", TENANT_ID);
        jdbc.update("DELETE FROM amos_t01_procurement_source_fixture WHERE tenant_id = ?", TENANT_ID);
    }

    @Test
    @DisplayName("survives rollback, crash/restart, duplicates, ordering, poison, takeover, replay and reconcile")
    void procurementToInventoryReliableLifecycle() {
        TransactionTemplate transaction = new TransactionTemplate(transactionManager);

        transaction.executeWithoutResult(status -> {
            jdbc.update("INSERT INTO amos_t01_procurement_source_fixture "
                            + "(event_id, tenant_id, purchase_order_pid) VALUES (?, ?, ?)",
                    "evt-atomic", TENANT_ID, "PO-ATOMIC");
            accessor.enqueue(envelope("evt-atomic", "PO-ATOMIC", 1, false));
        });
        worker.pollAndDispatch();
        assertStatus("evt-atomic", "delivered");
        assertThat(countProjection("evt-atomic")).isEqualTo(1);

        assertThatThrownBy(() -> transaction.executeWithoutResult(status -> {
            jdbc.update("INSERT INTO amos_t01_procurement_source_fixture "
                            + "(event_id, tenant_id, purchase_order_pid) VALUES (?, ?, ?)",
                    "evt-rollback", TENANT_ID, "PO-ROLLBACK");
            accessor.enqueue(envelope("evt-rollback", "PO-ROLLBACK", 1, false));
            throw new IllegalStateException("injected source transaction failure");
        })).isInstanceOf(IllegalStateException.class);
        assertThat(count("amos_t01_procurement_source_fixture", "evt-rollback")).isZero();
        assertThat(count("ab_outbox", "evt-rollback")).isZero();

        enqueue(transaction, envelope("evt-crash", "PO-CRASH", 1, false));
        String abandonedToken = "abandoned-worker-token";
        List<OutboxEvent> abandoned = outboxMapper.claimReadyEvents(
                1, "crashed-worker", abandonedToken, Instant.now().plusSeconds(30));
        assertThat(abandoned).extracting(OutboxEvent::getEventId).containsExactly("evt-crash");
        assertThat(countProjection("evt-crash")).isZero();
        jdbc.update("UPDATE ab_outbox SET lease_until = NOW() - INTERVAL '1 second' "
                + "WHERE tenant_id = ? AND event_id = ?", TENANT_ID, "evt-crash");
        ReliableIntegrationStateService.ReconcileResult reconcile = worker.reconcile();
        assertThat(reconcile.recoveredLeases()).isEqualTo(1);
        worker.pollAndDispatch();
        assertStatus("evt-crash", "delivered");
        assertThat(stateService.markDelivered(abandoned.getFirst(), abandonedToken)).isFalse();

        jdbc.update("UPDATE ab_outbox SET status = 'pending', delivered_at = NULL, next_retry_at = NOW() "
                + "WHERE tenant_id = ? AND event_id = ?", TENANT_ID, "evt-crash");
        worker.pollAndDispatch();
        assertThat(countProjection("evt-crash")).isEqualTo(1);
        assertThat(countReceipt("evt-crash")).isEqualTo(1);

        enqueue(transaction, envelope("evt-order-2", "PO-ORDER", 2, false));
        enqueue(transaction, envelope("evt-order-1", "PO-ORDER", 1, false));
        worker.pollAndDispatch();
        assertStatus("evt-order-1", "delivered");
        assertStatus("evt-order-2", "pending");
        worker.pollAndDispatch();
        List<Long> appliedSequences = jdbc.queryForList(
                "SELECT event_sequence FROM amos_t01_inventory_projection_fixture "
                        + "WHERE tenant_id = ? AND ordering_key = ? ORDER BY apply_order",
                Long.class, TENANT_ID, "purchase-order/PO-ORDER");
        assertThat(appliedSequences).containsExactly(1L, 2L);

        pilotConsumer.poisonEnabled.set(true);
        enqueue(transaction, envelope("evt-poison", "PO-POISON", 1, true));
        jdbc.update("UPDATE ab_outbox SET max_retries = 1 WHERE tenant_id = ? AND event_id = ?",
                TENANT_ID, "evt-poison");
        worker.pollAndDispatch();
        assertStatus("evt-poison", "failed");
        assertThat(countDeadLetter("evt-poison", "open")).isEqualTo(1);
        assertThat(health.health().getStatus()).isEqualTo(Status.DOWN);
        assertThat(operatorService.list(TENANT_ID, "open", EVENT_TYPE,
                "corr-PO-POISON", 1, 20).getTotal()).isEqualTo(1L);
        assertThatThrownBy(() -> operatorService.detail(TENANT_ID + 1, "evt-poison"))
                .isInstanceOf(java.util.NoSuchElementException.class)
                .hasMessage("dead letter not found");

        pilotConsumer.poisonEnabled.set(false);
        ReliableIntegrationOperatorContracts.ReplayResult replay = operatorService.replay(
                TENANT_ID, "evt-poison", "01M1AMOSOPERATOR00000000000", "pilot consumer recovered", 0);
        assertThat(replay.status()).isEqualTo("pending");
        assertThat(replay.replayCount()).isEqualTo(1);
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM ab_integration_dead_letter_replay "
                        + "WHERE tenant_id = ? AND event_id = ? AND replay_attempt = 1 "
                        + "AND requested_by_pid = ? AND reason = ? AND correlation_id = ?",
                Integer.class, TENANT_ID, "evt-poison", "01M1AMOSOPERATOR00000000000",
                "pilot consumer recovered", "corr-PO-POISON")).isEqualTo(1);
        ReliableIntegrationOperatorContracts.DeadLetterDetail replayedDetail =
                operatorService.detail(TENANT_ID, "evt-poison");
        assertThat(replayedDetail.replayHistory()).singleElement().satisfies(history -> {
            assertThat(history.attempt()).isEqualTo(1);
            assertThat(history.reason()).isEqualTo("pilot consumer recovered");
            assertThat(history.requestedBy()).isEqualTo("01M1AMOSOPERATOR00000000000");
        });
        ReliableIntegrationOperatorContracts.ReplayResult exactRetry = operatorService.replay(
                TENANT_ID, "evt-poison", "01M1AMOSOPERATOR00000000000", "pilot consumer recovered", 0);
        assertThat(exactRetry.eventId()).isEqualTo(replay.eventId());
        assertThat(exactRetry.status()).isEqualTo(replay.status());
        assertThat(exactRetry.replayCount()).isEqualTo(replay.replayCount());
        assertThat(exactRetry.requestedBy()).isEqualTo(replay.requestedBy());
        assertThat(exactRetry.reason()).isEqualTo(replay.reason());
        assertThat(exactRetry.correlationId()).isEqualTo(replay.correlationId());
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM ab_integration_dead_letter_replay "
                        + "WHERE tenant_id = ? AND event_id = ?", Integer.class,
                TENANT_ID, "evt-poison")).isEqualTo(1);
        assertThatThrownBy(() -> operatorService.replay(
                TENANT_ID, "evt-poison", "01M1AMOSOPERATOR00000000000", "duplicate retry", 0))
                .isInstanceOf(IllegalStateException.class)
                .hasMessage("dead letter changed or is not open");
        worker.pollAndDispatch();
        assertStatus("evt-poison", "delivered");
        assertThat(countDeadLetter("evt-poison", "replayed")).isEqualTo(1);
        assertThat(health.health().getStatus()).isEqualTo(Status.UP);

        assertThat(counter("claimed")).isGreaterThanOrEqualTo(7.0);
        assertThat(counter("duplicate_suppressed")).isGreaterThanOrEqualTo(1.0);
        assertThat(counter("dead_lettered")).isGreaterThanOrEqualTo(1.0);
        assertThat(counter("replayed")).isGreaterThanOrEqualTo(1.0);
        assertThat(counter("lease_recovered")).isGreaterThanOrEqualTo(1.0);
    }

    @Test
    void accessorFailsClosedWithoutSourceTransaction() {
        assertThatThrownBy(() -> accessor.enqueue(envelope("evt-no-tx", "PO-NO-TX", 1, false)))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("active business transaction");
        assertThat(count("ab_outbox", "evt-no-tx")).isZero();
    }

    private void enqueue(TransactionTemplate transaction, IntegrationEventEnvelope envelope) {
        transaction.executeWithoutResult(status -> accessor.enqueue(envelope));
    }

    private IntegrationEventEnvelope envelope(String eventId, String purchaseOrderPid,
                                               long sequence, boolean poison) {
        return new IntegrationEventEnvelope(
                IntegrationEventEnvelope.VERSION_1,
                eventId,
                EVENT_TYPE,
                "procurement",
                "purchase-order/" + purchaseOrderPid,
                Instant.now(),
                TENANT_ID,
                "corr-" + purchaseOrderPid,
                "pr:receive_purchase_order/" + eventId,
                "purchase-order/" + purchaseOrderPid,
                sequence,
                Map.of(
                        "purchaseOrderPid", purchaseOrderPid,
                        "receiptRequestPid", "RR-" + eventId,
                        "sourceVersion", sequence,
                        "poison", poison),
                Map.of("contractOwner", "AMOS-T01"));
    }

    private void assertStatus(String eventId, String expected) {
        assertThat(jdbc.queryForObject(
                "SELECT status FROM ab_outbox WHERE tenant_id = ? AND event_id = ?",
                String.class, TENANT_ID, eventId)).isEqualTo(expected);
    }

    private int countProjection(String eventId) {
        return count("amos_t01_inventory_projection_fixture", eventId);
    }

    private int countReceipt(String eventId) {
        return count("ab_integration_receipt", eventId);
    }

    private int countDeadLetter(String eventId, String status) {
        return jdbc.queryForObject(
                "SELECT COUNT(*) FROM ab_integration_dead_letter WHERE tenant_id = ? "
                        + "AND event_id = ? AND status = ?",
                Integer.class, TENANT_ID, eventId, status);
    }

    private int count(String table, String eventId) {
        return jdbc.queryForObject("SELECT COUNT(*) FROM " + table
                        + " WHERE tenant_id = ? AND event_id = ?",
                Integer.class, TENANT_ID, eventId);
    }

    private double counter(String outcome) {
        return meterRegistry.get("auraboot_integration_events_total")
                .tag("outcome", outcome).counter().count();
    }

    @TestConfiguration
    static class PilotConfiguration {
        @Bean
        PilotInventoryConsumer pilotInventoryConsumer(JdbcTemplate jdbcTemplate) {
            return new PilotInventoryConsumer(jdbcTemplate);
        }
    }

    static final class PilotInventoryConsumer implements ReliableEventConsumerExtension {
        private final JdbcTemplate jdbc;
        private final AtomicBoolean poisonEnabled = new AtomicBoolean();

        PilotInventoryConsumer(JdbcTemplate jdbc) {
            this.jdbc = jdbc;
        }

        @Override
        public String consumerCode() {
            return "inventory.receive-source-receipt.v1";
        }

        @Override
        public Set<String> subscribedEventTypes() {
            return Set.of(EVENT_TYPE);
        }

        @Override
        public void consume(IntegrationEventEnvelope envelope) {
            if (poisonEnabled.get() && Boolean.TRUE.equals(envelope.payload().get("poison"))) {
                throw new IllegalArgumentException("injected poison receipt request");
            }
            jdbc.update("INSERT INTO amos_t01_inventory_projection_fixture "
                            + "(event_id, tenant_id, ordering_key, event_sequence, receipt_request_pid) "
                            + "VALUES (?, ?, ?, ?, ?)",
                    envelope.eventId(), envelope.tenantId(), envelope.orderingKey(), envelope.sequence(),
                    envelope.payload().get("receiptRequestPid"));
        }
    }
}
