/**
 * Resolves icon name strings (from menu config / plugin JSON) to Lucide React components.
 * Falls back to a text abbreviation when no matching icon is found.
 */
import React, { lazy, Suspense } from 'react';
import type { LucideProps } from 'lucide-react';
import {
  AlertCircle,
  AlertTriangle,
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpRight,
  Award,
  BadgeCheck,
  BarChart,
  BarChart2,
  BarChart3,
  BookOpen,
  Bug,
  Building,
  Calculator,
  Calendar,
  CheckCircle,
  CheckSquare,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  Cog,
  Coins,
  Contact,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Droplets,
  ExternalLink,
  Factory,
  FileBarChart,
  FileCheck,
  FileCode,
  FileCog,
  FileEdit,
  FileQuestion,
  FileText,
  FileWarning,
  Fingerprint,
  FlaskConical,
  FolderKanban,
  FolderTree,
  GitBranch,
  GitMerge,
  HardHat,
  Hash,
  IdCard,
  Landmark,
  Layers,
  LayoutDashboard,
  Lightbulb,
  LineChart,
  Link,
  List,
  Lock,
  MapPin,
  MessageSquare,
  Monitor,
  Package,
  PackageCheck,
  PackageMinus,
  PackagePlus,
  PackageSearch,
  PieChart,
  PlayCircle,
  Plus,
  Puzzle,
  Receipt,
  RotateCcw,
  RotateCw,
  Route,
  Scale,
  ScanSearch,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Target,
  TrendingDown,
  TrendingUp,
  Truck,
  User,
  UserCheck,
  UserPlus,
  Users,
  Wallet,
  Warehouse,
  Wrench,
} from 'lucide-react';

// Map icon name strings → Lucide components
// Covers: PascalCase Lucide names, Icon-prefixed Tabler names, kebab-case Ant Design names, lowercase aliases
const iconMap: Record<string, React.ComponentType<LucideProps>> = {
  // Lucide PascalCase (direct match)
  AlertCircle,
  AlertTriangle,
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUpRight,
  Award,
  BadgeCheck,
  BarChart,
  BarChart2,
  BarChart3,
  BookOpen,
  Bug,
  Building,
  Calculator,
  Calendar,
  CheckCircle,
  CheckSquare,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Cloud,
  Cog,
  Coins,
  Contact,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Droplets,
  ExternalLink,
  Factory,
  FileBarChart,
  FileCheck,
  FileCode,
  FileCog,
  FileEdit,
  FileQuestion,
  FileText,
  FileWarning,
  Fingerprint,
  FlaskConical,
  FolderKanban,
  FolderTree,
  GitBranch,
  GitMerge,
  HardHat,
  Hash,
  IdCard,
  Landmark,
  Layers,
  LayoutDashboard,
  Lightbulb,
  LineChart,
  Link,
  List,
  Lock,
  MapPin,
  MessageSquare,
  Monitor,
  Package,
  PackageCheck,
  PackageMinus,
  PackagePlus,
  PackageSearch,
  PieChart,
  PlayCircle,
  Plus,
  Puzzle,
  Receipt,
  RotateCcw,
  RotateCw,
  Route,
  Scale,
  ScanSearch,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Target,
  TrendingDown,
  TrendingUp,
  Truck,
  User,
  UserCheck,
  UserPlus,
  Users,
  Wallet,
  Warehouse,
  Wrench,

  // Icon-prefixed Tabler-style aliases
  IconApi: Link,
  IconChecklist: ClipboardCheck,
  IconClock: Clock,
  IconCpu: Cpu,
  IconDashboard: LayoutDashboard,
  IconPlayerPlay: PlayCircle,
  IconPuzzle: Puzzle,
  IconRobot: Cpu, // closest match for robot/agent
  IconSettings: Settings,
  IconShieldCheck: ShieldCheck,
  IconTarget: Target,
  IconWebhook: Link,

  // kebab-case / lowercase Ant Design-style aliases
  'bar-chart': BarChart,
  'carry-out': PackageCheck,
  'clock-circle': Clock,
  'deployment-unit': GitMerge,
  field: Hash,
  'file-search': FileQuestion,
  apartment: Building,
  appstore: LayoutDashboard,
  book: BookOpen,
  cloud: Cloud,
  dashboard: LayoutDashboard,
  database: Database,
  layout: LayoutDashboard,
  login: User,
  monitor: Monitor,
  project: FolderKanban,
  safety: Shield,
  search: Search,
  setting: Settings,
  table: List,
  team: Users,
  thunderbolt: TrendingUp,
  tool: Wrench,
};

/**
 * Resolve an icon name string to a React element.
 * Returns a Lucide icon if found, otherwise a text abbreviation in a circle.
 */
export function resolveIcon(
  iconName: string | undefined | null,
  menuName: string,
  size: number = 18,
): React.ReactElement {
  if (iconName) {
    const IconComponent = iconMap[iconName];
    if (IconComponent) {
      return <IconComponent size={size} />;
    }
  }

  // Fallback: first character of menu name
  const char = (menuName || '?').charAt(0).toUpperCase();
  return (
    <span
      className="inline-flex items-center justify-center rounded bg-gray-200 text-xs font-medium text-gray-600 dark:bg-gray-600 dark:text-gray-300"
      style={{ width: size, height: size, fontSize: size * 0.6 }}
    >
      {char}
    </span>
  );
}

/**
 * Check if an icon name has a known mapping.
 */
export function hasIcon(iconName: string | undefined | null): boolean {
  return !!iconName && !!iconMap[iconName];
}
