import assert from 'node:assert/strict';
import fs from 'node:fs';

const gate = fs.readFileSync(new URL('./run-open-platform-release-image-gate.sh', import.meta.url), 'utf8');
const probe = fs.readFileSync(new URL('./ci/open-platform-release-probe.py', import.meta.url), 'utf8');
const slo = fs.readFileSync(new URL('../tests/load/k6/open-platform-slo.js', import.meta.url), 'utf8');
const dockerfile = fs.readFileSync(new URL('../platform/Dockerfile', import.meta.url), 'utf8');

assert.match(gate, /AURA_CI_EXPECTED_REF/);
assert.match(gate, /uname -s.*Linux/);
assert.match(gate, /uname -m.*x86_64/);
assert.match(gate, /status --porcelain --untracked-files=all/);
assert.match(gate, /registry publication requires a separate owner-authorized job/);
assert.match(gate, /GRADLE_DISTRIBUTION_SHA256="6f74b601422d6d6fc4e1f9a1ab6522f642c2fdcbc15ae33ebd30ba3d7198e854"/);
assert.match(gate, /sha256sum --check --status/);
assert.match(gate, /seeding BuildKit Gradle wrapper cache from verified host distribution/);
assert.match(gate, /--mount=type=cache,target=\/root\/\.gradle\/wrapper/);
assert.match(dockerfile, /COPY VERSION \/VERSION/);
assert.match(gate, /docker logs "\$APP" > "\$ARTIFACTS\/logs\/app\.log"/);
assert.match(gate, /-v "\$STAGE\/plugins":\/plugins:ro/);
assert.match(gate, /chmod -R a\+rX "\$STAGE\/plugins"/);
assert.match(gate, /: > "\$CREDENTIAL_ARTIFACT"/);
assert.match(gate, /chmod 0600 "\$CREDENTIAL_ARTIFACT"/);
assert.match(gate, /cleanup\(\)[\s\S]*rm -f "\$CREDENTIAL_ARTIFACT"/);
assert.match(gate, /RUNNER_UID="\$\(id -u\)"/);
assert.match(gate, /RUNNER_GID="\$\(id -g\)"/);
assert.equal((gate.match(/docker run --rm --user "\$RUNNER_UID:\$RUNNER_GID"/g) ?? []).length, 2);
assert.match(gate, /PROFILE=production/);
assert.match(gate, /SPRING_PROFILES_ACTIVE=community/);
assert.match(gate, /JWT_KEY="\$\(openssl rand -base64 64/);
assert.match(gate, /-e JWT_SECRET="\$JWT_KEY"/);
assert.doesNotMatch(probe, /\/api\/test\/seed/);
assert.match(slo, /open_api_errors/);
assert.match(slo, /p\(95\)<250/);
assert.match(gate, /delivery_status IN \('pending','processing','failed','dead_letter'\)/);
assert.match(gate, /webhookDrainBacklog/);
assert.match(gate, /AURA_OPEN_PLATFORM_RELEASE_MUTATION/);
assert.match(gate, /EXPECTED_RED: Webhook backlog mutation was rejected/);
assert.match(gate, /releaseReceiptCreated.*False/);
assert.match(probe, /inventory\.stock-ins\.confirm/);
assert.match(probe, /"tinv_pd_code": "REL-PRODUCT-001"/);
assert.match(probe, /"tinv_wh_code": "REL-WAREHOUSE-001"/);
assert.match(probe, /"tinv_si_code": "REL-STOCK-IN-001"/);
assert.match(probe, /expected=\(412,/);
assert.match(probe, /cursor \+ 'x'/);
assert.match(gate, /shared_preload_libraries=pg_stat_statements/);
assert.ok(gate.indexOf('pg_stat_statements_reset()') < gate.indexOf('SLO_RC=0'));
assert.ok(gate.indexOf('sql-profile.json') < gate.indexOf('[[ "$SLO_RC" == 0 ]]'));
assert.match(gate, /PROFILE_RC=0/);
assert.match(gate, /container-resources.jsonl/);
assert.match(gate, /track_wal_io_timing=on/);
assert.match(gate, /docker stop --timeout 120/);
assert.ok(gate.indexOf('db-io-before.json') < gate.indexOf('SLO_RC=0'));
assert.ok(gate.indexOf('db-io-after.json') < gate.indexOf('[[ "$SLO_RC" == 0 ]]'));
assert.match(gate, /wait "\$DB_SAMPLE_PID" \|\| PROFILE_RC=\$\?/);
const sampler = fs.readFileSync(new URL('./ci/sample-open-platform-db.sh', import.meta.url), 'utf8');
assert.match(sampler, /pg_blocking_pids/);
assert.doesNotMatch(sampler, /SELECT \*|usename|query,|query AS|client_addr/);
console.log('open-platform release-image contract: PASS');
