import type { Browser, Page } from '@playwright/test';
import { test, expect } from '../../fixtures';
import { uniqueId } from '../helpers';

/**
 * Quote/BOM 真机 — 组织管理 admin CRUD (ORG-01 部门新建 / ORG-03 详情).
 * Admin-only; non-admin denial is covered by role-capability-closed-loop.spec.ts (ORG-02).
 */
const DEPT_LIST = '/p/org_department';
const DEPT_NEW = '/p/org_department/new?commandCode=org:create_department';
const uid = uniqueId('org').replace(/_/g, '-');

function adminCtx(browser: Browser) {
  return browser.newContext({ storageState: process.env.PW_ADMIN_STORAGE_STATE || 'tests/storage/admin.json' });
}

async function waitForListReady(page: Page): Promise<void> {
  await expect.poll(async () => {
    const searchReady = await page.getByTestId('list-search-input').count();
    const tableReady = await page.locator('table, [role="table"]').first().count();
    const loading = await page.locator('[aria-busy="true"], .ant-spin-spinning, [data-loading="true"]').count();
    return (searchReady > 0 || tableReady > 0) && loading === 0;
  }).toBe(true);
}

async function listSearch(page: Page, listPath: string, keyword: string): Promise<number> {
  await page.goto(listPath, { waitUntil: 'domcontentloaded' });
  await waitForListReady(page);
  // The shell also owns a global Ctrl+K input whose placeholder contains
  // “搜索”. A broad placeholder locator opens that palette and never filters
  // the department table. The list toolbar has a stable, product-owned id.
  const q = page.getByTestId('list-search-input');
  await expect(q).toBeVisible();
  await q.fill(keyword);
  const response = page.waitForResponse((r) => (
    new URL(r.url()).pathname === '/api/dynamic/org_department/list' && r.request().method() === 'GET'
  ), { timeout: 5000 });
  await q.press('Enter');
  const result = await response;
  expect(result.status()).toBe(200);
  expect(String((await result.json()).code)).toBe('0');
  await waitForListReady(page);
  const matchingRows = page.locator('[data-testid^="table-row-"]').filter({ hasText: keyword });
  await expect.poll(() => matchingRows.count(), { timeout: 15_000 }).toBeGreaterThan(0);
  return matchingRows.count();
}

async function createDepartment(page: Page, marker: string, code: string): Promise<string> {
  await page.goto(DEPT_NEW, { waitUntil: 'domcontentloaded' });
  await expect(page.getByTestId('dynamic-page-form')).toBeVisible();
  // org_dept_code is read-only and generated by the command. Use the stable
  // field wrapper for the only required editable value; a generic text-input
  // fallback also matches the shell's Ctrl+K global search before the form.
  const nameInput = page.getByTestId('form-field-org_dept_name').locator('input').first();
  await expect(nameInput).toBeVisible();
  await nameInput.fill(marker);
  await expect(nameInput).toHaveValue(marker);
  void code;
  const saveResponse = page.waitForResponse((r) => (
    new URL(r.url()).pathname === '/api/meta/commands/execute/org:create_department' && r.request().method() === 'POST'
  ), { timeout: 15_000 });
  await page.getByRole('button', { name: '保存' }).first().click();
  const response = await saveResponse;
  expect(response.status()).toBe(200);
  expect(response.request().postDataJSON().payload.org_dept_name).toBe(marker);
  const body = await response.json();
  expect(String(body.code), `create department response: ${JSON.stringify(body).slice(0, 500)}`).toBe('0');
  const recordPid = body.data.data.recordPid;
  expect(recordPid, 'created department exposes its persistent identity').toEqual(expect.any(String));
  expect(recordPid).not.toBe('');
  return recordPid;
}

test.describe('Quote/BOM org admin CRUD (ORG-01/03) @smoke', () => {
  test.describe.configure({ mode: 'serial', timeout: 150_000 });

  // ── ORG-01: 部门新建 → 列表出现 ──
  test('ORG-01 admin creates a department, it appears in the list', async ({ browser }) => {
    const ctx = await adminCtx(browser);
    const page = await ctx.newPage();
    try {
      const marker = `ORG${uid}`.slice(0, 24);
      await createDepartment(page, marker, `C${uid}`.slice(0, 16));
      const rows = await listSearch(page, DEPT_LIST, marker);
      expect(rows, 'ORG-01: department created appears in list').toBeGreaterThan(0);
      expect(
        await page.locator('[data-testid^="table-row-"]').filter({ hasText: marker }).count(),
        'department row present',
      ).toBeGreaterThan(0);
    } finally {
      await ctx.close();
    }
  });

  // ── ORG-03: 打开部门详情 → 字段渲染 ──
  test('ORG-03 admin opens a department detail page', async ({ browser }, info) => {
    const ctx = await adminCtx(browser);
    const page = await ctx.newPage();
    try {
      const marker = `ORGD${uid}`.slice(0, 24);
      // ensure one department exists to open
      const departmentPid = await createDepartment(page, marker, `CD${uid}`.slice(0, 16));
      await listSearch(page, DEPT_LIST, marker);
      const row = page.locator('[data-testid^="table-row-"]').filter({ hasText: marker }).first();
      // The platform's unconfigured row-click contract navigates to a detail page.
      // ListTable test ids identify row positions, not persistent records.
      // Match the detail request to the exact identity returned by creation.
      const detailResponse = page.waitForResponse(response => {
        const path = new URL(response.url()).pathname;
        return path === `/api/dynamic/org_department/${departmentPid}`
          && response.request().method() === 'GET';
      });
      await row.getByRole('cell', { name: marker, exact: true }).click();
      await expect(page).toHaveURL(/\/p\/org_department(?:_detail)?\/view\/[^/?]+/);
      const response = await detailResponse;
      expect(response.status()).toBe(200);
      const body = await response.json();
      expect(String(body.code)).toBe('0');
      expect(body.data.org_dept_name).toBe(marker);
      expect(String(body.data.pid)).toBe(departmentPid);
      await expect(page.getByRole('heading', { name: /部门详情|Department Detail/ })).toBeVisible();
      await expect(page.locator('main')).toContainText(marker);
      await info.attach('department-detail', { body: await page.screenshot(), contentType: 'image/png' });
    } finally {
      await ctx.close();
    }
  });
});
