/**
 * BPM Process Definition E2E Tests
 *
 * Tests D1-E01, D1-E03: Process definition UI tests
 * API tests (D1-E02, D1-E04 ~ D1-E08) migrated to: tests/api/bpm-process-definition.spec.ts
 * - Open BPMN designer page
 * - Open process in designer
 *
 * Uses real database, NO MOCKING.
 *
 * @since 4.0.0
 */

import { test, expect } from '../../fixtures';

function isProcessUpdateForbidden(message: string): boolean {
  return /system\.process\.update|Access forbidden|Access denied/i.test(message);
}

/**
 * Minimal BPMN XML for a simple Start -> UserTask -> End process.
 * Used for creating test process definitions via API.
 */
function generateMinimalBpmn(processKey: string): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://www.omg.org/spec/BPMN/20100524/MODEL"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             targetNamespace="http://auraboot.com/bpm"
             id="definitions_${processKey}">
  <process id="${processKey}" name="E2E Test Process" isExecutable="true">
    <startEvent id="start"/>
    <userTask id="userTask1" name="Approve Task"/>
    <endEvent id="end"/>
    <sequenceFlow id="flow1" sourceRef="start" targetRef="userTask1"/>
    <sequenceFlow id="flow2" sourceRef="userTask1" targetRef="end"/>
  </process>
</definitions>`;
}

/**
 * Generate a unique process key for test isolation.
 */
function generateProcessKey(): string {
  const ts = Date.now();
  const rand = Math.random().toString(36).slice(2, 7);
  return `e2e_proc_${ts}_${rand}`;
}

test.describe('BPM Process Definition Lifecycle', () => {
  test.describe.configure({ mode: 'serial' });

  let processPid: string | null = null;
  let processKey: string;
  let missingProcessUpdatePermission = false;

  test.beforeAll(async ({ request }) => {
    processKey = generateProcessKey();
    const bpmnContent = generateMinimalBpmn(processKey);

    try {
      const response = await request.post(`/api/bpm/process-definitions`, {
        data: {
          processKey,
          processName: `E2E Test Process ${processKey}`,
          description: 'Auto-generated by E2E test',
          category: 'e2e-test',
          bpmnContent,
        },
      });

      if (!response.ok()) {
        const bodyText = await response.text().catch(() => '');
        console.warn(`Process definition setup: create failed ${response.status()} ${bodyText}`);
        if (response.status() === 403 && isProcessUpdateForbidden(bodyText)) {
          missingProcessUpdatePermission = true;
        }
        return;
      }

      const data = await response.json();
      processPid = data.data?.pid || data.pid;
      if (!processPid) {
        console.warn(
          'Process definition setup: response missing pid:',
          JSON.stringify(data).slice(0, 200),
        );
      }
    } catch (error) {
      console.warn('Process definition setup failed:', error);
    }
  });

  /**
   * D1-E01: Open BPMN designer page
   * Verify that the BPMN designer or process definition page loads successfully.
   */
  test('D1-E01: Open BPMN designer page', async ({ page }) => {
    await page.goto(`/bpmn-designer`, { waitUntil: 'domcontentloaded' });

    // Wait for main content to appear (avoid networkidle which is too slow under load)
    const contentLocator = page.locator('main, .react-flow, [class*="designer"]');
    const loginLocator = page.locator('text=请先登录, text=欢迎登录');

    // Race between content loading and login redirect
    const result = await Promise.race([
      contentLocator
        .first()
        .waitFor({ timeout: 8000 })
        .then(() => 'content'),
      loginLocator
        .first()
        .waitFor({ timeout: 8000 })
        .then(() => 'login'),
    ]).catch(() => 'timeout');

    if (result === 'login') {
      throw new Error(String('Authentication not available in this run'));
      return;
    }

    expect(result).toBe('content');
  });

  /**
   * D1-E03: Open process in designer -> canvas renders
   * Navigate to the BPMN designer with the created process and verify the canvas loads.
   */
  test('D1-E03: Open process in designer', async ({ page }) => {
    if (missingProcessUpdatePermission) {
      test.skip(true, 'Missing permission: system.process.update');
      return;
    }

    if (!processPid) {
      throw new Error(String('Skipped: process creation failed in beforeAll'));
    }

    // Navigate to BPMN designer with the process PID
    await page.goto(`/bpmn-designer?id=${processPid}`);
    await page.waitForLoadState('domcontentloaded');

    // Check for React Flow canvas or any designer content
    const hasCanvas = await page
      .locator('.react-flow, [data-testid="bpmn-canvas"], .bpmn-designer, canvas')
      .isVisible({ timeout: 8000 })
      .catch(() => false);

    const hasDesignerContent = await page
      .locator('[class*="designer"], [class*="flow"], main')
      .isVisible({ timeout: 3000 })
      .catch(() => false);

    expect(hasCanvas || hasDesignerContent).toBe(true);
  });

  /**
   * Cleanup: Delete test process definition after all tests.
   */
  test.afterAll(async ({ request }) => {
    if (!processPid) return;

    try {
      // Undeploy first if still deployed
      await request.post(`/api/bpm/process-definitions/${processPid}/undeploy`);
    } catch {
      // Ignore undeploy errors
    }

    try {
      await request.delete(`/api/bpm/process-definitions/${processPid}`);
    } catch (error) {
      console.warn('Failed to cleanup test process definition:', error);
    }
  });
});
