package com.auraboot.framework.billing.account.entity;

import com.baomidou.mybatisplus.annotation.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Billing account — the OSS identity spine for commercialization.
 *
 * <p>Backed by {@code ab_billing_account}.  One account aggregates subscriptions,
 * quota buckets, usage events, and invoices.  Tenants link to an account via
 * {@code ab_tenant.billing_account_id}.
 *
 * <p>The primary key uses {@link IdType#AUTO} because the DDL uses
 * {@code BIGINT GENERATED BY DEFAULT AS IDENTITY} (postgres sequence) — not
 * a snowflake.  {@code pid} is a ULID stable external identifier.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@TableName("ab_billing_account")
public class BillingAccount {

    /** Database auto-increment identity key. */
    @TableId(type = IdType.AUTO)
    private Long id;

    /** Stable external ULID identifier (26 chars). */
    private String pid;

    /** Unique human-readable account code (e.g. ACC-2024-001). */
    private String accountCode;

    /** Display name of the account. */
    private String name;

    /**
     * Lifecycle status.
     * Values: {@code active}, {@code suspended}, {@code closed}.
     */
    private String status;

    /** ISO 4217 currency code for billing defaults. */
    private String defaultCurrency;

    /**
     * Billing settlement mode.
     * Values: {@code PREPAID}, {@code POSTPAID}.
     */
    private String billingMode;

    /** Current prepaid/credit balance in {@link #defaultCurrency}. */
    private BigDecimal balance;

    @TableField(fill = FieldFill.INSERT)
    private Instant createdAt;

    @TableField(fill = FieldFill.INSERT_UPDATE)
    private Instant updatedAt;

    /** Soft-delete flag — active accounts have {@code false}. */
    private Boolean deletedFlag;
}
