package com.auraboot.framework.bpm.event;

import com.auraboot.framework.application.tenant.MetaContext;
import com.auraboot.framework.bpm.entity.EventLogEntity;
import com.auraboot.framework.bpm.mapper.EventLogMapper;
import com.baomidou.mybatisplus.core.conditions.query.QueryWrapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.function.Consumer;
import com.auraboot.framework.common.constant.StatusConstants;

/**
 * Event bus service for BPM events.
 * Publishes events to Spring ApplicationEvent and persists to event log.
 *
 * After migration to AuraEvent, BpmEvent fields (eventId, occurredAt, tenantId)
 * are final and auto-generated at construction time. The publish() method no longer
 * sets these fields — callers must supply tenantId when creating BpmEvent.
 *
 * Uses direct ApplicationEventPublisher (not AuraEventBus) to avoid double dispatch,
 * since AuraEventBus.publish() also calls springPublisher.publishEvent().
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class EventBusService {

    private final EventLogMapper eventLogMapper;
    private final ApplicationEventPublisher applicationEventPublisher;

    private final Map<String, List<Consumer<BpmEvent>>> subscribers = new ConcurrentHashMap<>();

    /**
     * Publish a BPM event.
     * Persists to event log and dispatches to subscribers.
     *
     * BpmEvent fields are immutable (set at construction time via AuraEvent).
     */
    @Transactional
    public void publish(BpmEvent event) {
        // Idempotency check — eventId is auto-generated by AuraEvent constructor
        EventLogEntity existing = eventLogMapper.findByEventId(event.getEventId());
        if (existing != null) {
            log.debug("Event already published, skipping: eventId={}", event.getEventId());
            return;
        }

        // Persist to event log
        Long tenantId = event.getTenantId() != null ? event.getTenantId() : 0L;

        EventLogEntity logEntity = EventLogEntity.builder()
                .eventId(event.getEventId())
                .tenantId(tenantId)
                .eventType(event.getBpmEventType())
                .sourceType(event.getSourceType() != null ? event.getSourceType() : "bpm")
                .processKey(event.getProcessKey())
                .instanceId(event.getInstanceId())
                .nodeId(event.getNodeId())
                .payload(event.getPayload())
                .status(StatusConstants.PUBLISHED)
                .retryCount(0)
                .createdAt(Instant.now())
                .build();
        eventLogMapper.insert(logEntity);

        // Dispatch to internal subscribers (keyed by raw BPM event type)
        dispatchToSubscribers(event);

        // Publish as Spring ApplicationEvent (direct, not via AuraEventBus to avoid double dispatch)
        applicationEventPublisher.publishEvent(event);

        log.info("Event published: eventId={}, type={}, instanceId={}",
                event.getEventId(), event.getBpmEventType(), event.getInstanceId());
    }

    /**
     * Subscribe to events of a specific BPM type (e.g. "process_started").
     */
    public void subscribe(String eventType, Consumer<BpmEvent> handler) {
        subscribers.computeIfAbsent(eventType, k -> new CopyOnWriteArrayList<>()).add(handler);
        log.info("Subscribed to event type: {}", eventType);
    }

    /**
     * Mark an event as consumed.
     */
    public void markConsumed(String eventId) {
        eventLogMapper.updateStatus(eventId, "consumed");
    }

    /**
     * Mark an event as failed.
     */
    public void markFailed(String eventId, String errorMessage) {
        EventLogEntity entity = eventLogMapper.findByEventId(eventId);
        if (entity != null) {
            entity.setStatus(StatusConstants.FAILED);
            entity.setRetryCount(entity.getRetryCount() + 1);
            entity.setErrorMessage(errorMessage);
            eventLogMapper.updateById(entity);
        }
    }

    /**
     * Get events by process instance.
     * Uses MyBatis Plus selectList (with autoResultMap) so that the JSONB payload
     * TypeHandler is applied correctly, rather than the raw @Select annotation which
     * bypasses the result map.
     */
    public List<EventLogEntity> getEventsByInstance(String instanceId) {
        return eventLogMapper.selectList(
                new QueryWrapper<EventLogEntity>()
                        .eq("instance_id", instanceId)
                        .orderByDesc("created_at"));
    }

    /**
     * Convenience method to publish a BPM process event.
     * Resolves tenantId from MetaContext.
     */
    public void publishProcessEvent(String eventType, String processKey,
                                     String instanceId, Map<String, Object> payload) {
        Long tenantId = resolveTenantId();
        publish(new BpmEvent(tenantId, eventType, "bpm", processKey, instanceId, null, payload));
    }

    private Long resolveTenantId() {
        try {
            return MetaContext.getCurrentTenantId();
        } catch (Exception e) {
            log.debug("Could not resolve tenantId from MetaContext, using 0L");
            return 0L;
        }
    }

    private void dispatchToSubscribers(BpmEvent event) {
        // Subscribers are keyed by raw BPM event type (e.g. "process_started")
        List<Consumer<BpmEvent>> handlers = subscribers.get(event.getBpmEventType());
        if (handlers == null || handlers.isEmpty()) {
            return;
        }
        for (Consumer<BpmEvent> handler : handlers) {
            try {
                handler.accept(event);
            } catch (Exception e) {
                log.error("Event handler failed: eventId={}, type={}",
                        event.getEventId(), event.getBpmEventType(), e);
            }
        }
    }
}
