package com.auraboot.framework.branding;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.mock.env.MockEnvironment;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class DeploymentBrandingProviderTest {

    @TempDir
    private Path tempDirectory;

    @Test
    void communityEditionIgnoresExternalBranding() throws IOException {
        Path config = writeBranding("SO-2026-001", "https://northstar.example.com");
        MockEnvironment environment = environment("community", config, "SO-2026-001");

        BrandingIdentity identity = new DeploymentBrandingProvider(
                environment, new ObjectMapper()).current();

        assertThat(identity).isEqualTo(BrandingIdentity.community());
    }

    @Test
    void standardEditionLoadsOrderBoundArtifactIdentity() throws IOException {
        Path config = writeBranding("SO-2026-001", "https://northstar.example.com");
        MockEnvironment environment = environment("standard", config, "SO-2026-001");

        BrandingIdentity identity = new DeploymentBrandingProvider(
                environment, new ObjectMapper()).current();

        assertThat(identity).isEqualTo(new BrandingIdentity(
                "Northstar",
                "Northstar Operations Platform",
                "Generated by Northstar Operations Platform"));
    }

    @Test
    void commercialBrandingFailsClosedWithoutMatchingOrderEvidence() throws IOException {
        Path config = writeBranding("SO-2026-001", "https://northstar.example.com");

        assertThatThrownBy(() -> new DeploymentBrandingProvider(
                environment("standard", config, ""), new ObjectMapper()))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("ORDER_REFERENCE is required");
        assertThatThrownBy(() -> new DeploymentBrandingProvider(
                environment("standard", config, "SO-OTHER"), new ObjectMapper()))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("orderReference does not match");
    }

    @Test
    void commercialBrandingRejectsUnsafeAssetUrls() throws IOException {
        Path config = writeBranding("SO-2026-001", "javascript:alert(1)");

        assertThatThrownBy(() -> new DeploymentBrandingProvider(
                environment("standard", config, "SO-2026-001"), new ObjectMapper()))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("same-origin path or an HTTPS URL");
    }

    @Test
    void commercialBrandingRejectsStringSchemaVersions() throws IOException {
        Path config = writeBranding("SO-2026-001", "https://northstar.example.com");
        ObjectMapper objectMapper = new ObjectMapper();
        ObjectNode document = (ObjectNode) objectMapper.readTree(config.toFile());
        document.put("schemaVersion", "1");
        objectMapper.writeValue(config.toFile(), document);

        assertThatThrownBy(() -> new DeploymentBrandingProvider(
                environment("standard", config, "SO-2026-001"), objectMapper))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("schemaVersion must be 1");
    }

    @Test
    void commercialBrandingRejectsUnsupportedFields() throws IOException {
        Path config = writeBranding("SO-2026-001", "https://northstar.example.com");
        ObjectMapper objectMapper = new ObjectMapper();
        ObjectNode document = (ObjectNode) objectMapper.readTree(config.toFile());
        document.put("licenseUrl", "https://northstar.example.com/license");
        objectMapper.writeValue(config.toFile(), document);

        assertThatThrownBy(() -> new DeploymentBrandingProvider(
                environment("standard", config, "SO-2026-001"), objectMapper))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("unsupported fields")
                .hasMessageContaining("licenseUrl");
    }

    private MockEnvironment environment(String edition, Path config, String orderReference) {
        return new MockEnvironment()
                .withProperty("EDITION", edition)
                .withProperty("AURABOOT_BRANDING_CONFIG_PATH", config.toString())
                .withProperty("AURABOOT_WHITE_LABEL_ORDER_REFERENCE", orderReference);
    }

    private Path writeBranding(String orderReference, String websiteUrl) throws IOException {
        Path config = tempDirectory.resolve("branding-" + System.nanoTime() + ".json");
        Files.writeString(config, """
                {
                  "schemaVersion": 1,
                  "orderReference": "%s",
                  "productName": "Northstar",
                  "platformName": "Northstar Operations Platform",
                  "logoUrl": "/customer-brand/logo.png",
                  "faviconUrl": "/customer-brand/favicon.ico",
                  "favicon32Url": "/customer-brand/favicon-32x32.png",
                  "appleTouchIconUrl": "/customer-brand/apple-touch-icon.png",
                  "manifestUrl": "/customer-brand/manifest.webmanifest",
                  "websiteUrl": "%s",
                  "docsUrl": "https://northstar.example.com/docs",
                  "supportUrl": "https://northstar.example.com/support",
                  "copyrightHolder": "Northstar Holdings Ltd.",
                  "poweredByText": "Powered by Northstar",
                  "generatedByText": "Generated by Northstar Operations Platform"
                }
                """.formatted(orderReference, websiteUrl));
        return config;
    }
}
