package com.auraboot.framework.branding;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.springframework.mock.env.MockEnvironment;

import java.io.IOException;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Objects;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class DeploymentBrandingProviderTest {

    @TempDir
    private Path tempDirectory;

    @Test
    void communityEditionIgnoresExternalBranding() throws IOException {
        Path config = writeBranding("SO-2026-001", "https://northstar.example.com");
        MockEnvironment environment = environment("community", config, "SO-2026-001")
                .withProperty(
                        "AURABOOT_COMMERCIAL_LICENSE_ENFORCEMENT",
                        CommercialLicenseVerifier.OFFLINE_SIGNATURE);

        BrandingIdentity identity = new DeploymentBrandingProvider(
                environment, new ObjectMapper()).current();

        assertThat(identity).isEqualTo(BrandingIdentity.community());
    }

    @Test
    void standardEditionLoadsOrderBoundArtifactIdentity() throws IOException {
        Path config = writeBranding("SO-2026-001", "https://northstar.example.com");
        MockEnvironment environment = environment("standard", config, "SO-2026-001");

        BrandingIdentity identity = new DeploymentBrandingProvider(
                environment, new ObjectMapper()).current();

        assertThat(identity).isEqualTo(new BrandingIdentity(
                "Northstar",
                "Northstar Operations Platform",
                "Generated by Northstar Operations Platform"));
    }

    @Test
    void standardEditionAcceptsSharedRs256LicenseFixture() throws Exception {
        Path config = writeBranding("SO-2026-001", "https://northstar.example.com");
        MockEnvironment environment = signedEnvironment(config);

        BrandingIdentity identity = new DeploymentBrandingProvider(
                environment, new ObjectMapper()).current();

        assertThat(identity.productName()).isEqualTo("Northstar");
    }

    @Test
    void signedCommercialBrandingRejectsTamperingAndDeploymentMismatch() throws Exception {
        Path config = writeBranding("SO-2026-001", "https://northstar.example.com");
        Path tamperedLicense = tempDirectory.resolve("tampered-license.json");
        Files.copy(fixturePath("license.json"), tamperedLicense);
        Files.writeString(tamperedLicense, " ", java.nio.file.StandardOpenOption.APPEND);
        MockEnvironment tampered = signedEnvironment(config)
                .withProperty("AURABOOT_COMMERCIAL_LICENSE_PATH", tamperedLicense.toString());

        assertThatThrownBy(() -> new DeploymentBrandingProvider(
                tampered, new ObjectMapper()))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("SHA-256 digest does not match");
        assertThatThrownBy(() -> new DeploymentBrandingProvider(
                signedEnvironment(config)
                        .withProperty("AURABOOT_COMMERCIAL_LICENSE_CUSTOMER", "other-customer"),
                new ObjectMapper()))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("customer does not match");
        assertThatThrownBy(() -> new DeploymentBrandingProvider(
                signedEnvironment(config)
                        .withProperty("AURABOOT_VERSION", "2.0.0"),
                new ObjectMapper()))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("platformVersion does not match");
    }

    @Test
    void signedCommercialBrandingRequiresWhiteLabelRight() throws Exception {
        Path config = writeBranding("SO-2026-001", "https://northstar.example.com");
        MockEnvironment environment = signedEnvironment(config)
                .withProperty(
                        "AURABOOT_COMMERCIAL_LICENSE_PATH",
                        fixturePath("license-no-white-label.json").toString())
                .withProperty(
                        "AURABOOT_COMMERCIAL_LICENSE_SIGNATURE_PATH",
                        fixturePath("license-no-white-label.sig").toString());

        assertThatThrownBy(() -> new DeploymentBrandingProvider(
                environment, new ObjectMapper()))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("does not grant required feature: white_label");
    }

    @Test
    void commercialBrandingRejectsUnknownLicenseEnforcementMode() throws IOException {
        Path config = writeBranding("SO-2026-001", "https://northstar.example.com");

        assertThatThrownBy(() -> new DeploymentBrandingProvider(
                environment("standard", config, "SO-2026-001")
                        .withProperty(
                                "AURABOOT_COMMERCIAL_LICENSE_ENFORCEMENT",
                                "remote-server"),
                new ObjectMapper()))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("Unsupported commercial License enforcement mode");
    }

    @Test
    void commercialBrandingFailsClosedWithoutMatchingOrderEvidence() throws IOException {
        Path config = writeBranding("SO-2026-001", "https://northstar.example.com");

        assertThatThrownBy(() -> new DeploymentBrandingProvider(
                environment("standard", config, ""), new ObjectMapper()))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("ORDER_REFERENCE is required");
        assertThatThrownBy(() -> new DeploymentBrandingProvider(
                environment("standard", config, "SO-OTHER"), new ObjectMapper()))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("orderReference does not match");
    }

    @Test
    void commercialBrandingRejectsUnsafeAssetUrls() throws IOException {
        Path config = writeBranding("SO-2026-001", "javascript:alert(1)");

        assertThatThrownBy(() -> new DeploymentBrandingProvider(
                environment("standard", config, "SO-2026-001"), new ObjectMapper()))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("same-origin path or an HTTPS URL");
    }

    @Test
    void commercialBrandingRejectsStringSchemaVersions() throws IOException {
        Path config = writeBranding("SO-2026-001", "https://northstar.example.com");
        ObjectMapper objectMapper = new ObjectMapper();
        ObjectNode document = (ObjectNode) objectMapper.readTree(config.toFile());
        document.put("schemaVersion", "1");
        objectMapper.writeValue(config.toFile(), document);

        assertThatThrownBy(() -> new DeploymentBrandingProvider(
                environment("standard", config, "SO-2026-001"), objectMapper))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("schemaVersion must be 1");
    }

    @Test
    void commercialBrandingRejectsUnsupportedFields() throws IOException {
        Path config = writeBranding("SO-2026-001", "https://northstar.example.com");
        ObjectMapper objectMapper = new ObjectMapper();
        ObjectNode document = (ObjectNode) objectMapper.readTree(config.toFile());
        document.put("licenseUrl", "https://northstar.example.com/license");
        objectMapper.writeValue(config.toFile(), document);

        assertThatThrownBy(() -> new DeploymentBrandingProvider(
                environment("standard", config, "SO-2026-001"), objectMapper))
                .isInstanceOf(IllegalStateException.class)
                .hasMessageContaining("unsupported fields")
                .hasMessageContaining("licenseUrl");
    }

    private MockEnvironment environment(String edition, Path config, String orderReference) {
        return new MockEnvironment()
                .withProperty("EDITION", edition)
                .withProperty("AURABOOT_BRANDING_CONFIG_PATH", config.toString())
                .withProperty("AURABOOT_WHITE_LABEL_ORDER_REFERENCE", orderReference);
    }

    private MockEnvironment signedEnvironment(Path config) throws URISyntaxException {
        return environment("standard", config, "SO-2026-001")
                .withProperty(
                        "AURABOOT_COMMERCIAL_LICENSE_ENFORCEMENT",
                        CommercialLicenseVerifier.OFFLINE_SIGNATURE)
                .withProperty(
                        "AURABOOT_COMMERCIAL_LICENSE_PATH",
                        fixturePath("license.json").toString())
                .withProperty(
                        "AURABOOT_COMMERCIAL_LICENSE_SIGNATURE_PATH",
                        fixturePath("license.sig").toString())
                .withProperty(
                        "AURABOOT_COMMERCIAL_LICENSE_PUBLIC_KEY_PATH",
                        fixturePath("public.pem").toString())
                .withProperty(
                        "AURABOOT_COMMERCIAL_LICENSE_KEY_ID",
                        "test-commercial-2026-01")
                .withProperty("AURABOOT_COMMERCIAL_LICENSE_CUSTOMER", "northstar")
                .withProperty("AURABOOT_VERSION", "1.0.0");
    }

    private Path fixturePath(String name) throws URISyntaxException {
        return Path.of(Objects.requireNonNull(
                getClass().getResource("/branding/commercial-license/" + name)).toURI());
    }

    private Path writeBranding(String orderReference, String websiteUrl) throws IOException {
        Path config = tempDirectory.resolve("branding-" + System.nanoTime() + ".json");
        Files.writeString(config, """
                {
                  "schemaVersion": 1,
                  "orderReference": "%s",
                  "productName": "Northstar",
                  "platformName": "Northstar Operations Platform",
                  "logoUrl": "/customer-brand/logo.png",
                  "faviconUrl": "/customer-brand/favicon.ico",
                  "favicon32Url": "/customer-brand/favicon-32x32.png",
                  "appleTouchIconUrl": "/customer-brand/apple-touch-icon.png",
                  "manifestUrl": "/customer-brand/manifest.webmanifest",
                  "websiteUrl": "%s",
                  "docsUrl": "https://northstar.example.com/docs",
                  "supportUrl": "https://northstar.example.com/support",
                  "copyrightHolder": "Northstar Holdings Ltd.",
                  "poweredByText": "Powered by Northstar",
                  "generatedByText": "Generated by Northstar Operations Platform"
                }
                """.formatted(orderReference, websiteUrl));
        return config;
    }
}
