package com.auraboot.framework.behavior.sitekey;

import com.auraboot.framework.application.TestApplication;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Real-Postgres integration test for {@link SiteKeyRegistry}.
 *
 * <p><b>Why this exists:</b> {@code resolveTenant} has no HTTP surface (it is the internal
 * contract SP2's anonymous {@code /api/collect} will consume), so its actual SQL — a
 * <i>cross-tenant</i> lookup with a {@code status='active'} filter against the real
 * {@code mt_behavior_site_key} table — cannot be validated by the unit test (which mocks
 * {@link JdbcTemplate}). This test seeds two tenants directly via {@link JdbcTemplate} and runs
 * the real registry SQL through the integration Postgres, so a wrong table/column name or a
 * dialect mistake surfaces here, and cross-tenant isolation + the cache/evict semantics are
 * proven on a real DB.
 *
 * <p>The fixture is created with {@code CREATE TABLE IF NOT EXISTS} and scoped to a dedicated
 * tenant range + {@code abk_it_} key prefix, cleaned up before and after — it never drops the
 * table (so it coexists with a published model) and is an integration-test fixture, not manual
 * DML against production data.
 */
@SpringBootTest(classes = TestApplication.class)
@ActiveProfiles("integration-test")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class SiteKeyRegistryIT {

    private static final long TENANT_ALPHA = 990_101L;
    private static final long TENANT_BETA = 990_102L;

    @Autowired
    private SiteKeyRegistry registry;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeAll
    void seed() {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS mt_behavior_site_key (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                pid VARCHAR(32) NOT NULL,
                tenant_id BIGINT,
                site_key VARCHAR(64),
                name VARCHAR(200) NOT NULL,
                status VARCHAR(255),
                origin_allowlist JSONB,
                created_at TIMESTAMPTZ,
                updated_at TIMESTAMPTZ
            )
            """);
        cleanup();
        insert("IT_PID_ALPHA", TENANT_ALPHA, "abk_it_alpha", "Alpha App", "active");
        insert("IT_PID_BETA", TENANT_BETA, "abk_it_beta", "Beta App", "active");
        insert("IT_PID_GAMMA", TENANT_ALPHA, "abk_it_gamma", "Gamma App (disabled)", "disabled");
        insert("IT_PID_EVICT", TENANT_ALPHA, "abk_it_evict", "Evict App", "active");
    }

    @AfterAll
    void teardown() {
        cleanup();
    }

    private void cleanup() {
        jdbcTemplate.update("DELETE FROM mt_behavior_site_key WHERE site_key LIKE 'abk_it_%'");
    }

    private void insert(String pid, long tenantId, String siteKey, String name, String status) {
        jdbcTemplate.update(
                "INSERT INTO mt_behavior_site_key (pid, tenant_id, site_key, name, status, created_at) "
                        + "VALUES (?, ?, ?, ?, ?, now())",
                pid, tenantId, siteKey, name, status);
    }

    @Test
    @DisplayName("resolveTenant returns the owning tenant for an active key")
    void resolvesActiveKey() {
        assertThat(registry.resolveTenant("abk_it_alpha")).contains(TENANT_ALPHA);
    }

    @Test
    @DisplayName("resolveTenant is cross-tenant — each key maps to its own tenant")
    void crossTenantIsolation() {
        assertThat(registry.resolveTenant("abk_it_alpha")).contains(TENANT_ALPHA);
        assertThat(registry.resolveTenant("abk_it_beta")).contains(TENANT_BETA);
        // Beta's key must never resolve to Alpha's tenant.
        assertThat(registry.resolveTenant("abk_it_beta").orElseThrow()).isNotEqualTo(TENANT_ALPHA);
    }

    @Test
    @DisplayName("resolveTenant returns empty for a disabled key")
    void disabledKeyResolvesEmpty() {
        assertThat(registry.resolveTenant("abk_it_gamma")).isEmpty();
    }

    @Test
    @DisplayName("resolveTenant returns empty for an unknown key")
    void unknownKeyResolvesEmpty() {
        assertThat(registry.resolveTenant("abk_it_does_not_exist")).isEmpty();
    }

    @Test
    @DisplayName("existsAnyTenant detects presence across tenants")
    void existsAnyTenant() {
        assertThat(registry.existsAnyTenant("abk_it_alpha")).isTrue();
        assertThat(registry.existsAnyTenant("abk_it_beta")).isTrue();
        assertThat(registry.existsAnyTenant("abk_it_never_generated")).isFalse();
    }

    @Test
    @DisplayName("cache serves stale until evicted; evict re-queries the real row")
    void cacheAndEvict() {
        // Warm the positive cache.
        assertThat(registry.resolveTenant("abk_it_evict")).contains(TENANT_ALPHA);
        // Disable the row directly in the DB (out-of-band) — cache still serves the old value.
        jdbcTemplate.update("UPDATE mt_behavior_site_key SET status='disabled' WHERE site_key='abk_it_evict'");
        assertThat(registry.resolveTenant("abk_it_evict"))
                .as("cached active result is served until evicted")
                .contains(TENANT_ALPHA);
        // After eviction the next resolve hits the DB and sees the disabled row.
        registry.evict("abk_it_evict");
        assertThat(registry.resolveTenant("abk_it_evict"))
                .as("post-evict resolve re-queries and finds the disabled key")
                .isEmpty();
    }
}
