-- Immutable operator-attributed replay history for the public reliable-integration DLQ API.

CREATE TABLE IF NOT EXISTS ab_integration_dead_letter_replay (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) NOT NULL UNIQUE,
    outbox_id BIGINT NOT NULL REFERENCES ab_outbox(id),
    tenant_id BIGINT NOT NULL,
    event_id TEXT NOT NULL,
    correlation_id TEXT,
    replay_attempt INTEGER NOT NULL CHECK (replay_attempt > 0),
    requested_by_pid TEXT NOT NULL,
    reason VARCHAR(512) NOT NULL CHECK (BTRIM(reason) <> ''),
    requested_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_integration_dead_letter_replay_attempt UNIQUE (outbox_id, replay_attempt)
);

CREATE INDEX IF NOT EXISTS idx_integration_dead_letter_replay_event
    ON ab_integration_dead_letter_replay (tenant_id, event_id, replay_attempt DESC);

CREATE INDEX IF NOT EXISTS idx_integration_dead_letter_replay_requested
    ON ab_integration_dead_letter_replay (tenant_id, requested_at DESC);

COMMENT ON TABLE ab_integration_dead_letter_replay IS
    'Append-only actor, reason, correlation and attempt history for explicit dead-letter replay';
