-- AuraBoot core-only migration
-- Generated by scripts/application/migration-ownership.mjs.
-- Do not edit this staged artifact; edit the owning source migration/config instead.
-- Source: V20260821110000__record_comment_threads.sql
-- AuraBoot core-only migration
-- Generated by scripts/application/migration-ownership.mjs.
-- Do not edit this staged artifact; edit the owning source migration/config instead.
-- Source: V20260821110000__record_comment_threads.sql
ALTER TABLE ab_record_comment
    ADD COLUMN IF NOT EXISTS parent_pid VARCHAR(26),
    ADD COLUMN IF NOT EXISTS reply_to_user_pid VARCHAR(26);

CREATE INDEX IF NOT EXISTS idx_record_comment_parent
    ON ab_record_comment (tenant_id, parent_pid, created_at ASC)
    WHERE deleted_flag = FALSE;
