-- Registration is not admission or deployment qualification.
-- The historical ab_platform_release table remains a deployment audit ledger.
CREATE TABLE ab_application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE CHECK (code ~ '^[a-z][a-z0-9-]{1,99}$'),
    name TEXT NOT NULL CHECK (length(btrim(name)) > 0),
    next_release_sequence BIGINT NOT NULL DEFAULT 1 CHECK (next_release_sequence > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE ab_application_release (
    release_id VARCHAR(26) PRIMARY KEY CHECK (release_id ~ '^[0-9A-HJKMNP-TV-Z]{26}$'),
    application_id BIGINT NOT NULL REFERENCES ab_application(id),
    release_sequence BIGINT NOT NULL CHECK (release_sequence > 0),
    compatibility_epoch INTEGER NOT NULL CHECK (compatibility_epoch > 0),
    source_lock_identity TEXT NOT NULL CHECK (source_lock_identity ~ '^sha256:[0-9a-f]{64}$'),
    manifest_text TEXT NOT NULL,
    manifest JSONB GENERATED ALWAYS AS (manifest_text::jsonb) STORED,
    digest TEXT NOT NULL CHECK (digest = 'sha256:' || encode(sha256(convert_to(manifest_text, 'UTF8')), 'hex')),
    registered_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
    UNIQUE (application_id, release_sequence),
    UNIQUE (application_id, release_id),
    CHECK (jsonb_typeof(manifest) = 'object')
);

CREATE TABLE ab_application_release_component (
    release_id VARCHAR(26) NOT NULL REFERENCES ab_application_release(release_id),
    component_key TEXT NOT NULL CHECK (length(btrim(component_key)) > 0),
    component_type TEXT NOT NULL CHECK (component_type IN
        ('definition', 'backend_plugin', 'frontend_contribution', 'asset', 'migration')),
    component_version TEXT NOT NULL CHECK (length(btrim(component_version)) > 0
        AND component_version !~* '(snapshot|latest|workspace|branch)'),
    component_digest TEXT NOT NULL CHECK (component_digest ~ '^sha256:[0-9a-f]{64}$'),
    compatibility_contract JSONB NOT NULL CHECK (jsonb_typeof(compatibility_contract) = 'object'),
    PRIMARY KEY (release_id, component_key)
);

CREATE FUNCTION ab_application_guard_identity() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.next_release_sequence <> 1 THEN RAISE EXCEPTION 'New application sequence must start at one'; END IF;
        RETURN NEW;
    END IF;
    IF NEW.code IS DISTINCT FROM OLD.code OR NEW.id IS DISTINCT FROM OLD.id
       OR (NEW.next_release_sequence IS DISTINCT FROM OLD.next_release_sequence AND pg_trigger_depth() < 2) THEN
        RAISE EXCEPTION 'Application identity and release sequence are registry-controlled';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_application_identity BEFORE INSERT OR UPDATE ON ab_application
    FOR EACH ROW EXECUTE FUNCTION ab_application_guard_identity();

CREATE FUNCTION ab_application_release_prepare() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
DECLARE
    body JSONB := NEW.manifest_text::jsonb;
    application_code TEXT;
BEGIN
    UPDATE ab_application SET next_release_sequence = next_release_sequence + 1
      WHERE id = NEW.application_id AND next_release_sequence = NEW.release_sequence
      RETURNING code INTO application_code;
    IF NOT FOUND THEN RAISE EXCEPTION 'Application release sequence conflict'; END IF;
    IF body->>'schemaVersion' IS DISTINCT FROM '1'
       OR body->>'application' IS DISTINCT FROM application_code
       OR body->>'releaseId' IS DISTINCT FROM NEW.release_id
       OR body->>'releaseSequence' IS DISTINCT FROM NEW.release_sequence::text
       OR body->>'compatibilityEpoch' IS DISTINCT FROM NEW.compatibility_epoch::text
       OR body->>'sourceLockIdentity' IS DISTINCT FROM NEW.source_lock_identity
       OR jsonb_typeof(body->'platformCompatibility') IS DISTINCT FROM 'object'
       OR jsonb_typeof(body->'components') IS DISTINCT FROM 'array' THEN
        RAISE EXCEPTION 'Application release manifest identity or shape mismatch';
    END IF;
    IF jsonb_array_length(body->'components') = 0 THEN
        RAISE EXCEPTION 'Application release requires components';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_application_release_prepare BEFORE INSERT ON ab_application_release
    FOR EACH ROW EXECUTE FUNCTION ab_application_release_prepare();

CREATE FUNCTION ab_application_release_project() RETURNS TRIGGER
LANGUAGE plpgsql SET search_path FROM CURRENT AS $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM jsonb_array_elements(NEW.manifest->'components') AS item
        JOIN ab_application_release_component component
          ON component.component_key = item->>'key'
         AND component.component_type = item->>'type'
         AND component.component_version = item->>'version'
        JOIN ab_application_release release ON release.release_id = component.release_id
        WHERE release.application_id = NEW.application_id
          AND component.component_digest IS DISTINCT FROM item->>'digest'
    ) THEN
        RAISE EXCEPTION 'Application component coordinate cannot change its digest';
    END IF;
    INSERT INTO ab_application_release_component
        (release_id, component_key, component_type, component_version, component_digest, compatibility_contract)
    SELECT NEW.release_id, item->>'key', item->>'type', item->>'version', item->>'digest',
           COALESCE(item->'compatibilityContract', '{}'::jsonb)
      FROM jsonb_array_elements(NEW.manifest->'components') AS item;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_application_release_project AFTER INSERT ON ab_application_release
    FOR EACH ROW EXECUTE FUNCTION ab_application_release_project();

CREATE FUNCTION ab_application_release_reject_mutation() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'Application release content is immutable: %', TG_TABLE_NAME;
END $$;
CREATE TRIGGER trg_application_release_immutable BEFORE UPDATE OR DELETE ON ab_application_release
    FOR EACH ROW EXECUTE FUNCTION ab_application_release_reject_mutation();
CREATE TRIGGER trg_application_component_immutable BEFORE UPDATE OR DELETE ON ab_application_release_component
    FOR EACH ROW EXECUTE FUNCTION ab_application_release_reject_mutation();

CREATE FUNCTION ab_application_component_guard_insert() RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
    IF pg_trigger_depth() <> 2 THEN
        RAISE EXCEPTION 'Release components must be projected from the immutable manifest';
    END IF;
    RETURN NEW;
END $$;
CREATE TRIGGER trg_application_component_project_only BEFORE INSERT ON ab_application_release_component
    FOR EACH ROW EXECUTE FUNCTION ab_application_component_guard_insert();

COMMENT ON TABLE ab_application_release IS
    'Immutable registered content only. Admission/revocation and target deployment compatibility are separate authorities.';

CREATE TRIGGER trg_application_release_no_truncate BEFORE TRUNCATE ON ab_application_release
    FOR EACH STATEMENT EXECUTE FUNCTION ab_application_release_reject_mutation();
CREATE TRIGGER trg_application_component_no_truncate BEFORE TRUNCATE ON ab_application_release_component
    FOR EACH STATEMENT EXECUTE FUNCTION ab_application_release_reject_mutation();
