-- B6-1 "clean report permission family" — REGRESSION-SAFE additive grant migration.
--
-- WHY: report endpoints are guarded today with STOPGAP, template/report-aliased codes:
--   REPORT_READ     = meta.template.read    (ReportDefinitionController view/list)
--   REPORT_MANAGE   = meta.template.update  (ReportDefinitionController create/upsert/delete)
--   REPORT_GENERATE = meta.report.generate  (ReportExportController + ReportScheduleController)
-- B6 introduces a clean report.* family (B1 discovery Q11). @RequirePermission takes a SINGLE code
-- (no any-of), so if a controller were switched to a new code BEFORE existing tenants hold it, those
-- tenants would 403. The safe order is: introduce + grant the new codes for EVERY tenant FIRST (this
-- slice — additive, no controller touched, zero enforcement change), then flip the controllers LATER
-- (B6-2), by which point every tenant already holds the new code so the flip cannot 403 anyone.
--
-- OLD -> NEW mapping (exactly preserves the access the stopgap grants — no regression):
--   meta.report.generate -> report.export.execute  AND  report.schedule.manage
--   meta.template.read    -> report.definition.view
--   meta.template.update  -> report.definition.manage
--
-- PERMISSION MODEL: permissions are PER-TENANT, not global. ab_permission has tenant_id NOT NULL with
-- uq_permission_code UNIQUE (tenant_id, code) — every tenant has its OWN row per code. Grants live in
-- ab_role_permission (role_id -> permission_id, both tenant-scoped). The bootstrap wildcard "*" is
-- MATERIALIZED into concrete ab_role_permission rows at tenant-bootstrap time (see
-- TenantBootstrapServiceImpl + RolePermissionServiceImpl.assignPermissionsToRole), so tenant_admin of
-- an EXISTING tenant has explicit grant rows for the OLD codes but NOT for these brand-new ones — which
-- is precisely why this migration is needed. New tenants get the codes via the bootstrap template
-- (default-bootstrap.json), so this migration is for the already-provisioned tenants only.
--
-- THEREFORE this migration has TWO parts, in order:
--   Part A — ensure a NEW-code ab_permission row exists for every tenant that holds the OLD code.
--   Part B — for every role that grants the OLD code's permission, also grant the NEW code's
--            permission (same tenant, same role).
--
-- IDEMPOTENT: every insert is gated by NOT EXISTS, so a second run inserts zero rows and never raises a
-- duplicate-key error (neither on the (tenant_id, code) permission unique nor on the pid unique).
--
-- ID / pid SAFETY:
--   * ab_permission.id and ab_role_permission.id are BIGINT GENERATED BY DEFAULT AS IDENTITY, so we OMIT
--     the id column and let the identity sequence assign it (exactly what the app/bootstrap insert path
--     does — the entity id is null on insert). This sidesteps any snowflake-collision concern entirely.
--   * pid is VARCHAR(32) UNIQUE NOT NULL; the app mints 26-char UPPERCASE Crockford-base32 ULIDs. We mint
--     a DETERMINISTIC pid from a fixed LOWERCASE prefix + the source row's globally-unique id + a
--     per-target-code suffix:  'b6p' || src_permission.id || '_' || <suffix>   (Part A)
--                              'b6rp' || src_role_permission.id || '_' || <suffix> (Part B)
--     A lowercase prefix can NEVER equal an uppercase ULID, so it is provably disjoint from app pids; the
--     source id is a unique PK and the suffix disambiguates the one OLD code (meta.report.generate) that
--     maps to TWO new codes — so the pid is unique within and across runs. Max length is well under 32
--     (e.g. 'b6rp' + 19-digit bigint + '_' + 1 = 25 chars).
--
-- RUNS ON: Flyway-based environments (prod deploy, reset-db). The host-first golden harness builds its DB
-- from database/schema.sql (not Flyway), so this migration does not run there — fine, a fresh harness has
-- no legacy tenants to backfill. Coverage is proven by ReportPermissionFamilyGrantIT against the real DB.

-- ============================================================================================
-- Part A: per-tenant NEW-code permission rows (one per tenant that holds the corresponding OLD code)
-- ============================================================================================

-- report.definition.view  <- holders of meta.template.read
INSERT INTO ab_permission (pid, tenant_id, code, name, description, resource_type, resource_code, action, source, source_ref, status, deleted_flag, created_at, updated_at)
SELECT 'b6p' || src.id || '_v', src.tenant_id, 'report.definition.view',
       'Report definition view', 'Report definition — view (load / get / list)',
       'function', 'report:definition', 'view', 'system', 'report', 'active', FALSE, NOW(), NOW()
FROM ab_permission src
WHERE src.code = 'meta.template.read'
  AND NOT EXISTS (
        SELECT 1 FROM ab_permission t
        WHERE t.tenant_id = src.tenant_id AND t.code = 'report.definition.view');

-- report.definition.manage  <- holders of meta.template.update
INSERT INTO ab_permission (pid, tenant_id, code, name, description, resource_type, resource_code, action, source, source_ref, status, deleted_flag, created_at, updated_at)
SELECT 'b6p' || src.id || '_m', src.tenant_id, 'report.definition.manage',
       'Report definition manage', 'Report definition — manage (create / update / delete)',
       'function', 'report:definition', 'manage', 'system', 'report', 'active', FALSE, NOW(), NOW()
FROM ab_permission src
WHERE src.code = 'meta.template.update'
  AND NOT EXISTS (
        SELECT 1 FROM ab_permission t
        WHERE t.tenant_id = src.tenant_id AND t.code = 'report.definition.manage');

-- report.export.execute  <- holders of meta.report.generate
INSERT INTO ab_permission (pid, tenant_id, code, name, description, resource_type, resource_code, action, source, source_ref, status, deleted_flag, created_at, updated_at)
SELECT 'b6p' || src.id || '_e', src.tenant_id, 'report.export.execute',
       'Report export execute', 'Report export — execute (Excel / PDF / JSON)',
       'function', 'report:export', 'execute', 'system', 'report', 'active', FALSE, NOW(), NOW()
FROM ab_permission src
WHERE src.code = 'meta.report.generate'
  AND NOT EXISTS (
        SELECT 1 FROM ab_permission t
        WHERE t.tenant_id = src.tenant_id AND t.code = 'report.export.execute');

-- report.schedule.manage  <- holders of meta.report.generate
INSERT INTO ab_permission (pid, tenant_id, code, name, description, resource_type, resource_code, action, source, source_ref, status, deleted_flag, created_at, updated_at)
SELECT 'b6p' || src.id || '_s', src.tenant_id, 'report.schedule.manage',
       'Report schedule manage', 'Report schedule — manage (schedule CRUD + test-send)',
       'function', 'report:schedule', 'manage', 'system', 'report', 'active', FALSE, NOW(), NOW()
FROM ab_permission src
WHERE src.code = 'meta.report.generate'
  AND NOT EXISTS (
        SELECT 1 FROM ab_permission t
        WHERE t.tenant_id = src.tenant_id AND t.code = 'report.schedule.manage');

-- ============================================================================================
-- Part B: grant the NEW-code permission to every role that currently grants the OLD code.
-- For each active grant of an old code, insert the mapped new-code grant for the SAME role/tenant,
-- carrying the same grant_type so the access is preserved exactly. Joins are tenant-scoped on both
-- the old and new permission rows so a grant is never created across tenants.
-- ============================================================================================

-- Helper shape (repeated per mapping): join the role's grant of the OLD permission to the tenant's NEW
-- permission row (created in Part A), and insert a grant of the NEW permission for that role.

-- report.definition.view  <- grants of meta.template.read
INSERT INTO ab_role_permission (pid, tenant_id, role_id, permission_id, grant_type, status, deleted_flag, created_at, updated_at)
SELECT 'b6rp' || rp.id || '_v', rp.tenant_id, rp.role_id, np.id, rp.grant_type, 'active', FALSE, NOW(), NOW()
FROM ab_role_permission rp
JOIN ab_permission op ON op.id = rp.permission_id AND op.code = 'meta.template.read'
JOIN ab_permission np ON np.tenant_id = rp.tenant_id AND np.code = 'report.definition.view'
WHERE rp.deleted_flag = FALSE
  AND rp.status = 'active'
  AND NOT EXISTS (
        SELECT 1 FROM ab_role_permission ex
        WHERE ex.tenant_id = rp.tenant_id
          AND ex.role_id = rp.role_id
          AND ex.permission_id = np.id
          AND ex.deleted_flag = FALSE);

-- report.definition.manage  <- grants of meta.template.update
INSERT INTO ab_role_permission (pid, tenant_id, role_id, permission_id, grant_type, status, deleted_flag, created_at, updated_at)
SELECT 'b6rp' || rp.id || '_m', rp.tenant_id, rp.role_id, np.id, rp.grant_type, 'active', FALSE, NOW(), NOW()
FROM ab_role_permission rp
JOIN ab_permission op ON op.id = rp.permission_id AND op.code = 'meta.template.update'
JOIN ab_permission np ON np.tenant_id = rp.tenant_id AND np.code = 'report.definition.manage'
WHERE rp.deleted_flag = FALSE
  AND rp.status = 'active'
  AND NOT EXISTS (
        SELECT 1 FROM ab_role_permission ex
        WHERE ex.tenant_id = rp.tenant_id
          AND ex.role_id = rp.role_id
          AND ex.permission_id = np.id
          AND ex.deleted_flag = FALSE);

-- report.export.execute  <- grants of meta.report.generate
INSERT INTO ab_role_permission (pid, tenant_id, role_id, permission_id, grant_type, status, deleted_flag, created_at, updated_at)
SELECT 'b6rp' || rp.id || '_e', rp.tenant_id, rp.role_id, np.id, rp.grant_type, 'active', FALSE, NOW(), NOW()
FROM ab_role_permission rp
JOIN ab_permission op ON op.id = rp.permission_id AND op.code = 'meta.report.generate'
JOIN ab_permission np ON np.tenant_id = rp.tenant_id AND np.code = 'report.export.execute'
WHERE rp.deleted_flag = FALSE
  AND rp.status = 'active'
  AND NOT EXISTS (
        SELECT 1 FROM ab_role_permission ex
        WHERE ex.tenant_id = rp.tenant_id
          AND ex.role_id = rp.role_id
          AND ex.permission_id = np.id
          AND ex.deleted_flag = FALSE);

-- report.schedule.manage  <- grants of meta.report.generate
INSERT INTO ab_role_permission (pid, tenant_id, role_id, permission_id, grant_type, status, deleted_flag, created_at, updated_at)
SELECT 'b6rp' || rp.id || '_s', rp.tenant_id, rp.role_id, np.id, rp.grant_type, 'active', FALSE, NOW(), NOW()
FROM ab_role_permission rp
JOIN ab_permission op ON op.id = rp.permission_id AND op.code = 'meta.report.generate'
JOIN ab_permission np ON np.tenant_id = rp.tenant_id AND np.code = 'report.schedule.manage'
WHERE rp.deleted_flag = FALSE
  AND rp.status = 'active'
  AND NOT EXISTS (
        SELECT 1 FROM ab_role_permission ex
        WHERE ex.tenant_id = rp.tenant_id
          AND ex.role_id = rp.role_id
          AND ex.permission_id = np.id
          AND ex.deleted_flag = FALSE);
