-- Per-user / per-team pins of a SavedView to the list-page quick-filter chip row.
--
-- Half A (plugin/admin global pins) needs no storage — the flag lives in
-- ab_saved_view.view_config.meta.pinnedAsQuickFilter. Half B (a user pinning any
-- view they can see) and its team extension cannot: a user pinning a shared/global
-- view must not mutate that view's meta, so the pin is a per-(principal, view)
-- association living here instead.
--
-- The table carries `scope` + `team_id` from the start so the M3 team-pin slice
-- adds behavior only, never DDL (executed migrations are immutable).
--
-- view_pid is a soft reference (no FK), matching ab_saved_view's PID-reference
-- convention; a deleted view's pins are filtered out by the read-side join.
-- The two partial-intent unique constraints stay independent because Postgres
-- treats NULLs as distinct: a team pin (user_id NULL) never collides on
-- uq_chip_pin_personal, and vice versa.

CREATE TABLE ab_saved_view_chip_pin (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) UNIQUE NOT NULL,
    tenant_id BIGINT NOT NULL,

    -- Pin scope: 'personal' (user_id set) or 'team' (team_id set)
    scope VARCHAR(20) NOT NULL DEFAULT 'personal',
    user_id VARCHAR(26),             -- Owner PID for personal pins
    team_id VARCHAR(26),             -- Team ID for team pins

    -- The pinned view + denormalized model/page for cheap per-list lookup
    view_pid VARCHAR(26) NOT NULL,   -- References ab_saved_view.pid (soft ref)
    model_code VARCHAR(100) NOT NULL,
    page_key VARCHAR(100),
    sort_order INT NOT NULL DEFAULT 0,

    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(26),

    CONSTRAINT chk_chip_pin_scope CHECK (scope IN ('personal', 'team')),
    CONSTRAINT uq_chip_pin_personal UNIQUE (tenant_id, user_id, view_pid),
    CONSTRAINT uq_chip_pin_team UNIQUE (tenant_id, team_id, view_pid)
);

CREATE INDEX idx_chip_pin_lookup ON ab_saved_view_chip_pin(tenant_id, model_code, page_key);

COMMENT ON TABLE ab_saved_view_chip_pin IS 'Per-user / per-team pins of a SavedView to the list-page quick-filter chip row';
COMMENT ON COLUMN ab_saved_view_chip_pin.scope IS 'Pin visibility: personal (user_id) or team (team_id)';
COMMENT ON COLUMN ab_saved_view_chip_pin.view_pid IS 'The pinned SavedView pid (soft reference to ab_saved_view.pid)';
