-- AuraBoot core-only migration
-- Generated by scripts/application/migration-ownership.mjs.
-- Do not edit this staged artifact; edit the owning source migration/config instead.
-- Source: V20260812120000__page_schema_history_description.sql
-- AuraBoot core-only migration
-- Generated by scripts/application/migration-ownership.mjs.
-- Do not edit this staged artifact; edit the owning source migration/config instead.
-- Source: V20260812120000__page_schema_history_description.sql
ALTER TABLE ab_page_schema_history
    ADD COLUMN IF NOT EXISTS description TEXT;

COMMENT ON COLUMN ab_page_schema_history.description
    IS 'Human-readable reason recorded for a page schema version or snapshot action';
