-- AuraBoot core-only migration
-- Generated by scripts/application/migration-ownership.mjs.
-- Do not edit this staged artifact; edit the owning source migration/config instead.
-- Source: V20260912010000__automation_node_execution.sql
-- Per-node execution status for the platform automation runtime.
CREATE TABLE IF NOT EXISTS ab_automation_node_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    automation_log_id BIGINT NOT NULL,
    automation_id VARCHAR(64) NOT NULL,
    process_instance_id VARCHAR(128),
    node_id VARCHAR(128) NOT NULL,
    status VARCHAR(20) NOT NULL,
    started_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_automation_node_exec_status CHECK (status IN (
        'pending', 'running', 'completed', 'failed', 'skipped'
    ))
);

CREATE INDEX IF NOT EXISTS idx_automation_node_exec_log
    ON ab_automation_node_execution(automation_log_id);

CREATE INDEX IF NOT EXISTS idx_automation_node_exec_tenant_automation
    ON ab_automation_node_execution(tenant_id, automation_id);

CREATE INDEX IF NOT EXISTS idx_automation_node_exec_pi
    ON ab_automation_node_execution(process_instance_id);

COMMENT ON TABLE ab_automation_node_execution IS
    'Per-node execution status for a platform automation run.';
