-- AuraBoot core-only migration
-- Generated by scripts/application/migration-ownership.mjs.
-- Do not edit this staged artifact; edit the owning source migration/config instead.
-- Source: V20260813213000__excel_import_job_error_details.sql
-- AuraBoot core-only migration
-- Generated by scripts/application/migration-ownership.mjs.
-- Do not edit this staged artifact; edit the owning source migration/config instead.
-- Source: V20260813213000__excel_import_job_error_details.sql
ALTER TABLE ab_import_job
    ADD COLUMN IF NOT EXISTS error_details TEXT;
