-- AuraBoot core-only migration
-- Generated by scripts/application/migration-ownership.mjs.
-- Do not edit this staged artifact; edit the owning source migration/config instead.
-- Source: V20260715103000__drt_log_output_snapshot.sql
-- AuraBoot core-only migration
-- Generated by scripts/application/migration-ownership.mjs.
-- Do not edit this staged artifact; edit the owning source migration/config instead.
-- Source: V20260715103000__drt_log_output_snapshot.sql
ALTER TABLE ab_drt_log
    ADD COLUMN IF NOT EXISTS output_snapshot JSONB;

COMMENT ON COLUMN ab_drt_log.output_snapshot IS 'Decision Runtime output snapshot for execution-log trace UI';
