-- Unified Open Platform identity, authorization and public API runtime.
-- Secrets and bearer tokens are never persisted in plaintext.

CREATE TABLE ab_external_application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) NOT NULL UNIQUE,
    owner_tenant_id BIGINT NOT NULL,
    name VARCHAR(160) NOT NULL,
    description VARCHAR(1000),
    status VARCHAR(24) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    created_by_pid VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_external_application_owner
    ON ab_external_application (owner_tenant_id, status, created_at DESC);

CREATE TABLE ab_application_installation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    application_id BIGINT NOT NULL REFERENCES ab_external_application(id),
    environment VARCHAR(32) NOT NULL CHECK (environment IN ('development', 'staging', 'production')),
    rate_limit_per_minute INTEGER NOT NULL DEFAULT 600 CHECK (rate_limit_per_minute BETWEEN 1 AND 100000),
    status VARCHAR(24) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    installed_by_pid VARCHAR(64),
    installed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_application_installation UNIQUE (application_id, tenant_id, environment),
    CONSTRAINT uq_application_installation_tenant_id UNIQUE (tenant_id, id)
);

CREATE INDEX idx_application_installation_tenant
    ON ab_application_installation (tenant_id, status, installed_at DESC);

CREATE TABLE ab_application_credential (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    installation_id BIGINT NOT NULL,
    client_id VARCHAR(96) NOT NULL UNIQUE,
    secret_hash VARCHAR(255) NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
    expires_at TIMESTAMPTZ,
    last_used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_application_credential_installation
        FOREIGN KEY (tenant_id, installation_id)
        REFERENCES ab_application_installation(tenant_id, id)
);

CREATE INDEX idx_application_credential_installation
    ON ab_application_credential (tenant_id, installation_id, status);

CREATE TABLE ab_application_scope_grant (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    installation_id BIGINT NOT NULL,
    scope_code VARCHAR(160) NOT NULL,
    granted_by_pid VARCHAR(64),
    granted_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_application_scope_installation
        FOREIGN KEY (tenant_id, installation_id)
        REFERENCES ab_application_installation(tenant_id, id),
    CONSTRAINT uq_application_scope_grant UNIQUE (installation_id, scope_code)
);

CREATE INDEX idx_application_scope_grant_tenant
    ON ab_application_scope_grant (tenant_id, installation_id);

CREATE TABLE ab_application_access_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    installation_id BIGINT NOT NULL,
    credential_id BIGINT NOT NULL REFERENCES ab_application_credential(id),
    token_hash CHAR(64) NOT NULL UNIQUE,
    scopes JSONB NOT NULL DEFAULT '[]'::jsonb,
    audience VARCHAR(96) NOT NULL DEFAULT 'auraboot-open-api',
    issued_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT fk_application_token_installation
        FOREIGN KEY (tenant_id, installation_id)
        REFERENCES ab_application_installation(tenant_id, id)
);

CREATE INDEX idx_application_access_token_lookup
    ON ab_application_access_token (token_hash, expires_at) WHERE revoked_at IS NULL;
CREATE INDEX idx_application_access_token_installation
    ON ab_application_access_token (tenant_id, installation_id, expires_at DESC);

CREATE TABLE ab_open_api_call_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    application_pid VARCHAR(26) NOT NULL,
    installation_pid VARCHAR(26) NOT NULL,
    token_pid VARCHAR(26),
    request_id VARCHAR(128),
    http_method VARCHAR(16) NOT NULL,
    request_path VARCHAR(512) NOT NULL,
    response_status INTEGER NOT NULL,
    duration_ms BIGINT NOT NULL,
    remote_address VARCHAR(96),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_open_api_call_audit_tenant_time
    ON ab_open_api_call_audit (tenant_id, occurred_at DESC);
CREATE INDEX idx_open_api_call_audit_installation_time
    ON ab_open_api_call_audit (installation_pid, occurred_at DESC);

CREATE TABLE ab_open_api_idempotency (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    installation_id BIGINT NOT NULL,
    route_code VARCHAR(160) NOT NULL,
    idempotency_key VARCHAR(255) NOT NULL,
    request_hash CHAR(64) NOT NULL,
    response_status INTEGER,
    response_body JSONB,
    status VARCHAR(24) NOT NULL DEFAULT 'processing' CHECK (status IN ('processing', 'completed', 'failed')),
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_open_api_idempotency_installation
        FOREIGN KEY (tenant_id, installation_id)
        REFERENCES ab_application_installation(tenant_id, id),
    CONSTRAINT uq_open_api_idempotency UNIQUE (installation_id, route_code, idempotency_key)
);

CREATE INDEX idx_open_api_idempotency_expiry
    ON ab_open_api_idempotency (expires_at);

CREATE TABLE ab_open_api_rate_window (
    installation_id BIGINT NOT NULL REFERENCES ab_application_installation(id),
    window_start TIMESTAMPTZ NOT NULL,
    request_count INTEGER NOT NULL CHECK (request_count > 0),
    PRIMARY KEY (installation_id, window_start)
);

CREATE INDEX idx_open_api_rate_window_expiry
    ON ab_open_api_rate_window (window_start);

COMMENT ON TABLE ab_external_application IS 'Platform external application catalog; no direct tenant data authority';
COMMENT ON TABLE ab_application_installation IS 'Tenant and environment authorization boundary for an external application';
COMMENT ON TABLE ab_application_credential IS 'Hashed client credentials with overlap-safe rotation and revocation';
COMMENT ON TABLE ab_application_access_token IS 'Hashed short-lived opaque OAuth2 client_credentials access tokens';
COMMENT ON TABLE ab_open_api_call_audit IS 'Secret-free request audit for public Open API calls';

-- Upgrade the legacy webhook attempt log into a durable delivery queue. Existing terminal rows
-- remain readable; new rows transition pending -> processing -> success|pending|dead_letter.
ALTER TABLE ab_webhook_delivery_log
    ADD COLUMN IF NOT EXISTS max_retries INTEGER NOT NULL DEFAULT 3,
    ADD COLUMN IF NOT EXISTS next_retry_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS lease_owner VARCHAR(160),
    ADD COLUMN IF NOT EXISTS lease_token VARCHAR(96),
    ADD COLUMN IF NOT EXISTS lease_until TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS last_attempt_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS installation_pid VARCHAR(26) REFERENCES ab_application_installation(pid),
    ADD COLUMN IF NOT EXISTS replay_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS last_replayed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS last_replayed_by_pid VARCHAR(64);

ALTER TABLE ab_webhook_subscription
    ADD COLUMN IF NOT EXISTS installation_pid VARCHAR(26) REFERENCES ab_application_installation(pid);

CREATE INDEX IF NOT EXISTS idx_webhook_subscription_installation
    ON ab_webhook_subscription (tenant_id, installation_pid, enabled);

CREATE INDEX IF NOT EXISTS idx_webhook_delivery_ready
    ON ab_webhook_delivery_log (delivery_status, next_retry_at, lease_until, created_at)
    WHERE delivery_status IN ('pending', 'processing');
