-- Permission v2 capability registry: business-language groupings of permission codes shipped by
-- plugins in config/capabilities.json (the unit the v2 UI presents instead of the raw resource x
-- action matrix). A capability resolves to its included permission codes; the runtime permission
-- engine never reads this table. Additive + idempotent.

CREATE TABLE IF NOT EXISTS ab_capability (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid                 VARCHAR(64),
    tenant_id           BIGINT NOT NULL,
    code                VARCHAR(255) NOT NULL,
    group_name          VARCHAR(255),
    name                VARCHAR(255),
    name_en             VARCHAR(255),
    description         TEXT,
    includes            TEXT NOT NULL,                  -- comma-separated permission codes
    tier                VARCHAR(32),                    -- viewer / editor / admin
    sensitive           BOOLEAN NOT NULL DEFAULT FALSE,
    unmasks_fields      TEXT,                           -- comma-separated model.field
    order_no            INTEGER NOT NULL DEFAULT 100,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_capability UNIQUE (tenant_id, code)
);

CREATE INDEX IF NOT EXISTS idx_capability_tenant_group ON ab_capability(tenant_id, group_name);

COMMENT ON TABLE ab_capability IS 'Permission v2 capability registry (plugin-shipped business-language permission bundles)';
