-- Single-business-tenant product model: retain tenant isolation and model business
-- participants as Party Actors.  Pre-auth login routing tables are deliberately
-- separate from tenant-scoped Party tables.

-- Composite keys are prerequisites for same-tenant foreign keys below.
CREATE UNIQUE INDEX IF NOT EXISTS uq_ab_tenant_member_tenant_id_id
    ON ab_tenant_member (tenant_id, id);

ALTER TABLE ab_role
    ADD COLUMN IF NOT EXISTS role_scope VARCHAR(20) NOT NULL DEFAULT 'tenant';

CREATE UNIQUE INDEX IF NOT EXISTS uq_ab_role_tenant_id_id_scope
    ON ab_role (tenant_id, id, role_scope);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'ck_ab_role_role_scope'
    ) THEN
        ALTER TABLE ab_role
            ADD CONSTRAINT ck_ab_role_role_scope
            CHECK (role_scope IN ('platform', 'tenant', 'party'));
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS ab_party (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) UNIQUE NOT NULL,
    tenant_id BIGINT NOT NULL,
    code VARCHAR(100) NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    legal_name VARCHAR(300),
    party_type VARCHAR(30) NOT NULL DEFAULT 'organization',
    lifecycle_status VARCHAR(30) NOT NULL DEFAULT 'pending',
    profile JSONB NOT NULL DEFAULT '{}'::jsonb,
    deleted_flag BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_party_tenant FOREIGN KEY (tenant_id) REFERENCES ab_tenant (id),
    CONSTRAINT ck_party_type CHECK (party_type IN ('organization', 'person')),
    CONSTRAINT ck_party_lifecycle CHECK (
        lifecycle_status IN ('pending', 'active', 'suspended', 'rejected', 'closed')
    ),
    CONSTRAINT uq_party_tenant_id_id UNIQUE (tenant_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_party_tenant_code_active
    ON ab_party (tenant_id, code) WHERE deleted_flag = FALSE;
CREATE INDEX IF NOT EXISTS idx_party_tenant_status
    ON ab_party (tenant_id, lifecycle_status) WHERE deleted_flag = FALSE;

CREATE TABLE IF NOT EXISTS ab_party_identifier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) UNIQUE NOT NULL,
    tenant_id BIGINT NOT NULL,
    party_id BIGINT NOT NULL,
    identifier_type VARCHAR(50) NOT NULL,
    identifier_value VARCHAR(300) NOT NULL,
    normalized_value VARCHAR(300) NOT NULL,
    issuing_authority VARCHAR(200),
    country_code VARCHAR(2),
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    verification_status VARCHAR(20) NOT NULL DEFAULT 'unverified',
    verified_at TIMESTAMPTZ,
    valid_from TIMESTAMPTZ,
    valid_until TIMESTAMPTZ,
    deleted_flag BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_party_identifier_party FOREIGN KEY (tenant_id, party_id)
        REFERENCES ab_party (tenant_id, id),
    CONSTRAINT ck_party_identifier_verification CHECK (
        verification_status IN ('unverified', 'pending', 'verified', 'rejected', 'expired')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_party_identifier_active
    ON ab_party_identifier (tenant_id, identifier_type, normalized_value)
    WHERE deleted_flag = FALSE;
CREATE INDEX IF NOT EXISTS idx_party_identifier_party
    ON ab_party_identifier (tenant_id, party_id) WHERE deleted_flag = FALSE;

CREATE TABLE IF NOT EXISTS ab_party_capability (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) UNIQUE NOT NULL,
    tenant_id BIGINT NOT NULL,
    party_id BIGINT NOT NULL,
    capability_code VARCHAR(100) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    effective_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ,
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
    granted_by BIGINT,
    revoked_by BIGINT,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_party_capability_party FOREIGN KEY (tenant_id, party_id)
        REFERENCES ab_party (tenant_id, id),
    CONSTRAINT ck_party_capability_status CHECK (
        status IN ('pending', 'active', 'suspended', 'revoked', 'expired')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_party_capability_current
    ON ab_party_capability (tenant_id, party_id, capability_code)
    WHERE status IN ('pending', 'active', 'suspended');
CREATE INDEX IF NOT EXISTS idx_party_capability_lookup
    ON ab_party_capability (tenant_id, capability_code, status);

CREATE TABLE IF NOT EXISTS ab_party_membership (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) UNIQUE NOT NULL,
    tenant_id BIGINT NOT NULL,
    party_id BIGINT NOT NULL,
    tenant_member_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    title VARCHAR(120),
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
    invited_at TIMESTAMPTZ,
    joined_at TIMESTAMPTZ,
    left_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_party_membership_party FOREIGN KEY (tenant_id, party_id)
        REFERENCES ab_party (tenant_id, id),
    CONSTRAINT fk_party_membership_tenant_member FOREIGN KEY (tenant_id, tenant_member_id)
        REFERENCES ab_tenant_member (tenant_id, id),
    CONSTRAINT ck_party_membership_status CHECK (
        status IN ('invited', 'pending', 'active', 'suspended', 'left', 'revoked')
    ),
    CONSTRAINT uq_party_membership_tenant_id_id UNIQUE (tenant_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_party_membership_current
    ON ab_party_membership (tenant_id, party_id, tenant_member_id)
    WHERE status IN ('invited', 'pending', 'active', 'suspended');
CREATE INDEX IF NOT EXISTS idx_party_membership_actor
    ON ab_party_membership (tenant_id, tenant_member_id, status);

CREATE TABLE IF NOT EXISTS ab_party_member_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) UNIQUE NOT NULL,
    tenant_id BIGINT NOT NULL,
    party_membership_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    role_scope VARCHAR(20) NOT NULL DEFAULT 'party',
    effective_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    CONSTRAINT fk_party_member_role_membership FOREIGN KEY (tenant_id, party_membership_id)
        REFERENCES ab_party_membership (tenant_id, id),
    CONSTRAINT fk_party_member_role_party_role FOREIGN KEY (tenant_id, role_id, role_scope)
        REFERENCES ab_role (tenant_id, id, role_scope),
    CONSTRAINT ck_party_member_role_scope CHECK (role_scope = 'party'),
    CONSTRAINT uq_party_member_role_assignment UNIQUE (tenant_id, party_membership_id, role_id)
);

CREATE INDEX IF NOT EXISTS idx_party_member_role_membership
    ON ab_party_member_role (tenant_id, party_membership_id);

CREATE TABLE IF NOT EXISTS ab_party_invitation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) UNIQUE NOT NULL,
    tenant_id BIGINT NOT NULL,
    party_id BIGINT NOT NULL,
    inviter_tenant_member_id BIGINT NOT NULL,
    invited_email VARCHAR(200),
    invited_phone VARCHAR(50),
    invitation_code_hash VARCHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    expires_at TIMESTAMPTZ NOT NULL,
    accepted_by_tenant_member_id BIGINT,
    accepted_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_party_invitation_party FOREIGN KEY (tenant_id, party_id)
        REFERENCES ab_party (tenant_id, id),
    CONSTRAINT fk_party_invitation_inviter FOREIGN KEY (tenant_id, inviter_tenant_member_id)
        REFERENCES ab_tenant_member (tenant_id, id),
    CONSTRAINT fk_party_invitation_acceptor FOREIGN KEY (tenant_id, accepted_by_tenant_member_id)
        REFERENCES ab_tenant_member (tenant_id, id),
    CONSTRAINT ck_party_invitation_subject CHECK (
        invited_email IS NOT NULL OR invited_phone IS NOT NULL
    ),
    CONSTRAINT ck_party_invitation_status CHECK (
        status IN ('pending', 'accepted', 'expired', 'revoked')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_party_invitation_code_current
    ON ab_party_invitation (invitation_code_hash)
    WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_party_invitation_party
    ON ab_party_invitation (tenant_id, party_id, status);

CREATE TABLE IF NOT EXISTS ab_actor_preference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) UNIQUE NOT NULL,
    tenant_id BIGINT NOT NULL,
    tenant_member_id BIGINT NOT NULL,
    preferred_party_id BIGINT,
    last_party_id BIGINT,
    actor_selection_mode VARCHAR(20) NOT NULL DEFAULT 'prompt',
    context_version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_actor_preference_member FOREIGN KEY (tenant_id, tenant_member_id)
        REFERENCES ab_tenant_member (tenant_id, id),
    CONSTRAINT fk_actor_preference_preferred_party FOREIGN KEY (tenant_id, preferred_party_id)
        REFERENCES ab_party (tenant_id, id),
    CONSTRAINT fk_actor_preference_last_party FOREIGN KEY (tenant_id, last_party_id)
        REFERENCES ab_party (tenant_id, id),
    CONSTRAINT ck_actor_selection_mode CHECK (
        actor_selection_mode IN ('prompt', 'last_used', 'preferred')
    ),
    CONSTRAINT uq_actor_preference_member UNIQUE (tenant_id, tenant_member_id)
);

CREATE TABLE IF NOT EXISTS ab_party_site (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) UNIQUE NOT NULL,
    tenant_id BIGINT NOT NULL,
    party_id BIGINT NOT NULL,
    code VARCHAR(100) NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    site_type VARCHAR(40) NOT NULL,
    country_code VARCHAR(2),
    region VARCHAR(120),
    city VARCHAR(120),
    address_line1 VARCHAR(300),
    address_line2 VARCHAR(300),
    postal_code VARCHAR(32),
    geo JSONB,
    contact JSONB,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    deleted_flag BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_party_site_party FOREIGN KEY (tenant_id, party_id)
        REFERENCES ab_party (tenant_id, id),
    CONSTRAINT ck_party_site_status CHECK (status IN ('active', 'inactive', 'closed')),
    CONSTRAINT uq_party_site_tenant_id_id UNIQUE (tenant_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_party_site_code_active
    ON ab_party_site (tenant_id, party_id, code) WHERE deleted_flag = FALSE;

CREATE TABLE IF NOT EXISTS ab_party_relation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) UNIQUE NOT NULL,
    tenant_id BIGINT NOT NULL,
    from_party_id BIGINT NOT NULL,
    to_party_id BIGINT NOT NULL,
    relation_type VARCHAR(60) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    valid_from TIMESTAMPTZ,
    valid_until TIMESTAMPTZ,
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    CONSTRAINT fk_party_relation_from FOREIGN KEY (tenant_id, from_party_id)
        REFERENCES ab_party (tenant_id, id),
    CONSTRAINT fk_party_relation_to FOREIGN KEY (tenant_id, to_party_id)
        REFERENCES ab_party (tenant_id, id),
    CONSTRAINT ck_party_relation_distinct CHECK (from_party_id <> to_party_id),
    CONSTRAINT ck_party_relation_status CHECK (
        status IN ('pending', 'active', 'suspended', 'ended', 'rejected')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_party_relation_current
    ON ab_party_relation (tenant_id, from_party_id, to_party_id, relation_type)
    WHERE status IN ('pending', 'active', 'suspended');

CREATE TABLE IF NOT EXISTS ab_business_network (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) UNIQUE NOT NULL,
    tenant_id BIGINT NOT NULL,
    code VARCHAR(100) NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    network_type VARCHAR(60) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    policy JSONB NOT NULL DEFAULT '{}'::jsonb,
    deleted_flag BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    CONSTRAINT fk_business_network_tenant FOREIGN KEY (tenant_id) REFERENCES ab_tenant (id),
    CONSTRAINT ck_business_network_status CHECK (status IN ('draft', 'active', 'suspended', 'closed')),
    CONSTRAINT uq_business_network_tenant_id_id UNIQUE (tenant_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_business_network_code_active
    ON ab_business_network (tenant_id, code) WHERE deleted_flag = FALSE;

CREATE TABLE IF NOT EXISTS ab_network_party_enrollment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) UNIQUE NOT NULL,
    tenant_id BIGINT NOT NULL,
    network_id BIGINT NOT NULL,
    party_id BIGINT NOT NULL,
    enrollment_role VARCHAR(60),
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    enrolled_at TIMESTAMPTZ,
    ended_at TIMESTAMPTZ,
    attributes JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_network_enrollment_network FOREIGN KEY (tenant_id, network_id)
        REFERENCES ab_business_network (tenant_id, id),
    CONSTRAINT fk_network_enrollment_party FOREIGN KEY (tenant_id, party_id)
        REFERENCES ab_party (tenant_id, id),
    CONSTRAINT ck_network_enrollment_status CHECK (
        status IN ('pending', 'active', 'suspended', 'ended', 'rejected')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_network_party_enrollment_current
    ON ab_network_party_enrollment (tenant_id, network_id, party_id)
    WHERE status IN ('pending', 'active', 'suspended');

CREATE TABLE IF NOT EXISTS ab_party_lifecycle_transition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) UNIQUE NOT NULL,
    tenant_id BIGINT NOT NULL,
    party_id BIGINT NOT NULL,
    from_status VARCHAR(30),
    to_status VARCHAR(30) NOT NULL,
    reason_code VARCHAR(100),
    reason TEXT,
    requested_by BIGINT,
    approved_by BIGINT,
    transition_metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_party_lifecycle_party FOREIGN KEY (tenant_id, party_id)
        REFERENCES ab_party (tenant_id, id),
    CONSTRAINT ck_party_lifecycle_to CHECK (
        to_status IN ('pending', 'active', 'suspended', 'rejected', 'closed')
    )
);

CREATE INDEX IF NOT EXISTS idx_party_lifecycle_history
    ON ab_party_lifecycle_transition (tenant_id, party_id, occurred_at DESC);

-- Login applications/channels are pre-auth routing metadata. They are queried
-- with explicit application and tenant selectors and must not depend on an
-- already-established TenantContext.
CREATE TABLE IF NOT EXISTS ab_login_application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) UNIQUE NOT NULL,
    code VARCHAR(100) UNIQUE NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    application_type VARCHAR(40) NOT NULL DEFAULT 'web',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    settings JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_login_application_status CHECK (status IN ('active', 'disabled'))
);

CREATE TABLE IF NOT EXISTS ab_login_channel (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) UNIQUE NOT NULL,
    application_id BIGINT NOT NULL,
    tenant_id BIGINT,
    code VARCHAR(100) NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    channel_type VARCHAR(40) NOT NULL DEFAULT 'business',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    sort_order INTEGER NOT NULL DEFAULT 0,
    settings JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_login_channel_application FOREIGN KEY (application_id)
        REFERENCES ab_login_application (id),
    CONSTRAINT fk_login_channel_tenant FOREIGN KEY (tenant_id) REFERENCES ab_tenant (id),
    CONSTRAINT ck_login_channel_status CHECK (status IN ('active', 'disabled')),
    CONSTRAINT uq_login_channel_application_id_id UNIQUE (application_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_login_channel_global_code
    ON ab_login_channel (application_id, code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_login_channel_tenant_code
    ON ab_login_channel (application_id, tenant_id, code) WHERE tenant_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS ab_login_channel_auth_method (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) UNIQUE NOT NULL,
    application_id BIGINT NOT NULL,
    login_channel_id BIGINT NOT NULL,
    auth_method VARCHAR(60) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    sort_order INTEGER NOT NULL DEFAULT 0,
    settings JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_login_auth_method_channel FOREIGN KEY (application_id, login_channel_id)
        REFERENCES ab_login_channel (application_id, id),
    CONSTRAINT ck_login_auth_method_status CHECK (status IN ('active', 'disabled')),
    CONSTRAINT uq_login_auth_method UNIQUE (login_channel_id, auth_method)
);

CREATE TABLE IF NOT EXISTS ab_identity_provider_instance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) UNIQUE NOT NULL,
    application_id BIGINT NOT NULL,
    tenant_id BIGINT,
    code VARCHAR(100) NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    provider_type VARCHAR(60) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    config JSONB NOT NULL DEFAULT '{}'::jsonb,
    secret_ref VARCHAR(300),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_identity_provider_application FOREIGN KEY (application_id)
        REFERENCES ab_login_application (id),
    CONSTRAINT fk_identity_provider_tenant FOREIGN KEY (tenant_id) REFERENCES ab_tenant (id),
    CONSTRAINT ck_identity_provider_status CHECK (status IN ('active', 'disabled')),
    CONSTRAINT uq_identity_provider_application_id_id UNIQUE (application_id, id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_identity_provider_global_code
    ON ab_identity_provider_instance (application_id, code) WHERE tenant_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_identity_provider_tenant_code
    ON ab_identity_provider_instance (application_id, tenant_id, code) WHERE tenant_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS ab_external_identity_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) UNIQUE NOT NULL,
    application_id BIGINT NOT NULL,
    identity_provider_instance_id BIGINT NOT NULL,
    tenant_id BIGINT,
    user_id BIGINT NOT NULL,
    external_subject VARCHAR(300) NOT NULL,
    external_username VARCHAR(300),
    email VARCHAR(300),
    claims JSONB NOT NULL DEFAULT '{}'::jsonb,
    linked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMPTZ,
    unlinked_at TIMESTAMPTZ,
    CONSTRAINT fk_external_identity_provider FOREIGN KEY (application_id, identity_provider_instance_id)
        REFERENCES ab_identity_provider_instance (application_id, id),
    CONSTRAINT fk_external_identity_tenant FOREIGN KEY (tenant_id) REFERENCES ab_tenant (id),
    CONSTRAINT fk_external_identity_user FOREIGN KEY (user_id) REFERENCES ab_user (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_external_identity_subject_active
    ON ab_external_identity_link (identity_provider_instance_id, external_subject)
    WHERE unlinked_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_external_identity_user
    ON ab_external_identity_link (user_id, application_id) WHERE unlinked_at IS NULL;

-- Session context is independent from user.security_version. context_version is
-- rotated whenever the effective Actor changes so the previous JWT can be rejected.
ALTER TABLE ab_user_session
    ADD COLUMN IF NOT EXISTS application_id BIGINT,
    ADD COLUMN IF NOT EXISTS login_channel_id BIGINT,
    ADD COLUMN IF NOT EXISTS tenant_id BIGINT,
    ADD COLUMN IF NOT EXISTS tenant_member_id BIGINT,
    ADD COLUMN IF NOT EXISTS execution_scope VARCHAR(20),
    ADD COLUMN IF NOT EXISTS actor_party_id BIGINT,
    ADD COLUMN IF NOT EXISTS party_membership_id BIGINT,
    ADD COLUMN IF NOT EXISTS session_stage VARCHAR(30) NOT NULL DEFAULT 'onboarding',
    ADD COLUMN IF NOT EXISTS context_version BIGINT NOT NULL DEFAULT 1;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_session_application') THEN
        ALTER TABLE ab_user_session ADD CONSTRAINT fk_user_session_application
            FOREIGN KEY (application_id) REFERENCES ab_login_application (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_session_login_channel') THEN
        ALTER TABLE ab_user_session ADD CONSTRAINT fk_user_session_login_channel
            FOREIGN KEY (login_channel_id) REFERENCES ab_login_channel (id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_session_member') THEN
        ALTER TABLE ab_user_session ADD CONSTRAINT fk_user_session_member
            FOREIGN KEY (tenant_id, tenant_member_id) REFERENCES ab_tenant_member (tenant_id, id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_session_actor_party') THEN
        ALTER TABLE ab_user_session ADD CONSTRAINT fk_user_session_actor_party
            FOREIGN KEY (tenant_id, actor_party_id) REFERENCES ab_party (tenant_id, id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_user_session_party_membership') THEN
        ALTER TABLE ab_user_session ADD CONSTRAINT fk_user_session_party_membership
            FOREIGN KEY (tenant_id, party_membership_id) REFERENCES ab_party_membership (tenant_id, id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_user_session_execution_scope') THEN
        ALTER TABLE ab_user_session ADD CONSTRAINT ck_user_session_execution_scope
            CHECK (execution_scope IS NULL OR execution_scope IN ('party', 'tenant', 'platform', 'system'));
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_user_session_stage') THEN
        ALTER TABLE ab_user_session ADD CONSTRAINT ck_user_session_stage
            CHECK (session_stage IN ('onboarding', 'actor_selection', 'ready', 'platform', 'tenant_admin'));
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_user_session_context
    ON ab_user_session (tenant_id, tenant_member_id, revoked, context_version);

-- Existing tenants receive the same Party permissions that future tenant bootstrap
-- creates from default-bootstrap.json. Only tenant_admin receives management.
INSERT INTO ab_permission (
    pid, tenant_id, code, name, description, resource_type, resource_code,
    action, source, source_ref, status
)
SELECT substring(md5(t.id::text || ':party.party.read') from 1 for 26),
       t.id, 'party.party.read', 'Business participant read',
       'Read Party and available Actor context in this tenant',
       'function', '/api/actors', 'read', 'system', 'party-actor-v1', 'active'
  FROM ab_tenant t
 WHERE t.deleted_flag = FALSE
ON CONFLICT (tenant_id, code) DO NOTHING;

INSERT INTO ab_permission (
    pid, tenant_id, code, name, description, resource_type, resource_code,
    action, source, source_ref, status
)
SELECT substring(md5(t.id::text || ':party.party.manage') from 1 for 26),
       t.id, 'party.party.manage', 'Business participant management',
       'Approve and manage Party lifecycle in this tenant',
       'function', '/api/actors/parties', 'manage', 'system', 'party-actor-v1', 'active'
  FROM ab_tenant t
 WHERE t.deleted_flag = FALSE
ON CONFLICT (tenant_id, code) DO NOTHING;

INSERT INTO ab_role_permission (
    pid, tenant_id, role_id, permission_id, grant_type, status
)
SELECT substring(md5(r.id::text || ':' || p.id::text) from 1 for 26),
       r.tenant_id, r.id, p.id, 'grant', 'active'
  FROM ab_role r
  JOIN ab_permission p
    ON p.tenant_id = r.tenant_id
   AND p.code IN ('party.party.read', 'party.party.manage')
 WHERE r.code = 'tenant_admin' AND r.deleted_flag = FALSE
ON CONFLICT (tenant_id, role_id, permission_id) DO NOTHING;

INSERT INTO ab_role_permission (
    pid, tenant_id, role_id, permission_id, grant_type, status
)
SELECT substring(md5(r.id::text || ':' || p.id::text) from 1 for 26),
       r.tenant_id, r.id, p.id, 'grant', 'active'
  FROM ab_role r
  JOIN ab_permission p
    ON p.tenant_id = r.tenant_id AND p.code = 'party.party.read'
 WHERE r.code = 'tenant_member' AND r.deleted_flag = FALSE
ON CONFLICT (tenant_id, role_id, permission_id) DO NOTHING;

-- Minimal default login surface. Tenant-specific channel overrides can be added
-- later without changing the model.
INSERT INTO ab_login_application (pid, code, display_name, application_type, status)
VALUES ('01K2AX1APP0000000000000000', 'business-web', 'Business Web', 'web', 'active')
ON CONFLICT (code) DO NOTHING;

INSERT INTO ab_login_channel (
    pid, application_id, tenant_id, code, display_name, channel_type, status, sort_order
)
SELECT '01K2AX1CHN0000000000000000', id, NULL, 'default-business-web',
       'Default Business Web', 'business', 'active', 0
FROM ab_login_application
WHERE code = 'business-web'
ON CONFLICT DO NOTHING;

INSERT INTO ab_login_channel_auth_method (
    pid, application_id, login_channel_id, auth_method, status, sort_order
)
SELECT '01K2AX1MET0000000000000000', c.application_id, c.id,
       'email_password', 'active', 0
FROM ab_login_channel c
JOIN ab_login_application a ON a.id = c.application_id
WHERE a.code = 'business-web' AND c.code = 'default-business-web' AND c.tenant_id IS NULL
ON CONFLICT (login_channel_id, auth_method) DO NOTHING;

COMMENT ON TABLE ab_party IS 'Business participant/organization within one tenant; Party is an Actor, not an isolation boundary';
COMMENT ON TABLE ab_party_capability IS 'Business qualification only; capability does not grant RBAC permission';
COMMENT ON TABLE ab_party_relation IS 'Business relationship only; a relation does not grant resource access';
COMMENT ON TABLE ab_network_party_enrollment IS 'Network participation only; enrollment does not grant resource access';
COMMENT ON TABLE ab_login_application IS 'Public login application registry used before tenant context exists';
COMMENT ON TABLE ab_login_channel IS 'Application login surface with optional explicit tenant override';
COMMENT ON COLUMN ab_user_session.context_version IS 'Session actor-context version (cv), independent from user security_version (sv)';
