CREATE TABLE IF NOT EXISTS ab_page_schema_contribution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    env_id BIGINT NOT NULL,
    plugin_pid VARCHAR(26) NOT NULL,
    plugin_version VARCHAR(50) NOT NULL,
    contribution_id VARCHAR(160) NOT NULL,
    target_page_key VARCHAR(200) NOT NULL,
    slot_id VARCHAR(160) NOT NULL,
    kind VARCHAR(20) NOT NULL,
    priority INTEGER NOT NULL DEFAULT 0,
    payload JSONB NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    deleted_flag BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_page_contribution_plugin FOREIGN KEY (plugin_pid) REFERENCES ab_plugin(pid),
    CONSTRAINT fk_page_contribution_env FOREIGN KEY (env_id) REFERENCES ab_environment(id),
    CONSTRAINT chk_page_contribution_kind CHECK (kind IN ('block', 'action')),
    CONSTRAINT uq_page_contribution_owner UNIQUE
        (tenant_id, env_id, plugin_pid, contribution_id)
);

CREATE INDEX IF NOT EXISTS idx_page_contribution_runtime
    ON ab_page_schema_contribution (tenant_id, env_id, target_page_key, active)
    WHERE deleted_flag = FALSE;

CREATE INDEX IF NOT EXISTS idx_page_contribution_plugin
    ON ab_page_schema_contribution (plugin_pid, tenant_id, env_id);
