CREATE TABLE IF NOT EXISTS ab_import_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(32) NOT NULL,
    tenant_id BIGINT NOT NULL,
    model_code VARCHAR(128) NOT NULL,
    file_name TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'pending',
    total_rows INTEGER NOT NULL DEFAULT 0,
    processed_rows INTEGER NOT NULL DEFAULT 0,
    success_rows INTEGER NOT NULL DEFAULT 0,
    error_rows INTEGER NOT NULL DEFAULT 0,
    import_mode VARCHAR(16) NOT NULL DEFAULT 'insert',
    error_report_url TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    created_by BIGINT,
    deleted_flag BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE ab_import_job ADD COLUMN IF NOT EXISTS pid VARCHAR(32);
UPDATE ab_import_job
SET pid = 'legacy-' || id::text
WHERE pid IS NULL;
ALTER TABLE ab_import_job ALTER COLUMN pid SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_import_job_pid ON ab_import_job(pid);
CREATE INDEX IF NOT EXISTS ix_import_job_tenant_status
    ON ab_import_job(tenant_id, status)
    WHERE deleted_flag = FALSE;
CREATE INDEX IF NOT EXISTS ix_import_job_tenant_model_created
    ON ab_import_job(tenant_id, model_code, created_at DESC)
    WHERE deleted_flag = FALSE;
