-- Tenant-scoped collaborators for Open Platform applications.
-- The creator of each existing application becomes its initial owner.

ALTER TABLE ab_external_application
    ADD CONSTRAINT uq_external_application_owner_id UNIQUE (owner_tenant_id, id);

CREATE TABLE ab_external_application_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    application_id BIGINT NOT NULL,
    user_pid VARCHAR(64) NOT NULL,
    role VARCHAR(24) NOT NULL CHECK (role IN ('owner', 'maintainer', 'viewer')),
    created_by_pid VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by_pid VARCHAR(64),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_external_application_member_application
        FOREIGN KEY (tenant_id, application_id)
        REFERENCES ab_external_application(owner_tenant_id, id),
    CONSTRAINT uq_external_application_member UNIQUE (application_id, user_pid)
);

CREATE INDEX idx_external_application_member_user
    ON ab_external_application_member (tenant_id, user_pid, role, application_id);

INSERT INTO ab_external_application_member
    (tenant_id, application_id, user_pid, role, created_by_pid, created_at, updated_by_pid, updated_at)
SELECT owner_tenant_id, id, created_by_pid, 'owner', created_by_pid, created_at, created_by_pid, updated_at
FROM ab_external_application
WHERE created_by_pid IS NOT NULL
ON CONFLICT (application_id, user_pid) DO NOTHING;

CREATE TABLE ab_external_application_member_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) NOT NULL UNIQUE,
    tenant_id BIGINT NOT NULL,
    application_id BIGINT NOT NULL,
    action VARCHAR(24) NOT NULL CHECK (action IN ('add', 'update', 'remove')),
    target_user_pid VARCHAR(64) NOT NULL,
    previous_role VARCHAR(24),
    new_role VARCHAR(24),
    actor_user_pid VARCHAR(64) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_external_application_member_audit_application
        FOREIGN KEY (tenant_id, application_id)
        REFERENCES ab_external_application(owner_tenant_id, id)
);

CREATE INDEX idx_external_application_member_audit_application
    ON ab_external_application_member_audit (tenant_id, application_id, occurred_at DESC);

COMMENT ON TABLE ab_external_application_member IS
    'Tenant-scoped owner, maintainer and viewer collaboration grants for external applications';
COMMENT ON TABLE ab_external_application_member_audit IS
    'Append-only audit trail for external application collaboration changes';
