-- Permission v2 capability registry: business-language groupings of permission codes shipped by
-- plugins in config/capabilities.json (the unit the v2 UI presents instead of the raw resource x
-- action matrix). A capability resolves to its included permission codes; the runtime permission
-- engine never reads this table. Table is ab_permission_capability — distinct from the unrelated
-- ab_capability (agent/MCP capability registry). Additive + idempotent.

CREATE TABLE IF NOT EXISTS ab_permission_capability (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid                 VARCHAR(64),
    tenant_id           BIGINT NOT NULL,
    code                VARCHAR(255) NOT NULL,
    group_name          VARCHAR(255),
    name                VARCHAR(255),
    name_en             VARCHAR(255),
    description         TEXT,
    include_codes       TEXT NOT NULL,                  -- comma-separated permission codes (column not named 'includes': jsqlparser keyword)
    tier                VARCHAR(32),                    -- viewer / editor / admin
    sensitive           BOOLEAN NOT NULL DEFAULT FALSE,
    unmasks_fields      TEXT,                           -- comma-separated model.field
    order_no            INTEGER NOT NULL DEFAULT 100,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_permission_capability UNIQUE (tenant_id, code)
);

CREATE INDEX IF NOT EXISTS idx_permission_capability_tenant_group ON ab_permission_capability(tenant_id, group_name);

COMMENT ON TABLE ab_permission_capability IS 'Permission v2 capability registry (plugin-shipped business-language permission bundles); distinct from ab_capability (agent capabilities)';
