-- AuraBoot core-only migration
-- Generated by scripts/application/migration-ownership.mjs.
-- Do not edit this staged artifact; edit the owning source migration/config instead.
-- Source: V20260715110000__drt_log_trace_snapshot.sql
-- AuraBoot core-only migration
-- Generated by scripts/application/migration-ownership.mjs.
-- Do not edit this staged artifact; edit the owning source migration/config instead.
-- Source: V20260715110000__drt_log_trace_snapshot.sql
ALTER TABLE ab_drt_log
    ADD COLUMN IF NOT EXISTS trace_snapshot JSONB;

COMMENT ON COLUMN ab_drt_log.trace_snapshot IS 'Decision Runtime trace diagnostics such as virtual source resolution evidence';
