-- WeChat mini-program identity binding: links one WeChat openid (per app) to a
-- platform user. A user may hold multiple provider identities; unionid is the
-- cross-app correlation key and may be absent until the WeChat open-platform
-- binding delivers it. session_key is intentionally not persisted.
CREATE TABLE ab_auth_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    provider VARCHAR(32) NOT NULL,
    app_id VARCHAR(64) NOT NULL,
    openid VARCHAR(64) NOT NULL,
    unionid VARCHAR(64),
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_auth_identity_provider_app_openid UNIQUE (provider, app_id, openid)
);

CREATE INDEX idx_auth_identity_user ON ab_auth_identity (user_id);
CREATE INDEX idx_auth_identity_unionid ON ab_auth_identity (unionid) WHERE unionid IS NOT NULL;
