-- AuraBoot core-only migration
-- Generated by scripts/application/migration-ownership.mjs.
-- Do not edit this staged artifact; edit the owning source migration/config instead.
-- Source: V20260624021000__record_comment_pid.sql
-- AuraBoot core-only migration
-- Generated by scripts/application/migration-ownership.mjs.
-- Do not edit this staged artifact; edit the owning source migration/config instead.
-- Source: V20260624021000__record_comment_pid.sql
ALTER TABLE ab_record_comment
    ADD COLUMN IF NOT EXISTS pid VARCHAR(26);

UPDATE ab_record_comment
SET pid = SUBSTRING(REPLACE(gen_random_uuid()::text, '-', ''), 1, 26)
WHERE pid IS NULL OR pid = '';

ALTER TABLE ab_record_comment
    ALTER COLUMN pid SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_ab_record_comment_pid
    ON ab_record_comment (pid);
