-- AuraBoot core-only migration
-- Generated by scripts/application/migration-ownership.mjs.
-- Do not edit this staged artifact; edit the owning source migration/config instead.
-- Source: V20260622003000__behavior_quarantine_retention_index.sql
-- AuraBoot core-only migration
-- Generated by scripts/application/migration-ownership.mjs.
-- Do not edit this staged artifact; edit the owning source migration/config instead.
-- Source: V20260622003000__behavior_quarantine_retention_index.sql
-- Supports bounded TTL cleanup of raw quarantine payloads.
CREATE INDEX IF NOT EXISTS idx_ab_behavior_quarantine_retention
    ON ab_behavior_quarantine (quarantined_at, id);
