-- AuraBoot core-only migration
-- Generated by scripts/application/migration-ownership.mjs.
-- Do not edit this staged artifact; edit the owning source migration/config instead.
-- Source: V20260714120000__permission_audit_record_pid.sql
-- AuraBoot core-only migration
-- Generated by scripts/application/migration-ownership.mjs.
-- Do not edit this staged artifact; edit the owning source migration/config instead.
-- Source: V20260714120000__permission_audit_record_pid.sql
ALTER TABLE ab_permission_audit_log
    ADD COLUMN IF NOT EXISTS record_pid VARCHAR(64);

CREATE INDEX IF NOT EXISTS idx_ab_perm_audit_resource_record_pid
    ON ab_permission_audit_log (tenant_id, resource_code, record_pid, created_at)
    WHERE record_pid IS NOT NULL;
