CREATE TABLE IF NOT EXISTS ab_drt_condition_fragment (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid                 VARCHAR(26) UNIQUE NOT NULL,
    tenant_id           BIGINT NOT NULL,
    fragment_code       VARCHAR(100) NOT NULL,
    fragment_name       VARCHAR(200) NOT NULL,
    description         TEXT,
    scope_type          VARCHAR(50),
    scope_ref           VARCHAR(200),
    version             INTEGER NOT NULL DEFAULT 1,
    status              VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    condition_spec_json JSONB NOT NULL,
    field_refs_json     JSONB NOT NULL DEFAULT '[]'::jsonb,
    decision_refs_json  JSONB NOT NULL DEFAULT '[]'::jsonb,
    owner_module        VARCHAR(100),
    enabled             BOOLEAN NOT NULL DEFAULT TRUE,
    published_by        VARCHAR(26),
    published_at        TIMESTAMPTZ,
    created_by          VARCHAR(26),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by          VARCHAR(26),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_drt_condition_fragment_tenant_code_version UNIQUE (tenant_id, fragment_code, version),
    CONSTRAINT chk_drt_condition_fragment_status CHECK (status IN (
        'DRAFT', 'VALIDATED', 'PUBLISHED', 'DEPRECATED', 'RETIRED'
    ))
);

CREATE INDEX IF NOT EXISTS idx_drt_condition_fragment_tenant_code
    ON ab_drt_condition_fragment (tenant_id, fragment_code);
CREATE INDEX IF NOT EXISTS idx_drt_condition_fragment_scope
    ON ab_drt_condition_fragment (tenant_id, scope_type, scope_ref);
CREATE INDEX IF NOT EXISTS idx_drt_condition_fragment_status
    ON ab_drt_condition_fragment (tenant_id, status);

COMMENT ON TABLE ab_drt_condition_fragment IS 'Decision Runtime - reusable ConditionSpec fragments shared by SLA, BPM, Automation, Permission and EventPolicy';
COMMENT ON COLUMN ab_drt_condition_fragment.condition_spec_json IS 'Serialized ConditionSpec with ConditionNode root and optional decisionBindings';
