-- Dashboard folder tree (Cordys dashboard-module parity, PAR-25).
-- Folders are tenant-scoped and soft-deleted; dashboards reference their
-- folder by module_id (nullable = unassigned / root level).

CREATE TABLE IF NOT EXISTS ab_dashboard_module (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid VARCHAR(26) UNIQUE NOT NULL,
    tenant_id BIGINT NOT NULL,
    name VARCHAR(200) NOT NULL,
    parent_id BIGINT,
    sort_order INT NOT NULL DEFAULT 0,

    deleted_flag BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(26),
    updated_by VARCHAR(26),

    CONSTRAINT fk_dashboard_module_parent
        FOREIGN KEY (parent_id) REFERENCES ab_dashboard_module(id)
);

CREATE INDEX IF NOT EXISTS idx_dashboard_module_tenant
    ON ab_dashboard_module(tenant_id) WHERE deleted_flag = FALSE;
CREATE INDEX IF NOT EXISTS idx_dashboard_module_parent
    ON ab_dashboard_module(parent_id) WHERE deleted_flag = FALSE;

ALTER TABLE ab_dashboard
    ADD COLUMN IF NOT EXISTS module_id BIGINT;
CREATE INDEX IF NOT EXISTS idx_dashboard_module
    ON ab_dashboard(module_id) WHERE deleted_flag = FALSE AND module_id IS NOT NULL;
