-- AMOS-T01 reliable integration runtime v1.
-- Extends the existing Core-owned outbox; no business domain table is owned here.

ALTER TABLE ab_outbox
    ADD COLUMN IF NOT EXISTS schema_version TEXT,
    ADD COLUMN IF NOT EXISTS event_source TEXT,
    ADD COLUMN IF NOT EXISTS subject TEXT,
    ADD COLUMN IF NOT EXISTS occurred_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS correlation_id TEXT,
    ADD COLUMN IF NOT EXISTS causation_id TEXT,
    ADD COLUMN IF NOT EXISTS ordering_key TEXT,
    ADD COLUMN IF NOT EXISTS event_sequence BIGINT,
    ADD COLUMN IF NOT EXISTS headers JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS lease_owner TEXT,
    ADD COLUMN IF NOT EXISTS lease_token TEXT,
    ADD COLUMN IF NOT EXISTS lease_until TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS replay_count INTEGER NOT NULL DEFAULT 0;

-- Older writers used enum names while the dispatcher SQL used lower-case values. Normalize the
-- existing lifecycle before the new lease predicate takes ownership, and release pre-lease claims.
UPDATE ab_outbox
SET status = LOWER(status)
WHERE status IN ('PENDING', 'PROCESSING', 'DELIVERED', 'FAILED');

UPDATE ab_outbox
SET status = 'pending',
    next_retry_at = COALESCE(next_retry_at, NOW()),
    last_error = 'Recovered legacy processing row during reliable runtime migration'
WHERE status = 'processing' AND lease_token IS NULL;

-- Legacy JVM-event rows keep their former identity rules. New versioned envelopes are unique per
-- tenant and event id, which makes the outbox source write idempotent without risking upgrade drift.
CREATE UNIQUE INDEX IF NOT EXISTS uq_outbox_reliable_tenant_event
    ON ab_outbox (tenant_id, event_id)
    WHERE schema_version IS NOT NULL;

DROP INDEX IF EXISTS idx_outbox_poll;
CREATE INDEX idx_outbox_poll ON ab_outbox (status, next_retry_at, lease_until, created_at)
    WHERE status IN ('pending', 'processing');

CREATE INDEX IF NOT EXISTS idx_outbox_ordering_fence
    ON ab_outbox (tenant_id, ordering_key, event_sequence, status)
    WHERE ordering_key IS NOT NULL AND status IN ('pending', 'processing');

CREATE TABLE IF NOT EXISTS ab_integration_receipt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    event_id TEXT NOT NULL,
    consumer_code TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('processing', 'applied')),
    lease_token TEXT NOT NULL,
    received_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    applied_at TIMESTAMPTZ,
    CONSTRAINT uq_integration_receipt UNIQUE (tenant_id, event_id, consumer_code)
);

CREATE INDEX IF NOT EXISTS idx_integration_receipt_event
    ON ab_integration_receipt (tenant_id, event_id, status);

CREATE TABLE IF NOT EXISTS ab_integration_dead_letter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outbox_id BIGINT NOT NULL REFERENCES ab_outbox(id),
    tenant_id BIGINT NOT NULL,
    event_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    payload JSONB NOT NULL,
    error_detail TEXT,
    failed_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('open', 'replayed')),
    replayed_at TIMESTAMPTZ,
    replayed_by TEXT,
    CONSTRAINT uq_integration_dead_letter_outbox UNIQUE (outbox_id)
);

CREATE INDEX IF NOT EXISTS idx_integration_dead_letter_status
    ON ab_integration_dead_letter (status, failed_at);

COMMENT ON TABLE ab_integration_receipt IS
    'Idempotency fence and durable receipt for reliable integration consumers';
COMMENT ON TABLE ab_integration_dead_letter IS
    'Terminal reliable integration failures available for explicit replay and reconciliation';
