package com.auraboot.framework.behavior.keyed;

import com.auraboot.framework.application.TestApplication;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.web.client.TestRestTemplate;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.catchThrowable;

/**
 * Real-Postgres HTTP golden for the SP2 anonymous keyed-collect path.
 *
 * <p><b>What it proves on a real DB + the real security filter chain (MockMvc):</b> an
 * unauthenticated {@code POST /api/collect/keyed} carrying a public {@code abk_} key is reachable
 * (whitelisted, no JWT), resolves the owning tenant server-side, ingests as anonymous (user null,
 * client anonId), keeps tenants isolated, and rejects unknown/disabled/missing keys with 403. It
 * also proves the {@code site_key} index artifact this slice ships: a <b>global</b>
 * {@code UNIQUE(site_key)} (single column, no tenant prefix) that enforces cross-tenant uniqueness
 * and turns the resolve lookup into an index scan.
 *
 * <p><b>Fixture discipline (mirrors SiteKeyRegistryIT):</b> the two tables are created with
 * {@code CREATE TABLE IF NOT EXISTS} and never dropped (so the IT coexists with a real model/store),
 * scoped to a dedicated tenant range + {@code abk_it_} key prefix, cleaned up before+after — an
 * integration-test fixture, not manual DML against production data.
 *
 * <p><b>Scope note:</b> the index is created here via the exact DDL the platform's
 * {@code SchemaManagementService.createFieldIndex(behavior_site_key, site_key, UNIQUE)} emits
 * (index name {@code uk_mt_behavior_site_key_site_key}). The initializer's <i>wiring</i> to that API
 * (dual trigger, idempotent) is unit-tested in {@code SiteKeyIndexInitializerTest}; the live
 * plugin-import → initializer → createFieldIndex execution against the registered model is
 * validated end-to-end in SP4's assembled golden (the model is not registered in this bare IT DB).
 */
@SpringBootTest(classes = TestApplication.class, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("integration-test")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class KeyedCollectIT {

    private static final long TENANT_A = 990_201L;
    private static final long TENANT_B = 990_202L;
    private static final String KEY_A = "abk_it_keyedA000000000000000000000";
    private static final String KEY_B = "abk_it_keyedB000000000000000000000";
    private static final String KEY_DISABLED = "abk_it_keyedD000000000000000000000";
    private static final String INDEX = "uk_mt_behavior_site_key_site_key";

    @Autowired
    private TestRestTemplate restTemplate;
    @Autowired
    private JdbcTemplate jdbc;

    /** POST the keyed-collect endpoint over a real servlet container (so the whitelist applies). */
    private ResponseEntity<String> postKeyed(String siteKey, String eventId) {
        return postKeyedBody(siteKey, body(eventId));
    }

    private ResponseEntity<String> postKeyedBody(String siteKey, String body) {
        HttpHeaders h = new HttpHeaders();
        h.setContentType(MediaType.APPLICATION_JSON);
        if (siteKey != null) {
            h.set("X-Site-Key", siteKey);
        }
        return restTemplate.exchange("/api/collect/keyed", HttpMethod.POST,
                new HttpEntity<>(body, h), String.class);
    }

    @BeforeAll
    void seed() {
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS mt_behavior_site_key (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                pid VARCHAR(32) NOT NULL,
                tenant_id BIGINT,
                site_key VARCHAR(64),
                name VARCHAR(200) NOT NULL,
                status VARCHAR(32) DEFAULT 'active',
                origin_allowlist JSONB,
                created_at TIMESTAMP DEFAULT now()
            )""");
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS ab_behavior_event (
                id BIGSERIAL PRIMARY KEY,
                event_id VARCHAR(40) NOT NULL,
                schema_version VARCHAR(16),
                event_name VARCHAR(120) NOT NULL,
                event_category VARCHAR(32),
                source VARCHAR(24),
                identity_quality VARCHAR(16),
                occurred_at TIMESTAMPTZ,
                received_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                tenant_id BIGINT NOT NULL,
                user_id BIGINT,
                anon_id VARCHAR(64),
                client_session_id VARCHAR(64),
                interaction_id VARCHAR(64),
                caused_by_event_id VARCHAR(40),
                trace_id VARCHAR(36),
                source_span_id VARCHAR(36),
                run_id VARCHAR(64),
                ui_element_id VARCHAR(80),
                app_id VARCHAR(64),
                page_id VARCHAR(64),
                block_id VARCHAR(64),
                element_code VARCHAR(64),
                props JSONB,
                consent_state VARCHAR(24),
                consent_version VARCHAR(16),
                sampling_unit VARCHAR(16),
                sampling_probability NUMERIC(6,5),
                producer_name VARCHAR(48),
                producer_version VARCHAR(24),
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
            )""");
        jdbc.execute("CREATE UNIQUE INDEX IF NOT EXISTS uk_ab_behavior_event_tenant_eventid "
                + "ON ab_behavior_event (tenant_id, event_id)");
        jdbc.execute("""
            CREATE TABLE IF NOT EXISTS ab_behavior_quarantine (
                id BIGSERIAL PRIMARY KEY,
                tenant_id BIGINT NOT NULL,
                user_id BIGINT,
                anon_id TEXT,
                event_id TEXT,
                event_name TEXT,
                reason VARCHAR(64) NOT NULL,
                detail TEXT,
                raw_event JSONB,
                replay_status VARCHAR(24) NOT NULL DEFAULT 'pending',
                replay_detail TEXT,
                replayed_behavior_event_id BIGINT,
                replayed_at TIMESTAMPTZ,
                quarantined_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
                created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
            )""");
        jdbc.execute("ALTER TABLE ab_behavior_quarantine ALTER COLUMN anon_id TYPE TEXT");
        jdbc.execute("ALTER TABLE ab_behavior_quarantine ALTER COLUMN event_id TYPE TEXT");
        jdbc.execute("ALTER TABLE ab_behavior_quarantine ALTER COLUMN event_name TYPE TEXT");
        jdbc.execute("ALTER TABLE ab_behavior_quarantine ADD COLUMN IF NOT EXISTS replay_status VARCHAR(24) NOT NULL DEFAULT 'pending'");
        jdbc.execute("ALTER TABLE ab_behavior_quarantine ADD COLUMN IF NOT EXISTS replay_detail TEXT");
        jdbc.execute("ALTER TABLE ab_behavior_quarantine ADD COLUMN IF NOT EXISTS replayed_behavior_event_id BIGINT");
        jdbc.execute("ALTER TABLE ab_behavior_quarantine ADD COLUMN IF NOT EXISTS replayed_at TIMESTAMPTZ");
        cleanup();
        insertKey("p_a", TENANT_A, KEY_A, "active");
        insertKey("p_b", TENANT_B, KEY_B, "active");
        insertKey("p_d", TENANT_A, KEY_DISABLED, "disabled");
        // The index this slice ships — identical DDL to createFieldIndex(...UNIQUE) output.
        jdbc.execute("CREATE UNIQUE INDEX IF NOT EXISTS " + INDEX
                + " ON mt_behavior_site_key (site_key)");
    }

    @AfterAll
    void tearDown() {
        cleanup();
    }

    private void insertKey(String pid, long tenant, String key, String status) {
        jdbc.update("INSERT INTO mt_behavior_site_key (pid, tenant_id, site_key, name, status) "
                + "VALUES (?,?,?,?,?)", pid, tenant, key, "IT " + key, status);
    }

    private void cleanup() {
        jdbc.update("DELETE FROM mt_behavior_site_key WHERE site_key LIKE 'abk_it_%'");
        jdbc.update("DELETE FROM ab_behavior_event WHERE tenant_id IN (?,?)", TENANT_A, TENANT_B);
        jdbc.update("DELETE FROM ab_behavior_quarantine WHERE tenant_id IN (?,?)", TENANT_A, TENANT_B);
    }

    private String body(String eventId) {
        return "{\"events\":[{\"eventId\":\"" + eventId + "\",\"eventName\":\"page_view\",\"anonId\":\"anon-it\"}]}";
    }

    private String body(String eventId, String eventName, String anonId) {
        return "{\"events\":[{\"eventId\":\"" + eventId + "\",\"eventName\":\"" + eventName
                + "\",\"anonId\":\"" + anonId + "\"}]}";
    }

    private int eventCount(long tenant) {
        Integer n = jdbc.queryForObject("SELECT count(1) FROM ab_behavior_event WHERE tenant_id = ?",
                Integer.class, tenant);
        return n == null ? 0 : n;
    }

    private int quarantineCount(long tenant) {
        Integer n = jdbc.queryForObject("SELECT count(1) FROM ab_behavior_quarantine WHERE tenant_id = ?",
                Integer.class, tenant);
        return n == null ? 0 : n;
    }

    private int eventCountById(long tenant, String eventId) {
        Integer n = jdbc.queryForObject(
                "SELECT count(1) FROM ab_behavior_event WHERE tenant_id=? AND event_id=?",
                Integer.class, tenant, eventId);
        return n == null ? 0 : n;
    }

    @Test
    @DisplayName("valid key → event lands in the key's tenant, user null, anon_id passed through")
    void validKey_ingestsToKeyTenant() {
        ResponseEntity<String> resp = postKeyed(KEY_A, "e-valid-1");
        assertThat(resp.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(resp.getBody()).contains("\"accepted\":1");
        assertThat(eventCount(TENANT_A)).isEqualTo(1);
        assertThat(jdbc.queryForObject(
                "SELECT user_id FROM ab_behavior_event WHERE tenant_id=? AND event_id='e-valid-1'",
                Long.class, TENANT_A)).isNull();
        assertThat(jdbc.queryForObject(
                "SELECT anon_id FROM ab_behavior_event WHERE tenant_id=? AND event_id='e-valid-1'",
                String.class, TENANT_A)).isEqualTo("anon-it");
    }

    @Test
    @DisplayName("cross-tenant isolation: key A never lands in tenant B")
    void crossTenantIsolation() {
        assertThat(postKeyed(KEY_A, "e-iso-1").getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(jdbc.queryForObject(
                "SELECT count(1) FROM ab_behavior_event WHERE tenant_id=? AND event_id='e-iso-1'",
                Integer.class, TENANT_B)).isZero();
    }

    @Test
    @DisplayName("duplicate event_id → both accepted, one durable behavior event")
    void duplicateEventId_idempotentSingleRow() {
        ResponseEntity<String> first = postKeyed(KEY_A, "e-dup-1");
        ResponseEntity<String> second = postKeyed(KEY_A, "e-dup-1");

        assertThat(first.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(second.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(first.getBody()).contains("\"accepted\":1");
        assertThat(second.getBody()).contains("\"accepted\":1");
        assertThat(eventCountById(TENANT_A, "e-dup-1")).isEqualTo(1);
    }

    @Test
    @DisplayName("malformed event → accepted by endpoint, quarantined, not stored as behavior event")
    void malformedEvent_quarantinedNotStored() {
        int quarantineBefore = quarantineCount(TENANT_A);
        ResponseEntity<String> resp = postKeyedBody(KEY_A,
                "{\"events\":[{\"eventName\":\"page_view\",\"anonId\":\"anon-bad\"}]}");

        assertThat(resp.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(resp.getBody()).contains("\"accepted\":1");
        assertThat(jdbc.queryForObject(
                "SELECT count(1) FROM ab_behavior_event WHERE tenant_id=? AND anon_id='anon-bad'",
                Integer.class, TENANT_A)).isZero();
        assertThat(quarantineCount(TENANT_A)).isEqualTo(quarantineBefore + 1);
        assertThat(jdbc.queryForObject(
                "SELECT reason FROM ab_behavior_quarantine WHERE tenant_id=? AND anon_id='anon-bad'",
                String.class, TENANT_A)).isEqualTo("malformed_missing_event_id");
    }

    @Test
    @DisplayName("constraint violation → accepted by endpoint, quarantined with raw over-long field")
    void constraintViolation_quarantinedNotStored() {
        String eventId = "e-overlong-" + "x".repeat(80);
        String anonId = "anon-overlong";
        int quarantineBefore = quarantineCount(TENANT_A);

        ResponseEntity<String> resp = postKeyedBody(KEY_A, body(eventId, "page_view", anonId));

        assertThat(resp.getStatusCode()).isEqualTo(HttpStatus.OK);
        assertThat(resp.getBody()).contains("\"accepted\":1");
        assertThat(jdbc.queryForObject(
                "SELECT count(1) FROM ab_behavior_event WHERE tenant_id=? AND anon_id=?",
                Integer.class, TENANT_A, anonId)).isZero();
        assertThat(quarantineCount(TENANT_A)).isEqualTo(quarantineBefore + 1);
        assertThat(jdbc.queryForObject(
                "SELECT reason FROM ab_behavior_quarantine WHERE tenant_id=? AND anon_id=?",
                String.class, TENANT_A, anonId)).isEqualTo("constraint_violation");
        assertThat(jdbc.queryForObject(
                "SELECT event_id FROM ab_behavior_quarantine WHERE tenant_id=? AND anon_id=?",
                String.class, TENANT_A, anonId)).isEqualTo(eventId);
    }

    @Test
    @DisplayName("unknown key → 403, nothing written")
    void unknownKey_403() {
        int before = eventCount(TENANT_A);
        assertThat(postKeyed("abk_it_nope0000000000000000000000", "e-unknown").getStatusCode())
                .isEqualTo(HttpStatus.FORBIDDEN);
        assertThat(eventCount(TENANT_A)).isEqualTo(before);
    }

    @Test
    @DisplayName("disabled key → 403")
    void disabledKey_403() {
        assertThat(postKeyed(KEY_DISABLED, "e-disabled").getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN);
    }

    @Test
    @DisplayName("missing site key header → 403")
    void missingKey_403() {
        assertThat(postKeyed(null, "e-nokey").getStatusCode()).isEqualTo(HttpStatus.FORBIDDEN);
    }

    @Test
    @DisplayName("CORS: cross-origin preflight from any origin allows POST + X-Site-Key (public, no credentials)")
    void corsPreflightAllowsPublicCrossOrigin() {
        // A published low-code app embeds the SDK on the customer's own domain (arbitrary origin)
        // and sends X-Site-Key, which triggers a browser preflight. The public keyed endpoint must
        // allow it (SP4) — the global /api/** CORS config only allows the admin app's own origins.
        HttpHeaders h = new HttpHeaders();
        h.set(HttpHeaders.ORIGIN, "https://customer-app.example.com");
        h.set(HttpHeaders.ACCESS_CONTROL_REQUEST_METHOD, "POST");
        h.set(HttpHeaders.ACCESS_CONTROL_REQUEST_HEADERS, "x-site-key,content-type");
        ResponseEntity<String> resp = restTemplate.exchange("/api/collect/keyed", HttpMethod.OPTIONS,
                new HttpEntity<>(h), String.class);

        assertThat(resp.getStatusCode().is2xxSuccessful())
                .as("preflight not rejected: %s", resp.getStatusCode()).isTrue();
        assertThat(resp.getHeaders().getAccessControlAllowOrigin())
                .as("allows the requesting origin").isNotNull();
        assertThat(resp.getHeaders().getAccessControlAllowMethods()).contains(HttpMethod.POST);
        assertThat(String.valueOf(resp.getHeaders().getAccessControlAllowHeaders()).toLowerCase())
                .as("allows the X-Site-Key request header").contains("x-site-key");
    }

    @Test
    @DisplayName("over-long field on one event → quarantined, batch still 200 (public endpoint stays resilient, no 500)")
    void oversizedEvent_quarantinedNotBatchFatal() {
        // event_id is VARCHAR(40); a misbehaving/hostile client sending a 60-char id must not 500
        // the whole batch — the bad event is quarantined and valid events persist.
        String longId = "e".repeat(60);
        int quarantineBefore = quarantineCount(TENANT_A);
        String body = "{\"events\":["
                + "{\"eventId\":\"e-ok-resilient\",\"eventName\":\"page_view\",\"anonId\":\"anon-it\"},"
                + "{\"eventId\":\"" + longId + "\",\"eventName\":\"page_view\",\"anonId\":\"anon-it\"}"
                + "]}";
        HttpHeaders h = new HttpHeaders();
        h.setContentType(MediaType.APPLICATION_JSON);
        h.set("X-Site-Key", KEY_A);
        ResponseEntity<String> resp = restTemplate.exchange("/api/collect/keyed", HttpMethod.POST,
                new HttpEntity<>(body, h), String.class);

        assertThat(resp.getStatusCode()).as("batch not 500'd by one bad event").isEqualTo(HttpStatus.OK);
        assertThat(resp.getBody()).as("both events accepted for durable async handling").contains("\"accepted\":2");
        assertThat(jdbc.queryForObject(
                "SELECT count(1) FROM ab_behavior_event WHERE tenant_id=? AND event_id='e-ok-resilient'",
                Integer.class, TENANT_A)).isEqualTo(1);
        assertThat(jdbc.queryForObject(
                "SELECT count(1) FROM ab_behavior_event WHERE tenant_id=? AND event_id=?",
                Integer.class, TENANT_A, longId)).as("over-long event not stored").isZero();
        assertThat(quarantineCount(TENANT_A)).isEqualTo(quarantineBefore + 1);
        assertThat(jdbc.queryForObject(
                "SELECT reason FROM ab_behavior_quarantine WHERE tenant_id=? AND event_id=?",
                String.class, TENANT_A, longId)).isEqualTo("constraint_violation");
    }

    @Test
    @DisplayName("index: global UNIQUE(site_key), single column, no tenant prefix")
    void indexIsGlobalUniqueSingleColumn() {
        String def = jdbc.queryForObject(
                "SELECT indexdef FROM pg_indexes WHERE tablename='mt_behavior_site_key' "
                + "AND indexname='" + INDEX + "'", String.class);
        assertThat(def).isNotNull().containsIgnoringCase("unique").contains("(site_key)");
        assertThat(def).doesNotContain("tenant_id");
    }

    @Test
    @DisplayName("global uniqueness enforced: same site_key in two tenants rejected")
    void globalUniquenessEnforced() {
        Throwable t = catchThrowable(() -> insertKey("p_dup", TENANT_B, KEY_A, "active"));
        assertThat(t).isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    @DisplayName("resolve can use the site_key index (seqscan disabled → Index Scan, not Seq Scan)")
    void resolveUsesIndexScan() {
        // On a tiny table the planner prefers a seq scan regardless of the index, so disable it
        // on the *same* connection as the EXPLAIN to prove the index is usable for the resolve.
        String plan = jdbc.execute((java.sql.Connection conn) -> {
            try (java.sql.Statement st = conn.createStatement()) {
                st.execute("SET enable_seqscan = off");
                StringBuilder sb = new StringBuilder();
                try (java.sql.ResultSet rs = st.executeQuery(
                        "EXPLAIN SELECT tenant_id FROM mt_behavior_site_key WHERE site_key='" + KEY_A
                        + "' AND status='active' LIMIT 1")) {
                    while (rs.next()) {
                        sb.append(rs.getString(1)).append("\n");
                    }
                }
                st.execute("SET enable_seqscan = on");
                return sb.toString();
            }
        });
        assertThat(plan).containsIgnoringCase("Index Scan").doesNotContainIgnoringCase("Seq Scan");
    }
}
