package com.auraboot.framework.billing;

import com.auraboot.framework.common.util.UniqueIdGenerator;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.support.TransactionTemplate;

import java.sql.Timestamp;
import java.time.Instant;

/**
 * Test-scoped seed helper: inserts a parent {@code ab_billing_account} row
 * before quota/metering IT {@code @BeforeEach} seeds bare account_id values.
 *
 * <p>Background: Task 2 of the billing P0 spine FK-ized the {@code account_id}
 * columns on {@code ab_billing_quota_pool}, {@code ab_billing_quota_bucket}, and
 * {@code ab_billing_usage_event} → {@code ab_billing_account(id)}.
 * ITs that seeded bare hardcoded account IDs (900_000_001, 900_100_001, 800_000_001)
 * now fail with FK violations.  This helper provides a single, shared way to
 * create the parent row before each quota/metering test method.
 *
 * <h3>Design choices</h3>
 * <ul>
 *   <li>Uses {@link JdbcTemplate} with an explicit {@code id} value (bypassing the
 *       sequence) so the test's hardcoded account id is honoured exactly.
 *   <li>{@link #ensureAccountExists} is idempotent: if the same account_code is
 *       already present (rare in FK-isolated tests, but safe), the insert is
 *       silently skipped via {@code ON CONFLICT (id) DO NOTHING}.
 * </ul>
 *
 * <p>Callers must be Spring beans (ITs are loaded via {@code @SpringBootTest}).
 * The test ITs that need it simply {@code @Autowired} this helper and call
 * {@link #ensureAccountExists} in their {@code @BeforeEach}.
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class BillingAccountSeedHelper {

    private final JdbcTemplate              jdbcTemplate;
    private final PlatformTransactionManager transactionManager;

    /**
     * Ensure an {@code ab_billing_account} row exists with the given {@code wantedId}.
     *
     * <p>Strategy: first try a direct JDBC insert with the exact {@code id} value
     * (bypassing the sequence so the test's hardcoded account ID is honoured exactly).
     * If the row already exists (idempotent re-run), the insert is silently skipped.
     *
     * <p>The {@code ab_billing_account} DDL uses
     * {@code BIGINT GENERATED BY DEFAULT AS IDENTITY} — "BY DEFAULT" allows explicit
     * id values, so this insert is legal.
     *
     * @param wantedId    the exact account id the IT seeds into quota/metering tables
     * @param accountCode a unique-enough code (caller supplies, e.g. "ACC-IT-900000001")
     */
    public void ensureAccountExists(Long wantedId, String accountCode) {
        doInsertAccount(wantedId, accountCode);
        log.debug("[seed] ensureAccountExists id={} accountCode={}", wantedId, accountCode);
    }

    /** Inner: executes the idempotent INSERT in the current transaction context. */
    private void doInsertAccount(Long wantedId, String accountCode) {
        jdbcTemplate.update(
                "INSERT INTO ab_billing_account "
                        + "(id, pid, account_code, name, status, default_currency, billing_mode, "
                        + " balance, created_at, updated_at, deleted_flag) "
                        + "VALUES (?, ?, ?, ?, 'active', 'CNY', 'POSTPAID', 0, ?, ?, false) "
                        + "ON CONFLICT (id) DO NOTHING",
                wantedId,
                UniqueIdGenerator.generate(),
                accountCode,
                "IT Account " + wantedId,
                // PostgreSQL JDBC requires java.sql.Timestamp (not java.time.Instant)
                // for TIMESTAMPTZ columns when using plain JdbcTemplate.update()
                Timestamp.from(Instant.now()),
                Timestamp.from(Instant.now())
        );
    }

    /**
     * Same as {@link #ensureAccountExists} but runs in a dedicated committed transaction
     * ({@code REQUIRES_NEW}) so the row is immediately visible to subsequent
     * {@code REQUIRES_NEW} inner transactions (e.g. {@code MeteringInsertHelper.tryInsertEvent}).
     *
     * <p>Use this for ITs where the production code being tested starts its own
     * {@code REQUIRES_NEW} transaction (such as {@link
     * com.auraboot.framework.billing.metering.service.MeteringInsertHelper#tryInsertEvent})
     * — in that scenario the account row must be committed before the inner TX starts
     * or the FK check will fail (the inner TX cannot see an uncommitted outer TX row).
     *
     * <p>Callers must manually call {@link #removeAccount} in their {@code @AfterEach}
     * because the row is committed, not rolled back.
     */
    public void ensureAccountExistsAndCommit(Long wantedId, String accountCode) {
        TransactionTemplate txTemplate = new TransactionTemplate(transactionManager);
        txTemplate.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRES_NEW);
        txTemplate.executeWithoutResult(status -> doInsertAccount(wantedId, accountCode));
        log.debug("[seed] ensureAccountExistsAndCommit id={} accountCode={}", wantedId, accountCode);
    }

    /**
     * Remove the seeded account row, running the DELETE in the current transaction.
     *
     * <p>Use this when the account was inserted within a test's {@code @Transactional}
     * context (quota ITs with manual cleanup), or as a no-op when the caller's
     * transaction will be rolled back anyway.
     *
     * @param accountId the account id to remove
     */
    public void removeAccount(Long accountId) {
        jdbcTemplate.update("DELETE FROM ab_billing_account WHERE id = ?", accountId);
        log.debug("[seed] removeAccount id={}", accountId);
    }

    /**
     * Remove a committed account row in its own dedicated committed transaction.
     *
     * <p>Must be called from {@code @AfterEach} when the account was seeded via
     * {@link #ensureAccountExistsAndCommit} — since that row is already committed,
     * it will not be rolled back by the test's own transaction and must be explicitly
     * deleted in a committed transaction.
     *
     * @param accountId the account id to remove
     */
    public void removeAccountAndCommit(Long accountId) {
        TransactionTemplate txTemplate = new TransactionTemplate(transactionManager);
        txTemplate.setPropagationBehavior(TransactionDefinition.PROPAGATION_REQUIRES_NEW);
        txTemplate.executeWithoutResult(status ->
                jdbcTemplate.update("DELETE FROM ab_billing_account WHERE id = ?", accountId));
        log.debug("[seed] removeAccountAndCommit id={}", accountId);
    }
}
