// web-admin/app/smart/automation/nodes/triggers.ts
import type { FlowNodeDefinition } from '~/flow-designer-sdk';

export const triggerNodes: FlowNodeDefinition[] = [
  {
    type: 'trigger-record-create',
    label: '$i18n:automation.trigger.recordCreate',
    icon: 'Plus',
    category: 'trigger',
    description: '$i18n:automation.trigger.recordCreate.desc',
    configSchema: [
      {
        key: 'modelCode',
        label: '$i18n:automation.field.modelCode',
        type: 'model-select',
        required: true,
        description: '$i18n:automation.field.modelCode.desc',
        group: 'trigger_source',
      },
    ],
    defaultConfig: {
      triggerType: 'on_record_create',
    },
  },
  {
    type: 'trigger-record-update',
    label: '$i18n:automation.trigger.recordUpdate',
    icon: 'Pencil',
    category: 'trigger',
    description: '$i18n:automation.trigger.recordUpdate.desc',
    configSchema: [
      {
        key: 'modelCode',
        label: '$i18n:automation.field.modelCode',
        type: 'model-select',
        required: true,
        group: 'trigger_source',
      },
      {
        key: 'watchFields',
        label: '$i18n:automation.field.watchFields',
        type: 'multiselect',
        description: '$i18n:automation.field.watchFields.desc',
        dependsOn: { field: 'modelCode' },
        group: 'filter',
      },
    ],
    defaultConfig: {
      triggerType: 'on_record_update',
    },
  },
  {
    type: 'trigger-field-change',
    label: '$i18n:automation.trigger.fieldChange',
    icon: 'RefreshCw',
    category: 'trigger',
    description: '$i18n:automation.trigger.fieldChange.desc',
    configSchema: [
      {
        key: 'modelCode',
        label: '$i18n:automation.field.modelCode',
        type: 'model-select',
        required: true,
        group: 'trigger_source',
      },
      {
        key: 'fieldCode',
        label: '$i18n:automation.field.fieldCode',
        type: 'field-select',
        required: true,
        dependsOn: { field: 'modelCode' },
        group: 'trigger_source',
      },
      {
        key: 'fromValue',
        label: '$i18n:automation.field.fromValue',
        type: 'text',
        description: '$i18n:automation.field.fromValue.desc',
        dependsOn: { field: 'fieldCode' },
        group: 'filter',
      },
      {
        key: 'toValue',
        label: '$i18n:automation.field.toValue',
        type: 'text',
        description: '$i18n:automation.field.toValue.desc',
        dependsOn: { field: 'fieldCode' },
        group: 'filter',
      },
    ],
    defaultConfig: {
      triggerType: 'on_field_change',
    },
  },
  {
    type: 'trigger-state-change',
    label: '$i18n:automation.trigger.stateChange',
    icon: 'GitBranch',
    category: 'trigger',
    description: '$i18n:automation.trigger.stateChange.desc',
    configSchema: [
      {
        key: 'modelCode',
        label: '$i18n:automation.field.modelCode',
        type: 'model-select',
        required: true,
        group: 'trigger_source',
      },
      {
        key: 'stateField',
        label: '$i18n:automation.field.stateField',
        type: 'field-select',
        required: true,
        dependsOn: { field: 'modelCode' },
        group: 'trigger_source',
      },
      {
        key: 'fromStates',
        label: '$i18n:automation.field.fromStates',
        type: 'multiselect',
        description: '$i18n:automation.field.fromStates.desc',
        dependsOn: { field: 'stateField' },
        group: 'filter',
      },
      {
        key: 'toStates',
        label: '$i18n:automation.field.toStates',
        type: 'multiselect',
        description: '$i18n:automation.field.toStates.desc',
        dependsOn: { field: 'stateField' },
        group: 'filter',
      },
    ],
    defaultConfig: {
      triggerType: 'on_state_change',
    },
  },
  {
    type: 'trigger-scheduled',
    label: '$i18n:automation.trigger.scheduled',
    icon: 'Clock',
    category: 'trigger',
    description: '$i18n:automation.trigger.scheduled.desc',
    configSchema: [
      {
        key: 'cron',
        label: '$i18n:automation.field.cron',
        type: 'text',
        required: true,
        placeholder: '0 0 * * *',
        description: '$i18n:automation.field.cron.desc',
        group: 'trigger_source',
      },
      {
        key: 'timezone',
        label: '$i18n:automation.field.timezone',
        type: 'select',
        options: [
          { label: 'Asia/Shanghai', value: 'Asia/Shanghai' },
          { label: 'UTC', value: 'utc' },
          { label: 'America/New_York', value: 'America/New_York' },
          { label: 'Europe/London', value: 'Europe/London' },
        ],
        group: 'trigger_source',
      },
      {
        key: 'maxExecutionTime',
        label: '$i18n:automation.field.maxExecutionTime',
        type: 'number',
        description: '$i18n:automation.field.maxExecutionTime.desc',
        group: 'advanced',
      },
    ],
    defaultConfig: {
      triggerType: 'scheduled',
      timezone: 'Asia/Shanghai',
    },
  },
  {
    type: 'trigger-webhook',
    label: '$i18n:automation.trigger.webhook',
    icon: 'Link',
    category: 'trigger',
    description: '$i18n:automation.trigger.webhook.desc',
    configSchema: [
      {
        key: 'secret',
        label: '$i18n:automation.field.secret',
        type: 'text',
        description: '$i18n:automation.field.secret.desc',
        group: 'trigger_source',
      },
      {
        key: 'validationMode',
        label: '$i18n:automation.field.validationMode',
        type: 'select',
        options: [
          { label: '$i18n:automation.field.validationMode.none', value: 'none' },
          { label: '$i18n:automation.field.validationMode.signature', value: 'signature' },
          { label: '$i18n:automation.field.validationMode.token', value: 'token' },
        ],
        group: 'trigger_source',
      },
      {
        key: 'expectedHeaders',
        label: '$i18n:automation.field.expectedHeaders',
        type: 'multiselect',
        description: '$i18n:automation.field.expectedHeaders.desc',
        group: 'advanced',
      },
    ],
    defaultConfig: {
      triggerType: 'webhook',
      validationMode: 'none',
    },
  },
];
